export const STRINGS = {
  en: {
    tasks: 'Tasks', kanban: 'Kanban', grades: 'Grades', calendar: 'Calendar', focus: 'Focus', settings: 'Settings',
    noSemester: 'No semester set up', goToSettings: 'Head to Settings to get started.',
    weekLabel: w => `Week ${w}`, done: 'done', timeToRelax: 'Time to relax!',
    addTask: 'New task', task: 'Task', class: 'Class', priority: 'Priority',
    editTask: 'Edit task', moveLeft: 'Move left', moveRight: 'Move right',
    addToKanban: 'Add to Kanban', themeLight: 'Light theme', themeDark: 'Dark theme', themeSystem: 'System theme',
    addPartTitle: 'Add part',
    fromWeek: 'From week', toWeek: 'To week', dueDate: 'Due date',
    other: 'Other', noTasks: 'No tasks this week.',
    whatNeedsDone: 'What needs to be done?',
    addTaskBtn: 'Add task', showOnCalendar: 'Show on calendar',
    clearDone: 'Clear done', wipeAll: 'Wipe all',
    addCard: 'Add card', addCardPlaceholder: 'Card title',
    save: 'Save', cancel: 'Cancel', confirm: 'Confirm',
    semester: 'Semester', classes: 'Classes', gradeComponents: 'Grade components',
    kanbanColumns: 'Kanban columns', general: 'General', data: 'Data & sync',
    holidays: 'Holidays',
    exportJson: 'Export JSON', importJson: 'Import JSON',
    semesterAvg: 'Semester average', ectsPassedLabel: 'ECTS passed',
    targetGrade: 'Target grade',
    previousSemesters: 'Previous semesters',
    courseAvg: 'Course average', finalGrade: 'Final grade', previousAvg: 'Previous avg', numSemesters: 'No. of semesters',
    getStarted: 'Get started', welcomeTitle: 'Welcome to organizer',
    welcomeDesc: 'Your space for uni work. Set up your semester and get organised.',
    step1: 'Set your semester dates', step2: 'Add your classes', step3: 'Plan tasks & track grades',
    shareLink: 'Copy share link', qrCode: 'QR Code', linkCopied: 'Link copied!',
    high: 'High', medium: 'Medium', low: 'Low', none: 'None',
    addSemester: 'Add semester', semesterName: 'Semester name', startDate: 'Start date', endDate: 'End date',
    weeks: n => `${n} weeks`, addAClass: 'Add class', className: 'Class name', ects: 'ECTS', colour: 'Colour',
    addComponent: 'Add component', componentName: 'Component name',
    taskSpanLabel: 'Task span behaviour', taskSpanDesc: 'When a task spans multiple weeks, how is it marked done?',
    kanbanChecklistInlineLabel: 'Kanban checklist preview',
    kanbanChecklistInlineDesc: 'Show checklist items directly on cards without opening details.',
    kanbanChecklistPreviewNone: 'Hide on cards',
    kanbanChecklistPreviewAll: 'Show on all cards',
    kanbanChecklistPreviewPerCard: 'Case by case',
    focusAlertModeLabel: 'Focus alert mode',
    focusAlertModeDesc: 'Choose how Focus alerts are delivered when the timer phase changes.',
    focusAlertNone: 'None',
    focusAlertVibration: 'Vibration',
    focusAlertNotification: 'Notification',
    focusAlertBoth: 'Both',
    taskAlertModeLabel: 'Task due-date alerts',
    taskAlertModeDesc: 'Choose how task due-date alerts are delivered.',
    taskAlertNone: 'None',
    taskAlertInApp: 'In-app',
    taskAlertNotification: 'Notification',
    taskAlertBoth: 'Both',
    taskAlertNextDayTimeLabel: 'Next-day alert time',
    taskAlertNextDayTimeDesc: 'Time for reminders about tasks due tomorrow.',
    taskDueTodayTitle: count => count === 1 ? 'Task due today' : `${count} tasks due today`,
    taskAlertHide: 'Hide alert',
    taskAlertRemindMeAt: 'Remind me at',
    settingEnabled: 'Enabled', settingDisabled: 'Disabled',
    spanSingle: 'One global checkbox (done once)', spanPerWeek: 'Per-week checkbox',
    dangerZone: 'Danger zone', deleteSemester: 'Delete this semester',
    clearPomodoros: 'Clear pomodoros',
    clearPomodorosTitle: 'Clear all pomodoros?',
    clearPomodorosDesc: 'All fallen pomodoros will be permanently deleted.',
    deleteSemesterTitle: 'Delete semester?', deleteSemesterDesc: 'All tasks, grades, and kanban data for this semester will be permanently deleted.',
    clearDoneTitle: 'Clear done column?', clearDoneDesc: 'All cards in the Done column will be deleted.',
    wipeAllTitle: 'Wipe all cards?', wipeAllDesc: 'Every card on the board will be permanently deleted.',
    selectSemester: 'Select semester', noClassesYet: 'No classes yet', addClassesInSettings: 'Add classes in Settings.',
    addUnlocks: 'Add a semester to unlock the rest.',
    checklist: 'Checklist', addItem: 'Add item', editCard: 'Edit card',
    notAchievable: '— not achievable', onRemaining: ' on remaining assessments',
    youNeed: 'You need', allGraded: 'All components graded.',
    noGradeComponents: 'No grade components configured. Go to Settings.',
    deleteClassTitle: 'Delete class?', deleteClassDesc: 'This will also delete all tasks for this class.',
    holidayName: 'Holiday name', holidayNamePlaceholder: 'e.g. Christmas Break',
    addHoliday: 'Add holiday',
    loadPreset: 'Load preset',
    presetLoading: 'Loading preset…', presetError: 'Failed to load preset.', retry: 'Retry', skip: 'Skip',
    newColumnName: 'New column name',
    focusStart: 'Start', focusPause: 'Pause', focusResume: 'Resume', focusReset: 'Reset', focusSkipBreak: 'Skip break',
    focusReady: 'ready', focusBreak: 'break',
    focusPhrases: ['keep going', 'stay with it', "you're doing great", 'one step at a time', 'deep work', 'stay present'],
    focusEvery: 'every (min)', focusBreakFor: 'break (min)',
    focusScheduledMode: 'Scheduled breaks',
    focusNextBreak: 'Next break at',
    focusFocusLabel: 'Focus message', focusBreakLabel: 'Break message',
    loadPresetTitle: 'Load a preset',
    presetGroupEI: 'EI Course',
    presetGroupGeneric: 'General',
    backToMenu: 'Back',
    importData: 'Import data',
    importFromFirebase: 'Import from Firebase',
    nextSemesterTitle: 'Semester ended',
    nextSemesterDesc: 'Your semester has ended. Load the next one?',
    loadNextSemester: 'Load next semester',
    dismissNextSemester: 'Dismiss',
    noSemesterYet: 'No semester configured',
    noSemesterDesc: 'Load a preset or import your data to get started.',
    focusIntervalMode: 'Interval breaks',
    focusIntervalEvery: 'every (min)',
    focusIntervalBreakFor: 'break (min)',
    focusScheduledBreakFor: 'break (min)',
    firebaseSync: 'Firebase sync',
    firebaseConnect: 'Connect',
    firebaseConnected: 'Connected',
    firebaseDisconnect: 'Disconnect',
    firebaseSyncing: 'Syncing…',
    firebaseLastSync: 'Last sync',
    firebaseError: 'Sync error',
    firebaseSetupTitle: 'Connect Firebase',
    firebaseStep1Title: 'Create a Firebase project',
    firebaseStep1Desc: 'Go to console.firebase.google.com → Add project → give it any name → disable Google Analytics → Create project.',
    firebaseStep2Title: 'Enable Firestore',
    firebaseStep2Desc: 'Go to Build → Firestore Database → Create database → choose a region → Start in production mode → Create. Then go to Rules, replace the content with: allow read, write: if true; and click Publish.',
    firebaseStep3Title: 'Get your config',
    firebaseStep3Desc: 'Go to Project Settings (gear icon) → Your apps → Add app → Web → register the app → copy the firebaseConfig object shown.',
    firebaseStep4Title: 'Paste your config',
    firebaseStep4Desc: 'Paste the full firebaseConfig object (as JSON) below.',
    firebaseConfigPlaceholder: '{ "apiKey": "...", "authDomain": "...", "projectId": "...", ... }',
    firebaseConfigInvalid: 'Invalid config — must include apiKey and projectId.',
    firebaseTestFailed: 'Could not connect. Check your config and database rules.',
    firebaseSave: 'Save & connect',
    pomodoroMode: 'Pomodoro mode',
    pomodoroModeDesc: 'Grow tomatoes during focus sessions. Each completed session drops a tomato.',
    pomodoroResetPeriod: 'Reset period',
    pomodoroResetDay: 'Daily', pomodoroResetWeek: 'Weekly', pomodoroResetMonth: 'Monthly', pomodoroResetSemester: 'Per semester',
    pomodoroTrackPeriodStats: 'Track period stats',
    pomodoroShowAbandoned: 'Show abandoned tomatoes',
    pomodoroShowPeriodPomodoros: 'Show period pomodoros',
    pomodoroStatsTitle: 'Pomodoro stats',
    pomodoroTotal: 'Total tomatoes', pomodoroAbandoned: 'Abandoned', pomodoroFocusTime: 'Total focus time',
    pomodoroPeriodTotal: 'This period', pomodoroPeriodFocus: 'Focus this period',
    pomodoroVsSinceLast: 'vs last period',
    pomodoroAllTime: 'All time',
    pomodoroInsightsDailyTitle: 'Daily focus this week',
    pomodoroInsightsWeeklyBreakdownTitle: 'Weekly averages',
    pomodoroInsightsAvgWeekLabel: 'avg/day (week)',
    pomodoroInsightsAvgPeriodLabel: 'avg/day (period)',
    pomodoroInsightsPerDaySuffix: '/d',
    pomodoroInsightsNoWeeklyData: 'No weekly data yet.',
    pomodoroInsightsDayLabels: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
    pomodoroTotalTimeLabel: 'total time',
    pomodoroClose: 'Close',
    pomodoroEraseStats: 'Erase stats',
    pomodoroEraseStatsTitle: 'Erase pomodoro stats?',
    pomodoroEraseStatsDesc: 'Historical focus-time stats will be removed, but tomato entries stay available.',
    pomodoroGraceCancel: 'Cancel (no tomato)',
    pomodoroGrace: s => `${s}s to cancel without losing a tomato`,
    workModeLabel: 'Work mode',
    workModeDesc: 'Hides grades and renames classes to groups.',
    workModeOnboarding: 'Using this for work?',
    groups: 'Groups', addAGroup: 'Add group', groupName: 'Group name',
    deleteGroupTitle: 'Delete group?', deleteGroupDesc: 'This will also delete all tasks for this group.',
    storageWarningTitle: 'Storage limit reached',
    storageWarningDesc: 'Please activate Firebase sync, reached max local storage.',
    storageWarningAction: 'Got it',
    collabConnect: 'Connect Organizer Collab',
    collabDisconnect: 'Disconnect Organizer Collab',
    collabRequiresFirebase: 'Connect Firebase sync first to use Organizer Collab.',
    collabGuideTitle: 'Organizer Collab setup',
    collabGuideIntro: 'One-time setup. Do these 4 steps in Firebase, then come back and enable collab.',
    collabGuideImportantTitle: 'What changes when collab is enabled',
    collabGuideImportant1: 'Your database starts requiring authenticated users (anonymous auth is enough).',
    collabGuideImportant2: 'Normal organizer sync keeps working, but it must authenticate first.',
    collabGuideImportant3: 'If collab is disabled later, auth-based rules can still be used safely.',
    collabGuideStep1: 'Open Firebase Console > Build > Firestore Database > Rules.',
    collabGuideStep2: 'Paste the rules snippet below and click Publish.',
    collabGuideStep3: 'Open Security > Authentication > Sign-in method > enable Anonymous > Save.',
    collabGuideStep4: 'Return to Organizer and press "I configured rules, enable collab".',
    collabGuideRulesLabel: 'Firestore rules',
    collabGuideTroubleshootTitle: 'If you see signUp 400 error',
    collabGuideTroubleshootBody: 'That means Anonymous authentication is still disabled in Firebase. Enable it in Security > Authentication > Sign-in method.',
    collabEnableNow: 'I configured rules, enable collab',
    collabPanelTitle: 'Organizer Collab',
    collabPanelSubtitle: 'Create teams, invite people, and share tasks/kanban cards.',
    collabCreateTeam: 'Create team',
    collabTeamName: 'Team name',
    collabTeamDays: 'team days',
    collabTeamDuration: 'team duration',
    collabDays: 'days',
    collabJoinTeam: 'Join team',
    collabInvitePlaceholder: 'Paste invite link',
    collabInviteTtl: 'Invite validity',
    collabYourTeams: 'Your teams',
    collabNoTeams: 'No teams yet.',
    collabRoleHost: 'host',
    collabRoleMember: 'member',
    collabEndsAt: 'ends',
    collabInvite: 'Invite',
    collabEditTeam: 'Edit team',
    collabTaskCompletionMode: 'Shared task completion',
    collabTaskCompletionPersonal: 'personal completion',
    collabTaskCompletionForAll: 'toggle for everyone',
    collabTaskPermissions: 'Task edit permissions',
    collabTaskPermissionsEveryone: 'anyone can add/edit/remove tasks',
    collabTaskPermissionsHostOnly: 'only host can add/edit/remove tasks',
    collabLeave: 'Leave',
    collabDeleteTeam: 'Delete',
    collabDefaultTeamName: 'Team',
    collabLeavePrompt: 'Leave this team?',
    collabLeaveWithLocalPrompt: 'You shared local tasks in this team. Keep them locally?',
    collabDeleteTeamPrompt: 'Delete this team?',
    collabDeleteTeamWithLocalPrompt: 'You shared local tasks in this team. Keep them locally before deleting the team?',
    collabKeepLocalTasks: 'Keep local tasks',
    collabDeleteLocalTasksToo: 'Delete local tasks',
    collabErrorCreate: 'Could not create team.',
    collabErrorInvite: 'Could not generate invite.',
    collabErrorJoin: 'Could not join team.',
    collabErrorInvalidLink: 'Invalid invite link.',
    collabErrorDeleteTeam: 'Could not delete team.',
  },
  pt: {
    tasks: 'Tarefas', kanban: 'Kanban', grades: 'Notas', calendar: 'Calendário', focus: 'Foco', settings: 'Definições',
    noSemester: 'Nenhum semestre configurado', goToSettings: 'Vai a Definições para começar.',
    weekLabel: w => `Semana ${w}`, done: 'concluídas', timeToRelax: 'Hora de descansar!',
    addTask: 'Nova tarefa', task: 'Tarefa', class: 'Disciplina', priority: 'Prioridade',
    editTask: 'Editar tarefa', moveLeft: 'Mover para a esquerda', moveRight: 'Mover para a direita',
    addToKanban: 'Adicionar ao Kanban', themeLight: 'Tema claro', themeDark: 'Tema escuro', themeSystem: 'Tema do sistema',
    addPartTitle: 'Adicionar parte',
    fromWeek: 'Da semana', toWeek: 'Até à semana', dueDate: 'Data limite',
    other: 'Outro', noTasks: 'Sem tarefas esta semana.',
    whatNeedsDone: 'O que precisa de ser feito?',
    addTaskBtn: 'Adicionar tarefa', showOnCalendar: 'Mostrar no calendário',
    clearDone: 'Limpar concluídos', wipeAll: 'Apagar tudo',
    addCard: 'Adicionar cartão', addCardPlaceholder: 'Título do cartão',
    save: 'Guardar', cancel: 'Cancelar', confirm: 'Confirmar',
    semester: 'Semestre', classes: 'Disciplinas', gradeComponents: 'Componentes de avaliação',
    kanbanColumns: 'Colunas do Kanban', general: 'Geral', data: 'Dados e sincronização',
    holidays: 'Feriados',
    exportJson: 'Exportar JSON', importJson: 'Importar JSON',
    semesterAvg: 'Média do semestre', ectsPassedLabel: 'ECTS obtidos',
    targetGrade: 'Nota alvo',
    previousSemesters: 'Semestres anteriores',
    courseAvg: 'Média do curso', finalGrade: 'Nota final', previousAvg: 'Média anterior', numSemesters: 'Nº de semestres',
    getStarted: 'Começar', welcomeTitle: 'Bem-vindo ao Organizador',
    welcomeDesc: 'O teu espaço para a vida universitária. Configura o semestre e organiza-te.',
    step1: 'Define as datas do semestre', step2: 'Adiciona as tuas disciplinas', step3: 'Planeia tarefas e acompanha notas',
    shareLink: 'Copiar link de partilha', qrCode: 'Código QR', linkCopied: 'Link copiado!',
    high: 'Alta', medium: 'Média', low: 'Baixa', none: 'Nenhuma',
    addSemester: 'Adicionar semestre', semesterName: 'Nome do semestre', startDate: 'Data de início', endDate: 'Data de fim',
    weeks: n => `${n} semanas`, addAClass: 'Adicionar disciplina', className: 'Nome da disciplina', ects: 'ECTS', colour: 'Cor',
    addComponent: 'Adicionar componente', componentName: 'Nome do componente',
    taskSpanLabel: 'Comportamento de tarefas multi-semana', taskSpanDesc: 'Quando uma tarefa abrange várias semanas, como é marcada como concluída?',
    kanbanChecklistInlineLabel: 'Pré-visualização da checklist no Kanban',
    kanbanChecklistInlineDesc: 'Mostra os itens da checklist diretamente nos cartões sem abrir os detalhes.',
    kanbanChecklistPreviewNone: 'Ocultar nos cartões',
    kanbanChecklistPreviewAll: 'Mostrar em todos os cartões',
    kanbanChecklistPreviewPerCard: 'Caso a caso',
    focusAlertModeLabel: 'Modo de alerta no foco',
    focusAlertModeDesc: 'Escolhe como os alertas de foco aparecem quando a fase do cronómetro muda.',
    focusAlertNone: 'Nenhum',
    focusAlertVibration: 'Vibração',
    focusAlertNotification: 'Notificação',
    focusAlertBoth: 'Ambos',
    taskAlertModeLabel: 'Alertas de prazo das tarefas',
    taskAlertModeDesc: 'Escolhe como os alertas de prazo das tarefas são apresentados.',
    taskAlertNone: 'Nenhum',
    taskAlertInApp: 'Na app',
    taskAlertNotification: 'Notificação',
    taskAlertBoth: 'Ambos',
    taskAlertNextDayTimeLabel: 'Hora do alerta para amanhã',
    taskAlertNextDayTimeDesc: 'Hora dos lembretes para tarefas com prazo amanhã.',
    taskDueTodayTitle: count => count === 1 ? 'Tarefa para hoje' : `${count} tarefas para hoje`,
    taskAlertHide: 'Ocultar alerta',
    taskAlertRemindMeAt: 'Lembrar-me às',
    settingEnabled: 'Ativado', settingDisabled: 'Desativado',
    spanSingle: 'Uma checkbox global (concluída uma vez)', spanPerWeek: 'Checkbox por semana',
    dangerZone: 'Zona de perigo', deleteSemester: 'Eliminar este semestre',
    clearPomodoros: 'Limpar pomodoros',
    clearPomodorosTitle: 'Limpar todos os pomodoros?',
    clearPomodorosDesc: 'Todos os pomodoros caídos serão eliminados permanentemente.',
    deleteSemesterTitle: 'Eliminar semestre?', deleteSemesterDesc: 'Todas as tarefas, notas e dados do Kanban deste semestre serão eliminados permanentemente.',
    clearDoneTitle: 'Limpar coluna concluída?', clearDoneDesc: 'Todos os cartões da coluna Concluído serão eliminados.',
    wipeAllTitle: 'Apagar todos os cartões?', wipeAllDesc: 'Todos os cartões do quadro serão eliminados permanentemente.',
    selectSemester: 'Selecionar semestre', noClassesYet: 'Ainda sem disciplinas', addClassesInSettings: 'Adiciona disciplinas em Definições.',
    addUnlocks: 'Adiciona um semestre para desbloquear o resto.',
    checklist: 'Lista de verificação', addItem: 'Adicionar item', editCard: 'Editar cartão',
    notAchievable: '— impossível de atingir', onRemaining: ' nas componentes restantes',
    youNeed: 'Precisas de', allGraded: 'Todas as componentes avaliadas.',
    noGradeComponents: 'Nenhuma componente configurada. Vai a Definições.',
    deleteClassTitle: 'Eliminar disciplina?', deleteClassDesc: 'Isto irá também eliminar todas as tarefas desta disciplina.',
    holidayName: 'Nome do feriado', holidayNamePlaceholder: 'ex. Natal',
    addHoliday: 'Adicionar feriado',
    loadPreset: 'Carregar preset',
    presetLoading: 'A carregar preset…', presetError: 'Falhou ao carregar o preset.', retry: 'Tentar novamente', skip: 'Saltar',
    newColumnName: 'Nome da nova coluna',
    focusStart: 'Iniciar', focusPause: 'Pausar', focusResume: 'Retomar', focusReset: 'Reiniciar', focusSkipBreak: 'Saltar pausa',
    focusReady: 'pronto', focusBreak: 'pausa',
    focusPhrases: ['continua', 'mantém o foco', 'estás a ir bem', 'um passo de cada vez', 'trabalho profundo', 'fica presente'],
    focusEvery: 'cada (min)', focusBreakFor: 'pausa (min)',
    focusScheduledMode: 'Pausas agendadas',
    focusNextBreak: 'Próxima pausa às',
    focusFocusLabel: 'Mensagem de foco', focusBreakLabel: 'Mensagem de pausa',
    loadPresetTitle: 'Carregar um preset',
    presetGroupEI: 'Curso EI',
    presetGroupGeneric: 'Geral',
    backToMenu: 'Voltar',
    importData: 'Importar dados',
    importFromFirebase: 'Importar do Firebase',
    nextSemesterTitle: 'Semestre terminado',
    nextSemesterDesc: 'O teu semestre terminou. Carregar o próximo?',
    loadNextSemester: 'Carregar próximo semestre',
    dismissNextSemester: 'Dispensar',
    noSemesterYet: 'Nenhum semestre configurado',
    noSemesterDesc: 'Carrega um preset ou importa os teus dados para começar.',
    focusIntervalMode: 'Pausas por intervalo',
    focusIntervalEvery: 'cada (min)',
    focusIntervalBreakFor: 'pausa (min)',
    focusScheduledBreakFor: 'pausa (min)',
    firebaseSync: 'Sincronização Firebase',
    firebaseConnect: 'Ligar',
    firebaseConnected: 'Ligado',
    firebaseDisconnect: 'Desligar',
    firebaseSyncing: 'A sincronizar…',
    firebaseLastSync: 'Última sincronização',
    firebaseError: 'Erro de sincronização',
    firebaseSetupTitle: 'Ligar ao Firebase',
    firebaseStep1Title: 'Criar um projeto Firebase',
    firebaseStep1Desc: 'Vai a console.firebase.google.com → Adicionar projeto → dá um nome → desativa o Google Analytics → Criar projeto.',
    firebaseStep2Title: 'Ativar o Firestore',
    firebaseStep2Desc: 'Vai a Criar → Firestore Database → Criar base de dados → escolhe uma região → Iniciar em modo de produção → Criar. Depois vai a Regras, substitui o conteúdo por: allow read, write: if true; e clica em Publicar.',
    firebaseStep3Title: 'Obter a configuração',
    firebaseStep3Desc: 'Vai às Definições do projeto (ícone de engrenagem) → As tuas apps → Adicionar app → Web → regista a app → copia o objeto firebaseConfig mostrado.',
    firebaseStep4Title: 'Cola a configuração',
    firebaseStep4Desc: 'Cola o objeto firebaseConfig completo (em JSON) abaixo.',
    firebaseConfigPlaceholder: '{ "apiKey": "...", "authDomain": "...", "projectId": "...", ... }',
    firebaseConfigInvalid: 'Configuração inválida — deve incluir apiKey e projectId.',
    firebaseTestFailed: 'Não foi possível ligar. Verifica a configuração e as regras da base de dados.',
    firebaseSave: 'Guardar e ligar',
    pomodoroMode: 'Modo pomodoro',
    pomodoroModeDesc: 'Faz crescer tomates durante as sessões de foco. Cada sessão completa deixa cair um tomate.',
    pomodoroResetPeriod: 'Período de reset',
    pomodoroResetDay: 'Diário', pomodoroResetWeek: 'Semanal', pomodoroResetMonth: 'Mensal', pomodoroResetSemester: 'Por semestre',
    pomodoroTrackPeriodStats: 'Guardar estatísticas do período',
    pomodoroShowAbandoned: 'Mostrar tomates abandonados',
    pomodoroShowPeriodPomodoros: 'Mostrar pomodoros do período',
    pomodoroStatsTitle: 'Estatísticas pomodoro',
    pomodoroTotal: 'Total de tomates', pomodoroAbandoned: 'Abandonados', pomodoroFocusTime: 'Tempo total de foco',
    pomodoroPeriodTotal: 'Este período', pomodoroPeriodFocus: 'Foco neste período',
    pomodoroVsSinceLast: 'vs período anterior',
    pomodoroAllTime: 'Todo o tempo',
    pomodoroInsightsDailyTitle: 'Foco diário desta semana',
    pomodoroInsightsWeeklyBreakdownTitle: 'Média por semana',
    pomodoroInsightsAvgWeekLabel: 'média por dia (semana)',
    pomodoroInsightsAvgPeriodLabel: 'média por dia (período)',
    pomodoroInsightsPerDaySuffix: '/d',
    pomodoroInsightsNoWeeklyData: 'Ainda sem dados semanais.',
    pomodoroInsightsDayLabels: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'],
    pomodoroTotalTimeLabel: 'tempo total',
    pomodoroClose: 'Fechar',
    pomodoroEraseStats: 'Apagar estatísticas',
    pomodoroEraseStatsTitle: 'Apagar estatísticas pomodoro?',
    pomodoroEraseStatsDesc: 'As estatísticas históricas de tempo de foco serão removidas, mas os registos de tomates mantêm-se.',
    pomodoroGraceCancel: 'Cancelar (sem tomate)',
    pomodoroGrace: s => `${s}s para cancelar sem perder um tomate`,
    workModeLabel: 'Modo trabalho',
    workModeDesc: 'Oculta notas e renomeia disciplinas para grupos.',
    workModeOnboarding: 'Usar para trabalho?',
    groups: 'Grupos', addAGroup: 'Adicionar grupo', groupName: 'Nome do grupo',
    deleteGroupTitle: 'Eliminar grupo?', deleteGroupDesc: 'Isto irá também eliminar todas as tarefas deste grupo.',
    storageWarningTitle: 'Limite de armazenamento atingido',
    storageWarningDesc: 'Por favor ativa a sincronização Firebase, atingiste o limite de armazenamento local.',
    storageWarningAction: 'Percebido',
    collabConnect: 'Ligar Organizer Collab',
    collabDisconnect: 'Desligar Organizer Collab',
    collabRequiresFirebase: 'Liga primeiro a sincronização Firebase para usar o Organizer Collab.',
    collabGuideTitle: 'Configuração do Organizer Collab',
    collabGuideIntro: 'Configuração única. Faz estes 4 passos no Firebase e depois volta para ativar o collab.',
    collabGuideImportantTitle: 'O que muda quando ativas collab',
    collabGuideImportant1: 'A base de dados passa a exigir utilizadores autenticados (anónimo chega).',
    collabGuideImportant2: 'A sincronização normal do organizer continua a funcionar, mas autentica primeiro.',
    collabGuideImportant3: 'Se desligares collab mais tarde, podes continuar com regras baseadas em auth sem problemas.',
    collabGuideStep1: 'Abre Firebase Console > Build > Firestore Database > Regras.',
    collabGuideStep2: 'Cola o snippet de regras abaixo e clica em Publicar.',
    collabGuideStep3: 'Abre Security > Authentication > Método de início de sessão > ativa Anónimo > Guardar.',
    collabGuideStep4: 'Volta ao Organizer e carrega em "Já configurei as regras, ativar collab".',
    collabGuideRulesLabel: 'Regras Firestore',
    collabGuideTroubleshootTitle: 'Se aparecer erro signUp 400',
    collabGuideTroubleshootBody: 'Significa que a autenticação Anónima ainda está desativada no Firebase. Ativa em Security > Authentication > Método de início de sessão.',
    collabEnableNow: 'Já configurei as regras, ativar collab',
    collabPanelTitle: 'Organizer Collab',
    collabPanelSubtitle: 'Cria equipas, convida pessoas e partilha tarefas/cartões do kanban.',
    collabCreateTeam: 'Criar equipa',
    collabTeamName: 'Nome da equipa',
    collabTeamDays: 'dias da equipa',
    collabTeamDuration: 'duração da equipa',
    collabDays: 'dias',
    collabJoinTeam: 'Entrar na equipa',
    collabInvitePlaceholder: 'Cola o link de convite',
    collabInviteTtl: 'Validade do convite',
    collabYourTeams: 'As tuas equipas',
    collabNoTeams: 'Ainda sem equipas.',
    collabRoleHost: 'host',
    collabRoleMember: 'membro',
    collabEndsAt: 'termina em',
    collabInvite: 'Convidar',
    collabEditTeam: 'Editar equipa',
    collabTaskCompletionMode: 'Conclusão de tarefas partilhadas',
    collabTaskCompletionPersonal: 'conclusão pessoal',
    collabTaskCompletionForAll: 'marcar para todos',
    collabTaskPermissions: 'Permissões de edição de tarefas',
    collabTaskPermissionsEveryone: 'qualquer membro pode adicionar/editar/remover tarefas',
    collabTaskPermissionsHostOnly: 'apenas o host pode adicionar/editar/remover tarefas',
    collabLeave: 'Sair',
    collabDeleteTeam: 'Eliminar',
    collabDefaultTeamName: 'Equipa',
    collabLeavePrompt: 'Sair desta equipa?',
    collabLeaveWithLocalPrompt: 'Partilhaste tarefas locais nesta equipa. Queres mantê-las localmente?',
    collabDeleteTeamPrompt: 'Eliminar esta equipa?',
    collabDeleteTeamWithLocalPrompt: 'Partilhaste tarefas locais nesta equipa. Queres mantê-las localmente antes de eliminar a equipa?',
    collabKeepLocalTasks: 'Manter locais',
    collabDeleteLocalTasksToo: 'Apagar as locais',
    collabErrorCreate: 'Não foi possível criar a equipa.',
    collabErrorInvite: 'Não foi possível gerar convite.',
    collabErrorJoin: 'Não foi possível entrar na equipa.',
    collabErrorInvalidLink: 'Link de convite inválido.',
    collabErrorDeleteTeam: 'Não foi possível eliminar a equipa.',
  },
}

export function useStrings(lang) {
  return STRINGS[lang] ?? STRINGS.en
}
