export const cs = {
    months: ['Leden', 'Únor', 'Březen', 'Duben', 'Květen', 'Červen', 'Červenec', 'Srpen', 'Září', 'Říjen', 'Listopad', 'Prosinec'],
    weekdaysShort: ['Po', 'Út', 'St', 'Čt', 'Pá', 'So', 'Ne'],
    weekdays: ['Pondělí', 'Úterý', 'Středa', 'Čtvrtek', 'Pátek', 'Sobota', 'Neděle'],
    tasks: 'Úkoly', kanban: 'Kanban', grades: 'Známky', calendar: 'Kalendář', focus: 'Soustředění', settings: 'Nastavení',
    noSemester: 'Žádný semestr nenastaven', goToSettings: 'Přejděte do Nastavení a začněte.',
    weekLabel: w => `Týden ${w}`, done: 'hotovo', timeToRelax: 'Čas na odpočinek!',
    addTask: 'Nový úkol', task: 'Úkol', class: 'Předmět', priority: 'Priorita',
    editTask: 'Upravit úkol', moveLeft: 'Posunout vlevo', moveRight: 'Posunout vpravo', markDone: 'Označit hotové',
    addToKanban: 'Přidat do Kanbanu', themeLight: 'Světlý motiv', themeDark: 'Tmavý motiv', themeSystem: 'Systémový motiv',
    fromWeek: 'Od týdne', toWeek: 'Do týdne', dueDate: 'Termín',
    other: 'Ostatní', noTasks: 'Tento týden žádné úkoly.',
    whatNeedsDone: 'Co je potřeba udělat?',
    addTaskBtn: 'Přidat úkol', showOnCalendar: 'Zobrazit v kalendáři', showOnTasks: 'Zobrazit v úkolech',
    clearDone: 'Vymazat hotové', wipeAll: 'Smazat vše',
    addCard: 'Přidat kartu', addCardPlaceholder: 'Název karty',
    save: 'Uložit', cancel: 'Zrušit', confirm: 'Potvrdit', delete: 'Smazat',
    addEvent: 'Přidat událost', newEvent: 'Nová událost', editEvent: 'Upravit událost',
    eventTitle: 'Název události', eventDate: 'Datum', eventRange: 'Rozsah dat',
    more: 'více', add: 'Přidat',
    apps: 'Aplikace', notes: 'Poznámky', collabApp: 'Spolupráce',
    notesEnable: 'Zapnout Poznámky', notesNew: 'Nová poznámka', notesTitle: 'Název', notesSearch: 'Hledat poznámky',
    semester: 'Semestr', classes: 'Předměty', gradeComponents: 'Složky známky',
    kanbanColumns: 'Sloupce Kanbanu', general: 'Obecné', data: 'Data a synchronizace',
    holidays: 'Prázdniny',
    getStarted: 'Začít', standby: 'Pohotovost', standbyEnable: 'Zapnout pohotovost na šířku',
    standbyDesc: 'Otočte telefon na šířku pro zobrazení nástěnky.',
    standbyPanels: 'Panely', standbyPane: n => `Panel ${n}`,
    standbyPaneSecond: 'Druhá karta (přejetí)', standbyPaneNone: 'Žádná',
    paneWheel: 'Kolo pokroku', paneWheelTime: 'Kolo + hodiny', paneCalendar: 'Kalendář',
    paneFocus: 'Soustředění', paneKanban: 'Kanban', paneTasksByCategory: 'Úkoly podle kategorie',
    high: 'Vysoká', medium: 'Střední', low: 'Nízká', none: 'Žádná',
    checklist: 'Kontrolní seznam', addItem: 'Přidat položku', editCard: 'Upravit kartu',
    focusStart: 'Start', focusPause: 'Pauza', focusResume: 'Pokračovat', focusReset: 'Reset', focusSkipBreak: 'Přeskočit pauzu',
    focusReady: 'připraven', focusBreak: 'pauza',
    focusPhrases: ['pokračuj', 'vydrž', 'daří se ti skvěle', 'krok za krokem', 'hluboká práce', 'buď přítomný'],
    obNext: 'Další', obBack: 'Zpět', obFinish: 'Dokončit', obSkip: 'Přeskočit',
    welcomeTitle: 'Vítejte v organizátoru',
}
