export const cs = {
    months: ['leden', 'únor', 'březen', 'duben', 'květen', 'červen', 'červenec', 'srpen', 'září', 'říjen', 'listopad', 'prosinec'],
    weekdaysShort: ['pon', 'úte', 'stř', 'čtv', 'pát', 'sob', 'ned'],
    weekdays: ['pondělí', 'úterý', 'středa', 'čtvrtek', 'pátek', 'sobota', 'neděle'],
    tasks: 'Úkoly', kanban: 'Kanban', grades: 'Známky', calendar: 'Kalendář', focus: 'Fokus', settings: 'Nastavení',
    guides: 'Návody',
    noSemester: 'Žádný semestr nenastaven', goToSettings: 'Přejděte do Nastavení a začněte.',
    weekLabel: w => `Týden ${w}`, done: 'hotovo', timeToRelax: 'Čas na odpočinek!',
    addTask: 'Nový úkol', task: 'Úkol', class: 'Předmět', priority: 'Priorita',
    editTask: 'Upravit úkol', moveLeft: 'Posunout vlevo', moveRight: 'Posunout vpravo', markDone: 'Označit hotové',
    addToKanban: 'Přidat do Kanbanu', themeLight: 'Světlý motiv', themeDark: 'Tmavý motiv', themeSystem: 'Systémový motiv',
    fromWeek: 'Od týdne', toWeek: 'Do týdne', dueDate: 'Termín',
    other: 'Ostatní', noTasks: 'Tento týden žádné úkoly.',
    whatNeedsDone: 'Co je potřeba udělat?',
    addTaskBtn: 'Přidat úkol', showOnCalendar: 'Zobrazit v kalendáři', showOnTasks: 'Zobrazit v úkolech',
    clearDone: 'Vymazat hotové', wipeAll: 'Smazat vše',
    addCard: 'Přidat kartu', addCardPlaceholder: 'Název karty',
    save: 'Uložit', cancel: 'Zrušit', confirm: 'Potvrdit', delete: 'Smazat',
    addEvent: 'Přidat událost', newEvent: 'Nová událost', editEvent: 'Upravit událost',
    eventTitle: 'Název události', eventDate: 'Datum', eventRange: 'Rozsah dat',
    more: 'více', add: 'Přidat',
    apps: 'Aplikace', notes: 'Poznámky', collabApp: 'Spolupráce',
    notesEnable: 'Zapnout Poznámky', notesNew: 'Nová poznámka', notesTitle: 'Název', notesSearch: 'Hledat poznámky',
    semester: 'Semestr', classes: 'Předměty', gradeComponents: 'Složky známky',
    kanbanColumns: 'Sloupce Kanbanu', general: 'Obecné', data: 'Data a synchronizace',
    holidays: 'Prázdniny',
    getStarted: 'Začít', standby: 'Pohotovost', standbyEnable: 'Zapnout pohotovost na šířku',
    standbyDesc: 'Otočte telefon na šířku pro zobrazení nástěnky.',
    standbyPanels: 'Panely', standbyPane: n => `Panel ${n}`,
    standbyPaneSecond: 'Druhá karta (přejetí)', standbyPaneNone: 'Žádná',
    paneWheel: 'Kolo pokroku', paneWheelTime: 'Kolo + hodiny', paneCalendar: 'Kalendář',
    paneFocus: 'Soustředění', paneKanban: 'Kanban', paneTasksByCategory: 'Úkoly podle kategorie',
    high: 'Vysoká', medium: 'Střední', low: 'Nízká', none: 'Žádná',
    checklist: 'Kontrolní seznam', addItem: 'Přidat položku', editCard: 'Upravit kartu',
    focusStart: 'Spustit', focusPause: 'Pauza', focusResume: 'Pokračovat', focusReset: 'Resetovat', focusSkipBreak: 'Přeskočit pauzu',
    focusReady: 'připraven', focusBreak: 'pauza',
    focusPhrases: ['pokračuj', 'vydrž', 'daří se ti skvěle', 'krok za krokem', 'hluboká práce', 'buď přítomný'],
    obNext: 'Další', obBack: 'Zpět', obFinish: 'Dokončit', obSkip: 'Přeskočit',
    welcomeTitle: 'Vítejte v organizátoru',

    nlpToday: ["today"],
    nlpTomorrow: ["tomorrow"],
    nlpNextWeek: ["next week"],
    nlpAt: ["at"],
    nlpDow: [["sunday","sun"],["monday","mon"],["tuesday","tue"],["wednesday","wed"],["thursday","thu"],["friday","fri"],["saturday","sat"]],
    addPartTitle: "Přidat část",
    voiceInputAria: "Dictate by voice",
    voiceInputStopAria: "Stop dictation",
    quickActionTaskWordsPlural: ['úkoly'],
    quickActionEventWordsPlural: ['události v kalendáři', 'události'],
    quickActionCardWordsPlural: ['kanban karty', 'karty'],
    quickActionRespectivelyWords: ['respektive', 'v tomto pořadí'],
    quickActionOrdinalWords: ['první', 'druhý', 'třetí', 'čtvrtý', 'pátý', 'šestý', 'sedmý', 'osmý', 'devátý', 'desátý', 'druhá', 'třetí', 'čtvrtá', 'pátá', 'šestá', 'sedmá', 'osmá', 'devátá', 'desátá'],
    eventMultiDay: "Více dní",
    eventColor: "Barva",
    eventNote: "Poznámka",
    eventNotePlaceholder: "Volitelná poznámka",
    eventAllDay: "All day",
    eventStartTime: "Start time",
    eventEndTime: "End time",
    viewDay: "Den",
    viewWeek: "Týden",
    viewMonth: "Měsíc",
    viewYear: "Rok",
    navbar: "Navigační lišta",
    navHide: "Skrýt",
    navVisBoth: 'Viditelné na počítači i mobilu', navVisNone: 'Všude skryté', navVisDesktop: 'Pouze počítač', navVisMobile: 'Pouze mobil',
    navOverflow: "Přesunout do nabídky více",
    navAddButton: "Zobrazit tlačítko pro přidání úkolu",
    navMore: "Více",
    navLabelMode: "Zobrazit",
    navLabelBoth: "Ikony + názvy",
    navLabelIcons: "Pouze ikony",
    navLabelNames: "Pouze názvy",
    navAddLabel: "Přidat",
    navDrag: "Přetažením změníte pořadí",
    appDisableTitle: "Vypnout a smazat data?",
    appDisableDesc: "Vypnutím této aplikace trvale smažete všechna její data.",
    collabDisableDesc: "Odpojením opustíte všechny týmy a trvale odstraníte data spolupráce z tohoto zařízení.",
    navAddAction: "Akce tlačítka přidat",
    navAddPicker: "Zeptat se pokaždé",
    navFolders: "Složky",
    navNewFolder: "Nová složka",
    navMobilePosition: "Umístění lišty na mobilu",
    navPosBottom: "Dolní lišta",
    navPosSide: "Boční lišta",
    addToTasks: "Přidat do úkolů",
    inTasks: "V úkolech",
    standbyLeft: "Levý panel",
    standbyCenter: "Střední panel",
    standbyRight: "Pravý panel",
    notesLastEdit: "Upraveno",
    notesFolder: "Složka",
    notesNoFolder: "Bez složky",
    notesNewFolder: "Nová složka",
    notesFolderName: "Název složky",
    notesRenameFolder: "Přejmenovat složku",
    notesDeleteFolder: "Smazat složku",
    notesMoveTo: "Přesunout do",
    chunkLoadError: "Tuto část se nepodařilo načíst.",
    chunkRetry: "Zkusit znovu",
    notesEdit: "Upravit",
    notesPreview: "Náhled",
    notesBack: "Zpět",
    appsSearch: "Hledat aplikace",
    appsNoResults: "Žádné aplikace nenalezeny.",
    notesEnableDesc: "Přidá záložku Poznámky pro rychlé textové poznámky.",
    notesBody: "Napište něco…",
    notesEmpty: "Zatím žádné poznámky.",
    notesFavorite: "Oblíbené",
    notesText: "Text",
    notesCanvas: "Rukopis",
    notesMentionNoResults: "No matching tasks",
    notesMentionDeletedTask: "Deleted task",
    notesArchive: "Archive",
    notesUnarchive: "Unarchive",
    notesArchived: "Archived",
    notesArchivedEmpty: "No archived notes.",
    eisenhower: "Eisenhowerova matice",
    eisenhowerEnable: "Zapnout Eisenhowerovu matici",
    eisenhowerEnableDesc: "Přidá kartu pro řazení úkolů podle naléhavosti a důležitosti.",
    eisenhowerDoNow: "Naléhavé a důležité",
    eisenhowerSchedule: "Důležité, ne naléhavé",
    eisenhowerDelegate: "Naléhavé, ne důležité",
    eisenhowerEliminate: "Ani jedno",
    eisenhowerUnsorted: "Nezařazené úkoly",
    eisenhowerUnsortedEmpty: "Není co řadit.",
    eisenhowerEmpty: "Přetáhni úkoly sem.",
    eiCalendar: "Kalendář EI",
    eiCalendarEnable: "Zobrazit kalendář EI",
    eiCalendarEnableDesc: "Přidá do kalendáře oficiální kalendář kurzu EI pro váš ročník, pouze ke čtení a vždy aktuální.",
    eiCalendarDisableTitle: "Skrýt kalendář EI?",
    eiCalendarDisableDesc: "Přestane zobrazovat události kalendáře EI. Nic se nesmaže a můžete jej kdykoli znovu zapnout.",
    exportJson: "Exportovat JSON",
    importJson: "Importovat JSON",
    semesterAvg: "Průměr semestru",
    ectsPassedLabel: "Splněné ECTS",
    targetGrade: "Cílová známka",
    previousSemesters: "Předchozí semestry",
    courseAvg: "Průměr studia",
    finalGrade: "Konečná známka",
    previousAvg: "Předchozí průměr",
    numSemesters: "Počet semestrů",
    welcomeDesc: "Váš prostor pro studium. Nastavte si semestr a získejte přehled.",
    step1: "Nastavte data semestru",
    step2: "Přidejte své předměty",
    step3: "Plánujte úkoly a sledujte známky",
    obWelcomeTitle: "Vítejte do Organizer",
    obWelcomeDesc: "Vaše klidné místo pro práci. Pro začátek si vyberte váš jazyk a motiv.",
    obModeTitle: "Jak ho budete používat?",
    obModeDesc: "Zaškrtněte co vám vyhovuje. Mohou být zapnuté obě možnosti.",
    obModeWorkToggle: "Pracovní režim",
    obModeWorkToggleDesc: "Skupiny místo tříd, žádné známky.",
    obModeWeeksToggle: "Žádné semestry",
    obModeWeeksToggleDesc: "Zobrazení podle kalendářních týdnů.",
    obImportOr: "nebo obnovte zálohu",
    obDatesTitle: "Váš semestr",
    obDatesDesc: "Kdy začíná a končí?",
    obClassesTitle: "Vaše třídy",
    obClassesDesc: "Přidejte třídy které máte.",
    obGroupsTitle: "Vaše skupiny",
    obGroupsDesc: "Přidejte skupiny se kterými pracujete.",
    obInfoTasksTitle: "Úkoly & Kanban",
    obInfoTasksDesc: "Přidávejte úkoly podle týdnů nebo data a pak je přetahujte po své Kanban tabuli.",
    obInfoCalTitle: "Kalendář & soustředění",
    obInfoCalDesc: "Mějte o všem přehled v kalendáři a spusťte relace soustředění abyste dotáhli věci do konce.",
    obInfoDoneTitle: "Vše je připraveno",
    obInfoDoneDesc: "Všechno můžete později změnit v nastavení.",
    shareLink: "Odkaz ke sdílení",
    qrCode: "QR kód",
    linkCopied: "Odkaz zkopírován!",
    addSemester: "Přidat semestr",
    semesterName: "Název semestru",
    startDate: "Datum začátku",
    endDate: "Datum konce",
    weeks: n => `${n} ${n === 1 ? 'týden' : n < 5 ? 'týdny' : 'týdnů'}`,
    addAClass: "Přidat třídu",
    className: "Jméno třídy",
    ects: "ECTS",
    colour: "Barva",
    addComponent: "Přidat část",
    componentName: "Jméno části",
    taskSpanLabel: "Chování víceletýdenních úkolů",
    taskSpanDesc: "Jak se označí jako splněný úkol, který zabírá více týdnů?",
    kanbanChecklistInlineLabel: "Náhled seznamu na Kanbanu",
    kanbanChecklistInlineDesc: "Zobrazí položky seznamu přímo na kartách bez otevírání detailů.",
    kanbanChecklistPreviewNone: "Skrýt na kartách",
    kanbanChecklistPreviewAll: "Zobrazit na všech kartách",
    kanbanChecklistPreviewPerCard: "Případ od případu",
    kanbanAutoAddLabel: "Automaticky přidat úkoly na nástěnku",
    kanbanAutoAddDesc: "Automaticky přidá úkoly tohoto týdne do prvního sloupce na Kanban nástěnce.",
    widgetsLabel: 'Widgety na ploše',
    widgetsDesc: 'Zobrazí úkoly, dnešní den a počty na Kanban nástěnce přímo na ploše.',
    widgetsEncryptionWarning: 'Widgety nedokážou číst šifrovaná data. Pokud je zapneš, jejich obsah se v tomto zařízení uloží nešifrovaně. Smaže se při zamknutí aplikace.',
    gradeScaleLabel: "Klasifikační stupnice",
    gradeScaleDesc: "Nejvyšší možná známka. Pole pro známky jsou omezena touto hodnotou.",
    passingGradeLabel: "Známka pro splnění",
    passingGradeDesc: "Minimální známka pro splnění. Používá se pro označení splnění a jako výchozí cílová známka.",
    focusAlertModeLabel: "Režim upozornění soustředění",
    focusAlertModeDesc: "Zvolte, jak se doručují upozornění při změně fáze časovače.",
    focusAlertNone: "Žádné",
    focusAlertVibration: "Vibrace",
    focusAlertNotification: "Oznámení",
    focusAlertBoth: "Obojí",
    taskAlertModeLabel: "Upozornění na termíny úkolů",
    taskAlertModeDesc: "Zvolte, jak se doručují upozornění na termíny úkolů.",
    taskAlertNone: "Žádné",
    taskAlertInApp: "V aplikaci",
    taskAlertNotification: "Oznámení",
    taskAlertBoth: "Obojí",
    taskAlertNextDayTimeLabel: "Čas upozornění na zítřek",
    taskAlertNextDayTimeDesc: "Čas připomenutí úkolů s termínem zítra.",
    taskDefaultToCalendarLabel: "Úkoly v kalendáři ve výchozím stavu",
    taskDefaultToCalendarDesc: "New tasks will have \"Show on calendar\" enabled by default.",
    hideCompletedTasksLabel: "Uklidit hotové úkoly",
    hideCompletedTasksDesc: "Seznam zůstane zaměřený na to, co zbývá. Hotové úkoly se přesunou do sekce „Hotovo“, kterou můžeš kdykoli otevřít.",
    completedTasks: count => `Hotovo (${count})`,
    speechInputLabel: "Hlas na text",
    speechInputDesc: "Zobrazit tlačítko mikrofonu pro diktování textu v polích úkolů, událostí a poznámek.",
    taskDueTodayTitle: count => count === 1 ? 'Task due today' : `${count} tasks due today`,
    taskAlertHide: "Skrýt upozornění",
    taskAlertRemindMeAt: "Připomenout v",
    settingEnabled: "Zapnuto",
    settingDisabled: "Vypnuto",
    spanSingle: "Jedno společné zaškrtnutí (splněno jednou)",
    spanPerWeek: "Zaškrtnutí pro každý týden",
    dangerZone: "Nebezpečná zóna",
    deleteSemester: "Smazat tento semestr",
    clearPomodoros: "Vymazat pomodora",
    clearPomodorosTitle: "Vymazat všechna pomodora?",
    clearPomodorosDesc: "Všechna spadlá pomodora budou trvale smazána.",
    deleteSemesterTitle: "Smazat semestr?",
    deleteSemesterDesc: "Všechny úkoly, známky a data Kanbanu pro tento semestr budou trvale smazány.",
    clearDoneTitle: "Vymazat sloupec Hotovo?",
    clearDoneDesc: "Všechny karty ve sloupci Hotovo budou smazány.",
    wipeAllTitle: "Smazat všechny karty?",
    wipeAllDesc: "Každá karta na nástěnce bude trvale smazána.",
    selectSemester: "Vyberte semestr",
    noClassesYet: "Zatím žádné předměty",
    addClassesInSettings: "Předměty přidáte v Nastavení.",
    addUnlocks: "Přidejte semestr a odemkněte zbytek.",
    notAchievable: "— nedosažitelné",
    onRemaining: " ze zbývajících hodnocení",
    youNeed: "Potřebujete",
    allGraded: "Všechny složky ohodnoceny.",
    noGradeComponents: "Nejsou nastaveny žádné složky hodnocení. Přejděte do Nastavení.",
    deleteClassTitle: "Smazat předmět?",
    deleteClassDesc: "Tím se smažou i všechny úkoly tohoto předmětu.",
    holidayName: "Název svátku",
    holidayNamePlaceholder: "např. Vánoční prázdniny",
    addHoliday: "Přidat svátek",
    loadPreset: "Načíst předlohu",
    presetLoading: "Načítání předlohy…",
    presetError: "Nepodařilo se načíst předlohu.",
    retry: "Zkusit znovu",
    skip: "Přeskočit",
    newColumnName: "Název nového sloupce",
    focusEvery: "každých (min)",
    focusBreakFor: "pauza (min)",
    focusScheduledMode: "Naplánované pauzy",
    focusNextBreak: "Další pauza v",
    focusFocusLabel: "Zpráva při soustředění",
    focusBreakLabel: "Zpráva při pauze",
    loadPresetTitle: "Načíst předlohu",
    presetGroupEI: "Kurz EI",
    presetGroupGeneric: "Obecné",
    backToMenu: "Zpět",
    importData: "Importovat data",
    importFromFirebase: "Importovat z Firebase",
    nextSemesterTitle: "Semestr skončil",
    nextSemesterDesc: "Váš semestr skončil. Načíst další?",
    loadNextSemester: "Načíst další semestr",
    dismissNextSemester: "Zavřít",
    carryOverTitle: "Převést",
    carryKanbanCards: "Kanban karty",
    carryUpcomingTasks: "Nadcházející úkoly",
    carryUpcomingEvents: "Nadcházející události",
    carryOverAlwaysKept: "Poznámky a nastavení zůstávají vždy zachovány.",
    carryOverDiscardWarning: "Vše ostatní z tohoto semestru se smaže.",
    noSemesterYet: "Není nastaven žádný semestr",
    noSemesterDesc: "Načtěte předlohu nebo importujte data a začněte.",
    focusIntervalMode: "Pauzy v intervalech",
    focusIntervalEvery: "každých (min)",
    focusIntervalBreakFor: "pauza (min)",
    focusScheduledBreakFor: "pauza (min)",
    focusAfterBreakReset: "Po pauze: resetovat časovač",
    focusAfterBreakContinue: "Po pauze: pokračovat v počítání",
    firebaseSync: "Synchronizace Firebase",
    firebaseConnect: "Připojit",
    firebaseConnected: "Připojeno",
    firebaseDisconnect: "Odpojit",
    firebaseSyncing: "Synchronizuje se…",
    firebaseLastSync: "Poslední synchronizace",
    firebaseError: "Chyba synchronizace",
    firebaseRemoteNewer: "Data v cloudu pocházejí z novější verze aplikace. Synchronizace pozastavena. Aktualizujte aplikaci.",
    collabSyncFailed: "Sdílenou změnu se nepodařilo synchronizovat. Byla vrácena zpět.",
    newerVersionWarning: "Vaše data byla uložena novější verzí aplikace. Něco se nemusí zobrazit správně, dokud neaktualizujete.",
    firebaseSetupTitle: "Připojit Firebase",
    firebaseStep1Title: "Vytvořte projekt Firebase",
    firebaseStep1Desc: "Přejděte na console.firebase.google.com → Přidat projekt → zadejte libovolný název → vypněte Google Analytics → Vytvořit projekt.",
    firebaseStep2Title: "Zapněte Firestore",
    firebaseStep2Desc: 'Jdi na Build → Firestore Database → Vytvořit databázi → vyber region → Spustit v produkčním režimu → Vytvořit. Potom otevři záložku Pravidla, nahraď celý obsah pravidly níže a klikni na Publikovat.',
    firebaseStep3Title: "Získejte konfiguraci",
    firebaseStep3Desc: "Přejděte do Nastavení projektu (ikona ozubeného kola) → Vaše aplikace → Přidat aplikaci → Web → zaregistrujte aplikaci → zkopírujte zobrazený objekt firebaseConfig.",
    firebaseStep4Title: "Vložte konfiguraci",
    firebaseStep4Desc: "Vložte níže celý objekt firebaseConfig (jako JSON).",
    firebaseConfigPlaceholder: "{ \"apiKey\": \"...\", \"authDomain\": \"...\", \"projectId\": \"...\", ... }",
    firebaseConfigInvalid: "Neplatná konfigurace: musí obsahovat apiKey a projectId.",
    firebaseTestFailed: "Nepodařilo se připojit. Zkontrolujte konfiguraci a pravidla databáze.",
    firebaseSave: "Uložit a připojit",
    pomodoro: "Pomodoro",
    pomodoroOverlayFocusing: "soustředění",
    pomodoroMode: "Režim Pomodoro",
    pomodoroModeDesc: "Pěstuj rajčata během soustředění. Každé dokončené sezení shodí rajče.",
    pomodoroResetPeriod: "Období resetu",
    pomodoroResetDay: "Denně",
    pomodoroResetWeek: "Týdně",
    pomodoroResetMonth: "Měsíčně",
    pomodoroResetSemester: "Za semestr",
    pomodoroTrackPeriodStats: "Sledovat statistiky období",
    pomodoroShowAbandoned: "Zobrazit opuštěná rajčata",
    pomodoroShowPeriodPomodoros: "Zobrazit pomodora za období",
    pomodoroShowOverlay: "Zobrazit globální překryv přes všechny karty",
    focusNotifTitle: "Organizér Focus",
    focusNotifBreakBody: "Čas na pomodoro přestávku.",
    focusNotifFocusBody: "Zpátky k soustředění.",
    tasksNotifTitle: "Organizér Úkoly",
    taskReminderTitle: "Připomínka úkolu",
    pomodoroStatsTitle: "Statistiky pomodoro",
    pomodoroTotal: "Celkem rajčat",
    pomodoroAbandoned: "Opuštěná",
    pomodoroFocusTime: "Celkový čas soustředění",
    pomodoroPeriodTotal: "Toto období",
    pomodoroPeriodFocus: "Soustředění v tomto období",
    pomodoroVsSinceLast: "oproti minulému období",
    pomodoroAllTime: "Za celou dobu",
    pomodoroInsightsDailyTitle: "Denní soustředění tento týden",
    pomodoroInsightsWeeklyBreakdownTitle: "Týdenní průměry",
    pomodoroInsightsAvgWeekLabel: "průměr/den (týden)",
    pomodoroInsightsAvgPeriodLabel: "průměr/den (období)",
    pomodoroInsightsPerDaySuffix: "/d",
    pomodoroInsightsNoWeeklyData: "Zatím žádná týdenní data.",
    pomodoroInsightsDayLabels: ["N","P","Ú","S","Č","P","S"],
    pomodoroTotalTimeLabel: "celkový čas",
    pomodoroClose: "Zavřít",
    pomodoroEraseStats: "Smazat statistiky",
    pomodoroEraseStatsTitle: "Smazat statistiky pomodoro?",
    pomodoroEraseStatsDesc: "Historické statistiky času soustředění budou odstraněny, záznamy rajčat zůstanou.",
    pomodoroGraceCancel: "Zrušit (bez rajčete)",
    pomodoroGrace: s => `${s}s na zrušení bez ztráty rajčete`,
    pomodoroStreakTitle: "Série",
    pomodoroCurrentStreak: "Aktuální série",
    pomodoroBestStreak: "Nejlepší série",
    pomodoroStreakDaySuffix: "d",
    pomodoroTrendTitle: "Měsíční trend",
    pomodoroTrendNoData: "Zatím žádná měsíční data.",
    pomodoroCopySummary: "Kopírovat souhrn",
    pomodoroCopiedSummary: "Zkopírováno!",
    workModeLabel: "Pracovní režim",
    workModeDesc: "Skryje známky a přejmenuje předměty na skupiny.",
    workModeOnboarding: "Používáte to pro práci?",
    semesterModeLabel: "Režim bez semestrů",
    semesterModeDesc: "Zapněte pro použití běžných týdnů v roce místo semestrů. Známky budou skryté.",
    semesterModeNone: "Bez semestrů (týdny v roce)",
    semesterModeSemesters: "Používat semestry",
    semesterModeOnboarding: "Bez semestrů, jen týdny?",
    groups: "Skupiny", group: "Skupina",
    addAGroup: "Přidat skupinu",
    groupName: "Jméno skupiny",
    deleteGroupTitle: "Smazat skupinu?",
    deleteGroupDesc: "Tím se smažou i všechny úkoly této skupiny.",
    storageWarningTitle: "Dosažen limit úložiště",
    storageWarningDesc: "Aktivujte prosím synchronizaci Firebase, místní úložiště je plné.",
    storageWarningAction: "Rozumím",
    collabConnect: "Připojit Organizer Collab",
    collabDisconnect: "Odpojit Organizer Collab",
    collabRequiresFirebase: "Nejprve připojte synchronizaci Firebase, abyste mohli používat Organizer Collab.",
    collabGuideTitle: "Nastavení Organizer Collab",
    collabGuideIntro: "Jednorázové nastavení. Proveďte tyto 4 kroky ve Firebase, pak se vraťte a zapněte collab.",
    collabGuideImportantTitle: "Co se změní po zapnutí collabu",
    collabGuideImportant1: "Vaše databáze začne vyžadovat ověřené uživatele (anonymní ověření stačí).",
    collabGuideImportant2: "Běžná synchronizace Organizeru funguje dál, ale musí se nejdřív ověřit.",
    collabGuideImportant3: "Pokud collab později vypnete, pravidla založená na ověření lze i tak bezpečně používat.",
    collabGuideStep1: "Otevřete Firebase Console > Build > Firestore Database > Rules.",
    collabGuideStep2: "Vložte níže uvedená pravidla a klikněte na Publish.",
    collabGuideStep3: "Otevřete Security > Authentication > Sign-in method > zapněte Anonymous > Save.",
    collabGuideStep4: "Return to Organizer and press \"I configured rules, enable collab\".",
    collabGuideRulesLabel: "Pravidla Firestore",
    collabRulesHelpTitle: "Pravidla Firestore",
    collabRulesHelpHost: "Pravidla Firestore tvého týmu jsou zastaralá nebo příliš přísná. Vlož níže uvedená pravidla do konzole Firebase a obnov stránku.",
    collabRulesHelpMember: "K tomuto týmu se nelze připojit. Opravit to může jen hostitel — pošli mu níže uvedená pravidla, aby je vložil do své konzole Firebase.",
    copy: "Kopírovat",
    copied: "Zkopírováno!",
    collabGuideGotIt: "Rozumím",
    collabFirebaseOnlyForCreating: "Zapni spolupráci a sdílej úkoly s ostatními přes týmy. Firebase je potřeba jen k vytváření týmů.",
    collabGuideTroubleshootTitle: "Pokud vidíte chybu signUp 400",
    collabGuideTroubleshootBody: "To znamená, že anonymní ověření je ve Firebase stále vypnuté. Zapněte jej v Security > Authentication > Sign-in method.",
    collabEnableNow: "Pravidla jsou nastavena, zapnout collab",
    collabPanelTitle: "Organizer Collab",
    collabPanelSubtitle: "Vytvářejte týmy, zvěte lidi a sdílejte úkoly a karty Kanbanu.",
    collabCreateTeam: "Vytvořit tým",
    collabTeamName: "Název týmu",
    collabTeamDays: "dní týmu",
    collabTeamDuration: "trvání týmu",
    collabDays: "dní",
    collabJoinTeam: "Připojit se k týmu",
    collabInvitePlaceholder: "Vložte pozvánkový odkaz",
    collabInviteTtl: "Platnost pozvánky",
    collabYourTeams: "Vaše týmy",
    collabNoTeams: "Zatím žádné týmy.",
    collabRoleHost: "host",
    collabRoleMember: "člen",
    all: "Vše",
    collabAlias: "Tvoje jméno",
    collabEditAlias: "Upravit jméno",
    collabMembers: "Členové",
    collabAssignedOnlyComplete: "Dokončit může jen řešitel",
    collabKanbanDividers: "Oddělovače Kanbanu",
    collabSeparateByTeam: "Rozdělit podle týmu",
    collabPersonal: "Osobní",
    collabUnassigned: "Nepřiřazeno",
    collabMe: "Já",
    collabAssignee: "Řešitel",
    collabSeparateByClass: "Rozdělit podle předmětu",
    kanbanAllTeams: "Všechny týmy",
    kanbanAllAssignees: "Všichni řešitelé",
    kanbanAllClasses: "Všechny předměty",
    kanbanFilterTeam: "Tým",
    kanbanFilterClass: "Předmět",
    kanbanNoClass: "Bez předmětu",
    kanbanResetFilters: "Zrušit filtry",
    collabEndsAt: "končí",
    collabInvite: "Pozvat",
    collabEditTeam: "Upravit tým",
    collabTaskCompletionMode: "Dokončení sdílených úkolů",
    collabTaskCompletionPersonal: "osobní dokončení",
    collabTaskCompletionForAll: "přepnout pro všechny",
    collabTaskPermissions: "Oprávnění k úpravě úkolů",
    collabTaskPermissionsEveryone: "kdokoli může přidávat/upravovat/mazat úkoly",
    collabTaskPermissionsHostOnly: "úkoly může spravovat jen hostitel",
    collabLeave: "Opustit",
    collabDeleteTeam: "Smazat",
    collabDefaultTeamName: "Tým",
    collabLeavePrompt: "Opustit tento tým?",
    collabLeaveWithLocalPrompt: "V tomto týmu jste sdíleli místní úkoly. Ponechat je místně?",
    collabDeleteTeamPrompt: "Smazat tento tým?",
    collabDeleteTeamWithLocalPrompt: "V tomto týmu jste sdíleli místní úkoly. Ponechat je místně před smazáním týmu?",
    collabKeepLocalTasks: "Ponechat místní úkoly",
    collabDeleteLocalTasksToo: "Smazat místní úkoly",
    collabErrorCreate: "Nepodařilo se vytvořit tým.",
    collabErrorInvite: "Nepodařilo se vygenerovat pozvánku.",
    collabErrorJoin: "Nepodařilo se připojit k týmu.",
    collabErrorInvalidLink: "Neplatný pozvánkový odkaz.",
    collabErrorDeleteTeam: "Nepodařilo se smazat tým.",
    collabGuideChecklistTitle: "Stále se nesynchronizuje?",
    collabGuideChecklistBody: "Dva kroky, které za vás Organizer nemůže udělat: zapnout anonymní ověření a publikovat výše uvedená pravidla Firestore. Pokud se sdílené úkoly nikdy neobjeví, jeden z nich v hostitelském projektu chybí.",
    collabSyncErrorHint: "Tento tým je nedostupný. Zkontrolujte, že hostitelův Firebase má zapnuté anonymní ověření a otevřená pravidla.",
    collabKeyRequiredHint: "Tento tým je šifrovaný a tvůj pozvánkový odkaz neobsahoval klíč. Požádej o nový odkaz.",
    collabDeviceUnlinkedHint: "Toto zařízení zatím není k týmu připojeno. Otevři na něm pozvánku, aby se synchronizoval.",
    collabErrorPermission: "Blokováno pravidly Firebase. Hostitel musí zapnout anonymní ověření a otevřít pravidla Firestore.",
    collabErrorAuthDisabled: "Anonymní přihlášení je v hostitelově projektu Firebase vypnuté. Hostitel ho musí zapnout v Authentication › Sign-in method.",
    collabErrorNotFound: "Tým nenalezen. Mohl být smazán.",
    collabErrorInviteExpired: "Platnost této pozvánky vypršela. Požádejte hostitele o nový odkaz.",
    collabErrorInviteInvalid: "Tento pozvánkový odkaz pro daný tým neplatí.",
    firebaseRulesTemplateLink: "View Firestore rules template",
    firebaseOpenRulesWarningTitle: "Your database rules may be open",
    firebaseOpenRulesWarningDesc: "Sync is working without authentication, which usually means your Firestore rules allow anyone to read and write your data. Publish the rules template linked below to lock this down.",
    firebaseEncryptionOffTitle: "End-to-end encryption is off",
    firebaseEncryptionOffDesc: "Your data is stored in Firestore as plain text. Turn on encryption so only devices with your key can read it — even if your database rules are ever misconfigured.",
    firebaseEncryptNow: "Encrypt now",
    firebaseEncryptMigrateFailed: "Could not enable encryption. Check your connection and try again.",
    firebaseHaveKeyAlready: "This device already has a key from another install",
    firebaseKeyPastePlaceholder: "Paste your recovery key",
    firebaseKeyInvalid: "That does not look like a valid key.",
    firebaseKeyWrongOrUnreadable: "Could not decrypt with this key. Double check it and try again.",
    firebaseRecoveryKeyShownOnceTitle: "Save this recovery key now",
    firebaseRecoveryKeyShownOnceDesc: "This key is shown only once and is never sent to Firebase. Anyone with it can read your data; anyone without it (including you) cannot recover it if lost. Store it somewhere safe.",
    firebaseKeySavedItConfirm: "I've saved my key",
    firebaseEncryptionOnTitle: "End-to-end encryption is on",
    firebaseEncryptionOnDesc: "Tvá data jsou šifrována na tomto zařízení — v místním úložišti i před odesláním do Firestore. Dešifrovat je mohou jen zařízení s obnovovacím klíčem.",
    firebaseShowRecoveryKey: "Show recovery key",
    firebaseShowRecoveryKeyConfirmTitle: "Show recovery key?",
    firebaseShowRecoveryKeyConfirmDesc: "Anyone who sees this key can decrypt your data. Only do this somewhere private.",
    firebaseKeyRequiredTitle: "Encryption key needed",
    firebaseKeyRequiredDesc: "This project’s data is encrypted. Paste the recovery key from a device that already has it to unlock sync on this device.",
    firebaseKeyRequiredForImport: "This backup is encrypted. Set up sync with the matching key first, then import again.",
    exportEncrypted: "Organizer format (encrypted)",
    encUnlockTitle: "Odemkni svá data",
    encUnlockDesc: "Na tomto zařízení jsou zašifrovaná data. Zadej svou přístupovou frázi a odemkni je.",
    encUnlockHintLabel: "Tvá nápověda",
    encPassphraseLabel: "Přístupová fráze",
    encPassphrasePlaceholder: "Tvá přístupová fráze",
    encPassphraseConfirmLabel: "Potvrď přístupovou frázi",
    encPassphraseMismatch: "Přístupové fráze se neshodují.",
    encPassphraseTooShort: "Použij alespoň 8 znaků.",
    encHintLabel: "Nápověda k přístupové frázi (nepovinné)",
    encHintPlaceholder: "Soukromá připomínka, ne samotná fráze",
    encRecoveryCodeTitle: "Ulož si záložní kód",
    encRecoveryCodeDesc: "Těchto 12 anglických slov je jediná cesta zpět, pokud zapomeneš přístupovou frázi. Zapiš si je nebo je ulož do správce hesel. Znovu je nezobrazíme.",
    encRecoveryCodeWordsNote: "12 anglických slov. Opiš je přesně a ve správném pořadí.",
    encRecoveryCodeSavedConfirm: "Záložní kód mám uložený",
    encRecoveryCodeQr: "Zobrazit QR kód",
    encRecoveryCodeQrDesc: "Naskenuj ho na jiném zařízení a přenes tak záložní kód.",
    encUseRecoveryCode: "Použít záložní kód",
    encUsePassphrase: "Použít přístupovou frázi",
    encRecoveryCodeLabel: "Záložní kód",
    encRecoveryCodePlaceholder: "dvanáct slov oddělených mezerami",
    encRecoveryCodeInvalid: "Tohle není platný záložní kód z 12 slov.",
    encUnlockFailed: "Tímto se odemknout nepodařilo. Zkontroluj to a zkus to znovu.",
    encUnlocking: "Odemykám…",
    encDeriving: "Odvozuji klíč…",
    encEnableTitle: "Zapnout end-to-end šifrování",
    encEnableDesc: "Tvá data se zašifrují na tomto zařízení, ještě než se dostanou do Firestore. Přečtou je jen zařízení s tvou přístupovou frází nebo záložním kódem.",
    encEnableWarning: "Pokud ztratíš přístupovou frázi i záložní kód, tvá data už nikdo neobnoví, ani my.",
    encEnableSubmit: "Zapnout šifrování",
    encEnableFailed: "Šifrování se nepodařilo zapnout. Zkontroluj připojení a zkus to znovu.",
    encManageTitle: "Šifrování",
    encManageDesc: "Tvá data jsou šifrovaná end-to-end. Odemčení probíhá jen na tomto zařízení.",
    encChangePassphrase: "Změnit přístupovou frázi",
    encChangePassphraseDesc: "Zadej současnou přístupovou frázi a potom novou.",
    encCurrentPassphraseLabel: "Současná přístupová fráze",
    encRegenerateRecoveryCode: "Vygenerovat nový záložní kód",
    encRegenerateRecoveryCodeDesc: "Nahradí tvůj stávající kód. Ten starý přestane fungovat.",
    encEditHint: "Upravit nápovědu",
    encRotateDekTitle: "Otočit šifrovací klíč",
    encRotateDekDesc: "Znovu zašifruje všechna tvá data pod úplně novým klíčem. Ostatní zařízení bude potřeba znovu odemknout.",
    encRotateDekWarning: "Nezavírej aplikaci, dokud to neskončí.",
    encRotating: "Znovu šifruji…",
    encRotateFailed: "Klíč se nepodařilo otočit. Nic se nezměnilo.",
    encSaved: "Uloženo.",
    encStoreUnavailableTitle: "Bezpečné úložiště není dostupné",
    encStoreUnavailableDesc: "Tento prohlížeč zablokoval úložiště klíčů, což se často děje v anonymním režimu. Tvá zašifrovaná data zůstala nedotčená. Zkus to v běžném okně.",
    encPlaintextSyncWarnTitle: "Synchronizace není šifrovaná",
    encPlaintextSyncWarnDesc: "Tvá data jsou ve Firestore uložená jako čitelný text. Přečte je každý, kdo se dostane k tvé databázi.",
    encPlaintextSyncEnable: "Zapnout šifrování",
    encPlaintextSyncDismiss: "Teď ne a už se neptej",
    encRemoteAlreadyEncrypted: "Tento projekt je už zašifrovaný. Odemkni ho a připoj tak toto zařízení.",
    encRemoteNotEncryptedTitle: "Zašifrovat tento projekt?",
    encRemoteNotEncryptedDesc: "Tento projekt obsahuje nezašifrovaná data. Zapni šifrování a data se nahrají znovu, už zašifrovaná.",
    encRemoteNotEncryptedMigrate: "Zašifrovat a převést",
    encRemoteNotEncryptedSkip: "Nechat nezašifrované",
    encRemoteUnrecoverable: "Tento projekt je zašifrovaný, ale nemá žádná data pro obnovu, takže ho nelze odemknout. Odpoj se a začni nový projekt.",
    encRemoteDekMismatch: "Tento projekt byl znovu zašifrován novým klíčem. Odemkni ho znovu přístupovou frází nebo záložním kódem.",
    encExportPassphraseTitle: "Ochránit tuto záložní kopii",
    encExportPassphraseDesc: "Zvol pro soubor přístupovou frázi. Budeš ji potřebovat k obnovení, na jakémkoli zařízení.",
    encImportPassphraseTitle: "Odemknout tuto záložní kopii",
    encImportPassphraseDesc: "Zadej přístupovou frázi, kterou jsi zvolil při exportu.",
    encImportPassphraseFailed: "Špatná přístupová fráze pro tuto záložní kopii.",
    encTitle: "Šifrování",
    encOffTitle: "Šifrování je vypnuté",
    encOffDesc: "Tvá data se ukládají jako čitelný text všude, kde leží. Zapni šifrování a bez tvé přístupové fráze budou nečitelná — na tomto zařízení i všude, kam se synchronizují.",
    encOnDesc: "Tvá data se zašifrují ještě před uložením nebo synchronizací. Přečtou je jen zařízení s tvou přístupovou frází nebo záložním kódem.",
    encLockedDesc: "Tvá uložená data jsou zašifrovaná. Zadej přístupovou frázi a odemkni je na tomto zařízení.",
    encEnableAction: "Zapnout šifrování",
    encDisableAction: "Vypnout šifrování",
    encDisableTitle: "Vypnout šifrování?",
    encDisableDesc: "Tvá data se všude, kde jsou uložená, zapíšou znovu jako čitelný text a přístupová fráze i záložní kód přestanou fungovat.",
    encStorageShedTitle: "Některá data se nevešla",
    encStorageShedDesc: "Tomuto zařízení se vyčerpalo místní úložiště, takže se lokálně neuložilo toto:",
    exportPlaintext: "Human-readable (plaintext JSON)",
    repeat: "Opakovat",
    repeatFreqLabel: "Frekvence",
    repeatFreqDaily: "Denně",
    repeatFreqWeekly: "Týdně",
    repeatFreqMonthly: "Měsíčně",
    repeatEvery: () => 'Každý',
    repeatIntervalDaily: n => (n === 1 ? 'den' : n < 5 ? 'dny' : 'dní'),
    repeatIntervalWeekly: n => (n === 1 ? 'týden' : n < 5 ? 'týdny' : 'týdnů'),
    repeatIntervalMonthly: n => (n === 1 ? 'měsíc' : n < 5 ? 'měsíce' : 'měsíců'),
    repeatUntil: "Do (nepovinné)",
    kanbanColTodo: "Úkoly", kanbanColInProgress: "Řeší se", kanbanColDone: "Hotovo",
    colourCustom: "Vlastní barva",
    googleCalendar: "Google Calendar",
    gcalConnect: "Connect",
    gcalConnected: "Connected",
    gcalConnecting: "Connecting…",
    gcalDisconnect: "Disconnect",
    gcalEnable: "Sync with Google Calendar",
    gcalScopeNotice: "This grants full read/write access to your primary Google Calendar (the \"calendar\" scope). Organizer only reads and writes events you interact with here; your Google credentials never leave your device and are not sent anywhere but Google.",
    gcalStep1Title: "Create a Google Cloud project",
    gcalStep1Desc: "Go to console.cloud.google.com → create a new project (or pick one) → APIs & Services → enable the \"Google Calendar API\".",
    gcalStep2Title: "Configure OAuth consent + credentials",
    gcalStep2Desc: "APIs & Services → OAuth consent screen → set it up (External is fine for personal use, add yourself as a test user). Then Credentials → Create credentials → OAuth client ID → Application type: Web application → add this app's URL to Authorized JavaScript origins.",
    gcalStep3Title: "Paste your Client ID",
    gcalStep3Desc: "Copy the Client ID (ends in .apps.googleusercontent.com) shown after creating it, and paste it below. This value is not secret and is safe to store in this browser.",
    gcalClientIdPlaceholder: "xxxxxxxx.apps.googleusercontent.com",
    gcalClientIdInvalid: "Enter a valid OAuth Client ID.",
    gcalConnectFailed: "Could not connect. Check your Client ID and try again.",
    gcalDisableTitle: "Disconnect Google Calendar?",
    gcalDisableDesc: "Stops syncing with Google Calendar on this device. Events already created stay in both places; sync bookkeeping (Client ID, links) is removed here.",
    eventSyncToGoogle: "Sync to Google Calendar",
    eventSyncToGoogleDesc: "Push this event to your connected Google Calendar.",
    quickActionTaskWords: ["úkol","ukol"],
    quickActionEventWords: ["událost v kalendáři","udalost v kalendari","událost","udalost"],
    quickActionCardWords: ["kanban kartu","kanban karta","kartu","karta"],
    quickActionAddWords: ["přidej","pridej","přidat","pridat","vytvoř","vytvor","vytvořit","vytvorit"],
    quickActionForWords: ["pro","na"],
    quickActionAndWords: ["a"],
    quickActionOnWords: ["dne","v"],
    quickActionArticleWords: [],
    quickActionBoardWords: ["kanban","nástěnka","nastenka"],
    quickAction: "Quick action",
    quickActionPlaceholder: "e.g. add task and calendar event for a cbd test on 18/07 at 15h",
    quickActionTab: "Quick action",
    quickActionFormTab: "Form",
    quickActionPreviewTitle: "Will create",
    quickActionPreviewTask: "task",
    quickActionPreviewTaskCalendar: "task (shown on calendar)",
    quickActionPreviewEvent: "calendar event",
    quickActionPreviewCard: column => `kanban card in ${column}`,
    quickActionEmpty: "Couldn't understand that. Try rephrasing.",
    quickActionCreate: "Create",
    quickActionBack: "Back",
    notesDeleteConfirmTitle: "Delete this note?",
    notesDeleteConfirmDesc: "This note will be permanently deleted.",
    notesEmptyTitle: "No notes yet",
    notesEmptyDesc: "Create your first note to get started.",
    notesFilterEmpty: "No notes match your search.",
    notesSelectNote: "Select a note to start editing",
    notesTextNote: "Text note",
    notesCanvasNote: "Canvas note",
    eventStartTimeFirstDay: "Čas začátku (první den)",
    eventEndTimeLastDay: "Čas konce (poslední den)",
    notesBold: "Tučné",
    notesItalic: "Kurzíva",
    notesStrike: "Přeškrtnuté",
    notesHeading1: "Nadpis 1",
    notesHeading2: "Nadpis 2",
    notesHeading3: "Nadpis 3",
    notesBulletList: "Odrážkový seznam",
    notesOrderedList: "Číslovaný seznam",
    notesTaskList: "Kontrolní seznam",
    notesQuote: "Citace",
    notesInsertTable: "Vložit tabulku",
    notesCodeBlock: "Blok kódu",
    notesDivider: "Oddělovač",
    notesAddLink: "Přidat odkaz",
    notesRemoveLink: "Odebrat odkaz",
    notesTextColor: "Barva textu",
    notesColorReset: "Výchozí barva",
    notesColorCustom: "Vybrat vlastní barvu",
    notesColorApply: "Použít",
    notesExport: "Exportovat poznámku",
    notesImport: "Importovat poznámku",
    notesGraphEdit: "Upravit graf",
    notesGraphRange: "x od",
    notesGraphResize: "Tažením změň velikost",
    notesGraphResizeWidth: "Tažením změň šířku a výšku",
    notesGraphInvalid: "Výraz nelze vykreslit",
    notesGraphAlignleft: "Zarovnat vlevo",
    notesGraphAligncenter: "Na střed",
    notesGraphAlignright: "Zarovnat vpravo",
    notesTextSize: "Velikost textu",
    notesSizeNormal: "Normální",
    notesSizeSmall: "Malé",
    notesSizeLarge: "Velké",
    notesSizeHuge: "Obrovské",
    notesUndo: "Zpět",
    notesRedo: "Znovu",
    notesViewList: "Zobrazení seznamu",
    notesViewMosaic: "Dlaždicové zobrazení",
    notesMathEnable: "Řešení matematiky",
    notesMathEnableDesc: "Napiš rovnici zakončenou = a stiskni Enter pro vyřešení. Použij x pro vykreslení grafu.",
    notesMathSolve: "Vyřešit pro x",
    notesMathSolveDesc: "Změní 3x = 3 na x = 1, včetně nerovnic a kvadratických rovnic.",
    notesMathSelection: "Vykreslit výběr",
    notesMathSelectionDesc: "Označ rovnici a stiskni Enter pro její vykreslení.",
    notesMathSteps: "Zobrazit postup",
    notesMathStepsDesc: "Zobrazí každý krok řešení místo pouhého výsledku.",
    eisenhowerAddTask: "Přidat úkol",
    eisenhowerCustomize: "Upravit kvadranty",
    eisenhowerResetDefaults: "Obnovit výchozí",
    eisenhowerCleanDone: "Vymazat dokončené",
    eisenhowerCleanDoneTitle: "Vymazat dokončené úkoly?",
    eisenhowerCleanDoneDesc: "Odebere dokončené úkoly z matice. V seznamu úkolů zůstanou.",
    quickActionApp: "Quick Action",
    quickActionAppEnable: "Enable Quick Action",
    quickActionAppEnableDesc: "Adds a spotlight overlay for quickly creating tasks, events, and cards.",
    quickActionTripleTapEnable: "Trojité klepnutí na obrazovku", quickActionTripleTapEnableDesc: "Klepněte 3x kdekoli pro otevření Quick Action",
    quickActionShortcutEnable: "Keyboard shortcut",
    quickActionShortcutKey: "Shortcut",
    quickActionNavbarButton: "Show in navbar add menu",
    spotlightPlaceholder: "Quick action… (e.g. add task for exam on Monday)",
    themeColor: "Accent color",
    themeColorDesc: "Pick a color for buttons, links, and highlights.",
    themeColorReset: "Reset to default",
    themeFontColor: "Barva písma", themeHighlightColor: "Barva zvýraznění", themeBgColor: "Barva pozadí",
    defaultTabLabel: "Výchozí obrazovka", defaultTabDesc: "Vyber záložku, kterou se aplikace otevře.",
    defaultTabLast: "Naposledy použitá",
    taskReminderOffsetsLabel: "Předstih připomínek", taskReminderOffsetsDesc: "Kolik dní před termínem ti připomenout. Platí pro každý úkol s termínem.",
    taskReminderTimeLabel: "Čas připomínky", taskReminderTimeDesc: "Denní doba, kdy se předběžné připomínky spustí.",
    taskReminderAddOffset: "Dny",
    taskReminderOffsetDays: n => (n === 0 ? "V den termínu" : n === 1 ? "1 den předem" : `${n} dní předem`),
    taskReminderIn: n => (n === 0 ? "Termín dnes" : n === 1 ? "Termín zítra" : `Termín za ${n} dní`),
    habits: "Návyky", habitsEnable: "Zapnout Návyky", habitsEnableDesc: "Sleduj dlouhodobé návyky pomocí tlačítka a kalendáře sérií.",
    habitsEmpty: "Zatím žádné návyky. Přidej si první.",
    habitAdd: "Přidat návyk", habitEdit: "Upravit návyk",
    habitTitleLabel: "Návyk", habitTitlePlaceholder: "Číst 20 minut",
    habitCadenceLabel: "Zapsat", habitCadenceDesc: "Jak často chceš mačkat tlačítko.",
    habitCadenceDaily: "Každý den", habitCadence2Days: "Každé 2 dny", habitCadence3Days: "Každé 3 dny",
    habitCadenceWeekly: "Každý týden", habitCadenceMonthly: "Každý měsíc",
    habitRequireNote: "Zeptat se na poznámku", habitRequireNoteDesc: "Napiš krátkou poznámku při každém zápisu.",
    habitColor: "Barva",
    habitClickPrompt: "Označit jako splněné", habitDoneForNow: "Hotovo",
    habitNotePrompt: "Jak to šlo?", habitNotePlaceholder: "Pár slov",
    habitSeeProgress: "Zobrazit pokrok", habitUndoToday: "Vrátit tento zápis", habitDelete: "Smazat návyk",
    habitDeleteTitle: "Smazat tento návyk?", habitDeleteDesc: "Návyk i celá jeho historie budou odstraněny.",
    habitCurrentStreak: "Aktuální série", habitBestStreak: "Nejlepší série",
    habitTotalCheckIns: "Zápisy", habitCompletionRate: "Plnění",
    habitNotesTitle: "Poznámky",
    habitCadenceCustom: "Vlastní dny", habitWeekdaysLabel: "Dny v týdnu", habitWeekdaysDesc: "Vyber dny, kdy chceš zapisovat.", habitRestDay: "Den volna",
    habitToneLabel: "Styl povzbuzení", habitToneDesc: "Jakou zprávu dostaneš po každém zápisu.",
    habitTonePurpose: "Smysl a pokrok", habitToneWarm: "Vřelé a posilující",
    habitToneUpbeat: "Veselé a uspokojivé", habitToneGame: "Videohra",
    habitToneRandom: "Pokaždé náhodně", habitToneCustom: "Vlastní zpráva",
    habitToneCustomPlaceholder: "Tvoje zpráva",
    habitTargetLabel: "Cílová čára", habitTargetDesc: "Kdy se návyk počítá za dokončený.",
    habitTargetEndless: "Pokračovat dál", habitTargetCount: "Po počtu zápisů", habitTargetDate: "Do data",
    habitTargetCountPlaceholder: "Zápisy",
    habitTargetReached: "Návyk splněn.",
    habitTargetRemaining: n => (n === 1 ? "Zbývá 1 zápis" : `Zbývá ${n} zápisů`),
    habitTargetDaysLeft: n => (n === 0 ? "Poslední den" : n === 1 ? "Zbývá 1 den" : `Zbývá ${n} dní`),
    habitMessages: {
      purpose: {
        day1: "První zápis hotov. Cesta začíná.",
        early: "Vytrvalost roste den za dnem.",
        week: "7 dní v řadě kupředu.",
        month: "30 dní v řadě dokončeno.",
        daily: "Zase o den blíž ke svému dlouhodobému cíli.",
        rescue: "Dnes zpátky na správné cestě.",
      },
      warm: {
        day1: "Udělal jsi ten nejtěžší krok. Klobouk dolů.",
        early: "Dokazuješ si, že se na sebe můžeš spolehnout.",
        week: "Celý týden! Podívej, kam ses dostal.",
        month: "30 dní odhodlání. Vybudoval sis skutečný návyk.",
        daily: "Další pevný krok dnes.",
        rescue: "Dobře, že jsi zpět. Každý den je nová šance.",
      },
      upbeat: {
        day1: "Skvělý začátek!",
        early: "Další povedený den v záznamech!",
        week: "7 dní v řadě! Vynikající práce.",
        month: "30 dní! To je obrovský milník.",
        daily: "Odškrtnuto! Dobrý pocit.",
        rescue: "Dobře, že jsi zpět! Jedeme dál.",
      },
      game: {
        day1: "Úkol zahájen: úroveň 1 splněna.",
        early: "Combo aktivní. Získáno XP.",
        week: "Odemčen úspěch: Bojovník prvního týdne.",
        month: "Velký milník: boss poražen.",
        daily: "Denní úkol splněn +100 XP.",
        rescue: "Oživen. Získejme sérii zpátky.",
      },
    },
    collabShare: 'Sdílet',
    collabShareTask: 'Sdílet úkol',
    collabShareCard: 'Sdílet kartu',
    collabSelectTeam: 'Vybrat tým',
}
