export const cs = {
    months: ['Leden', 'Únor', 'Březen', 'Duben', 'Květen', 'Červen', 'Červenec', 'Srpen', 'Září', 'Říjen', 'Listopad', 'Prosinec'],
    weekdaysShort: ['Po', 'Út', 'St', 'Čt', 'Pá', 'So', 'Ne'],
    weekdays: ['Pondělí', 'Úterý', 'Středa', 'Čtvrtek', 'Pátek', 'Sobota', 'Neděle'],
    tasks: 'Úkoly', kanban: 'Kanban', grades: 'Známky', calendar: 'Kalendář', focus: 'Soustředění', settings: 'Nastavení',
    noSemester: 'Žádný semestr nenastaven', goToSettings: 'Přejděte do Nastavení a začněte.',
    weekLabel: w => `Týden ${w}`, done: 'hotovo', timeToRelax: 'Čas na odpočinek!',
    addTask: 'Nový úkol', task: 'Úkol', class: 'Předmět', priority: 'Priorita',
    editTask: 'Upravit úkol', moveLeft: 'Posunout vlevo', moveRight: 'Posunout vpravo', markDone: 'Označit hotové',
    addToKanban: 'Přidat do Kanbanu', themeLight: 'Světlý motiv', themeDark: 'Tmavý motiv', themeSystem: 'Systémový motiv',
    fromWeek: 'Od týdne', toWeek: 'Do týdne', dueDate: 'Termín',
    other: 'Ostatní', noTasks: 'Tento týden žádné úkoly.',
    whatNeedsDone: 'Co je potřeba udělat?',
    addTaskBtn: 'Přidat úkol', showOnCalendar: 'Zobrazit v kalendáři', showOnTasks: 'Zobrazit v úkolech',
    clearDone: 'Vymazat hotové', wipeAll: 'Smazat vše',
    addCard: 'Přidat kartu', addCardPlaceholder: 'Název karty',
    save: 'Uložit', cancel: 'Zrušit', confirm: 'Potvrdit', delete: 'Smazat',
    addEvent: 'Přidat událost', newEvent: 'Nová událost', editEvent: 'Upravit událost',
    eventTitle: 'Název události', eventDate: 'Datum', eventRange: 'Rozsah dat',
    more: 'více', add: 'Přidat',
    apps: 'Aplikace', notes: 'Poznámky', collabApp: 'Spolupráce',
    notesEnable: 'Zapnout Poznámky', notesNew: 'Nová poznámka', notesTitle: 'Název', notesSearch: 'Hledat poznámky',
    semester: 'Semestr', classes: 'Předměty', gradeComponents: 'Složky známky',
    kanbanColumns: 'Sloupce Kanbanu', general: 'Obecné', data: 'Data a synchronizace',
    holidays: 'Prázdniny',
    getStarted: 'Začít', standby: 'Pohotovost', standbyEnable: 'Zapnout pohotovost na šířku',
    standbyDesc: 'Otočte telefon na šířku pro zobrazení nástěnky.',
    standbyPanels: 'Panely', standbyPane: n => `Panel ${n}`,
    standbyPaneSecond: 'Druhá karta (přejetí)', standbyPaneNone: 'Žádná',
    paneWheel: 'Kolo pokroku', paneWheelTime: 'Kolo + hodiny', paneCalendar: 'Kalendář',
    paneFocus: 'Soustředění', paneKanban: 'Kanban', paneTasksByCategory: 'Úkoly podle kategorie',
    high: 'Vysoká', medium: 'Střední', low: 'Nízká', none: 'Žádná',
    checklist: 'Kontrolní seznam', addItem: 'Přidat položku', editCard: 'Upravit kartu',
    focusStart: 'Start', focusPause: 'Pauza', focusResume: 'Pokračovat', focusReset: 'Reset', focusSkipBreak: 'Přeskočit pauzu',
    focusReady: 'připraven', focusBreak: 'pauza',
    focusPhrases: ['pokračuj', 'vydrž', 'daří se ti skvěle', 'krok za krokem', 'hluboká práce', 'buď přítomný'],
    obNext: 'Další', obBack: 'Zpět', obFinish: 'Dokončit', obSkip: 'Přeskočit',
    welcomeTitle: 'Vítejte v organizátoru',

    nlpToday: ["today"],
    nlpTomorrow: ["tomorrow"],
    nlpNextWeek: ["next week"],
    nlpAt: ["at"],
    nlpDow: [["sunday","sun"],["monday","mon"],["tuesday","tue"],["wednesday","wed"],["thursday","thu"],["friday","fri"],["saturday","sat"]],
    addPartTitle: "Add part",
    voiceInputAria: "Dictate by voice",
    voiceInputStopAria: "Stop dictation",
    quickActionTaskWordsPlural: ['úkoly'],
    quickActionEventWordsPlural: ['události v kalendáři', 'události'],
    quickActionCardWordsPlural: ['kanban karty', 'karty'],
    quickActionRespectivelyWords: ['respektive', 'v tomto pořadí'],
    quickActionOrdinalWords: ['první', 'druhý', 'třetí', 'čtvrtý', 'pátý', 'šestý', 'sedmý', 'osmý', 'devátý', 'desátý', 'druhá', 'třetí', 'čtvrtá', 'pátá', 'šestá', 'sedmá', 'osmá', 'devátá', 'desátá'],
    eventMultiDay: "Multiple days",
    eventColor: "Color",
    eventNote: "Note",
    eventNotePlaceholder: "Optional note",
    eventAllDay: "All day",
    eventStartTime: "Start time",
    eventEndTime: "End time",
    viewDay: "Den",
    viewWeek: "Týden",
    viewMonth: "Měsíc",
    viewYear: "Rok",
    navbar: "Navbar",
    navHide: "Hide",
    navOverflow: "Move to more menu",
    navAddButton: "Show add-task button",
    navMore: "More",
    navLabelMode: "Show",
    navLabelBoth: "Icons + names",
    navLabelIcons: "Icons only",
    navLabelNames: "Names only",
    navAddLabel: "Add",
    navDrag: "Drag to reorder",
    appDisableTitle: "Disable and erase data?",
    appDisableDesc: "Turning this app off permanently deletes all its data.",
    collabDisableDesc: "Disconnecting leaves all teams and permanently removes collaboration data from this device.",
    navAddAction: "Add button action",
    navAddPicker: "Ask each time",
    navFolders: "Folders",
    navNewFolder: "New folder",
    navMobilePosition: "Mobile navbar position",
    navPosBottom: "Bottom bar",
    navPosSide: "Side bar",
    addToTasks: "Add to tasks",
    inTasks: "In tasks",
    standbyLeft: "Left pane",
    standbyCenter: "Center pane",
    standbyRight: "Right pane",
    notesLastEdit: "Edited",
    notesFolder: "Folder",
    notesNoFolder: "No folder",
    notesNewFolder: "New folder",
    notesFolderName: "Folder name",
    notesRenameFolder: "Rename folder",
    notesDeleteFolder: "Delete folder",
    notesMoveTo: "Move to",
    chunkLoadError: "Tuto část se nepodařilo načíst.",
    chunkRetry: "Zkusit znovu",
    notesEdit: "Edit",
    notesPreview: "Preview",
    notesBack: "Back",
    appsSearch: "Search apps",
    appsNoResults: "No apps found.",
    notesEnableDesc: "Add a Notes tab for quick text notes.",
    notesBody: "Write something…",
    notesEmpty: "No notes yet.",
    notesFavorite: "Favorite",
    notesText: "Text",
    notesCanvas: "Handwriting",
    notesMentionNoResults: "No matching tasks",
    notesMentionDeletedTask: "Deleted task",
    notesArchive: "Archive",
    notesUnarchive: "Unarchive",
    notesArchived: "Archived",
    notesArchivedEmpty: "No archived notes.",
    eisenhower: "Eisenhower Matrix",
    eisenhowerEnable: "Enable Eisenhower Matrix",
    eisenhowerEnableDesc: "Add a tab to sort tasks by urgency and importance.",
    eisenhowerDoNow: "Urgent & Important",
    eisenhowerSchedule: "Important, Not Urgent",
    eisenhowerDelegate: "Urgent, Not Important",
    eisenhowerEliminate: "Neither",
    eisenhowerUnsorted: "Unsorted tasks",
    eisenhowerUnsortedEmpty: "Nothing to sort.",
    eisenhowerEmpty: "Drag tasks here.",
    notesCanvasWarning: "Notes with drawings may use a lot of space, and as such are only available with Firebase active.",
    eiCalendar: "EI Calendar",
    eiCalendarEnable: "Show EI calendar",
    eiCalendarEnableDesc: "Adds the official EI course calendar for your year to the calendar, read-only and always up to date.",
    eiCalendarDisableTitle: "Hide EI calendar?",
    eiCalendarDisableDesc: "Stops showing the EI calendar events. Nothing is deleted and you can turn it back on anytime.",
    exportJson: "Export JSON",
    importJson: "Import JSON",
    semesterAvg: "Semester average",
    ectsPassedLabel: "ECTS passed",
    targetGrade: "Target grade",
    previousSemesters: "Previous semesters",
    courseAvg: "Course average",
    finalGrade: "Final grade",
    previousAvg: "Previous avg",
    numSemesters: "No. of semesters",
    welcomeDesc: "Your space for uni work. Set up your semester and get organised.",
    step1: "Set your semester dates",
    step2: "Add your classes",
    step3: "Plan tasks & track grades",
    obWelcomeTitle: "Welcome to Organizer",
    obWelcomeDesc: "Your calm space for uni work. Pick your language and theme to start.",
    obModeTitle: "How will you use it?",
    obModeDesc: "Toggle what fits you. Both can be on.",
    obModeWorkToggle: "Work mode",
    obModeWorkToggleDesc: "Groups instead of classes, no grades.",
    obModeWeeksToggle: "No semesters",
    obModeWeeksToggleDesc: "Organise by calendar week instead of semester.",
    obImportOr: "or restore a backup",
    obDatesTitle: "Your semester",
    obDatesDesc: "When does it start and end?",
    obClassesTitle: "Your classes",
    obClassesDesc: "Add the classes you are taking.",
    obGroupsTitle: "Your groups",
    obGroupsDesc: "Add the groups you work with.",
    obInfoTasksTitle: "Tasks & Kanban",
    obInfoTasksDesc: "Add tasks per week or date, then drag them across your kanban board.",
    obInfoCalTitle: "Calendar & Focus",
    obInfoCalDesc: "See everything on the calendar and run focus sessions to get things done.",
    obInfoDoneTitle: "You are all set",
    obInfoDoneDesc: "You can change any of this later in settings.",
    shareLink: "Copy share link",
    qrCode: "QR Code",
    linkCopied: "Link copied!",
    addSemester: "Add semester",
    semesterName: "Semester name",
    startDate: "Start date",
    endDate: "End date",
    weeks: n => `${n} weeks`,
    addAClass: "Add class",
    className: "Class name",
    ects: "ECTS",
    colour: "Colour",
    addComponent: "Add component",
    componentName: "Component name",
    taskSpanLabel: "Task span behaviour",
    taskSpanDesc: "When a task spans multiple weeks, how is it marked done?",
    kanbanChecklistInlineLabel: "Kanban checklist preview",
    kanbanChecklistInlineDesc: "Show checklist items directly on cards without opening details.",
    kanbanChecklistPreviewNone: "Hide on cards",
    kanbanChecklistPreviewAll: "Show on all cards",
    kanbanChecklistPreviewPerCard: "Case by case",
    kanbanAutoAddLabel: "Automaticky přidat úkoly na nástěnku",
    kanbanAutoAddDesc: "Automaticky přidá úkoly tohoto týdne do prvního sloupce na Kanban nástěnce.",
    focusAlertModeLabel: "Focus alert mode",
    focusAlertModeDesc: "Choose how Focus alerts are delivered when the timer phase changes.",
    focusAlertNone: "None",
    focusAlertVibration: "Vibration",
    focusAlertNotification: "Notification",
    focusAlertBoth: "Both",
    taskAlertModeLabel: "Task due-date alerts",
    taskAlertModeDesc: "Choose how task due-date alerts are delivered.",
    taskAlertNone: "None",
    taskAlertInApp: "In-app",
    taskAlertNotification: "Notification",
    taskAlertBoth: "Both",
    taskAlertNextDayTimeLabel: "Next-day alert time",
    taskAlertNextDayTimeDesc: "Time for reminders about tasks due tomorrow.",
    taskDefaultToCalendarLabel: "Tasks on calendar by default",
    taskDefaultToCalendarDesc: "New tasks will have \"Show on calendar\" enabled by default.",
    taskDueTodayTitle: count => count === 1 ? 'Task due today' : `${count} tasks due today`,
    taskAlertHide: "Hide alert",
    taskAlertRemindMeAt: "Remind me at",
    settingEnabled: "Enabled",
    settingDisabled: "Disabled",
    spanSingle: "One global checkbox (done once)",
    spanPerWeek: "Per-week checkbox",
    dangerZone: "Danger zone",
    deleteSemester: "Delete this semester",
    clearPomodoros: "Clear pomodoros",
    clearPomodorosTitle: "Clear all pomodoros?",
    clearPomodorosDesc: "All fallen pomodoros will be permanently deleted.",
    deleteSemesterTitle: "Delete semester?",
    deleteSemesterDesc: "All tasks, grades, and kanban data for this semester will be permanently deleted.",
    clearDoneTitle: "Clear done column?",
    clearDoneDesc: "All cards in the Done column will be deleted.",
    wipeAllTitle: "Wipe all cards?",
    wipeAllDesc: "Every card on the board will be permanently deleted.",
    selectSemester: "Select semester",
    noClassesYet: "No classes yet",
    addClassesInSettings: "Add classes in Settings.",
    addUnlocks: "Add a semester to unlock the rest.",
    notAchievable: "— not achievable",
    onRemaining: " on remaining assessments",
    youNeed: "You need",
    allGraded: "All components graded.",
    noGradeComponents: "No grade components configured. Go to Settings.",
    deleteClassTitle: "Delete class?",
    deleteClassDesc: "This will also delete all tasks for this class.",
    holidayName: "Holiday name",
    holidayNamePlaceholder: "e.g. Christmas Break",
    addHoliday: "Add holiday",
    loadPreset: "Load preset",
    presetLoading: "Loading preset…",
    presetError: "Failed to load preset.",
    retry: "Retry",
    skip: "Přeskočit",
    newColumnName: "New column name",
    focusEvery: "every (min)",
    focusBreakFor: "break (min)",
    focusScheduledMode: "Scheduled breaks",
    focusNextBreak: "Next break at",
    focusFocusLabel: "Focus message",
    focusBreakLabel: "Break message",
    loadPresetTitle: "Load a preset",
    presetGroupEI: "EI Course",
    presetGroupGeneric: "General",
    backToMenu: "Back",
    importData: "Import data",
    importFromFirebase: "Import from Firebase",
    nextSemesterTitle: "Semester ended",
    nextSemesterDesc: "Your semester has ended. Load the next one?",
    loadNextSemester: "Load next semester",
    dismissNextSemester: "Dismiss",
    noSemesterYet: "No semester configured",
    noSemesterDesc: "Load a preset or import your data to get started.",
    focusIntervalMode: "Interval breaks",
    focusIntervalEvery: "every (min)",
    focusIntervalBreakFor: "break (min)",
    focusScheduledBreakFor: "break (min)",
    focusAfterBreakReset: "After break: reset timer",
    focusAfterBreakContinue: "After break: keep counting",
    firebaseSync: "Firebase sync",
    firebaseConnect: "Connect",
    firebaseConnected: "Connected",
    firebaseDisconnect: "Disconnect",
    firebaseSyncing: "Syncing…",
    firebaseLastSync: "Last sync",
    firebaseError: "Sync error",
    firebaseRemoteNewer: "Cloud data is from a newer app version. Sync paused. Update the app.",
    collabSyncFailed: "Could not sync shared change. It was reverted.",
    newerVersionWarning: "Your data was saved by a newer app version. Some things may not display correctly until you update.",
    firebaseSetupTitle: "Connect Firebase",
    firebaseStep1Title: "Create a Firebase project",
    firebaseStep1Desc: "Go to console.firebase.google.com → Add project → give it any name → disable Google Analytics → Create project.",
    firebaseStep2Title: "Enable Firestore",
    firebaseStep2Desc: "Go to Build → Firestore Database → Create database → choose a region → Start in production mode → Create. Then go to Rules, replace the content with: allow read, write: if true; and click Publish.",
    firebaseStep3Title: "Get your config",
    firebaseStep3Desc: "Go to Project Settings (gear icon) → Your apps → Add app → Web → register the app → copy the firebaseConfig object shown.",
    firebaseStep4Title: "Paste your config",
    firebaseStep4Desc: "Paste the full firebaseConfig object (as JSON) below.",
    firebaseConfigPlaceholder: "{ \"apiKey\": \"...\", \"authDomain\": \"...\", \"projectId\": \"...\", ... }",
    firebaseConfigInvalid: "Invalid config: must include apiKey and projectId.",
    firebaseTestFailed: "Could not connect. Check your config and database rules.",
    firebaseSave: "Save & connect",
    pomodoro: "Pomodoro",
    pomodoroOverlayFocusing: "focusing",
    pomodoroMode: "Pomodoro mode",
    pomodoroModeDesc: "Grow tomatoes during focus sessions. Each completed session drops a tomato.",
    pomodoroResetPeriod: "Reset period",
    pomodoroResetDay: "Daily",
    pomodoroResetWeek: "Weekly",
    pomodoroResetMonth: "Monthly",
    pomodoroResetSemester: "Per semester",
    pomodoroTrackPeriodStats: "Track period stats",
    pomodoroShowAbandoned: "Show abandoned tomatoes",
    pomodoroShowPeriodPomodoros: "Show period pomodoros",
    pomodoroStatsTitle: "Pomodoro stats",
    pomodoroTotal: "Total tomatoes",
    pomodoroAbandoned: "Abandoned",
    pomodoroFocusTime: "Total focus time",
    pomodoroPeriodTotal: "This period",
    pomodoroPeriodFocus: "Focus this period",
    pomodoroVsSinceLast: "vs last period",
    pomodoroAllTime: "All time",
    pomodoroInsightsDailyTitle: "Daily focus this week",
    pomodoroInsightsWeeklyBreakdownTitle: "Weekly averages",
    pomodoroInsightsAvgWeekLabel: "avg/day (week)",
    pomodoroInsightsAvgPeriodLabel: "avg/day (period)",
    pomodoroInsightsPerDaySuffix: "/d",
    pomodoroInsightsNoWeeklyData: "No weekly data yet.",
    pomodoroInsightsDayLabels: ["S","M","T","W","T","F","S"],
    pomodoroTotalTimeLabel: "total time",
    pomodoroClose: "Close",
    pomodoroEraseStats: "Erase stats",
    pomodoroEraseStatsTitle: "Erase pomodoro stats?",
    pomodoroEraseStatsDesc: "Historical focus-time stats will be removed, but tomato entries stay available.",
    pomodoroGraceCancel: "Cancel (no tomato)",
    pomodoroGrace: s => `${s}s to cancel without losing a tomato`,
    pomodoroStreakTitle: "Streak",
    pomodoroCurrentStreak: "Current streak",
    pomodoroBestStreak: "Best streak",
    pomodoroStreakDaySuffix: "d",
    pomodoroTrendTitle: "Monthly trend",
    pomodoroTrendNoData: "No monthly data yet.",
    pomodoroCopySummary: "Copy summary",
    pomodoroCopiedSummary: "Copied!",
    workModeLabel: "Work mode",
    workModeDesc: "Hides grades and renames classes to groups.",
    workModeOnboarding: "Using this for work?",
    semesterModeLabel: "No semester mode",
    semesterModeDesc: "Turn on to use plain year weeks instead of semesters. Grades are hidden.",
    semesterModeNone: "No semesters (year weeks)",
    semesterModeSemesters: "Using semesters",
    semesterModeOnboarding: "No semesters, just weeks?",
    groups: "Skupiny", group: "Skupina",
    addAGroup: "Add group",
    groupName: "Group name",
    deleteGroupTitle: "Delete group?",
    deleteGroupDesc: "This will also delete all tasks for this group.",
    storageWarningTitle: "Storage limit reached",
    storageWarningDesc: "Please activate Firebase sync, reached max local storage.",
    storageWarningAction: "Got it",
    collabConnect: "Connect Organizer Collab",
    collabDisconnect: "Disconnect Organizer Collab",
    collabRequiresFirebase: "Connect Firebase sync first to use Organizer Collab.",
    collabGuideTitle: "Organizer Collab setup",
    collabGuideIntro: "One-time setup. Do these 4 steps in Firebase, then come back and enable collab.",
    collabGuideImportantTitle: "What changes when collab is enabled",
    collabGuideImportant1: "Your database starts requiring authenticated users (anonymous auth is enough).",
    collabGuideImportant2: "Normal organizer sync keeps working, but it must authenticate first.",
    collabGuideImportant3: "If collab is disabled later, auth-based rules can still be used safely.",
    collabGuideStep1: "Open Firebase Console > Build > Firestore Database > Rules.",
    collabGuideStep2: "Paste the rules snippet below and click Publish.",
    collabGuideStep3: "Open Security > Authentication > Sign-in method > enable Anonymous > Save.",
    collabGuideStep4: "Return to Organizer and press \"I configured rules, enable collab\".",
    collabGuideRulesLabel: "Firestore rules",
    collabGuideTroubleshootTitle: "If you see signUp 400 error",
    collabGuideTroubleshootBody: "That means Anonymous authentication is still disabled in Firebase. Enable it in Security > Authentication > Sign-in method.",
    collabEnableNow: "I configured rules, enable collab",
    collabPanelTitle: "Organizer Collab",
    collabPanelSubtitle: "Create teams, invite people, and share tasks/kanban cards.",
    collabCreateTeam: "Create team",
    collabTeamName: "Team name",
    collabTeamDays: "team days",
    collabTeamDuration: "team duration",
    collabDays: "days",
    collabJoinTeam: "Join team",
    collabInvitePlaceholder: "Paste invite link",
    collabInviteTtl: "Invite validity",
    collabYourTeams: "Your teams",
    collabNoTeams: "No teams yet.",
    collabRoleHost: "host",
    collabRoleMember: "member",
    collabEndsAt: "ends",
    collabInvite: "Invite",
    collabEditTeam: "Edit team",
    collabTaskCompletionMode: "Shared task completion",
    collabTaskCompletionPersonal: "personal completion",
    collabTaskCompletionForAll: "toggle for everyone",
    collabTaskPermissions: "Task edit permissions",
    collabTaskPermissionsEveryone: "anyone can add/edit/remove tasks",
    collabTaskPermissionsHostOnly: "only host can add/edit/remove tasks",
    collabLeave: "Leave",
    collabDeleteTeam: "Delete",
    collabDefaultTeamName: "Team",
    collabLeavePrompt: "Leave this team?",
    collabLeaveWithLocalPrompt: "You shared local tasks in this team. Keep them locally?",
    collabDeleteTeamPrompt: "Delete this team?",
    collabDeleteTeamWithLocalPrompt: "You shared local tasks in this team. Keep them locally before deleting the team?",
    collabKeepLocalTasks: "Keep local tasks",
    collabDeleteLocalTasksToo: "Delete local tasks",
    collabErrorCreate: "Could not create team.",
    collabErrorInvite: "Could not generate invite.",
    collabErrorJoin: "Could not join team.",
    collabErrorInvalidLink: "Invalid invite link.",
    collabErrorDeleteTeam: "Could not delete team.",
    collabGuideChecklistTitle: "Still not syncing?",
    collabGuideChecklistBody: "The two steps Organizer cannot do for you: enable Anonymous Auth, and publish the Firestore rules above. If shared tasks never appear, one of these is missing on the host project.",
    collabSyncErrorHint: "Can't reach this team. Check the host's Firebase has Anonymous Auth enabled and open rules.",
    collabKeyRequiredHint: "Tento tým je šifrovaný a tvůj pozvánkový odkaz neobsahoval klíč. Požádej o nový odkaz.",
    collabErrorPermission: "Blocked by Firebase rules. Host must enable Anonymous Auth and open Firestore rules.",
    collabErrorNotFound: "Team not found. It may have been deleted.",
    collabErrorInviteExpired: "This invite has expired. Ask the host for a new link.",
    collabErrorInviteInvalid: "This invite link is not valid for that team.",
    firebaseRulesTemplateLink: "View Firestore rules template",
    firebaseOpenRulesWarningTitle: "Your database rules may be open",
    firebaseOpenRulesWarningDesc: "Sync is working without authentication, which usually means your Firestore rules allow anyone to read and write your data. Publish the rules template linked below to lock this down.",
    firebaseEncryptionOffTitle: "End-to-end encryption is off",
    firebaseEncryptionOffDesc: "Your data is stored in Firestore as plain text. Turn on encryption so only devices with your key can read it — even if your database rules are ever misconfigured.",
    firebaseEncryptNow: "Encrypt now",
    firebaseEncryptMigrateFailed: "Could not enable encryption. Check your connection and try again.",
    firebaseHaveKeyAlready: "This device already has a key from another install",
    firebaseKeyPastePlaceholder: "Paste your recovery key",
    firebaseKeyInvalid: "That does not look like a valid key.",
    firebaseKeyWrongOrUnreadable: "Could not decrypt with this key. Double check it and try again.",
    firebaseRecoveryKeyShownOnceTitle: "Save this recovery key now",
    firebaseRecoveryKeyShownOnceDesc: "This key is shown only once and is never sent to Firebase. Anyone with it can read your data; anyone without it (including you) cannot recover it if lost. Store it somewhere safe.",
    firebaseKeySavedItConfirm: "I've saved my key",
    firebaseEncryptionOnTitle: "End-to-end encryption is on",
    firebaseEncryptionOnDesc: "Tvá data jsou šifrována na tomto zařízení — v místním úložišti i před odesláním do Firestore. Dešifrovat je mohou jen zařízení s obnovovacím klíčem.",
    firebaseShowRecoveryKey: "Show recovery key",
    firebaseShowRecoveryKeyConfirmTitle: "Show recovery key?",
    firebaseShowRecoveryKeyConfirmDesc: "Anyone who sees this key can decrypt your data. Only do this somewhere private.",
    firebaseKeyRequiredTitle: "Encryption key needed",
    firebaseKeyRequiredDesc: "This project’s data is encrypted. Paste the recovery key from a device that already has it to unlock sync on this device.",
    firebaseKeyRequiredForImport: "This backup is encrypted. Set up sync with the matching key first, then import again.",
    exportEncrypted: "Organizer format (encrypted)",
    encUnlockTitle: "Odemkni svá data",
    encUnlockDesc: "Na tomto zařízení jsou zašifrovaná data. Zadej svou přístupovou frázi a odemkni je.",
    encUnlockHintLabel: "Tvá nápověda",
    encPassphraseLabel: "Přístupová fráze",
    encPassphrasePlaceholder: "Tvá přístupová fráze",
    encPassphraseConfirmLabel: "Potvrď přístupovou frázi",
    encPassphraseMismatch: "Přístupové fráze se neshodují.",
    encPassphraseTooShort: "Použij alespoň 8 znaků.",
    encHintLabel: "Nápověda k přístupové frázi (nepovinné)",
    encHintPlaceholder: "Soukromá připomínka, ne samotná fráze",
    encRecoveryCodeTitle: "Ulož si záložní kód",
    encRecoveryCodeDesc: "Těchto 12 anglických slov je jediná cesta zpět, pokud zapomeneš přístupovou frázi. Zapiš si je nebo je ulož do správce hesel. Znovu je nezobrazíme.",
    encRecoveryCodeWordsNote: "12 anglických slov. Opiš je přesně a ve správném pořadí.",
    encRecoveryCodeSavedConfirm: "Záložní kód mám uložený",
    encRecoveryCodeQr: "Zobrazit QR kód",
    encRecoveryCodeQrDesc: "Naskenuj ho na jiném zařízení a přenes tak záložní kód.",
    encUseRecoveryCode: "Použít záložní kód",
    encUsePassphrase: "Použít přístupovou frázi",
    encRecoveryCodeLabel: "Záložní kód",
    encRecoveryCodePlaceholder: "dvanáct slov oddělených mezerami",
    encRecoveryCodeInvalid: "Tohle není platný záložní kód z 12 slov.",
    encUnlockFailed: "Tímto se odemknout nepodařilo. Zkontroluj to a zkus to znovu.",
    encUnlocking: "Odemykám…",
    encDeriving: "Odvozuji klíč…",
    encEnableTitle: "Zapnout end-to-end šifrování",
    encEnableDesc: "Tvá data se zašifrují na tomto zařízení, ještě než se dostanou do Firestore. Přečtou je jen zařízení s tvou přístupovou frází nebo záložním kódem.",
    encEnableWarning: "Pokud ztratíš přístupovou frázi i záložní kód, tvá data už nikdo neobnoví, ani my.",
    encEnableSubmit: "Zapnout šifrování",
    encEnableFailed: "Šifrování se nepodařilo zapnout. Zkontroluj připojení a zkus to znovu.",
    encManageTitle: "Šifrování",
    encManageDesc: "Tvá data jsou šifrovaná end-to-end. Odemčení probíhá jen na tomto zařízení.",
    encChangePassphrase: "Změnit přístupovou frázi",
    encChangePassphraseDesc: "Zadej současnou přístupovou frázi a potom novou.",
    encCurrentPassphraseLabel: "Současná přístupová fráze",
    encRegenerateRecoveryCode: "Vygenerovat nový záložní kód",
    encRegenerateRecoveryCodeDesc: "Nahradí tvůj stávající kód. Ten starý přestane fungovat.",
    encEditHint: "Upravit nápovědu",
    encRotateDekTitle: "Otočit šifrovací klíč",
    encRotateDekDesc: "Znovu zašifruje všechna tvá data pod úplně novým klíčem. Ostatní zařízení bude potřeba znovu odemknout.",
    encRotateDekWarning: "Nezavírej aplikaci, dokud to neskončí.",
    encRotating: "Znovu šifruji…",
    encRotateFailed: "Klíč se nepodařilo otočit. Nic se nezměnilo.",
    encSaved: "Uloženo.",
    encStoreUnavailableTitle: "Bezpečné úložiště není dostupné",
    encStoreUnavailableDesc: "Tento prohlížeč zablokoval úložiště klíčů, což se často děje v anonymním režimu. Tvá zašifrovaná data zůstala nedotčená. Zkus to v běžném okně.",
    encPlaintextSyncWarnTitle: "Synchronizace není šifrovaná",
    encPlaintextSyncWarnDesc: "Tvá data jsou ve Firestore uložená jako čitelný text. Přečte je každý, kdo se dostane k tvé databázi.",
    encPlaintextSyncEnable: "Zapnout šifrování",
    encPlaintextSyncDismiss: "Teď ne a už se neptej",
    encRemoteAlreadyEncrypted: "Tento projekt je už zašifrovaný. Odemkni ho a připoj tak toto zařízení.",
    encRemoteNotEncryptedTitle: "Zašifrovat tento projekt?",
    encRemoteNotEncryptedDesc: "Tento projekt obsahuje nezašifrovaná data. Zapni šifrování a data se nahrají znovu, už zašifrovaná.",
    encRemoteNotEncryptedMigrate: "Zašifrovat a převést",
    encRemoteNotEncryptedSkip: "Nechat nezašifrované",
    encRemoteUnrecoverable: "Tento projekt je zašifrovaný, ale nemá žádná data pro obnovu, takže ho nelze odemknout. Odpoj se a začni nový projekt.",
    encRemoteDekMismatch: "Tento projekt byl znovu zašifrován novým klíčem. Odemkni ho znovu přístupovou frází nebo záložním kódem.",
    encExportPassphraseTitle: "Ochránit tuto záložní kopii",
    encExportPassphraseDesc: "Zvol pro soubor přístupovou frázi. Budeš ji potřebovat k obnovení, na jakémkoli zařízení.",
    encImportPassphraseTitle: "Odemknout tuto záložní kopii",
    encImportPassphraseDesc: "Zadej přístupovou frázi, kterou jsi zvolil při exportu.",
    encImportPassphraseFailed: "Špatná přístupová fráze pro tuto záložní kopii.",
    encTitle: "Šifrování",
    encOffTitle: "Šifrování je vypnuté",
    encOffDesc: "Tvá data se ukládají jako čitelný text všude, kde leží. Zapni šifrování a bez tvé přístupové fráze budou nečitelná — na tomto zařízení i všude, kam se synchronizují.",
    encOnDesc: "Tvá data se zašifrují ještě před uložením nebo synchronizací. Přečtou je jen zařízení s tvou přístupovou frází nebo záložním kódem.",
    encLockedDesc: "Tvá uložená data jsou zašifrovaná. Zadej přístupovou frázi a odemkni je na tomto zařízení.",
    encEnableAction: "Zapnout šifrování",
    encDisableAction: "Vypnout šifrování",
    encDisableTitle: "Vypnout šifrování?",
    encDisableDesc: "Tvá data se všude, kde jsou uložená, zapíšou znovu jako čitelný text a přístupová fráze i záložní kód přestanou fungovat.",
    encStorageShedTitle: "Některá data se nevešla",
    encStorageShedDesc: "Tomuto zařízení se vyčerpalo místní úložiště, takže se lokálně neuložilo toto:",
    exportPlaintext: "Human-readable (plaintext JSON)",
    repeat: "Repeat",
    repeatFreqLabel: "Frequency",
    repeatFreqDaily: "Daily",
    repeatFreqWeekly: "Weekly",
    repeatFreqMonthly: "Monthly",
    repeatEvery: "Every",
    repeatIntervalDaily: n => (n === 1 ? 'day' : 'days'),
    repeatIntervalWeekly: n => (n === 1 ? 'week' : 'weeks'),
    repeatIntervalMonthly: n => (n === 1 ? 'month' : 'months'),
    repeatUntil: "Until (optional)",
    googleCalendar: "Google Calendar",
    gcalConnect: "Connect",
    gcalConnected: "Connected",
    gcalConnecting: "Connecting…",
    gcalDisconnect: "Disconnect",
    gcalEnable: "Sync with Google Calendar",
    gcalScopeNotice: "This grants full read/write access to your primary Google Calendar (the \"calendar\" scope). Organizer only reads and writes events you interact with here; your Google credentials never leave your device and are not sent anywhere but Google.",
    gcalStep1Title: "Create a Google Cloud project",
    gcalStep1Desc: "Go to console.cloud.google.com → create a new project (or pick one) → APIs & Services → enable the \"Google Calendar API\".",
    gcalStep2Title: "Configure OAuth consent + credentials",
    gcalStep2Desc: "APIs & Services → OAuth consent screen → set it up (External is fine for personal use, add yourself as a test user). Then Credentials → Create credentials → OAuth client ID → Application type: Web application → add this app's URL to Authorized JavaScript origins.",
    gcalStep3Title: "Paste your Client ID",
    gcalStep3Desc: "Copy the Client ID (ends in .apps.googleusercontent.com) shown after creating it, and paste it below. This value is not secret and is safe to store in this browser.",
    gcalClientIdPlaceholder: "xxxxxxxx.apps.googleusercontent.com",
    gcalClientIdInvalid: "Enter a valid OAuth Client ID.",
    gcalConnectFailed: "Could not connect. Check your Client ID and try again.",
    gcalDisableTitle: "Disconnect Google Calendar?",
    gcalDisableDesc: "Stops syncing with Google Calendar on this device. Events already created stay in both places; sync bookkeeping (Client ID, links) is removed here.",
    eventSyncToGoogle: "Sync to Google Calendar",
    eventSyncToGoogleDesc: "Push this event to your connected Google Calendar.",
    quickActionTaskWords: ["úkol","ukol"],
    quickActionEventWords: ["událost v kalendáři","udalost v kalendari","událost","udalost"],
    quickActionCardWords: ["kanban kartu","kanban karta","kartu","karta"],
    quickActionAddWords: ["přidej","pridej","přidat","pridat","vytvoř","vytvor","vytvořit","vytvorit"],
    quickActionForWords: ["pro","na"],
    quickActionAndWords: ["a"],
    quickActionOnWords: ["dne","v"],
    quickActionArticleWords: [],
    quickActionBoardWords: ["kanban","nástěnka","nastenka"],
    quickAction: "Quick action",
    quickActionPlaceholder: "e.g. add task and calendar event for a cbd test on 18/07 at 15h",
    quickActionTab: "Quick action",
    quickActionFormTab: "Form",
    quickActionPreviewTitle: "Will create",
    quickActionPreviewTask: "task",
    quickActionPreviewTaskCalendar: "task (shown on calendar)",
    quickActionPreviewEvent: "calendar event",
    quickActionPreviewCard: column => `kanban card in ${column}`,
    quickActionEmpty: "Couldn't understand that. Try rephrasing.",
    quickActionCreate: "Create",
    quickActionBack: "Back",
    notesDeleteConfirmTitle: "Delete this note?",
    notesDeleteConfirmDesc: "This note will be permanently deleted.",
    notesEmptyTitle: "No notes yet",
    notesEmptyDesc: "Create your first note to get started.",
    notesFilterEmpty: "No notes match your search.",
    notesSelectNote: "Select a note to start editing",
    notesTextNote: "Text note",
    notesCanvasNote: "Canvas note",
    eventStartTimeFirstDay: "Čas začátku (první den)",
    eventEndTimeLastDay: "Čas konce (poslední den)",
    notesBold: "Tučné",
    notesItalic: "Kurzíva",
    notesStrike: "Přeškrtnuté",
    notesHeading1: "Nadpis 1",
    notesHeading2: "Nadpis 2",
    notesHeading3: "Nadpis 3",
    notesBulletList: "Odrážkový seznam",
    notesOrderedList: "Číslovaný seznam",
    notesTaskList: "Kontrolní seznam",
    notesQuote: "Citace",
    notesInsertTable: "Vložit tabulku",
    notesCodeBlock: "Blok kódu",
    notesDivider: "Oddělovač",
    notesAddLink: "Přidat odkaz",
    notesRemoveLink: "Odebrat odkaz",
    notesTextColor: "Barva textu",
    notesColorReset: "Výchozí barva",
    notesColorCustom: "Vybrat vlastní barvu",
    notesColorApply: "Použít",
    notesExport: "Exportovat poznámku",
    notesImport: "Importovat poznámku",
    notesGraphEdit: "Upravit graf",
    notesGraphRange: "x od",
    notesGraphResize: "Tažením změň velikost",
    notesGraphInvalid: "Výraz nelze vykreslit",
    notesGraphAlignleft: "Zarovnat vlevo",
    notesGraphAligncenter: "Na střed",
    notesGraphAlignright: "Zarovnat vpravo",
    notesTextSize: "Velikost textu",
    notesSizeNormal: "Normální",
    notesSizeSmall: "Malé",
    notesSizeLarge: "Velké",
    notesSizeHuge: "Obrovské",
    notesUndo: "Zpět",
    notesRedo: "Znovu",
    notesViewList: "Zobrazení seznamu",
    notesViewMosaic: "Dlaždicové zobrazení",
    notesMathEnable: "Řešení matematiky",
    notesMathEnableDesc: "Napiš rovnici zakončenou = a stiskni Enter pro vyřešení. Použij x pro vykreslení grafu.",
    notesMathSolve: "Vyřešit pro x",
    notesMathSolveDesc: "Změní 3x = 3 na x = 1, včetně nerovnic a kvadratických rovnic.",
    notesMathSelection: "Vykreslit výběr",
    notesMathSelectionDesc: "Označ rovnici a stiskni Enter pro její vykreslení.",
    notesMathSteps: "Zobrazit postup",
    notesMathStepsDesc: "Zobrazí každý krok řešení místo pouhého výsledku.",
    eisenhowerAddTask: "Add task",
    eisenhowerCustomize: "Customize quadrants",
    eisenhowerResetDefaults: "Reset to defaults",
    quickActionApp: "Quick Action",
    quickActionAppEnable: "Enable Quick Action",
    quickActionAppEnableDesc: "Adds a spotlight overlay for quickly creating tasks, events, and cards.",
    quickActionTripleTapEnable: "Trojité klepnutí na obrazovku", quickActionTripleTapEnableDesc: "Klepněte 3x kdekoli pro otevření Quick Action",
    quickActionShortcutEnable: "Keyboard shortcut",
    quickActionShortcutKey: "Shortcut",
    quickActionNavbarButton: "Show in navbar add menu",
    spotlightPlaceholder: "Quick action… (e.g. add task for exam on Monday)",
    themeColor: "Accent color",
    themeColorDesc: "Pick a color for buttons, links, and highlights.",
    themeColorReset: "Reset to default",
    themeFontColor: "Barva písma", themeHighlightColor: "Barva zvýraznění", themeBgColor: "Barva pozadí",
}
