export const en = {
    months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    weekdaysShort: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    weekdays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    nlpToday: ['today'], nlpTomorrow: ['tomorrow'], nlpNextWeek: ['next week'], nlpAt: ['at'],
    nlpDow: [['sunday', 'sun'], ['monday', 'mon'], ['tuesday', 'tue'], ['wednesday', 'wed'], ['thursday', 'thu'], ['friday', 'fri'], ['saturday', 'sat']],
    tasks: 'Tasks', kanban: 'Kanban', grades: 'Grades', calendar: 'Calendar', focus: 'Focus', settings: 'Settings',
    guides: 'Guides',
    noSemester: 'No semester set up', goToSettings: 'Head to Settings to get started.',
    weekLabel: w => `Week ${w}`, done: 'done', timeToRelax: 'Time to relax!',
    addTask: 'New task', task: 'Task', class: 'Class', priority: 'Priority',
    editTask: 'Edit task', moveLeft: 'Move left', moveRight: 'Move right', markDone: 'Mark done',
    calendarCreateNote: 'Create linked note', calendarOpenNote: 'Open linked note',
    calendarDayEmpty: 'Nothing on this day.',
    calendarNowColor: 'Current time line', calendarNowColorDesc: 'Colour of the line marking now in day and week views.',
    calendarColors: 'Calendar colors',
    weekStartDay: 'First day of week',
    weatherPreview: 'Weather preview', weatherPreviewDesc: 'Show small weather icons for the next 7 days on the week and month calendar.',
    weatherCategory: { clear: 'Clear', 'partly-cloudy': 'Partly cloudy', cloudy: 'Cloudy', fog: 'Fog', rain: 'Rain', snow: 'Snow', storm: 'Thunderstorm' },
    weatherCityPlaceholder: 'Write city name eg. Lisbon', weatherCityLoading: 'Looking up city…', weatherCityError: 'City not found.', weatherCitySaved: 'Weather enabled.',
    scheduleImportTitle: 'Import schedule',
    scheduleImportDesc: 'Scan a timetable screenshot. Day and time come from the grid layout; rooms and class codes go to the note. Check the preview before importing.',
    scheduleImportPick: 'Choose image', scheduleImportError: 'Could not read that image. Try a clearer screenshot.',
    scheduleImportTitleField: 'Title', scheduleImportNoteField: 'Note (room, type)',
    scheduleImportHistory: 'Past imports', scheduleImportUndo: 'Remove',
    scheduleImportRepeatLabel: 'How often',
    scheduleImportEveryWeek: 'Every week', scheduleImportThisWeek: 'Just this week',
    scheduleImportPreview: 'Preview', scheduleImportSkipped: 'Skipped lines', scheduleImportConfirm: 'Import',
    notesCalendarLink: 'Calendar event notes', notesCalendarLinkDesc: 'Add a note button to calendar events, linked per date.',
    addToKanban: 'Add to Kanban', themeLight: 'Light theme', themeDark: 'Dark theme', themeSystem: 'System theme',
    addPartTitle: 'Add part', gradeParts: n => `${n} parts`, pctDone: pct => `${pct}% done`,
    fromWeek: 'From week', toWeek: 'To week', dueDate: 'Due date',
    other: 'Other', noTasks: 'No tasks this week.',
    whatNeedsDone: 'What needs to be done?',
    voiceInputAria: 'Dictate by voice', voiceInputStopAria: 'Stop dictation',
    addTaskBtn: 'Add task', showOnCalendar: 'Show on calendar', showOnTasks: 'Show on tasks',
    clearDone: 'Clear done', wipeAll: 'Wipe all',
    addCard: 'Add card', addCardPlaceholder: 'Card title',
    quickActionTaskWordsPlural: ['tasks'], quickActionEventWordsPlural: ['calendar events', 'events'], quickActionCardWordsPlural: ['kanban cards', 'cards'],
    save: 'Save', cancel: 'Cancel', confirm: 'Confirm', delete: 'Delete',
    addEvent: 'Add event', newEvent: 'New event', editEvent: 'Edit event',
    quickActionRespectivelyWords: ['respectively'],
    quickActionOrdinalWords: ['first', 'second', 'third', 'fourth', 'fifth', 'sixth', 'seventh', 'eighth', 'ninth', 'tenth'],
    eventTitle: 'Event title', eventDate: 'Date', eventRange: 'Date range',
    eventMultiDay: 'Multiple days', eventColor: 'Color', eventNote: 'Note',
    eventNotePlaceholder: 'Optional note', more: 'more',
    eventAllDay: 'All day', eventStartTime: 'Start time', eventEndTime: 'End time',
    viewDay: 'Day', viewWeek: 'Week', viewMonth: 'Month', viewYear: 'Year',
    navbar: 'Navbar', navHide: 'Hide', navOverflow: 'Move to more menu', navAddButton: 'Show add-task button',
    navVisBoth: 'Visible on desktop and mobile', navVisNone: 'Hidden everywhere', navVisDesktop: 'Desktop only', navVisMobile: 'Mobile only',
    navMore: 'More', navLabelMode: 'Show', navLabelBoth: 'Icons + names', navLabelIcons: 'Icons only', navLabelNames: 'Names only',
    add: 'Add', navAddLabel: 'Add', navDrag: 'Drag to reorder',
    appDisableTitle: 'Disable and erase data?', appDisableDesc: 'Turning this app off permanently deletes all its data.',
    collabDisableDesc: 'Disconnecting leaves all teams and permanently removes collaboration data from this device.',
    navAddAction: 'Add button action', navAddPicker: 'Ask each time',
    navFolders: 'Folders', navNewFolder: 'New folder',
    navMobilePosition: 'Mobile navbar position', navPosBottom: 'Bottom bar', navPosSide: 'Side bar',
    addToTasks: 'Add to tasks', inTasks: 'In tasks',
    standby: 'Standby', standbyEnable: 'Enable landscape standby',
    standbyDesc: 'Turn your phone landscape to show an ambient dashboard.',
    standbyLeft: 'Left pane', standbyCenter: 'Center pane', standbyRight: 'Right pane',
    standbyPanels: 'Panels', standbyPane: n => `Pane ${n}`,
    standbyPaneSecond: 'Second card (swipe)', standbyPaneNone: 'None',
    paneWheel: 'Progress wheel', paneWheelTime: 'Wheel + clock', paneCalendar: 'Calendar',
    paneFocus: 'Focus', paneKanban: 'Kanban', paneTasksByCategory: 'Tasks by category',
    notesLastEdit: 'Edited', notesFolder: 'Folder', notesNoFolder: 'No folder', notesNewFolder: 'New folder',
    notesFolderName: 'Folder name', notesRenameFolder: 'Rename folder', notesDeleteFolder: 'Delete folder', notesDeleteNote: 'Delete note', notesMoveTo: 'Move to', notesMoveOut: 'Move out of folder',
    notesEdit: 'Edit', notesPreview: 'Preview', notesBack: 'Back',
    chunkLoadError: 'This part could not be loaded.', chunkRetry: 'Try again',
    apps: 'Apps', appsSearch: 'Search apps', appsNoResults: 'No apps found.', notes: 'Notes',
    notesEnable: 'Enable Notes', notesEnableDesc: 'Add a Notes tab for quick text notes.',
    notesNew: 'New note', notesTitle: 'Title', notesBody: 'Write something…', notesSearch: 'Search notes',
    notesEmpty: 'No notes yet.', notesFavorite: 'Favorite', notesText: 'Text', notesCanvas: 'Handwriting',
    notesMentionNoResults: 'No matching tasks', notesMentionDeletedTask: 'Deleted task',
    notesArchive: 'Archive', notesUnarchive: 'Unarchive', notesArchived: 'Archived', notesArchivedEmpty: 'No archived notes.',
    eisenhower: 'Eisenhower Matrix',
    eisenhowerEnable: 'Enable Eisenhower Matrix', eisenhowerEnableDesc: 'Add a tab to sort tasks by urgency and importance.',
    eisenhowerDoNow: 'Urgent & Important', eisenhowerSchedule: 'Important, Not Urgent',
    eisenhowerDelegate: 'Urgent, Not Important', eisenhowerEliminate: 'Neither',
    eisenhowerUnsorted: 'Unsorted tasks', eisenhowerUnsortedEmpty: 'Nothing to sort.',
    eisenhowerEmpty: 'Drag tasks here.',
    collabApp: 'Collaboration',
    eiCalendar: 'EI Calendar', eiCalendarEnable: 'Show EI calendar',
    eiCalendarEnableDesc: 'Adds the official EI course calendar for your year to the calendar, read-only and always up to date.',
    eiCalendarDisableTitle: 'Hide EI calendar?', eiCalendarDisableDesc: 'Stops showing the EI calendar events. Nothing is deleted and you can turn it back on anytime.',
    semester: 'Semester', classes: 'Classes', gradeComponents: 'Grade components',
    kanbanColumns: 'Kanban columns', general: 'General', data: 'Data & sync',
    holidays: 'Holidays',
    exportJson: 'Export JSON', importJson: 'Import JSON',
    semesterAvg: 'Semester average', ectsPassedLabel: 'ECTS passed',
    targetGrade: 'Target grade',
    previousSemesters: 'Previous semesters',
    courseAvg: 'Course average', finalGrade: 'Final grade', previousAvg: 'Previous avg', numSemesters: 'No. of semesters',
    getStarted: 'Get started', welcomeTitle: 'Welcome to organizer',
    welcomeDesc: 'Your space for uni work. Set up your semester and get organised.',
    step1: 'Set your semester dates', step2: 'Add your classes', step3: 'Plan tasks & track grades',
    obNext: 'Next', obBack: 'Back', obFinish: 'Finish', obSkip: 'Skip',
    obWelcomeTitle: 'Welcome to Organizer', obWelcomeDesc: 'Your calm space for uni work. Pick your language and theme to start.',
    obModeTitle: 'How will you use it?', obModeDesc: 'Toggle what fits you. Both can be on.',
    obModeWorkToggle: 'Work mode', obModeWorkToggleDesc: 'Groups instead of classes, no grades.',
    obModeWeeksToggle: 'No semesters', obModeWeeksToggleDesc: 'Organise by calendar week instead of semester.',
    obImportOr: 'or restore a backup',
    obDatesTitle: 'Your semester', obDatesDesc: 'When does it start and end?',
    obClassesTitle: 'Your classes', obClassesDesc: 'Add the classes you are taking.',
    obGroupsTitle: 'Your groups', obGroupsDesc: 'Add the groups you work with.',
    obInfoTasksTitle: 'Tasks & Kanban', obInfoTasksDesc: 'Add tasks per week or date, then drag them across your kanban board.',
    obInfoCalTitle: 'Calendar & Focus', obInfoCalDesc: 'See everything on the calendar and run focus sessions to get things done.',
    obInfoDoneTitle: 'You are all set', obInfoDoneDesc: 'You can change any of this later in settings.',
    shareLink: 'Share link', qrCode: 'QR Code', linkCopied: 'Link copied!',
    high: 'High', medium: 'Medium', low: 'Low', none: 'None',
    addSemester: 'Add semester', semesterName: 'Semester name', startDate: 'Start date', endDate: 'End date',
    weeks: n => `${n} weeks`, addAClass: 'Add class', className: 'Class name', ects: 'ECTS', colour: 'Colour',
    addComponent: 'Add component', componentName: 'Component name',
    taskSpanLabel: 'Task span behaviour', taskSpanDesc: 'When a task spans multiple weeks, how is it marked done?',
    kanbanChecklistInlineLabel: 'Kanban checklist preview',
    kanbanChecklistInlineDesc: 'Show checklist items directly on cards without opening details.',
    kanbanAutoAddLabel: 'Auto-add tasks to board',
    kanbanAutoAddDesc: 'Automatically add this week\'s tasks to the first column on the Kanban board.',
    widgetsLabel: 'Home screen widgets',
    widgetsDesc: 'Show tasks, today\'s schedule, and Kanban counts on your home screen.',
    widgetsEncryptionWarning: 'Widgets cannot read encrypted data. If you turn them on, the content they show is stored unencrypted on this device. It is erased when you lock the app.',
    gradeScaleLabel: 'Grading scale',
    gradeScaleDesc: 'Highest grade possible. Grade inputs are capped at this value.',
    passingGradeLabel: 'Passing grade',
    passingGradeDesc: 'Minimum grade needed to pass. Used for pass marks and the default target grade.',
    kanbanChecklistPreviewNone: 'Hide on cards',
    kanbanChecklistPreviewAll: 'Show on all cards',
    kanbanChecklistPreviewPerCard: 'Case by case',
    focusAlertsEnabledLabel: 'Focus alerts',
    focusAlertsEnabledDesc: 'Alert when the timer phase changes between focus and break.',
    taskAlertModeLabel: 'Task due-date alerts',
    taskAlertModeDesc: 'Alert when a task is due or a lead-time reminder fires.',
    taskAlertInAppLabel: 'In-app panel',
    taskAlertInAppDesc: 'Show a dismissible panel of due and upcoming tasks in the Tasks tab.',
    taskAlertNextDayTimeLabel: 'Next-day alert time',
    taskAlertNextDayTimeDesc: 'Time for reminders about tasks due tomorrow.',
    notifications: 'Notifications',
    notificationIntrusivenessLabel: 'Alert style',
    notificationIntrusivenessDesc: 'Toasts stack quietly and dismiss themselves. Alerts take over the screen until you dismiss them.',
    notificationIntrusivenessToast: 'Toasts (less intrusive)',
    notificationIntrusivenessAlert: 'Full alerts (more intrusive)',
    notificationVibrateLabel: 'Vibrate',
    notificationSoundLabel: 'Play sound',
    notificationBrowserPushLabel: 'Send to browser notifications',
    notificationDismiss: 'Dismiss',
    notificationBellVisibilityLabel: 'Bell icon visibility',
    notificationBellVisibilityDesc: 'Choose when the notification bell appears in the desktop sidebar.',
    notificationBellAlways: 'Always show',
    notificationBellHideEmpty: 'Hide when nothing unread',
    notificationBellHideNone: 'Hide when nothing scheduled or unread',
    notificationBellUnread: 'Unread',
    notificationBellUpcoming: 'Upcoming',
    notificationBellEmpty: 'Nothing to show yet.',
    taskDefaultToCalendarLabel: 'Tasks on calendar by default', taskTimesLabel: 'Task start and end times', taskTimesDesc: 'Give calendar tasks a time slot instead of showing them as all-day.',
    taskDefaultToCalendarDesc: 'New tasks will have "Show on calendar" enabled by default.',
    hideCompletedTasksLabel: 'Tuck away finished tasks',
    hideCompletedTasksDesc: 'Keep the list focused on what is left. Finished tasks move into a "Completed" section you can open any time.',
    completedTasks: count => `Completed (${count})`,
    speechInputLabel: 'Voice to text',
    speechInputDesc: 'Show a microphone button to dictate text in task, event and note fields.',
    taskDueTodayTitle: count => count === 1 ? 'Task due today' : `${count} tasks due today`,
    taskAlertHide: 'Hide alert',
    taskAlertRemindMeAt: 'Remind me at',
    settingEnabled: 'Enabled', settingDisabled: 'Disabled',
    spanSingle: 'One global checkbox (done once)', spanPerWeek: 'Per-week checkbox',
    dangerZone: 'Danger zone', deleteSemester: 'Delete this semester',
    clearPomodoros: 'Clear pomodoros',
    clearPomodorosTitle: 'Clear all pomodoros?',
    clearPomodorosDesc: 'All fallen pomodoros will be permanently deleted.',
    deleteSemesterTitle: 'Delete semester?', deleteSemesterDesc: 'All tasks, grades, and kanban data for this semester will be permanently deleted.',
    clearDoneTitle: 'Clear done column?', clearDoneDesc: 'All cards in the Done column will be deleted.',
    wipeAllTitle: 'Wipe all cards?', wipeAllDesc: 'Every card on the board will be permanently deleted.',
    selectSemester: 'Select semester', noClassesYet: 'No classes yet', addClassesInSettings: 'Add classes in Settings.',
    addUnlocks: 'Add a semester to unlock the rest.',
    checklist: 'Checklist', addItem: 'Add item', editCard: 'Edit card',
    notAchievable: '— not achievable', onRemaining: ' on remaining assessments',
    youNeed: 'You need', allGraded: 'All components graded.',
    noGradeComponents: 'No grade components configured. Go to Settings.',
    deleteClassTitle: 'Delete class?', deleteClassDesc: 'This will also delete all tasks for this class.',
    holidayName: 'Holiday name', holidayNamePlaceholder: 'e.g. Christmas Break',
    addHoliday: 'Add holiday',
    loadPreset: 'Load preset',
    presetLoading: 'Loading preset…', presetError: 'Failed to load preset.', retry: 'Retry', skip: 'Skip',
    newColumnName: 'New column name',
    focusStart: 'Start', focusPause: 'Pause', focusResume: 'Resume', focusReset: 'Reset', focusSkipBreak: 'Skip break',
    focusReady: 'ready', focusBreak: 'break', focusDetach: 'Detach floating timer', focusAlwaysOnTop: 'Show over other apps',
    focusPhrases: ['keep going', 'stay with it', "you're doing great", 'one step at a time', 'deep work', 'stay present'],
    focusEvery: 'every (min)', focusBreakFor: 'break (min)',
    focusScheduledMode: 'Scheduled breaks',
    focusNextBreak: 'Next break at',
    focusFocusLabel: 'Focus message', focusBreakLabel: 'Break message',
    loadPresetTitle: 'Load a preset',
    presetGroupEI: 'EI Course',
    presetGroupGeneric: 'General',
    backToMenu: 'Back',
    importData: 'Import data',
    importFromFirebase: 'Import from Firebase',
    nextSemesterTitle: 'Semester ended',
    nextSemesterDesc: 'Your semester has ended. Load the next one?',
    loadNextSemester: 'Load next semester',
    dismissNextSemester: 'Dismiss',
    carryOverTitle: 'Carry over',
    carryKanbanCards: 'Kanban cards',
    carryUpcomingTasks: 'Upcoming tasks',
    carryUpcomingEvents: 'Upcoming events',
    carryOverAlwaysKept: 'Notes and settings are always kept.',
    carryOverDiscardWarning: 'Everything else from this semester is deleted.',
    noSemesterYet: 'No semester configured',
    noSemesterDesc: 'Load a preset or import your data to get started.',
    focusIntervalMode: 'Interval breaks',
    focusIntervalEvery: 'every (min)',
    focusIntervalBreakFor: 'break (min)',
    focusScheduledBreakFor: 'break (min)',
    focusAfterBreakReset: 'After break: reset timer',
    focusAfterBreakContinue: 'After break: keep counting',
    firebaseSync: 'Firebase sync',
    firebaseConnect: 'Connect',
    firebaseConnected: 'Connected',
    firebaseDisconnect: 'Disconnect',
    firebaseSyncing: 'Syncing…',
    firebaseLastSync: 'Last sync',
    firebaseError: 'Sync error',
    firebaseRemoteNewer: 'Cloud data is from a newer app version. Sync paused. Update the app.',
    collabSyncFailed: 'Could not sync shared change. It was reverted.',
    newerVersionWarning: 'Your data was saved by a newer app version. Some things may not display correctly until you update.',
    firebaseSetupTitle: 'Connect Firebase',
    firebaseStep1Title: 'Create a Firebase project',
    firebaseStep1Desc: 'Go to console.firebase.google.com → Add project → give it any name → disable Google Analytics → Create project.',
    firebaseStep2Title: 'Enable Firestore',
    firebaseStep2Desc: 'Go to Build → Firestore Database → Create database → choose a region → Start in production mode → Create. Then open the Rules tab, replace everything with the rules below, and click Publish.',
    firebaseStep3Title: 'Get your config',
    firebaseStep3Desc: 'Go to Project Settings (gear icon) → Your apps → Add app → Web → register the app → copy the firebaseConfig object shown.',
    firebaseStep4Title: 'Paste your config',
    firebaseStep4Desc: 'Paste the full firebaseConfig object (as JSON) below.',
    firebaseConfigPlaceholder: '{ "apiKey": "...", "authDomain": "...", "projectId": "...", ... }',
    firebaseConfigInvalid: 'Invalid config: must include apiKey and projectId.',
    firebaseTestFailed: 'Could not connect. Check your config and database rules.',
    firebaseSave: 'Save & connect',
    pomodoro: 'Pomodoro',
    pomodoroOverlayFocusing: 'focusing',
    pomodoroMode: 'Pomodoro mode',
    pomodoroModeDesc: 'Grow tomatoes during focus sessions. Each completed session drops a tomato.',
    pomodoroResetPeriod: 'Reset period',
    pomodoroResetDay: 'Daily', pomodoroResetWeek: 'Weekly', pomodoroResetMonth: 'Monthly', pomodoroResetSemester: 'Per semester',
    pomodoroTrackPeriodStats: 'Track exact durations',
    pomodoroShowAbandoned: 'Show abandoned tomatoes',
    pomodoroShowPeriodPomodoros: 'Show stats row',
    pomodoroShowOverlay: 'Show global overlay over all tabs',
    focusNotifTitle: 'Organiser Focus',
    focusNotifBreakBody: 'Time for your pomodoro break.',
    focusNotifFocusBody: 'Back to focus.',
    tasksNotifTitle: 'Organiser Tasks',
    taskReminderTitle: 'Task Reminder',
    pomodoroStatsTitle: 'Pomodoro stats',
    pomodoroTotal: 'Total tomatoes', pomodoroAbandoned: 'Abandoned', pomodoroFocusTime: 'Total focus time',
    pomodoroPeriodTotal: 'This period', pomodoroPeriodFocus: 'Focus this period',
    pomodoroVsSinceLast: 'vs last period',
    pomodoroAllTime: 'All time',
    pomodoroInsightsDailyTitle: 'Daily focus this week',
    pomodoroInsightsWeeklyBreakdownTitle: 'Weekly averages',
    pomodoroInsightsAvgWeekLabel: 'avg/day (week)',
    pomodoroInsightsAvgPeriodLabel: 'avg/day (period)',
    pomodoroInsightsPerDaySuffix: '/d',
    pomodoroInsightsNoWeeklyData: 'No weekly data yet.',
    pomodoroInsightsDayLabels: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
    pomodoroTotalTimeLabel: 'total time',
    pomodoroClose: 'Close',
    pomodoroEraseStats: 'Erase stats',
    pomodoroEraseStatsTitle: 'Erase pomodoro stats?',
    pomodoroEraseStatsDesc: 'Historical focus-time stats will be removed, but tomato entries stay available.',
    pomodoroGraceCancel: 'Cancel (no tomato)',
    pomodoroGrace: s => `${s}s to cancel without losing a tomato`,
    pomodoroStreakTitle: 'Streak', pomodoroCurrentStreak: 'Current streak', pomodoroBestStreak: 'Best streak',
    pomodoroStreakDaySuffix: 'd',
    pomodoroTrendTitle: 'Monthly trend', pomodoroTrendNoData: 'No monthly data yet.',
    pomodoroCopySummary: 'Copy summary', pomodoroCopiedSummary: 'Copied!',
    workModeLabel: 'Work mode',
    workModeDesc: 'Hides grades and renames classes to groups.',
    workModeOnboarding: 'Using this for work?',
    semesterModeLabel: 'No semester mode',
    semesterModeDesc: 'Turn on to use plain year weeks instead of semesters. Grades are hidden.',
    semesterModeNone: 'No semesters (year weeks)',
    semesterModeSemesters: 'Using semesters',
    semesterModeOnboarding: 'No semesters, just weeks?',
    groups: 'Groups', group: 'Group', addAGroup: 'Add group', groupName: 'Group name',
    deleteGroupTitle: 'Delete group?', deleteGroupDesc: 'This will also delete all tasks for this group.',
    storageWarningTitle: 'Storage limit reached',
    storageWarningDesc: 'Please activate Firebase sync, reached max local storage.',
    storageWarningAction: 'Got it',
    collabConnect: 'Connect Organizer Collab',
    collabDisconnect: 'Disconnect Organizer Collab',
    collabRequiresFirebase: 'Connect Firebase sync first to use Organizer Collab.',
    collabGuideTitle: 'Organizer Collab setup',
    collabGuideIntro: 'One-time setup. Do these 4 steps in Firebase, then come back and enable collab.',
    collabGuideImportantTitle: 'What changes when collab is enabled',
    collabGuideImportant1: 'Your database starts requiring authenticated users (anonymous auth is enough).',
    collabGuideImportant2: 'Normal organizer sync keeps working, but it must authenticate first.',
    collabGuideImportant3: 'If collab is disabled later, auth-based rules can still be used safely.',
    collabGuideStep1: 'Open Firebase Console > Build > Firestore Database > Rules.',
    collabGuideStep2: 'Paste the rules snippet below and click Publish.',
    collabGuideStep3: 'Open Security > Authentication > Sign-in method > enable Anonymous > Save.',
    collabGuideStep4: 'Return to Organizer and press "I configured rules, enable collab".',
    collabGuideRulesLabel: 'Firestore rules',
    collabRulesHelpTitle: "Firestore rules",
    collabRulesHelpHost: "Your team's Firestore rules are out of date or too strict. Paste the rules below into your Firebase console, then reload.",
    collabRulesHelpMember: "This team can't be reached. Only the host can fix it — send them the rules below to paste into their Firebase console.",
    copy: "Copy",
    copied: "Copied!",
    collabGuideGotIt: "Got it",
    collabFirebaseOnlyForCreating: "Enable collab to share tasks with other people through teams. Firebase is necessary to create teams.",
    collabGuideTroubleshootTitle: 'If you see signUp 400 error',
    collabGuideTroubleshootBody: 'That means Anonymous authentication is still disabled in Firebase. Enable it in Security > Authentication > Sign-in method.',
    collabEnableNow: 'I configured rules, enable collab',
    collabPanelTitle: 'Organizer Collab',
    collabPanelSubtitle: 'Create teams, invite people, and share tasks/kanban cards.',
    collabCreateTeam: 'Create team',
    collabTeamName: 'Team name',
    collabTeamDays: 'team days',
    collabTeamDuration: 'team duration',
    collabNeverExpires: 'never expires',
    collabDays: 'days',
    collabJoinTeam: 'Join team',
    collabInvitePlaceholder: 'Paste invite link',
    collabInviteTtl: 'Invite validity',
    collabYourTeams: 'Your teams',
    collabNoTeams: 'No teams yet.',
    collabShare: 'Share',
    collabShareTask: 'Share task', collabShareEvent: 'Share event',
    collabShareCard: 'Share card',
    collabShareNote: 'Share note',
    collabShared: 'Shared',
    notesSaveLocalCopy: 'Save local copy',
    notesOfflineOnlyOn: 'Keep this note offline only (won\'t sync)',
    notesOfflineOnlyOff: 'Keep offline only',
    collabSelectTeam: 'Select team',
    collabRoleHost: 'host',
    collabRoleMember: 'member',
    all: 'All',
    collabAlias: 'Your alias',
    collabEditAlias: 'Edit alias',
    collabAliasPromptTitle: 'Add your name?',
    collabAliasPromptDesc: teamName => `Let others in "${teamName}" see who you are. You can skip this and set it later.`,
    collabMembers: 'Members',
    collabAssignedOnlyComplete: 'Only assigned can complete',
    collabKanbanDividers: 'Kanban dividers',
    collabSeparateByTeam: 'Separate by team',
    collabPersonal: 'Personal',
    collabUnassigned: 'Unassigned',
    collabMe: 'Me',
    collabAssignee: 'Assignee',
    collabSeparateByClass: 'Separate by class',
    kanbanAllTeams: 'All teams',
    kanbanAllAssignees: 'All assignees',
    kanbanAllClasses: 'All classes',
    kanbanFilterTeam: 'Team',
    kanbanFilterClass: 'Class',
    kanbanNoClass: 'No class',
    kanbanResetFilters: 'Reset',
    kanbanFilterCount: '{n} selected',
    collabEndsAt: 'ends',
    collabInvite: 'Invite',
    collabEditTeam: 'Edit team',
    collabTaskCompletionMode: 'Shared task completion',
    collabTaskCompletionPersonal: 'personal completion',
    collabTaskCompletionForAll: 'toggle for everyone',
    collabTaskPermissions: 'Task edit permissions',
    collabTaskPermissionsEveryone: 'anyone can add/edit/remove tasks',
    collabTaskPermissionsHostOnly: 'only host can add/edit/remove tasks',
    collabLeave: 'Leave',
    collabDeleteTeam: 'Delete',
    collabDefaultTeamName: 'Team',
    collabLeavePrompt: 'Leave this team?',
    collabLeaveWithLocalPrompt: 'You shared local tasks in this team. Keep them locally?',
    collabDeleteTeamPrompt: 'Delete this team?',
    collabDeleteTeamWithLocalPrompt: 'You shared local tasks in this team. Keep them locally before deleting the team?',
    collabKeepLocalTasks: 'Keep local tasks',
    collabDeleteLocalTasksToo: 'Delete local tasks',
    collabErrorCreate: 'Could not create team.',
    collabErrorInvite: 'Could not generate invite.',
    collabErrorJoin: 'Could not join team.',
    collabErrorInvalidLink: 'Invalid invite link.',
    collabErrorDeleteTeam: 'Could not delete team.',
    collabGuideChecklistTitle: 'Still not syncing?',
    collabGuideChecklistBody: 'The two steps Organizer cannot do for you: enable Anonymous Auth, and publish the Firestore rules above. If shared tasks never appear, one of these is missing on the host project.',
    collabSyncErrorHint: "Can't reach this team. Check the host's Firebase has Anonymous Auth enabled and open rules.",
    collabKeyRequiredHint: 'This team is encrypted and your invite link had no key. Ask for a fresh invite link.',
    collabDeviceUnlinkedHint: "This device is not linked to this team yet. Open an invite link here to sync.",
    collabErrorPermission: 'Blocked by Firebase rules. Host must enable Anonymous Auth and open Firestore rules.',
    collabErrorAuthDisabled: "Anonymous sign-in is turned off in the host's Firebase project. The host must enable it under Authentication › Sign-in method.",
    collabErrorNotFound: 'Team not found. It may have been deleted.',
    collabErrorInviteExpired: 'This invite has expired. Ask the host for a new link.',
    collabErrorInviteInvalid: 'This invite link is not valid for that team.',
    collabErrorNoteTooLarge: 'This note is too large to share with the team. Try splitting it into smaller notes.',
    firebaseRulesTemplateLink: 'View Firestore rules template',
    firebaseOpenRulesWarningTitle: 'Your database rules may be open',
    firebaseOpenRulesWarningDesc: 'Sync is working without authentication, which usually means your Firestore rules allow anyone to read and write your data. Publish the rules template linked below to lock this down.',
    firebaseEncryptionOffTitle: 'End-to-end encryption is off',
    firebaseEncryptionOffDesc: 'Your data is stored in Firestore as plain text. Turn on encryption so only devices with your key can read it — even if your database rules are ever misconfigured.',
    firebaseEncryptNow: 'Encrypt now',
    firebaseEncryptMigrateFailed: 'Could not enable encryption. Check your connection and try again.',
    firebaseHaveKeyAlready: 'This device already has a key from another install',
    firebaseKeyPastePlaceholder: 'Paste your recovery key',
    firebaseKeyInvalid: 'That does not look like a valid key.',
    firebaseKeyWrongOrUnreadable: 'Could not decrypt with this key. Double check it and try again.',
    firebaseRecoveryKeyShownOnceTitle: 'Save this recovery key now',
    firebaseRecoveryKeyShownOnceDesc: 'This key is shown only once and is never sent to Firebase. Anyone with it can read your data; anyone without it (including you) cannot recover it if lost. Store it somewhere safe.',
    firebaseKeySavedItConfirm: "I've saved my key",
    firebaseEncryptionOnTitle: 'End-to-end encryption is on',
    firebaseEncryptionOnDesc: 'Your data is encrypted on this device — both in local storage and before it reaches Firestore. Only devices with the recovery key can decrypt it.',
    firebaseShowRecoveryKey: 'Show recovery key',
    firebaseShowRecoveryKeyConfirmTitle: 'Show recovery key?',
    firebaseShowRecoveryKeyConfirmDesc: 'Anyone who sees this key can decrypt your data. Only do this somewhere private.',
    firebaseKeyRequiredTitle: 'Encryption key needed',
    firebaseKeyRequiredDesc: 'This project’s data is encrypted. Paste the recovery key from a device that already has it to unlock sync on this device.',
    firebaseKeyRequiredForImport: 'This backup is encrypted. Set up sync with the matching key first, then import again.',
    exportEncrypted: 'Organizer format (encrypted)',
    exportPlaintext: 'Human-readable (plaintext JSON)',
    encUnlockTitle: 'Unlock your data',
    encUnlockDesc: 'Your stored data is encrypted. Enter your passphrase to unlock it.',
    encUnlockHintLabel: 'Your hint',
    encPassphraseLabel: 'Passphrase',
    encPassphrasePlaceholder: 'Your passphrase',
    encPassphraseConfirmLabel: 'Confirm passphrase',
    encPassphraseMismatch: 'The two passphrases do not match.',
    encPassphraseTooShort: 'Use at least 8 characters.',
    encHintLabel: 'Passphrase hint (optional)',
    encHintPlaceholder: 'A private reminder, not the passphrase itself',
    encRecoveryCodeTitle: 'Save your recovery code',
    encRecoveryCodeDesc: 'These 12 English words are the only way back in if you forget your passphrase. Write them down or store them in a password manager. We cannot show them again.',
    encRecoveryCodeWordsNote: '12 English words. Copy them exactly, in order.',
    encRecoveryCodeSavedConfirm: 'I have saved my recovery code',
    encRecoveryCodeQr: 'Show QR code',
    encRecoveryCodeQrDesc: 'Scan this on another device to transfer the recovery code.',
    encUseRecoveryCode: 'Use recovery code instead',
    encUsePassphrase: 'Use passphrase instead',
    encRecoveryCodeLabel: 'Recovery code',
    encRecoveryCodePlaceholder: 'twelve words separated by spaces',
    encRecoveryCodeInvalid: 'That is not a valid 12-word recovery code.',
    encUnlockFailed: 'Could not unlock with that. Check it and try again.',
    encUnlocking: 'Unlocking…',
    encDeriving: 'Deriving key…',
    encEnableTitle: 'Turn on end-to-end encryption',
    encEnableDesc: 'Your data is encrypted on this device before it is stored or synced anywhere. Only devices with your passphrase or recovery code can read it.',
    encEnableWarning: 'If you lose both your passphrase and your recovery code, your data cannot be recovered by anyone, including us.',
    encEnableSubmit: 'Turn on encryption',
    encEnableFailed: 'Could not turn on encryption. Check your connection and try again.',
    encManageTitle: 'Encryption',
    encManageDesc: 'Your data is end-to-end encrypted. Unlocking happens on this device only.',
    encChangePassphrase: 'Change passphrase',
    encChangePassphraseDesc: 'Enter your current passphrase, then the new one.',
    encCurrentPassphraseLabel: 'Current passphrase',
    encRegenerateRecoveryCode: 'Generate a new recovery code',
    encRegenerateRecoveryCodeDesc: 'Replaces your existing code. The old one stops working.',
    encEditHint: 'Edit hint',
    encRotateDekTitle: 'Rotate encryption key',
    encRotateDekDesc: 'Re-encrypts all your data under a brand new key. Other devices will need to unlock again.',
    encRotateDekWarning: 'Do not close the app until this finishes.',
    encRotating: 'Re-encrypting…',
    encRotateFailed: 'Could not rotate the key. Nothing was changed.',
    encSaved: 'Saved.',
    encStoreUnavailableTitle: 'Cannot reach secure storage',
    encStoreUnavailableDesc: 'This browser blocked the secure key store, often in private browsing. Your encrypted data was left untouched. Try a normal window.',
    encPlaintextSyncWarnTitle: 'Sync is not encrypted',
    encPlaintextSyncWarnDesc: 'Your synced data is stored as plain text. Anyone who can read your database can read it.',
    encPlaintextSyncEnable: 'Turn on encryption',
    encPlaintextSyncDismiss: 'Not now, do not ask again',
    encRemoteAlreadyEncrypted: 'This project is already encrypted. Unlock it to connect this device.',
    encRemoteNotEncryptedTitle: 'Encrypt this project?',
    encRemoteNotEncryptedDesc: 'This project holds unencrypted data. Turn on encryption now and it will be re-uploaded encrypted.',
    encRemoteNotEncryptedMigrate: 'Encrypt and migrate',
    encRemoteNotEncryptedSkip: 'Keep it unencrypted',
    encRemoteUnrecoverable: 'This project is encrypted but has no recovery data, so it cannot be unlocked. Disconnect and start a new project.',
    encRemoteDekMismatch: 'This project was re-encrypted with a new key. Unlock it again with your passphrase or recovery code.',
    encExportPassphraseTitle: 'Protect this backup',
    encExportPassphraseDesc: 'Choose a passphrase for the file. You will need it to restore, on any device.',
    encImportPassphraseTitle: 'Unlock this backup',
    encImportPassphraseDesc: 'Enter the passphrase you chose when exporting.',
    encImportPassphraseFailed: 'Wrong passphrase for this backup.',
    encTitle: 'Encryption',
    encOffTitle: 'Encryption is off',
    encOffDesc: 'Your data is stored as plain text wherever it is kept. Turn on encryption and it becomes unreadable without your passphrase, on this device and anywhere it syncs.',
    encOnDesc: 'Your data is encrypted before it is stored or synced. Only devices with your passphrase or recovery code can read it.',
    encLockedDesc: 'Your stored data is encrypted. Enter your passphrase to unlock it on this device.',
    encEnableAction: 'Turn on encryption',
    encDisableAction: 'Turn off encryption',
    encDisableTitle: 'Turn off encryption?',
    encDisableDesc: 'Your data will be rewritten as plain text wherever it is stored, and your passphrase and recovery code stop working.',
    encStorageShedTitle: 'Some data did not fit',
    encStorageShedDesc: 'This device ran out of local storage, so the following was left unsaved locally:',
    repeat: 'Repeat', repeatFreqLabel: 'Frequency',
    repeatFreqDaily: 'Daily', repeatFreqWeekly: 'Weekly', repeatFreqMonthly: 'Monthly',
    repeatEvery: () => 'Every', repeatIntervalDaily: n => (n === 1 ? 'day' : 'days'),
    repeatIntervalWeekly: n => (n === 1 ? 'week' : 'weeks'),
    repeatIntervalMonthly: n => (n === 1 ? 'month' : 'months'),
    repeatUntil: 'Until (optional)',
    kanbanColTodo: 'To Do', kanbanColInProgress: 'In Progress', kanbanColDone: 'Done',
    colourCustom: 'Custom colour',
    googleCalendar: 'Google Calendar',
    gcalConnect: 'Connect', gcalConnected: 'Connected', gcalConnecting: 'Connecting…', gcalDisconnect: 'Disconnect',
    gcalEnable: 'Sync with Google Calendar',
    gcalScopeNotice: 'This grants full read/write access to your primary Google Calendar (the "calendar" scope). Organizer only reads and writes events you interact with here; your Google credentials never leave your device and are not sent anywhere but Google.',
    gcalStep1Title: 'Create a Google Cloud project', gcalStep1Desc: 'Go to console.cloud.google.com → create a new project (or pick one) → APIs & Services → enable the "Google Calendar API".',
    gcalStep2Title: 'Configure OAuth consent + credentials', gcalStep2Desc: 'APIs & Services → OAuth consent screen → set it up (External is fine for personal use, add yourself as a test user). Then Credentials → Create credentials → OAuth client ID → Application type: Web application → add this app\'s URL to Authorized JavaScript origins.',
    gcalStep3Title: 'Paste your Client ID', gcalStep3Desc: 'Copy the Client ID (ends in .apps.googleusercontent.com) shown after creating it, and paste it below. This value is not secret and is safe to store in this browser.',
    gcalClientIdPlaceholder: 'xxxxxxxx.apps.googleusercontent.com',
    gcalClientIdInvalid: 'Enter a valid OAuth Client ID.',
    gcalConnectFailed: 'Could not connect. Check your Client ID and try again.',
    gcalDisableTitle: 'Disconnect Google Calendar?', gcalDisableDesc: 'Stops syncing with Google Calendar on this device. Events already created stay in both places; sync bookkeeping (Client ID, links) is removed here.',
    eventSyncToGoogle: 'Sync to Google Calendar', eventSyncToGoogleDesc: 'Push this event to your connected Google Calendar.',
    quickActionTaskWords: ['task'], quickActionEventWords: ['calendar event', 'event'], quickActionCardWords: ['kanban card', 'card'], quickActionAddWords: ['add'],
    quickActionForWords: ['for'], quickActionAndWords: ['and'],
    quickActionOnWords: ['on'], quickActionArticleWords: ['a', 'an', 'the'], quickActionBoardWords: ['kanban', 'board'],
    quickAction: 'Quick action', quickActionPlaceholder: 'e.g. add task and calendar event for test on 18/07 at 15h',
    quickActionTab: 'Quick action', quickActionFormTab: 'Form',
    quickActionPreviewTitle: 'Will create',
    quickActionPreviewTask: 'task', quickActionPreviewTaskCalendar: 'task (shown on calendar)',
    quickActionPreviewEvent: 'calendar event', quickActionPreviewCard: column => `kanban card in ${column}`,
    quickActionEmpty: "Couldn't understand that. Try rephrasing.",
    quickActionCreate: 'Create', quickActionBack: 'Back',
    notesDeleteConfirmTitle: 'Delete this note?', notesDeleteConfirmDesc: 'This note will be permanently deleted.',
    notesEmptyTitle: 'No notes yet', notesEmptyDesc: 'Create your first note to get started.',
    notesFilterEmpty: 'No notes match your search.',
    notesFolderEmpty: 'This folder is empty.',
    notesTableAddRow: 'Add row', notesTableAddColumn: 'Add column', notesTableResize: 'Resize table',
    notesSelectNote: 'Select a note to start editing',
    notesTextNote: 'Text note', notesCanvasNote: 'Canvas note',
    eventStartTimeFirstDay: 'Start time (first day)', eventEndTimeLastDay: 'End time (last day)',
    notesBold: 'Bold', notesItalic: 'Italic', notesStrike: 'Strikethrough',
    notesHeading1: 'Heading 1', notesHeading2: 'Heading 2', notesHeading3: 'Heading 3',
    notesBulletList: 'Bullet list', notesOrderedList: 'Numbered list', notesTaskList: 'Checklist',
    notesQuote: 'Quote', notesInsertTable: 'Insert table', notesCodeBlock: 'Code block', notesDivider: 'Divider',
    notesAddLink: 'Add link', notesRemoveLink: 'Remove link',
    notesTextColor: 'Text colour', notesColorReset: 'Default colour',
    notesColorCustom: 'Pick a custom colour', notesColorApply: 'Apply',
    notesExport: 'Export note', notesImport: 'Import note',
    notesGraphEdit: 'Edit graph', notesGraphRange: 'x from', notesGraphResize: 'Drag to resize', notesGraphResizeWidth: 'Drag to resize width and height',
    notesGraphInvalid: 'Not a plottable expression',
    notesGraphAlignleft: 'Align left', notesGraphAligncenter: 'Centre', notesGraphAlignright: 'Align right',
    notesGraphWrapLeft: 'Wrap text on the right', notesGraphWrapRight: 'Wrap text on the left', notesGraphFullWidth: 'Full block', notesGraphMove: 'Drag to move sideways',
    notesTextSize: 'Text size', notesSizeNormal: 'Normal', notesSizeSmall: 'Small', notesSizeLarge: 'Large', notesSizeHuge: 'Huge',
    notesUndo: 'Undo', notesRedo: 'Redo',
    notesViewList: 'List view', notesViewMosaic: 'Mosaic view',
    notesMathEnable: 'Maths solving', notesMathEnableDesc: 'Type an equation ending in = and press Enter to solve it. Use x to draw a graph.',
    notesMathSolve: 'Solve for x', notesMathSolveDesc: 'Turn 3x = 3 into x = 1, including inequalities and quadratics.',
    notesMathSelection: 'Graph a selection', notesMathSelectionDesc: 'Select an equation and press Enter to plot it.',
    notesMathSteps: 'Show the working', notesMathStepsDesc: 'Reveal each step of the solution instead of only the answer.',
    eisenhowerAddTask: 'Add task', eisenhowerCustomize: 'Customize quadrants', eisenhowerResetDefaults: 'Reset to defaults',
    eisenhowerCleanDone: 'Clear completed',
    eisenhowerCleanDoneTitle: 'Clear completed tasks?',
    eisenhowerCleanDoneDesc: 'Removes completed tasks from the matrix. They stay in your task list.',
    aiAssistant: 'AI Assistant',
    aiSetupIntro: "The assistant can read and edit your data using a model you choose. Prompts and the data you include are sent to that model's provider.",
    aiSetupStep1Title: 'Choose your main model',
    aiSetupStep1Desc: 'This model drives the assistant. Pick a provider, enter the model, and add your API key.',
    aiSetupSave: 'Save',
    aiConfigured: 'AI Assistant connected',
    aiNotConnected: 'Not connected',
    aiEnable: 'Enable AI Assistant',
    aiDisable: 'Disconnect',
    aiDisableTitle: 'Disconnect AI Assistant?',
    aiDisableDesc: "This clears your model settings, API keys, and the assistant's activity journal. This can't be undone.",
    aiOptimizeForLabel: 'Usage priority',
    aiOptimizeRequestsShort: 'Requests', aiOptimizeBalancedShort: 'Balanced', aiOptimizeTokensShort: 'Tokens',
    aiModelSlots: 'Model slots',
    aiSlotLowLabel: 'Cheap',
    aiSlotMediumLabel: 'Normal',
    aiSlotHighLabel: 'Best',
    aiSlotLow: 'Cheap', aiSlotMedium: 'Normal', aiSlotHigh: 'Best',
    aiSlotProvider: 'Provider', aiSlotProviderPlaceholder: 'Choose a provider',
    aiSlotBaseUrl: 'Base URL', aiSlotBaseUrlPlaceholder: 'http://localhost:11434/v1',
    aiSlotModel: 'Model', aiSlotModelPlaceholder: 'e.g. claude-sonnet-4-5',
    aiSlotApiKey: 'API key', aiSlotApiKeyPlaceholder: 'Paste your API key',
    aiSlotDailyCap: 'Requests per day (optional)', aiSlotDailyCapPlaceholder: 'No limit',
    aiSlotClear: 'Clear',
    aiTestModel: 'Test this model', aiTesting: 'Testing...',
    aiTestOkWithTools: 'It answered and supports tools.',
    aiTestOkNoTools: 'It answered, but does not support tools.',
    aiErrorAuth: 'That API key was rejected.',
    aiErrorRateLimit: 'Rate limited — try again shortly.',
    aiErrorNoSuchModel: "That model wasn't found.",
    aiErrorNoToolSupport: "That model doesn't support tools.",
    aiErrorNetwork: "Couldn't reach the provider.",
    aiErrorUnknown: 'Something went wrong testing that model.',
    aiToolSupportRedirect: 'That model has no tool support — put it in the cheap slot instead.',
    aiConsentLocalNotice: 'This model runs on your own device or network. Nothing leaves your control.',
    aiConsentThirdPartyNotice: 'Prompts and the data you include will be sent to {provider}.',
    aiConsentAccept: 'I understand, continue',
    aiProactiveLabel: 'AI with initiative',
    aiProactiveDesc: 'The assistant quietly reviews changes you make and may offer a suggestion. This increases AI spend and sends more of your data to the model provider.',
    aiProactiveConsentNotice: 'When this is on, the app sends extra background requests to your configured AI model after changes you make, which increases your AI spend and shares more of your data with the model provider. You can turn it off at any time.',
    aiProactiveOpenInAssistant: 'Open in assistant',
    aiLocalhostHintWeb: "A page served over HTTPS can't reach http://localhost — this needs a local HTTPS proxy or a browser exception (e.g. OLLAMA_ORIGINS). That's a setup step on your machine, not something the app can fix.",
    aiLocalhostHintNative: "On your phone, localhost means the phone itself. Use your computer's LAN address instead (e.g. http://192.168.x.x:11434) and run Ollama with OLLAMA_HOST=0.0.0.0.",
    aiPillReplyReady: 'Reply ready',
    aiPillFailed: 'AI run failed',
    aiPillInterrupted: 'AI run interrupted',
    aiViewConversation: 'Conversation', aiViewTarget: 'Target',
    aiJournalHeading: 'Run journal',
    aiScopeGlobal: 'everything', aiScopeFolder: 'this folder', aiScopeClass: 'this class',
    aiScopeSemester: 'this semester', aiScopeSelection: 'selection',
    aiStatusRunning: 'Working…', aiStatusFailed: 'The run failed.',
    aiErrorValidation: 'Some of the proposed changes were invalid and the run was stopped.',
    aiRetry: 'Retry', aiDismiss: 'Dismiss',
    aiErrorNoSlot: 'No model is configured for this. Add one in AI settings.',
    aiErrorBudget: "Today's request budget for this model is used up.",
    aiRejectUnknownId: "couldn't find that item",
    aiRejectUnknownEntityType: 'unrecognised item type',
    aiRejectUnknownOpType: 'unrecognised action',
    aiRejectMissingId: 'missing an id',
    aiRejectMalformedOp: 'malformed request',
    aiRejectOutOfScope: 'outside what this run can touch',
    aiRejectDisallowedField: 'invalid field(s): {fields}',
    aiRejectUnresolvedDate: "couldn't understand the date for {field}",
    aiRejectUnknown: 'rejected',
    aiGreeting: 'What should the assistant do?',
    aiGreetingGeneric2: 'Ready when you are.',
    aiGreetingGeneric3: "What's on your mind?",
    aiGreetingGeneric4: 'How can I help today?',
    aiGreetingMorning: 'Good morning.',
    aiGreetingMorning2: 'Hope your morning is off to a great start.',
    aiGreetingAfternoon: 'Good afternoon.',
    aiGreetingAfternoon2: 'Ready to tackle the rest of the day?',
    aiGreetingEvening: 'Good evening.',
    aiGreetingEvening2: 'Winding down or getting things done?',
    aiGreetingNight: 'Working late?',
    aiGreetingNight2: 'Burning the midnight oil?',
    aiGreetingWeatherClear: "It's clear out today.",
    aiGreetingWeatherClear2: 'Sunny skies outside today.',
    aiGreetingWeatherCloudy: 'A bit cloudy today.',
    aiGreetingWeatherCloudy2: 'Overcast skies today.',
    aiGreetingWeatherRain: 'Rainy out there today.',
    aiGreetingWeatherRain2: "Don't forget your umbrella today.",
    aiGreetingWeatherSnow: "It's snowing today.",
    aiGreetingWeatherSnow2: 'Bundle up, it is snowing outside.',
    aiGreetingWeatherStorm: 'Stormy today — stay in.',
    aiGreetingWeatherStorm2: 'Thunderstorms today — stay safe indoors.',
    aiGreetingWeatherFog: "It's foggy today.",
    aiGreetingWeatherFog2: 'Misty and foggy out there today.',
    aiGoalPlaceholder: 'What should the assistant do?',
    aiCancelRun: 'Cancel', aiStartRun: 'Start',
    aiThinkingToggle: 'Requests made ({count})',
    aiConfirmHeading: 'Ready to review',
    aiConfirmApprove: 'Approve', aiConfirmDiscard: 'Discard',
    aiConfirmOpCount: '{count} change(s)',
    aiOpVerbCreate: 'Create', aiOpVerbUpdate: 'Update', aiOpVerbDelete: 'Delete',
    aiJournalUnknownModel: 'Unknown model',
    aiJournalRequestCount: '{count} request(s)',
    aiJournalUndo: 'Undo', aiJournalUndoBlocked: "This run can't be undone right now.",
    aiJournalEmpty: 'No runs yet.',
    aiOverlayCreated: 'proposed', aiOverlayDeleted: 'to remove', aiOverlayUpdated: 'proposed edit',
    aiTargetNoteMissing: "This note isn't available.",
    aiTargetUntitled: 'Untitled note',
    aiTargetCard: 'Card',
    aiTargetTask: 'Task',
    aiTargetNoteEmpty: 'This note is empty.',
    aiTargetListEmpty: 'No proposed changes yet.',
    aiNewConversation: 'New',
    aiHistory: 'History',
    aiHistoryEmpty: 'No recent chats',
    aiHistorySave: 'Save chat',
    aiHistorySaved: 'Saved',
    aiHistoryDelete: 'Delete chat',
    aiModeAuto: 'auto',
    aiModeManual: 'manual',
    aiAutoModeLabel: 'Auto-apply changes',
    aiDefaultModelLabel: 'Default model',
    aiShortcutLabel: 'Keyboard shortcut',
    aiShortcutPlaceholder: 'Disabled (click to set)',
    aiPreferencesLabel: 'AI preferences',
    aiPreferencesPlaceholder: 'e.g. never touch my calendar without asking',
    aiShortcutListening: 'Press key combo or Backspace…',
    aiContextPrefixTemplate: "I'm looking at {context}. ",
    aiContextTabNotes: 'my notes', aiContextTabTasks: 'my tasks', aiContextTabKanban: 'my kanban board',
    aiContextTabCalendar: 'my calendar', aiContextTabGrades: 'my grades', aiContextTabFocus: 'my focus session',
    aiHideTarget: 'Hide',
    aiShowTarget: 'Show proposed changes',
    aiSummaryNoChanges: 'No changes',
    aiSummaryJoin: ', ',
    aiSummaryTaskCreated: '{count} task(s) created', aiSummaryTaskUpdated: '{count} task(s) updated', aiSummaryTaskDeleted: '{count} task(s) removed',
    aiSummaryEventCreated: '{count} event(s) created', aiSummaryEventUpdated: '{count} event(s) updated', aiSummaryEventDeleted: '{count} event(s) removed',
    aiSummaryNoteCreated: '{count} note(s) created', aiSummaryNoteUpdated: '{count} note(s) updated', aiSummaryNoteDeleted: '{count} note(s) removed',
    aiSummaryFolderCreated: '{count} folder(s) created', aiSummaryFolderUpdated: '{count} folder(s) updated', aiSummaryFolderDeleted: '{count} folder(s) removed',
    aiSummaryHabitCreated: '{count} habit(s) created', aiSummaryHabitUpdated: '{count} habit(s) updated', aiSummaryHabitDeleted: '{count} habit(s) removed',
    aiSummaryClassCreated: '{count} class(es) created', aiSummaryClassUpdated: '{count} class(es) updated', aiSummaryClassDeleted: '{count} class(es) removed',
    aiSummaryCardCreated: '{count} card(s) created', aiSummaryCardUpdated: '{count} card(s) updated', aiSummaryCardDeleted: '{count} card(s) removed',
    quickActionApp: 'Quick Action',
    quickActionAppEnable: 'Enable Quick Action', quickActionAppEnableDesc: 'Adds a spotlight overlay for quickly creating tasks, events, and cards.',
    quickActionTripleTapEnable: 'Triple tap on screen', quickActionTripleTapEnableDesc: 'Tap 3 times anywhere to open Quick Action',
    quickActionShortcutEnable: 'Keyboard shortcut', quickActionShortcutKey: 'Shortcut',
    quickActionNavbarButton: 'Show in navbar add menu',
    spotlightPlaceholder: 'Quick action… (e.g. add task for exam on Monday)',
    themeColor: 'Theme colors', themeColorDesc: 'Pick colors for font, highlights, and background.',
    themeColorReset: 'Reset to default',
    themeFontColor: 'Font color', themeHighlightColor: 'Highlight color', themeBgColor: 'Background color', themeDoneColor: 'Done color', canvasAddPage: 'Add page', canvasRemovePage: 'Remove page',
    defaultTabLabel: 'Default screen', defaultTabDesc: 'Pick the tab the app opens on.',
    defaultTabLast: 'Last used',
    taskReminderOffsetsLabel: 'Reminder lead times', taskReminderOffsetsDesc: 'How many days before a due date to remind you. Applies to every task with a due date.',
    taskReminderTimeLabel: 'Reminder time', taskReminderTimeDesc: 'Time of day the lead-time reminders fire.',
    taskReminderAddOffset: 'Days',
    taskReminderOffsetDays: n => (n === 0 ? 'On the day' : n === 1 ? '1 day before' : `${n} days before`),
    taskReminderIn: n => (n === 0 ? 'Due today' : n === 1 ? 'Due tomorrow' : `Due in ${n} days`),
    habits: 'Habits', habitsEnable: 'Enable Habits', habitsEnableDesc: 'Track long-term habits with a check-in button and a streak calendar.',
    habitsEmpty: 'No habits yet. Add one to get started.',
    habitAdd: 'Add habit', habitEdit: 'Edit habit',
    habitTitleLabel: 'Habit', habitTitlePlaceholder: 'Read for 20 minutes',
    habitCadenceLabel: 'Check in', habitCadenceDesc: 'How often you want to click the button.',
    habitCadenceDaily: 'Every day', habitCadence2Days: 'Every 2 days', habitCadence3Days: 'Every 3 days',
    habitCadenceWeekly: 'Every week', habitCadenceMonthly: 'Every month',
    habitRequireNote: 'Ask for a note', habitRequireNoteDesc: 'Write a short note each time you check in.',
    habitColor: 'Color',
    habitClickPrompt: 'Mark as complete', habitDoneForNow: 'Done',
    habitNotePrompt: 'How did it go?', habitNotePlaceholder: 'A few words',
    habitSeeProgress: 'See progress', habitUndoToday: 'Undo this check-in', habitDelete: 'Delete habit',
    habitDeleteTitle: 'Delete this habit?', habitDeleteDesc: 'The habit and its whole track record will be removed.',
    habitCurrentStreak: 'Current streak', habitBestStreak: 'Best streak',
    habitTotalCheckIns: 'Check-ins', habitCompletionRate: 'Completion',
    habitNotesTitle: 'Notes',
    habitCadenceCustom: 'Custom days', habitWeekdaysLabel: 'Days of the week', habitWeekdaysDesc: 'Pick the days you want to check in on.', habitRestDay: 'Rest day',
    habitToneLabel: 'Encouragement style', habitToneDesc: 'What kind of message you get after each check-in.',
    habitTonePurpose: 'Purpose & progress', habitToneWarm: 'Warm & empowering',
    habitToneUpbeat: 'Upbeat & satisfying', habitToneGame: 'Video game',
    habitToneRandom: 'Random each time', habitToneCustom: 'My own message',
    habitToneCustomPlaceholder: 'Your message',
    habitTargetLabel: 'Finish line', habitTargetDesc: 'When this habit counts as finished.',
    habitTargetEndless: 'Keep going', habitTargetCount: 'After a number of check-ins', habitTargetDate: 'By a date',
    habitTargetCountPlaceholder: 'Check-ins',
    habitTargetReached: 'Habit reached.',
    habitTargetRemaining: n => (n === 1 ? '1 check-in to go' : `${n} check-ins to go`),
    habitTargetDaysLeft: n => (n === 0 ? 'Last day' : n === 1 ? '1 day left' : `${n} days left`),
    habitMessages: {
      purpose: {
        day1: 'First entry logged. The journey begins.',
        early: 'Stacking consistency day by day.',
        week: '7 straight days of moving forward.',
        month: '30 consecutive days completed.',
        daily: 'Another day closer to your long-term habit.',
        rescue: 'Back on target today.',
      },
      warm: {
        day1: 'You took the hardest step. Proud of you.',
        early: 'You are proving you can trust yourself.',
        week: 'One whole week! Look how far you have come.',
        month: '30 days of dedication. You built a real habit.',
        daily: 'Another solid step forward today.',
        rescue: 'Glad you are back. Every day is a fresh opportunity.',
      },
      upbeat: {
        day1: 'Off to a fantastic start!',
        early: 'Another great day in the books!',
        week: '7 days straight! Fantastic work.',
        month: '30 days! That is a huge milestone.',
        daily: 'Checked off! Feeling good.',
        rescue: 'Glad you are back! Let us keep going.',
      },
      game: {
        day1: 'Quest Started: Level 1 complete.',
        early: 'Combo streak active. XP earned.',
        week: 'Achievement Unlocked: Week One Warrior.',
        month: 'Major Milestone: Boss Level Defeated.',
        daily: 'Daily Quest Complete +100 XP.',
        rescue: 'Respawned. Let us reclaim the streak.',
      },
    },
}
