export const en = {
    tasks: 'Tasks', kanban: 'Kanban', grades: 'Grades', calendar: 'Calendar', focus: 'Focus', settings: 'Settings',
    noSemester: 'No semester set up', goToSettings: 'Head to Settings to get started.',
    weekLabel: w => `Week ${w}`, done: 'done', timeToRelax: 'Time to relax!',
    addTask: 'New task', task: 'Task', class: 'Class', priority: 'Priority',
    editTask: 'Edit task', moveLeft: 'Move left', moveRight: 'Move right', markDone: 'Mark done',
    addToKanban: 'Add to Kanban', themeLight: 'Light theme', themeDark: 'Dark theme', themeSystem: 'System theme',
    addPartTitle: 'Add part',
    fromWeek: 'From week', toWeek: 'To week', dueDate: 'Due date',
    other: 'Other', noTasks: 'No tasks this week.',
    whatNeedsDone: 'What needs to be done?',
    addTaskBtn: 'Add task', showOnCalendar: 'Show on calendar', showOnTasks: 'Show on tasks',
    clearDone: 'Clear done', wipeAll: 'Wipe all',
    addCard: 'Add card', addCardPlaceholder: 'Card title',
    save: 'Save', cancel: 'Cancel', confirm: 'Confirm', delete: 'Delete',
    addEvent: 'Add event', newEvent: 'New event', editEvent: 'Edit event',
    eventTitle: 'Event title', eventDate: 'Date', eventRange: 'Date range',
    eventMultiDay: 'Multiple days', eventColor: 'Color', eventNote: 'Note',
    eventNotePlaceholder: 'Optional note', more: 'more',
    navbar: 'Navbar', navHide: 'Hide', navOverflow: 'Move to more menu', navAddButton: 'Show add-task button',
    navMore: 'More', navLabelMode: 'Show', navLabelBoth: 'Icons + names', navLabelIcons: 'Icons only', navLabelNames: 'Names only',
    add: 'Add', navAddLabel: 'Add', navDrag: 'Drag to reorder',
    appDisableTitle: 'Disable and erase data?', appDisableDesc: 'Turning this app off permanently deletes all its data.',
    collabDisableDesc: 'Disconnecting leaves all teams and permanently removes collaboration data from this device.',
    navAddAction: 'Add button action', navAddPicker: 'Ask each time',
    navFolders: 'Folders', navNewFolder: 'New folder',
    navMobilePosition: 'Mobile navbar position', navPosBottom: 'Bottom bar', navPosSide: 'Side bar',
    addToTasks: 'Add to tasks', inTasks: 'In tasks',
    standby: 'Standby', standbyEnable: 'Enable landscape standby',
    standbyDesc: 'Turn your phone landscape to show an ambient dashboard.',
    standbyLeft: 'Left pane', standbyCenter: 'Center pane', standbyRight: 'Right pane',
    standbyPanels: 'Panels', standbyPane: n => `Pane ${n}`,
    standbyPaneSecond: 'Second card (swipe)', standbyPaneNone: 'None',
    paneWheel: 'Progress wheel', paneWheelTime: 'Wheel + clock', paneCalendar: 'Calendar',
    paneFocus: 'Focus', paneKanban: 'Kanban', paneTasksByCategory: 'Tasks by category',
    notesLastEdit: 'Edited', notesFolder: 'Folder', notesNoFolder: 'No folder', notesNewFolder: 'New folder',
    notesFolderName: 'Folder name', notesRenameFolder: 'Rename folder', notesDeleteFolder: 'Delete folder', notesMoveTo: 'Move to',
    notesEdit: 'Edit', notesPreview: 'Preview', notesBack: 'Back',
    apps: 'Apps', appsSearch: 'Search apps', appsNoResults: 'No apps found.', notes: 'Notes',
    notesEnable: 'Enable Notes', notesEnableDesc: 'Add a Notes tab for quick text notes.',
    notesNew: 'New note', notesTitle: 'Title', notesBody: 'Write something…', notesSearch: 'Search notes',
    notesEmpty: 'No notes yet.', notesFavorite: 'Favorite', notesText: 'Text', notesCanvas: 'Handwriting',
    notesCanvasWarning: 'Notes with drawings may use a lot of space, and as such are only available with Firebase active.',
    collabApp: 'Collaboration',
    eiCalendar: 'EI Calendar', eiCalendarEnable: 'Show EI calendar',
    eiCalendarEnableDesc: 'Adds the official EI course calendar for your year to the calendar, read-only and always up to date.',
    eiCalendarDisableTitle: 'Hide EI calendar?', eiCalendarDisableDesc: 'Stops showing the EI calendar events. Nothing is deleted and you can turn it back on anytime.',
    semester: 'Semester', classes: 'Classes', gradeComponents: 'Grade components',
    kanbanColumns: 'Kanban columns', general: 'General', data: 'Data & sync',
    holidays: 'Holidays',
    exportJson: 'Export JSON', importJson: 'Import JSON',
    semesterAvg: 'Semester average', ectsPassedLabel: 'ECTS passed',
    targetGrade: 'Target grade',
    previousSemesters: 'Previous semesters',
    courseAvg: 'Course average', finalGrade: 'Final grade', previousAvg: 'Previous avg', numSemesters: 'No. of semesters',
    getStarted: 'Get started', welcomeTitle: 'Welcome to organizer',
    welcomeDesc: 'Your space for uni work. Set up your semester and get organised.',
    step1: 'Set your semester dates', step2: 'Add your classes', step3: 'Plan tasks & track grades',
    obNext: 'Next', obBack: 'Back', obFinish: 'Finish', obSkip: 'Skip',
    obWelcomeTitle: 'Welcome to Organizer', obWelcomeDesc: 'Your calm space for uni work. Pick your language and theme to start.',
    obModeTitle: 'How will you use it?', obModeDesc: 'Toggle what fits you. Both can be on.',
    obModeWorkToggle: 'Work mode', obModeWorkToggleDesc: 'Groups instead of classes, no grades.',
    obModeWeeksToggle: 'No semesters', obModeWeeksToggleDesc: 'Organise by calendar week instead of semester.',
    obImportOr: 'or restore a backup',
    obDatesTitle: 'Your semester', obDatesDesc: 'When does it start and end?',
    obClassesTitle: 'Your classes', obClassesDesc: 'Add the classes you are taking.',
    obGroupsTitle: 'Your groups', obGroupsDesc: 'Add the groups you work with.',
    obInfoTasksTitle: 'Tasks & Kanban', obInfoTasksDesc: 'Add tasks per week or date, then drag them across your kanban board.',
    obInfoCalTitle: 'Calendar & Focus', obInfoCalDesc: 'See everything on the calendar and run focus sessions to get things done.',
    obInfoDoneTitle: 'You are all set', obInfoDoneDesc: 'You can change any of this later in settings.',
    shareLink: 'Copy share link', qrCode: 'QR Code', linkCopied: 'Link copied!',
    high: 'High', medium: 'Medium', low: 'Low', none: 'None',
    addSemester: 'Add semester', semesterName: 'Semester name', startDate: 'Start date', endDate: 'End date',
    weeks: n => `${n} weeks`, addAClass: 'Add class', className: 'Class name', ects: 'ECTS', colour: 'Colour',
    addComponent: 'Add component', componentName: 'Component name',
    taskSpanLabel: 'Task span behaviour', taskSpanDesc: 'When a task spans multiple weeks, how is it marked done?',
    kanbanChecklistInlineLabel: 'Kanban checklist preview',
    kanbanChecklistInlineDesc: 'Show checklist items directly on cards without opening details.',
    kanbanChecklistPreviewNone: 'Hide on cards',
    kanbanChecklistPreviewAll: 'Show on all cards',
    kanbanChecklistPreviewPerCard: 'Case by case',
    focusAlertModeLabel: 'Focus alert mode',
    focusAlertModeDesc: 'Choose how Focus alerts are delivered when the timer phase changes.',
    focusAlertNone: 'None',
    focusAlertVibration: 'Vibration',
    focusAlertNotification: 'Notification',
    focusAlertBoth: 'Both',
    taskAlertModeLabel: 'Task due-date alerts',
    taskAlertModeDesc: 'Choose how task due-date alerts are delivered.',
    taskAlertNone: 'None',
    taskAlertInApp: 'In-app',
    taskAlertNotification: 'Notification',
    taskAlertBoth: 'Both',
    taskAlertNextDayTimeLabel: 'Next-day alert time',
    taskAlertNextDayTimeDesc: 'Time for reminders about tasks due tomorrow.',
    taskDefaultToCalendarLabel: 'Tasks on calendar by default',
    taskDefaultToCalendarDesc: 'New tasks will have "Show on calendar" enabled by default.',
    taskDueTodayTitle: count => count === 1 ? 'Task due today' : `${count} tasks due today`,
    taskAlertHide: 'Hide alert',
    taskAlertRemindMeAt: 'Remind me at',
    settingEnabled: 'Enabled', settingDisabled: 'Disabled',
    spanSingle: 'One global checkbox (done once)', spanPerWeek: 'Per-week checkbox',
    dangerZone: 'Danger zone', deleteSemester: 'Delete this semester',
    clearPomodoros: 'Clear pomodoros',
    clearPomodorosTitle: 'Clear all pomodoros?',
    clearPomodorosDesc: 'All fallen pomodoros will be permanently deleted.',
    deleteSemesterTitle: 'Delete semester?', deleteSemesterDesc: 'All tasks, grades, and kanban data for this semester will be permanently deleted.',
    clearDoneTitle: 'Clear done column?', clearDoneDesc: 'All cards in the Done column will be deleted.',
    wipeAllTitle: 'Wipe all cards?', wipeAllDesc: 'Every card on the board will be permanently deleted.',
    selectSemester: 'Select semester', noClassesYet: 'No classes yet', addClassesInSettings: 'Add classes in Settings.',
    addUnlocks: 'Add a semester to unlock the rest.',
    checklist: 'Checklist', addItem: 'Add item', editCard: 'Edit card',
    notAchievable: '— not achievable', onRemaining: ' on remaining assessments',
    youNeed: 'You need', allGraded: 'All components graded.',
    noGradeComponents: 'No grade components configured. Go to Settings.',
    deleteClassTitle: 'Delete class?', deleteClassDesc: 'This will also delete all tasks for this class.',
    holidayName: 'Holiday name', holidayNamePlaceholder: 'e.g. Christmas Break',
    addHoliday: 'Add holiday',
    loadPreset: 'Load preset',
    presetLoading: 'Loading preset…', presetError: 'Failed to load preset.', retry: 'Retry', skip: 'Skip',
    newColumnName: 'New column name',
    focusStart: 'Start', focusPause: 'Pause', focusResume: 'Resume', focusReset: 'Reset', focusSkipBreak: 'Skip break',
    focusReady: 'ready', focusBreak: 'break',
    focusPhrases: ['keep going', 'stay with it', "you're doing great", 'one step at a time', 'deep work', 'stay present'],
    focusEvery: 'every (min)', focusBreakFor: 'break (min)',
    focusScheduledMode: 'Scheduled breaks',
    focusNextBreak: 'Next break at',
    focusFocusLabel: 'Focus message', focusBreakLabel: 'Break message',
    loadPresetTitle: 'Load a preset',
    presetGroupEI: 'EI Course',
    presetGroupGeneric: 'General',
    backToMenu: 'Back',
    importData: 'Import data',
    importFromFirebase: 'Import from Firebase',
    nextSemesterTitle: 'Semester ended',
    nextSemesterDesc: 'Your semester has ended. Load the next one?',
    loadNextSemester: 'Load next semester',
    dismissNextSemester: 'Dismiss',
    noSemesterYet: 'No semester configured',
    noSemesterDesc: 'Load a preset or import your data to get started.',
    focusIntervalMode: 'Interval breaks',
    focusIntervalEvery: 'every (min)',
    focusIntervalBreakFor: 'break (min)',
    focusScheduledBreakFor: 'break (min)',
    focusAfterBreakReset: 'After break: reset timer',
    focusAfterBreakContinue: 'After break: keep counting',
    firebaseSync: 'Firebase sync',
    firebaseConnect: 'Connect',
    firebaseConnected: 'Connected',
    firebaseDisconnect: 'Disconnect',
    firebaseSyncing: 'Syncing…',
    firebaseLastSync: 'Last sync',
    firebaseError: 'Sync error',
    firebaseRemoteNewer: 'Cloud data is from a newer app version. Sync paused. Update the app.',
    collabSyncFailed: 'Could not sync shared change. It was reverted.',
    newerVersionWarning: 'Your data was saved by a newer app version. Some things may not display correctly until you update.',
    firebaseSetupTitle: 'Connect Firebase',
    firebaseStep1Title: 'Create a Firebase project',
    firebaseStep1Desc: 'Go to console.firebase.google.com → Add project → give it any name → disable Google Analytics → Create project.',
    firebaseStep2Title: 'Enable Firestore',
    firebaseStep2Desc: 'Go to Build → Firestore Database → Create database → choose a region → Start in production mode → Create. Then go to Rules, replace the content with: allow read, write: if true; and click Publish.',
    firebaseStep3Title: 'Get your config',
    firebaseStep3Desc: 'Go to Project Settings (gear icon) → Your apps → Add app → Web → register the app → copy the firebaseConfig object shown.',
    firebaseStep4Title: 'Paste your config',
    firebaseStep4Desc: 'Paste the full firebaseConfig object (as JSON) below.',
    firebaseConfigPlaceholder: '{ "apiKey": "...", "authDomain": "...", "projectId": "...", ... }',
    firebaseConfigInvalid: 'Invalid config: must include apiKey and projectId.',
    firebaseTestFailed: 'Could not connect. Check your config and database rules.',
    firebaseSave: 'Save & connect',
    pomodoroMode: 'Pomodoro mode',
    pomodoroModeDesc: 'Grow tomatoes during focus sessions. Each completed session drops a tomato.',
    pomodoroResetPeriod: 'Reset period',
    pomodoroResetDay: 'Daily', pomodoroResetWeek: 'Weekly', pomodoroResetMonth: 'Monthly', pomodoroResetSemester: 'Per semester',
    pomodoroTrackPeriodStats: 'Track period stats',
    pomodoroShowAbandoned: 'Show abandoned tomatoes',
    pomodoroShowPeriodPomodoros: 'Show period pomodoros',
    pomodoroStatsTitle: 'Pomodoro stats',
    pomodoroTotal: 'Total tomatoes', pomodoroAbandoned: 'Abandoned', pomodoroFocusTime: 'Total focus time',
    pomodoroPeriodTotal: 'This period', pomodoroPeriodFocus: 'Focus this period',
    pomodoroVsSinceLast: 'vs last period',
    pomodoroAllTime: 'All time',
    pomodoroInsightsDailyTitle: 'Daily focus this week',
    pomodoroInsightsWeeklyBreakdownTitle: 'Weekly averages',
    pomodoroInsightsAvgWeekLabel: 'avg/day (week)',
    pomodoroInsightsAvgPeriodLabel: 'avg/day (period)',
    pomodoroInsightsPerDaySuffix: '/d',
    pomodoroInsightsNoWeeklyData: 'No weekly data yet.',
    pomodoroInsightsDayLabels: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
    pomodoroTotalTimeLabel: 'total time',
    pomodoroClose: 'Close',
    pomodoroEraseStats: 'Erase stats',
    pomodoroEraseStatsTitle: 'Erase pomodoro stats?',
    pomodoroEraseStatsDesc: 'Historical focus-time stats will be removed, but tomato entries stay available.',
    pomodoroGraceCancel: 'Cancel (no tomato)',
    pomodoroGrace: s => `${s}s to cancel without losing a tomato`,
    workModeLabel: 'Work mode',
    workModeDesc: 'Hides grades and renames classes to groups.',
    workModeOnboarding: 'Using this for work?',
    semesterModeLabel: 'No semester mode',
    semesterModeDesc: 'Turn on to use plain year weeks instead of semesters. Grades are hidden.',
    semesterModeNone: 'No semesters (year weeks)',
    semesterModeSemesters: 'Using semesters',
    semesterModeOnboarding: 'No semesters, just weeks?',
    groups: 'Groups', addAGroup: 'Add group', groupName: 'Group name',
    deleteGroupTitle: 'Delete group?', deleteGroupDesc: 'This will also delete all tasks for this group.',
    storageWarningTitle: 'Storage limit reached',
    storageWarningDesc: 'Please activate Firebase sync, reached max local storage.',
    storageWarningAction: 'Got it',
    collabConnect: 'Connect Organizer Collab',
    collabDisconnect: 'Disconnect Organizer Collab',
    collabRequiresFirebase: 'Connect Firebase sync first to use Organizer Collab.',
    collabGuideTitle: 'Organizer Collab setup',
    collabGuideIntro: 'One-time setup. Do these 4 steps in Firebase, then come back and enable collab.',
    collabGuideImportantTitle: 'What changes when collab is enabled',
    collabGuideImportant1: 'Your database starts requiring authenticated users (anonymous auth is enough).',
    collabGuideImportant2: 'Normal organizer sync keeps working, but it must authenticate first.',
    collabGuideImportant3: 'If collab is disabled later, auth-based rules can still be used safely.',
    collabGuideStep1: 'Open Firebase Console > Build > Firestore Database > Rules.',
    collabGuideStep2: 'Paste the rules snippet below and click Publish.',
    collabGuideStep3: 'Open Security > Authentication > Sign-in method > enable Anonymous > Save.',
    collabGuideStep4: 'Return to Organizer and press "I configured rules, enable collab".',
    collabGuideRulesLabel: 'Firestore rules',
    collabGuideTroubleshootTitle: 'If you see signUp 400 error',
    collabGuideTroubleshootBody: 'That means Anonymous authentication is still disabled in Firebase. Enable it in Security > Authentication > Sign-in method.',
    collabEnableNow: 'I configured rules, enable collab',
    collabPanelTitle: 'Organizer Collab',
    collabPanelSubtitle: 'Create teams, invite people, and share tasks/kanban cards.',
    collabCreateTeam: 'Create team',
    collabTeamName: 'Team name',
    collabTeamDays: 'team days',
    collabTeamDuration: 'team duration',
    collabDays: 'days',
    collabJoinTeam: 'Join team',
    collabInvitePlaceholder: 'Paste invite link',
    collabInviteTtl: 'Invite validity',
    collabYourTeams: 'Your teams',
    collabNoTeams: 'No teams yet.',
    collabRoleHost: 'host',
    collabRoleMember: 'member',
    collabEndsAt: 'ends',
    collabInvite: 'Invite',
    collabEditTeam: 'Edit team',
    collabTaskCompletionMode: 'Shared task completion',
    collabTaskCompletionPersonal: 'personal completion',
    collabTaskCompletionForAll: 'toggle for everyone',
    collabTaskPermissions: 'Task edit permissions',
    collabTaskPermissionsEveryone: 'anyone can add/edit/remove tasks',
    collabTaskPermissionsHostOnly: 'only host can add/edit/remove tasks',
    collabLeave: 'Leave',
    collabDeleteTeam: 'Delete',
    collabDefaultTeamName: 'Team',
    collabLeavePrompt: 'Leave this team?',
    collabLeaveWithLocalPrompt: 'You shared local tasks in this team. Keep them locally?',
    collabDeleteTeamPrompt: 'Delete this team?',
    collabDeleteTeamWithLocalPrompt: 'You shared local tasks in this team. Keep them locally before deleting the team?',
    collabKeepLocalTasks: 'Keep local tasks',
    collabDeleteLocalTasksToo: 'Delete local tasks',
    collabErrorCreate: 'Could not create team.',
    collabErrorInvite: 'Could not generate invite.',
    collabErrorJoin: 'Could not join team.',
    collabErrorInvalidLink: 'Invalid invite link.',
    collabErrorDeleteTeam: 'Could not delete team.',
}
