export const es = {
    tasks: 'Tareas', kanban: 'Kanban', grades: 'Calificaciones', calendar: 'Calendario', focus: 'Enfoque', settings: 'Ajustes',
    noSemester: 'Ningún semestre configurado', goToSettings: 'Ve a Ajustes para empezar.',
    weekLabel: w => `Semana ${w}`, done: 'completadas', timeToRelax: '¡Hora de relajarse!',
    addTask: 'Nueva tarea', task: 'Tarea', class: 'Asignatura', priority: 'Prioridad',
    editTask: 'Editar tarea', moveLeft: 'Mover a la izquierda', moveRight: 'Mover a la derecha', markDone: 'Marcar como hecha',
    addToKanban: 'Añadir al Kanban', themeLight: 'Tema claro', themeDark: 'Tema oscuro', themeSystem: 'Tema del sistema',
    addPartTitle: 'Añadir parte',
    fromWeek: 'Desde la semana', toWeek: 'Hasta la semana', dueDate: 'Fecha límite',
    other: 'Otro', noTasks: 'Sin tareas esta semana.',
    whatNeedsDone: '¿Qué hay que hacer?',
    addTaskBtn: 'Añadir tarea', showOnCalendar: 'Mostrar en el calendario', showOnTasks: 'Mostrar en las tareas',
    clearDone: 'Borrar completadas', wipeAll: 'Borrar todo',
    addCard: 'Añadir tarjeta', addCardPlaceholder: 'Título de la tarjeta',
    save: 'Guardar', cancel: 'Cancelar', confirm: 'Confirmar', delete: 'Eliminar',
    addEvent: 'Añadir evento', newEvent: 'Nuevo evento', editEvent: 'Editar evento',
    eventTitle: 'Título del evento', eventDate: 'Fecha', eventRange: 'Rango de fechas',
    eventMultiDay: 'Varios días', eventColor: 'Color', eventNote: 'Nota',
    eventNotePlaceholder: 'Nota opcional', more: 'más',
    navbar: 'Barra de navegación', navHide: 'Ocultar', navOverflow: 'Mover al menú más', navAddButton: 'Mostrar botón de añadir',
    navMore: 'Más', navLabelMode: 'Mostrar', navLabelBoth: 'Iconos + nombres', navLabelIcons: 'Solo iconos', navLabelNames: 'Solo nombres',
    add: 'Añadir', navAddLabel: 'Añadir', navDrag: 'Arrastra para reordenar',
    appDisableTitle: '¿Desactivar y borrar datos?', appDisableDesc: 'Desactivar esta app elimina permanentemente todos sus datos.',
    collabDisableDesc: 'Desconectar abandona todos los equipos y elimina permanentemente los datos de colaboración de este dispositivo.',
    navAddAction: 'Acción del botón de añadir', navAddPicker: 'Preguntar cada vez',
    navFolders: 'Carpetas', navNewFolder: 'Nueva carpeta',
    navMobilePosition: 'Posición de la barra móvil', navPosBottom: 'Barra inferior', navPosSide: 'Barra lateral',
    addToTasks: 'Añadir a tareas', inTasks: 'En tareas',
    standby: 'Reposo', standbyEnable: 'Activar reposo horizontal',
    standbyDesc: 'Pon tu teléfono en horizontal para mostrar un panel ambiental.',
    standbyLeft: 'Panel izquierdo', standbyCenter: 'Panel central', standbyRight: 'Panel derecho',
    standbyPanels: 'Paneles', standbyPane: n => `Panel ${n}`,
    standbyPaneSecond: 'Segunda tarjeta (deslizar)', standbyPaneNone: 'Ninguna',
    paneWheel: 'Rueda de progreso', paneWheelTime: 'Rueda + reloj', paneCalendar: 'Calendario',
    paneFocus: 'Enfoque', paneKanban: 'Kanban', paneTasksByCategory: 'Tareas por categoría',
    notesLastEdit: 'Editado', notesFolder: 'Carpeta', notesNoFolder: 'Sin carpeta', notesNewFolder: 'Nueva carpeta',
    notesFolderName: 'Nombre de la carpeta', notesRenameFolder: 'Renombrar carpeta', notesDeleteFolder: 'Eliminar carpeta', notesMoveTo: 'Mover a',
    notesEdit: 'Editar', notesPreview: 'Vista previa', notesBack: 'Atrás',
    apps: 'Apps', appsSearch: 'Buscar apps', appsNoResults: 'No se encontraron apps.', notes: 'Notas',
    notesEnable: 'Activar Notas', notesEnableDesc: 'Añade una pestaña de Notas para notas rápidas.',
    notesNew: 'Nueva nota', notesTitle: 'Título', notesBody: 'Escribe algo…', notesSearch: 'Buscar notas',
    notesEmpty: 'Aún no hay notas.', notesFavorite: 'Favorita', notesText: 'Texto', notesCanvas: 'Escritura a mano',
    notesCanvasWarning: 'Las notas con dibujos pueden usar mucho espacio, por lo que solo están disponibles con Firebase activo.',
    collabApp: 'Colaboración',
    eiCalendar: 'Calendario EI', eiCalendarEnable: 'Mostrar calendario EI',
    eiCalendarEnableDesc: 'Añade el calendario oficial del grado EI de tu año al calendario, de solo lectura y siempre actualizado.',
    eiCalendarDisableTitle: '¿Ocultar calendario EI?', eiCalendarDisableDesc: 'Deja de mostrar los eventos del calendario EI. No se elimina nada y puedes reactivarlo cuando quieras.',
    semester: 'Semestre', classes: 'Asignaturas', gradeComponents: 'Componentes de nota',
    kanbanColumns: 'Columnas Kanban', general: 'General', data: 'Datos y sync',
    holidays: 'Vacaciones',
    exportJson: 'Exportar JSON', importJson: 'Importar JSON',
    semesterAvg: 'Media del semestre', ectsPassedLabel: 'ECTS aprobados',
    targetGrade: 'Nota objetivo',
    previousSemesters: 'Semestres anteriores',
    courseAvg: 'Media del curso', finalGrade: 'Nota final', previousAvg: 'Media anterior', numSemesters: 'Nº de semestres',
    getStarted: 'Empezar', welcomeTitle: 'Bienvenido a organizer',
    welcomeDesc: 'Tu espacio para el trabajo universitario. Configura tu semestre y organízate.',
    step1: 'Define las fechas del semestre', step2: 'Añade tus asignaturas', step3: 'Planifica tareas y sigue las notas',
    obNext: 'Siguiente', obBack: 'Atrás', obFinish: 'Finalizar', obSkip: 'Omitir',
    obWelcomeTitle: 'Bienvenido a Organizer', obWelcomeDesc: 'Tu espacio tranquilo para el trabajo universitario. Elige tu idioma y tema para empezar.',
    obModeTitle: '¿Cómo lo usarás?', obModeDesc: 'Activa lo que te convenga. Ambos pueden estar activos.',
    obModeWorkToggle: 'Modo trabajo', obModeWorkToggleDesc: 'Grupos en vez de asignaturas, sin notas.',
    obModeWeeksToggle: 'Sin semestres', obModeWeeksToggleDesc: 'Organizar por semana natural en vez de semestre.',
    obImportOr: 'o restaurar una copia de seguridad',
    obDatesTitle: 'Tu semestre', obDatesDesc: '¿Cuándo empieza y termina?',
    obClassesTitle: 'Tus asignaturas', obClassesDesc: 'Añade las asignaturas que cursas.',
    obGroupsTitle: 'Tus grupos', obGroupsDesc: 'Añade los grupos con los que trabajas.',
    obInfoTasksTitle: 'Tareas y Kanban', obInfoTasksDesc: 'Añade tareas por semana o fecha y arrástralas por tu tablero kanban.',
    obInfoCalTitle: 'Calendario y Enfoque', obInfoCalDesc: 'Ve todo en el calendario y ejecuta sesiones de enfoque para avanzar.',
    obInfoDoneTitle: 'Todo listo', obInfoDoneDesc: 'Puedes cambiar todo esto más tarde en los ajustes.',
    shareLink: 'Copiar enlace para compartir', qrCode: 'Código QR', linkCopied: '¡Enlace copiado!',
    high: 'Alta', medium: 'Media', low: 'Baja', none: 'Ninguna',
    addSemester: 'Añadir semestre', semesterName: 'Nombre del semestre', startDate: 'Fecha de inicio', endDate: 'Fecha de fin',
    weeks: n => `${n} semanas`, addAClass: 'Añadir asignatura', className: 'Nombre de la asignatura', ects: 'ECTS', colour: 'Color',
    addComponent: 'Añadir componente', componentName: 'Nombre del componente',
    taskSpanLabel: 'Comportamiento de tareas de varias semanas', taskSpanDesc: 'Cuando una tarea abarca varias semanas, ¿cómo se marca como hecha?',
    kanbanChecklistInlineLabel: 'Vista previa de checklist Kanban',
    kanbanChecklistInlineDesc: 'Muestra los elementos de la checklist directamente en las tarjetas sin abrir los detalles.',
    kanbanChecklistPreviewNone: 'Ocultar en las tarjetas',
    kanbanChecklistPreviewAll: 'Mostrar en todas las tarjetas',
    kanbanChecklistPreviewPerCard: 'Caso por caso',
    focusAlertModeLabel: 'Modo de alerta de Enfoque',
    focusAlertModeDesc: 'Elige cómo se entregan las alertas de Enfoque al cambiar de fase el temporizador.',
    focusAlertNone: 'Ninguna',
    focusAlertVibration: 'Vibración',
    focusAlertNotification: 'Notificación',
    focusAlertBoth: 'Ambas',
    taskAlertModeLabel: 'Alertas de fecha límite',
    taskAlertModeDesc: 'Elige cómo se entregan las alertas de fecha límite.',
    taskAlertNone: 'Ninguna',
    taskAlertInApp: 'En la app',
    taskAlertNotification: 'Notificación',
    taskAlertBoth: 'Ambas',
    taskAlertNextDayTimeLabel: 'Hora de alerta del día siguiente',
    taskAlertNextDayTimeDesc: 'Hora de los recordatorios de tareas que vencen mañana.',
    taskDefaultToCalendarLabel: 'Tareas en el calendario por defecto',
    taskDefaultToCalendarDesc: 'Las nuevas tareas tendrán «Mostrar en el calendario» activado por defecto.',
    taskDueTodayTitle: count => count === 1 ? 'Tarea para hoy' : `${count} tareas para hoy`,
    taskAlertHide: 'Ocultar alerta',
    taskAlertRemindMeAt: 'Recordarme a las',
    settingEnabled: 'Activado', settingDisabled: 'Desactivado',
    spanSingle: 'Una casilla global (hecha una vez)', spanPerWeek: 'Casilla por semana',
    dangerZone: 'Zona de peligro', deleteSemester: 'Eliminar este semestre',
    clearPomodoros: 'Borrar pomodoros',
    clearPomodorosTitle: '¿Borrar todos los pomodoros?',
    clearPomodorosDesc: 'Todos los pomodoros caídos se eliminarán permanentemente.',
    deleteSemesterTitle: '¿Eliminar semestre?', deleteSemesterDesc: 'Todas las tareas, notas y datos kanban de este semestre se eliminarán permanentemente.',
    clearDoneTitle: '¿Borrar la columna Hecho?', clearDoneDesc: 'Todas las tarjetas de la columna Hecho se eliminarán.',
    wipeAllTitle: '¿Borrar todas las tarjetas?', wipeAllDesc: 'Cada tarjeta del tablero se eliminará permanentemente.',
    selectSemester: 'Seleccionar semestre', noClassesYet: 'Aún no hay asignaturas', addClassesInSettings: 'Añade asignaturas en Ajustes.',
    addUnlocks: 'Añade un semestre para desbloquear el resto.',
    checklist: 'Checklist', addItem: 'Añadir elemento', editCard: 'Editar tarjeta',
    notAchievable: '— no alcanzable', onRemaining: ' en las evaluaciones restantes',
    youNeed: 'Necesitas', allGraded: 'Todos los componentes calificados.',
    noGradeComponents: 'No hay componentes de nota configurados. Ve a Ajustes.',
    deleteClassTitle: '¿Eliminar asignatura?', deleteClassDesc: 'Esto también eliminará todas las tareas de esta asignatura.',
    holidayName: 'Nombre de las vacaciones', holidayNamePlaceholder: 'ej: Vacaciones de Navidad',
    addHoliday: 'Añadir vacaciones',
    loadPreset: 'Cargar preajuste',
    presetLoading: 'Cargando preajuste…', presetError: 'Error al cargar el preajuste.', retry: 'Reintentar', skip: 'Omitir',
    newColumnName: 'Nombre de la nueva columna',
    focusStart: 'Iniciar', focusPause: 'Pausar', focusResume: 'Reanudar', focusReset: 'Reiniciar', focusSkipBreak: 'Saltar descanso',
    focusReady: 'listo', focusBreak: 'descanso',
    focusPhrases: ['sigue así', 'mantente en ello', 'lo estás haciendo genial', 'paso a paso', 'trabajo profundo', 'mantente presente'],
    focusEvery: 'cada (min)', focusBreakFor: 'descanso (min)',
    focusScheduledMode: 'Descansos programados',
    focusNextBreak: 'Próximo descanso a las',
    focusFocusLabel: 'Mensaje de enfoque', focusBreakLabel: 'Mensaje de descanso',
    loadPresetTitle: 'Cargar un preajuste',
    presetGroupEI: 'Grado EI',
    presetGroupGeneric: 'General',
    backToMenu: 'Atrás',
    importData: 'Importar datos',
    importFromFirebase: 'Importar desde Firebase',
    nextSemesterTitle: 'Semestre terminado',
    nextSemesterDesc: 'Tu semestre ha terminado. ¿Cargar el siguiente?',
    loadNextSemester: 'Cargar el próximo semestre',
    dismissNextSemester: 'Descartar',
    noSemesterYet: 'Ningún semestre configurado',
    noSemesterDesc: 'Carga un preajuste o importa tus datos para empezar.',
    focusIntervalMode: 'Descansos por intervalo',
    focusIntervalEvery: 'cada (min)',
    focusIntervalBreakFor: 'descanso (min)',
    focusScheduledBreakFor: 'descanso (min)',
    focusAfterBreakReset: 'Tras el descanso: reiniciar temporizador',
    focusAfterBreakContinue: 'Tras el descanso: seguir contando',
    firebaseSync: 'Sync de Firebase',
    firebaseConnect: 'Conectar',
    firebaseConnected: 'Conectado',
    firebaseDisconnect: 'Desconectar',
    firebaseSyncing: 'Sincronizando…',
    firebaseLastSync: 'Última sync',
    firebaseError: 'Error de sync',
    firebaseRemoteNewer: 'Los datos de la nube son de una versión más reciente. Sync en pausa. Actualiza la app.',
    collabSyncFailed: 'No se pudo sincronizar el cambio compartido. Se revirtió.',
    newerVersionWarning: 'Tus datos se guardaron con una versión más reciente. Algunas cosas pueden no mostrarse bien hasta que actualices.',
    firebaseSetupTitle: 'Conectar Firebase',
    firebaseStep1Title: 'Crear un proyecto de Firebase',
    firebaseStep1Desc: 'Ve a console.firebase.google.com → Añadir proyecto → dale un nombre → desactiva Google Analytics → Crear proyecto.',
    firebaseStep2Title: 'Activar Firestore',
    firebaseStep2Desc: 'Ve a Build → Firestore Database → Crear base de datos → elige una región → Iniciar en modo producción → Crear. Luego en Reglas, reemplaza el contenido por: allow read, write: if true; y pulsa Publicar.',
    firebaseStep3Title: 'Obtener tu configuración',
    firebaseStep3Desc: 'Ve a Configuración del proyecto (icono de engranaje) → Tus apps → Añadir app → Web → registra la app → copia el objeto firebaseConfig mostrado.',
    firebaseStep4Title: 'Pegar tu configuración',
    firebaseStep4Desc: 'Pega el objeto firebaseConfig completo (como JSON) abajo.',
    firebaseConfigPlaceholder: '{ "apiKey": "...", "authDomain": "...", "projectId": "...", ... }',
    firebaseConfigInvalid: 'Config inválida: debe incluir apiKey y projectId.',
    firebaseTestFailed: 'No se pudo conectar. Revisa tu config y las reglas de la base de datos.',
    firebaseSave: 'Guardar y conectar',
    pomodoroMode: 'Modo Pomodoro',
    pomodoroModeDesc: 'Cultiva tomates durante las sesiones de enfoque. Cada sesión completada suelta un tomate.',
    pomodoroResetPeriod: 'Periodo de reinicio',
    pomodoroResetDay: 'Diario', pomodoroResetWeek: 'Semanal', pomodoroResetMonth: 'Mensual', pomodoroResetSemester: 'Por semestre',
    pomodoroTrackPeriodStats: 'Seguir estadísticas del periodo',
    pomodoroShowAbandoned: 'Mostrar tomates abandonados',
    pomodoroShowPeriodPomodoros: 'Mostrar pomodoros del periodo',
    pomodoroStatsTitle: 'Estadísticas Pomodoro',
    pomodoroTotal: 'Total de tomates', pomodoroAbandoned: 'Abandonados', pomodoroFocusTime: 'Tiempo total de enfoque',
    pomodoroPeriodTotal: 'Este periodo', pomodoroPeriodFocus: 'Enfoque este periodo',
    pomodoroVsSinceLast: 'vs periodo anterior',
    pomodoroAllTime: 'Histórico',
    pomodoroInsightsDailyTitle: 'Enfoque diario esta semana',
    pomodoroInsightsWeeklyBreakdownTitle: 'Medias semanales',
    pomodoroInsightsAvgWeekLabel: 'media/día (semana)',
    pomodoroInsightsAvgPeriodLabel: 'media/día (periodo)',
    pomodoroInsightsPerDaySuffix: '/d',
    pomodoroInsightsNoWeeklyData: 'Aún no hay datos semanales.',
    pomodoroInsightsDayLabels: ['D', 'L', 'M', 'X', 'J', 'V', 'S'],
    pomodoroTotalTimeLabel: 'tiempo total',
    pomodoroClose: 'Cerrar',
    pomodoroEraseStats: 'Borrar estadísticas',
    pomodoroEraseStatsTitle: '¿Borrar estadísticas Pomodoro?',
    pomodoroEraseStatsDesc: 'Se eliminarán las estadísticas históricas de tiempo de enfoque, pero las entradas de tomate seguirán disponibles.',
    pomodoroGraceCancel: 'Cancelar (sin tomate)',
    pomodoroGrace: s => `${s}s para cancelar sin perder un tomate`,
    workModeLabel: 'Modo trabajo',
    workModeDesc: 'Oculta las notas y renombra las asignaturas como grupos.',
    workModeOnboarding: '¿Usas esto para el trabajo?',
    semesterModeLabel: 'Modo sin semestre',
    semesterModeDesc: 'Activa para usar simples semanas del año en vez de semestres. Las notas se ocultan.',
    semesterModeNone: 'Sin semestres (semanas del año)',
    semesterModeSemesters: 'Con semestres',
    semesterModeOnboarding: '¿Sin semestres, solo semanas?',
    groups: 'Grupos', addAGroup: 'Añadir grupo', groupName: 'Nombre del grupo',
    deleteGroupTitle: '¿Eliminar grupo?', deleteGroupDesc: 'Esto también eliminará todas las tareas de este grupo.',
    storageWarningTitle: 'Límite de almacenamiento alcanzado',
    storageWarningDesc: 'Activa la sync de Firebase, se alcanzó el máximo de almacenamiento local.',
    storageWarningAction: 'Entendido',
    collabConnect: 'Conectar Organizer Collab',
    collabDisconnect: 'Desconectar Organizer Collab',
    collabRequiresFirebase: 'Conecta primero la sync de Firebase para usar Organizer Collab.',
    collabGuideTitle: 'Configuración de Organizer Collab',
    collabGuideIntro: 'Configuración única. Haz estos 4 pasos en Firebase y luego vuelve para activar collab.',
    collabGuideImportantTitle: 'Qué cambia cuando collab está activado',
    collabGuideImportant1: 'Tu base de datos empieza a requerir usuarios autenticados (basta con auth anónima).',
    collabGuideImportant2: 'La sync normal sigue funcionando, pero debe autenticarse primero.',
    collabGuideImportant3: 'Si collab se desactiva luego, las reglas basadas en auth siguen siendo seguras de usar.',
    collabGuideStep1: 'Abre Firebase Console > Build > Firestore Database > Reglas.',
    collabGuideStep2: 'Pega el fragmento de reglas de abajo y pulsa Publicar.',
    collabGuideStep3: 'Abre Security > Authentication > Método de acceso > activa Anónimo > Guardar.',
    collabGuideStep4: 'Vuelve a Organizer y pulsa «Configuré las reglas, activar collab».',
    collabGuideRulesLabel: 'Reglas de Firestore',
    collabGuideTroubleshootTitle: 'Si ves un error signUp 400',
    collabGuideTroubleshootBody: 'Significa que la autenticación anónima sigue desactivada en Firebase. Actívala en Security > Authentication > Método de acceso.',
    collabEnableNow: 'Configuré las reglas, activar collab',
    collabPanelTitle: 'Organizer Collab',
    collabPanelSubtitle: 'Crea equipos, invita a personas y comparte tareas/tarjetas kanban.',
    collabCreateTeam: 'Crear equipo',
    collabTeamName: 'Nombre del equipo',
    collabTeamDays: 'días del equipo',
    collabTeamDuration: 'duración del equipo',
    collabDays: 'días',
    collabJoinTeam: 'Unirse a un equipo',
    collabInvitePlaceholder: 'Pega el enlace de invitación',
    collabInviteTtl: 'Validez de la invitación',
    collabYourTeams: 'Tus equipos',
    collabNoTeams: 'Aún no hay equipos.',
    collabRoleHost: 'anfitrión',
    collabRoleMember: 'miembro',
    collabEndsAt: 'termina',
    collabInvite: 'Invitar',
    collabEditTeam: 'Editar equipo',
    collabTaskCompletionMode: 'Finalización de tareas compartidas',
    collabTaskCompletionPersonal: 'finalización personal',
    collabTaskCompletionForAll: 'alternar para todos',
    collabTaskPermissions: 'Permisos de edición de tareas',
    collabTaskPermissionsEveryone: 'cualquiera puede añadir/editar/eliminar tareas',
    collabTaskPermissionsHostOnly: 'solo el anfitrión puede añadir/editar/eliminar tareas',
    collabLeave: 'Salir',
    collabDeleteTeam: 'Eliminar',
    collabDefaultTeamName: 'Equipo',
    collabLeavePrompt: '¿Salir de este equipo?',
    collabLeaveWithLocalPrompt: 'Compartiste tareas locales en este equipo. ¿Conservarlas localmente?',
    collabDeleteTeamPrompt: '¿Eliminar este equipo?',
    collabDeleteTeamWithLocalPrompt: 'Compartiste tareas locales en este equipo. ¿Conservarlas localmente antes de eliminar el equipo?',
    collabKeepLocalTasks: 'Conservar tareas locales',
    collabDeleteLocalTasksToo: 'Eliminar tareas locales',
    collabErrorCreate: 'No se pudo crear el equipo.',
    collabErrorInvite: 'No se pudo generar la invitación.',
    collabErrorJoin: 'No se pudo unir al equipo.',
    collabErrorInvalidLink: 'Enlace de invitación inválido.',
    collabErrorDeleteTeam: 'No se pudo eliminar el equipo.',
    collabGuideChecklistTitle: '¿Sigue sin sincronizar?',
    collabGuideChecklistBody: 'Los dos pasos que Organizer no puede hacer por ti: activar la autenticación anónima y publicar las reglas de Firestore de arriba. Si las tareas compartidas nunca aparecen, falta uno de estos en el proyecto del anfitrión.',
    collabSyncErrorHint: 'No se puede acceder a este equipo. Verifica que el Firebase del anfitrión tenga la autenticación anónima activada y reglas abiertas.',
    collabErrorPermission: 'Bloqueado por las reglas de Firebase. El anfitrión debe activar la autenticación anónima y abrir las reglas de Firestore.',
    collabErrorNotFound: 'Equipo no encontrado. Puede que se haya eliminado.',
    collabErrorInviteExpired: 'Esta invitación ha caducado. Pide un nuevo enlace al anfitrión.',
    collabErrorInviteInvalid: 'Este enlace de invitación no es válido para ese equipo.',
}
