export const es = {
    months: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
    weekdaysShort: ['Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb', 'Dom'],
    weekdays: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo'],
    tasks: 'Tareas', kanban: 'Kanban', grades: 'Calificaciones', calendar: 'Calendario', focus: 'Enfoque', settings: 'Ajustes',
    guides: 'Guías',
    noSemester: 'Ningún semestre configurado', goToSettings: 'Ve a Ajustes para empezar.',
    weekLabel: w => `Semana ${w}`, done: 'completadas', timeToRelax: '¡Hora de relajarse!',
    addTask: 'Nueva tarea', task: 'Tarea', class: 'Asignatura', priority: 'Prioridad',
    editTask: 'Editar tarea', moveLeft: 'Mover a la izquierda', moveRight: 'Mover a la derecha', markDone: 'Marcar como hecha',
    addToKanban: 'Añadir al Kanban', themeLight: 'Tema claro', themeDark: 'Tema oscuro', themeSystem: 'Tema del sistema',
    addPartTitle: 'Añadir parte',
    fromWeek: 'Desde la semana', toWeek: 'Hasta la semana', dueDate: 'Fecha límite',
    other: 'Otro', noTasks: 'Sin tareas esta semana.',
    whatNeedsDone: '¿Qué hay que hacer?',
    addTaskBtn: 'Añadir tarea', showOnCalendar: 'Mostrar en el calendario', showOnTasks: 'Mostrar en las tareas',
    clearDone: 'Borrar completadas', wipeAll: 'Borrar todo',
    addCard: 'Añadir tarjeta', addCardPlaceholder: 'Título de la tarjeta',
    save: 'Guardar', cancel: 'Cancelar', confirm: 'Confirmar', delete: 'Eliminar',
    addEvent: 'Añadir evento', newEvent: 'Nuevo evento', editEvent: 'Editar evento',
    eventTitle: 'Título del evento', eventDate: 'Fecha', eventRange: 'Rango de fechas',
    eventMultiDay: 'Varios días', eventColor: 'Color', eventNote: 'Nota',
    eventNotePlaceholder: 'Nota opcional', more: 'más',
    navbar: 'Barra de navegación', navHide: 'Ocultar', navOverflow: 'Mover al menú más', navAddButton: 'Mostrar botón de añadir',
    navMore: 'Más', navLabelMode: 'Mostrar', navLabelBoth: 'Iconos + nombres', navLabelIcons: 'Solo iconos', navLabelNames: 'Solo nombres',
    add: 'Añadir', navAddLabel: 'Añadir', navDrag: 'Arrastra para reordenar',
    appDisableTitle: '¿Desactivar y borrar datos?', appDisableDesc: 'Desactivar esta app elimina permanentemente todos sus datos.',
    collabDisableDesc: 'Desconectar abandona todos los equipos y elimina permanentemente los datos de colaboración de este dispositivo.',
    navAddAction: 'Acción del botón de añadir', navAddPicker: 'Preguntar cada vez',
    navFolders: 'Carpetas', navNewFolder: 'Nueva carpeta',
    navMobilePosition: 'Posición de la barra móvil', navPosBottom: 'Barra inferior', navPosSide: 'Barra lateral',
    addToTasks: 'Añadir a tareas', inTasks: 'En tareas',
    standby: 'Reposo', standbyEnable: 'Activar reposo horizontal',
    standbyDesc: 'Pon tu teléfono en horizontal para mostrar un panel ambiental.',
    standbyLeft: 'Panel izquierdo', standbyCenter: 'Panel central', standbyRight: 'Panel derecho',
    standbyPanels: 'Paneles', standbyPane: n => `Panel ${n}`,
    standbyPaneSecond: 'Segunda tarjeta (deslizar)', standbyPaneNone: 'Ninguna',
    paneWheel: 'Rueda de progreso', paneWheelTime: 'Rueda + reloj', paneCalendar: 'Calendario',
    paneFocus: 'Enfoque', paneKanban: 'Kanban', paneTasksByCategory: 'Tareas por categoría',
    notesLastEdit: 'Editado', notesFolder: 'Carpeta', notesNoFolder: 'Sin carpeta', notesNewFolder: 'Nueva carpeta',
    notesFolderName: 'Nombre de la carpeta', notesRenameFolder: 'Renombrar carpeta', notesDeleteFolder: 'Eliminar carpeta', notesMoveTo: 'Mover a',
    notesEdit: 'Editar', notesPreview: 'Vista previa', notesBack: 'Atrás',
    chunkLoadError: 'No se pudo cargar esta parte.', chunkRetry: 'Reintentar',
    apps: 'Apps', appsSearch: 'Buscar apps', appsNoResults: 'No se encontraron apps.', notes: 'Notas',
    notesEnable: 'Activar Notas', notesEnableDesc: 'Añade una pestaña de Notas para notas rápidas.',
    notesNew: 'Nueva nota', notesTitle: 'Título', notesBody: 'Escribe algo…', notesSearch: 'Buscar notas',
    notesEmpty: 'Aún no hay notas.', notesFavorite: 'Favorita', notesText: 'Texto', notesCanvas: 'Escritura a mano',
    collabApp: 'Colaboración',
    eiCalendar: 'Calendario EI', eiCalendarEnable: 'Mostrar calendario EI',
    eiCalendarEnableDesc: 'Añade el calendario oficial del grado EI de tu año al calendario, de solo lectura y siempre actualizado.',
    eiCalendarDisableTitle: '¿Ocultar calendario EI?', eiCalendarDisableDesc: 'Deja de mostrar los eventos del calendario EI. No se elimina nada y puedes reactivarlo cuando quieras.',
    semester: 'Semestre', classes: 'Asignaturas', gradeComponents: 'Componentes de nota',
    kanbanColumns: 'Columnas Kanban', general: 'General', data: 'Datos y sync',
    holidays: 'Vacaciones',
    exportJson: 'Exportar JSON', importJson: 'Importar JSON',
    semesterAvg: 'Media del semestre', ectsPassedLabel: 'ECTS aprobados',
    targetGrade: 'Nota objetivo',
    previousSemesters: 'Semestres anteriores',
    courseAvg: 'Media del curso', finalGrade: 'Nota final', previousAvg: 'Media anterior', numSemesters: 'Nº de semestres',
    getStarted: 'Empezar', welcomeTitle: 'Bienvenido a organizer',
    welcomeDesc: 'Tu espacio para el trabajo universitario. Configura tu semestre y organízate.',
    step1: 'Define las fechas del semestre', step2: 'Añade tus asignaturas', step3: 'Planifica tareas y sigue las notas',
    obNext: 'Siguiente', obBack: 'Atrás', obFinish: 'Finalizar', obSkip: 'Omitir',
    obWelcomeTitle: 'Bienvenido a Organizer', obWelcomeDesc: 'Tu espacio tranquilo para el trabajo universitario. Elige tu idioma y tema para empezar.',
    obModeTitle: '¿Cómo lo usarás?', obModeDesc: 'Activa lo que te convenga. Ambos pueden estar activos.',
    obModeWorkToggle: 'Modo trabajo', obModeWorkToggleDesc: 'Grupos en vez de asignaturas, sin notas.',
    obModeWeeksToggle: 'Sin semestres', obModeWeeksToggleDesc: 'Organizar por semana natural en vez de semestre.',
    obImportOr: 'o restaurar una copia de seguridad',
    obDatesTitle: 'Tu semestre', obDatesDesc: '¿Cuándo empieza y termina?',
    obClassesTitle: 'Tus asignaturas', obClassesDesc: 'Añade las asignaturas que cursas.',
    obGroupsTitle: 'Tus grupos', obGroupsDesc: 'Añade los grupos con los que trabajas.',
    obInfoTasksTitle: 'Tareas y Kanban', obInfoTasksDesc: 'Añade tareas por semana o fecha y arrástralas por tu tablero kanban.',
    obInfoCalTitle: 'Calendario y Enfoque', obInfoCalDesc: 'Ve todo en el calendario y ejecuta sesiones de enfoque para avanzar.',
    obInfoDoneTitle: 'Todo listo', obInfoDoneDesc: 'Puedes cambiar todo esto más tarde en los ajustes.',
    shareLink: 'Copiar enlace para compartir', qrCode: 'Código QR', linkCopied: '¡Enlace copiado!',
    high: 'Alta', medium: 'Media', low: 'Baja', none: 'Ninguna',
    addSemester: 'Añadir semestre', semesterName: 'Nombre del semestre', startDate: 'Fecha de inicio', endDate: 'Fecha de fin',
    weeks: n => `${n} semanas`, addAClass: 'Añadir asignatura', className: 'Nombre de la asignatura', ects: 'ECTS', colour: 'Color',
    addComponent: 'Añadir componente', componentName: 'Nombre del componente',
    taskSpanLabel: 'Comportamiento de tareas de varias semanas', taskSpanDesc: 'Cuando una tarea abarca varias semanas, ¿cómo se marca como hecha?',
    kanbanChecklistInlineLabel: 'Vista previa de checklist Kanban',
    kanbanChecklistInlineDesc: 'Muestra los elementos de la checklist directamente en las tarjetas sin abrir los detalles.',
    kanbanChecklistPreviewNone: 'Ocultar en las tarjetas',
    kanbanChecklistPreviewAll: 'Mostrar en todas las tarjetas',
    kanbanChecklistPreviewPerCard: 'Caso por caso',
    kanbanAutoAddLabel: 'Añadir tareas al tablero automáticamente',
    kanbanAutoAddDesc: 'Añade automáticamente las tareas de esta semana a la primera columna del tablero Kanban.',
    widgetsLabel: 'Widgets en la pantalla de inicio',
    widgetsDesc: 'Muestra tareas, la agenda de hoy y recuentos del Kanban en la pantalla de inicio.',
    widgetsEncryptionWarning: 'Los widgets no pueden leer datos cifrados. Si los activas, el contenido que muestran se guarda sin cifrar en este dispositivo. Se borra al bloquear la app.',
    gradeScaleLabel: 'Escala de calificación',
    gradeScaleDesc: 'Nota máxima posible. Los campos de nota se limitan a este valor.',
    passingGradeLabel: 'Nota de aprobado',
    passingGradeDesc: 'Nota mínima para aprobar. Se usa para marcar aprobados y como nota objetivo por defecto.',
    focusAlertModeLabel: 'Modo de alerta de Enfoque',
    focusAlertModeDesc: 'Elige cómo se entregan las alertas de Enfoque al cambiar de fase el temporizador.',
    focusAlertNone: 'Ninguna',
    focusAlertVibration: 'Vibración',
    focusAlertNotification: 'Notificación',
    focusAlertBoth: 'Ambas',
    taskAlertModeLabel: 'Alertas de fecha límite',
    taskAlertModeDesc: 'Elige cómo se entregan las alertas de fecha límite.',
    taskAlertNone: 'Ninguna',
    taskAlertInApp: 'En la app',
    taskAlertNotification: 'Notificación',
    taskAlertBoth: 'Ambas',
    taskAlertNextDayTimeLabel: 'Hora de alerta del día siguiente',
    taskAlertNextDayTimeDesc: 'Hora de los recordatorios de tareas que vencen mañana.',
    taskDefaultToCalendarLabel: 'Tareas en el calendario por defecto',
    taskDefaultToCalendarDesc: 'Las nuevas tareas tendrán «Mostrar en el calendario» activado por defecto.',
    hideCompletedTasksLabel: 'Guardar las tareas terminadas',
    hideCompletedTasksDesc: 'Mantén la lista centrada en lo que queda. Las tareas terminadas pasan a una sección «Completadas» que puedes abrir cuando quieras.',
    completedTasks: count => `Completadas (${count})`,
    speechInputLabel: 'Voz a texto',
    speechInputDesc: 'Mostrar un botón de micrófono para dictar texto en los campos de tareas, eventos y notas.',
    taskDueTodayTitle: count => count === 1 ? 'Tarea para hoy' : `${count} tareas para hoy`,
    taskAlertHide: 'Ocultar alerta',
    taskAlertRemindMeAt: 'Recordarme a las',
    settingEnabled: 'Activado', settingDisabled: 'Desactivado',
    spanSingle: 'Una casilla global (hecha una vez)', spanPerWeek: 'Casilla por semana',
    dangerZone: 'Zona de peligro', deleteSemester: 'Eliminar este semestre',
    clearPomodoros: 'Borrar pomodoros',
    clearPomodorosTitle: '¿Borrar todos los pomodoros?',
    clearPomodorosDesc: 'Todos los pomodoros caídos se eliminarán permanentemente.',
    deleteSemesterTitle: '¿Eliminar semestre?', deleteSemesterDesc: 'Todas las tareas, notas y datos kanban de este semestre se eliminarán permanentemente.',
    clearDoneTitle: '¿Borrar la columna Hecho?', clearDoneDesc: 'Todas las tarjetas de la columna Hecho se eliminarán.',
    wipeAllTitle: '¿Borrar todas las tarjetas?', wipeAllDesc: 'Cada tarjeta del tablero se eliminará permanentemente.',
    selectSemester: 'Seleccionar semestre', noClassesYet: 'Aún no hay asignaturas', addClassesInSettings: 'Añade asignaturas en Ajustes.',
    addUnlocks: 'Añade un semestre para desbloquear el resto.',
    checklist: 'Checklist', addItem: 'Añadir elemento', editCard: 'Editar tarjeta',
    notAchievable: '— no alcanzable', onRemaining: ' en las evaluaciones restantes',
    youNeed: 'Necesitas', allGraded: 'Todos los componentes calificados.',
    noGradeComponents: 'No hay componentes de nota configurados. Ve a Ajustes.',
    deleteClassTitle: '¿Eliminar asignatura?', deleteClassDesc: 'Esto también eliminará todas las tareas de esta asignatura.',
    holidayName: 'Nombre de las vacaciones', holidayNamePlaceholder: 'ej: Vacaciones de Navidad',
    addHoliday: 'Añadir vacaciones',
    loadPreset: 'Cargar preajuste',
    presetLoading: 'Cargando preajuste…', presetError: 'Error al cargar el preajuste.', retry: 'Reintentar', skip: 'Omitir',
    newColumnName: 'Nombre de la nueva columna',
    focusStart: 'Iniciar', focusPause: 'Pausar', focusResume: 'Reanudar', focusReset: 'Reiniciar', focusSkipBreak: 'Saltar descanso',
    focusReady: 'listo', focusBreak: 'descanso',
    focusPhrases: ['sigue así', 'mantente en ello', 'lo estás haciendo genial', 'paso a paso', 'trabajo profundo', 'mantente presente'],
    focusEvery: 'cada (min)', focusBreakFor: 'descanso (min)',
    focusScheduledMode: 'Descansos programados',
    focusNextBreak: 'Próximo descanso a las',
    focusFocusLabel: 'Mensaje de enfoque', focusBreakLabel: 'Mensaje de descanso',
    loadPresetTitle: 'Cargar un preajuste',
    presetGroupEI: 'Grado EI',
    presetGroupGeneric: 'General',
    backToMenu: 'Atrás',
    importData: 'Importar datos',
    importFromFirebase: 'Importar desde Firebase',
    nextSemesterTitle: 'Semestre terminado',
    nextSemesterDesc: 'Tu semestre ha terminado. ¿Cargar el siguiente?',
    loadNextSemester: 'Cargar el próximo semestre',
    dismissNextSemester: 'Descartar',
    carryOverTitle: 'Transferir',
    carryKanbanCards: 'Tarjetas del kanban',
    carryUpcomingTasks: 'Tareas próximas',
    carryUpcomingEvents: 'Eventos próximos',
    carryOverAlwaysKept: 'Las notas y los ajustes siempre se conservan.',
    carryOverDiscardWarning: 'Todo lo demás de este semestre se elimina.',
    noSemesterYet: 'Ningún semestre configurado',
    noSemesterDesc: 'Carga un preajuste o importa tus datos para empezar.',
    focusIntervalMode: 'Descansos por intervalo',
    focusIntervalEvery: 'cada (min)',
    focusIntervalBreakFor: 'descanso (min)',
    focusScheduledBreakFor: 'descanso (min)',
    focusAfterBreakReset: 'Tras el descanso: reiniciar temporizador',
    focusAfterBreakContinue: 'Tras el descanso: seguir contando',
    firebaseSync: 'Sync de Firebase',
    firebaseConnect: 'Conectar',
    firebaseConnected: 'Conectado',
    firebaseDisconnect: 'Desconectar',
    firebaseSyncing: 'Sincronizando…',
    firebaseLastSync: 'Última sync',
    firebaseError: 'Error de sync',
    firebaseRemoteNewer: 'Los datos de la nube son de una versión más reciente. Sync en pausa. Actualiza la app.',
    collabSyncFailed: 'No se pudo sincronizar el cambio compartido. Se revirtió.',
    newerVersionWarning: 'Tus datos se guardaron con una versión más reciente. Algunas cosas pueden no mostrarse bien hasta que actualices.',
    firebaseSetupTitle: 'Conectar Firebase',
    firebaseStep1Title: 'Crear un proyecto de Firebase',
    firebaseStep1Desc: 'Ve a console.firebase.google.com → Añadir proyecto → dale un nombre → desactiva Google Analytics → Crear proyecto.',
    firebaseStep2Title: 'Activar Firestore',
    firebaseStep2Desc: 'Ve a Build → Firestore Database → Crear base de datos → elige una región → Iniciar en modo producción → Crear. Luego abre la pestaña Reglas, reemplaza todo por las reglas de abajo y pulsa Publicar.',
    firebaseStep3Title: 'Obtener tu configuración',
    firebaseStep3Desc: 'Ve a Configuración del proyecto (icono de engranaje) → Tus apps → Añadir app → Web → registra la app → copia el objeto firebaseConfig mostrado.',
    firebaseStep4Title: 'Pegar tu configuración',
    firebaseStep4Desc: 'Pega el objeto firebaseConfig completo (como JSON) abajo.',
    firebaseConfigPlaceholder: '{ "apiKey": "...", "authDomain": "...", "projectId": "...", ... }',
    firebaseConfigInvalid: 'Config inválida: debe incluir apiKey y projectId.',
    firebaseTestFailed: 'No se pudo conectar. Revisa tu config y las reglas de la base de datos.',
    firebaseSave: 'Guardar y conectar',
    pomodoroMode: 'Modo Pomodoro',
    pomodoroModeDesc: 'Cultiva tomates durante las sesiones de enfoque. Cada sesión completada suelta un tomate.',
    pomodoroResetPeriod: 'Periodo de reinicio',
    pomodoroResetDay: 'Diario', pomodoroResetWeek: 'Semanal', pomodoroResetMonth: 'Mensual', pomodoroResetSemester: 'Por semestre',
    pomodoroTrackPeriodStats: 'Seguir estadísticas del periodo',
    pomodoroShowAbandoned: 'Mostrar tomates abandonados',
    pomodoroShowPeriodPomodoros: 'Mostrar pomodoros del periodo',
    pomodoroShowOverlay: 'Mostrar superposición global en todas las pestañas',
    focusNotifTitle: 'Organizador Focus',
    focusNotifBreakBody: 'Hora de tu descanso pomodoro.',
    focusNotifFocusBody: 'De vuelta al enfoque.',
    tasksNotifTitle: 'Organizador Tareas',
    taskReminderTitle: 'Recordatorio de tarea',
    pomodoroStatsTitle: 'Estadísticas Pomodoro',
    pomodoroTotal: 'Total de tomates', pomodoroAbandoned: 'Abandonados', pomodoroFocusTime: 'Tiempo total de enfoque',
    pomodoroPeriodTotal: 'Este periodo', pomodoroPeriodFocus: 'Enfoque este periodo',
    pomodoroVsSinceLast: 'vs periodo anterior',
    pomodoroAllTime: 'Histórico',
    pomodoroInsightsDailyTitle: 'Enfoque diario esta semana',
    pomodoroInsightsWeeklyBreakdownTitle: 'Medias semanales',
    pomodoroInsightsAvgWeekLabel: 'media/día (semana)',
    pomodoroInsightsAvgPeriodLabel: 'media/día (periodo)',
    pomodoroInsightsPerDaySuffix: '/d',
    pomodoroInsightsNoWeeklyData: 'Aún no hay datos semanales.',
    pomodoroInsightsDayLabels: ['D', 'L', 'M', 'X', 'J', 'V', 'S'],
    pomodoroTotalTimeLabel: 'tiempo total',
    pomodoroClose: 'Cerrar',
    pomodoroEraseStats: 'Borrar estadísticas',
    pomodoroEraseStatsTitle: '¿Borrar estadísticas Pomodoro?',
    pomodoroEraseStatsDesc: 'Se eliminarán las estadísticas históricas de tiempo de enfoque, pero las entradas de tomate seguirán disponibles.',
    pomodoroGraceCancel: 'Cancelar (sin tomate)',
    pomodoroGrace: s => `${s}s para cancelar sin perder un tomate`,
    workModeLabel: 'Modo trabajo',
    workModeDesc: 'Oculta las notas y renombra las asignaturas como grupos.',
    workModeOnboarding: '¿Usas esto para el trabajo?',
    semesterModeLabel: 'Modo sin semestre',
    semesterModeDesc: 'Activa para usar simples semanas del año en vez de semestres. Las notas se ocultan.',
    semesterModeNone: 'Sin semestres (semanas del año)',
    semesterModeSemesters: 'Con semestres',
    semesterModeOnboarding: '¿Sin semestres, solo semanas?',
    groups: 'Grupos', group: 'Grupo', addAGroup: 'Añadir grupo', groupName: 'Nombre del grupo',
    deleteGroupTitle: '¿Eliminar grupo?', deleteGroupDesc: 'Esto también eliminará todas las tareas de este grupo.',
    storageWarningTitle: 'Límite de almacenamiento alcanzado',
    storageWarningDesc: 'Activa la sync de Firebase, se alcanzó el máximo de almacenamiento local.',
    storageWarningAction: 'Entendido',
    collabConnect: 'Conectar Organizer Collab',
    collabDisconnect: 'Desconectar Organizer Collab',
    collabRequiresFirebase: 'Conecta primero la sync de Firebase para usar Organizer Collab.',
    collabGuideTitle: 'Configuración de Organizer Collab',
    collabGuideIntro: 'Configuración única. Haz estos 4 pasos en Firebase y luego vuelve para activar collab.',
    collabGuideImportantTitle: 'Qué cambia cuando collab está activado',
    collabGuideImportant1: 'Tu base de datos empieza a requerir usuarios autenticados (basta con auth anónima).',
    collabGuideImportant2: 'La sync normal sigue funcionando, pero debe autenticarse primero.',
    collabGuideImportant3: 'Si collab se desactiva luego, las reglas basadas en auth siguen siendo seguras de usar.',
    collabGuideStep1: 'Abre Firebase Console > Build > Firestore Database > Reglas.',
    collabGuideStep2: 'Pega el fragmento de reglas de abajo y pulsa Publicar.',
    collabGuideStep3: 'Abre Security > Authentication > Método de acceso > activa Anónimo > Guardar.',
    collabGuideStep4: 'Vuelve a Organizer y pulsa «Configuré las reglas, activar collab».',
    collabGuideRulesLabel: 'Reglas de Firestore',
    collabRulesHelpTitle: "Reglas de Firestore",
    collabRulesHelpHost: "Las reglas de Firestore de tu equipo están desactualizadas o son demasiado estrictas. Pega las reglas de abajo en la consola de Firebase y recarga.",
    collabRulesHelpMember: "No se puede acceder a este equipo. Solo el anfitrión puede solucionarlo: envíale las reglas de abajo para pegarlas en su consola de Firebase.",
    copy: "Copiar",
    copied: "¡Copiado!",
    collabGuideGotIt: "Entendido",
    collabFirebaseOnlyForCreating: "Firebase solo hace falta para crear equipos. Puedes unirte a uno desde un enlace de invitación sin él.",
    collabGuideTroubleshootTitle: 'Si ves un error signUp 400',
    collabGuideTroubleshootBody: 'Significa que la autenticación anónima sigue desactivada en Firebase. Actívala en Security > Authentication > Método de acceso.',
    collabEnableNow: 'Configuré las reglas, activar collab',
    collabPanelTitle: 'Organizer Collab',
    collabPanelSubtitle: 'Crea equipos, invita a personas y comparte tareas/tarjetas kanban.',
    collabCreateTeam: 'Crear equipo',
    collabTeamName: 'Nombre del equipo',
    collabTeamDays: 'días del equipo',
    collabTeamDuration: 'duración del equipo',
    collabDays: 'días',
    collabJoinTeam: 'Unirse a un equipo',
    collabInvitePlaceholder: 'Pega el enlace de invitación',
    collabInviteTtl: 'Validez de la invitación',
    collabYourTeams: 'Tus equipos',
    collabNoTeams: 'Aún no hay equipos.',
    collabShare: 'Compartir',
    collabShareTask: 'Compartir tarea',
    collabShareCard: 'Compartir tarjeta',
    collabSelectTeam: 'Elegir equipo',
    collabRoleHost: 'anfitrión',
    collabRoleMember: 'miembro',
    all: "Todo",
    collabAlias: "Tu alias",
    collabEditAlias: "Editar alias",
    collabMembers: "Miembros",
    collabAssignedOnlyComplete: "Solo el responsable puede completar",
    collabKanbanDividers: "Separadores del Kanban",
    collabSeparateByTeam: "Separar por equipo",
    collabPersonal: "Personal",
    collabUnassigned: "Sin asignar",
    collabMe: "Yo",
    collabAssignee: "Responsable",
    collabSeparateByClass: "Separar por asignatura",
    kanbanAllTeams: "Todos los equipos",
    kanbanAllAssignees: "Todos los responsables",
    kanbanAllClasses: "Todas las asignaturas",
    kanbanFilterTeam: "Equipo",
    kanbanFilterClass: "Asignatura",
    kanbanNoClass: "Sin asignatura",
    kanbanResetFilters: "Restablecer",
    collabEndsAt: 'termina',
    collabInvite: 'Invitar',
    collabEditTeam: 'Editar equipo',
    collabTaskCompletionMode: 'Finalización de tareas compartidas',
    collabTaskCompletionPersonal: 'finalización personal',
    collabTaskCompletionForAll: 'alternar para todos',
    collabTaskPermissions: 'Permisos de edición de tareas',
    collabTaskPermissionsEveryone: 'cualquiera puede añadir/editar/eliminar tareas',
    collabTaskPermissionsHostOnly: 'solo el anfitrión puede añadir/editar/eliminar tareas',
    collabLeave: 'Salir',
    collabDeleteTeam: 'Eliminar',
    collabDefaultTeamName: 'Equipo',
    collabLeavePrompt: '¿Salir de este equipo?',
    collabLeaveWithLocalPrompt: 'Compartiste tareas locales en este equipo. ¿Conservarlas localmente?',
    collabDeleteTeamPrompt: '¿Eliminar este equipo?',
    collabDeleteTeamWithLocalPrompt: 'Compartiste tareas locales en este equipo. ¿Conservarlas localmente antes de eliminar el equipo?',
    collabKeepLocalTasks: 'Conservar tareas locales',
    collabDeleteLocalTasksToo: 'Eliminar tareas locales',
    collabErrorCreate: 'No se pudo crear el equipo.',
    collabErrorInvite: 'No se pudo generar la invitación.',
    collabErrorJoin: 'No se pudo unir al equipo.',
    collabErrorInvalidLink: 'Enlace de invitación inválido.',
    collabErrorDeleteTeam: 'No se pudo eliminar el equipo.',
    collabGuideChecklistTitle: '¿Sigue sin sincronizar?',
    collabGuideChecklistBody: 'Los dos pasos que Organizer no puede hacer por ti: activar la autenticación anónima y publicar las reglas de Firestore de arriba. Si las tareas compartidas nunca aparecen, falta uno de estos en el proyecto del anfitrión.',
    collabSyncErrorHint: 'No se puede acceder a este equipo. Verifica que el Firebase del anfitrión tenga la autenticación anónima activada y reglas abiertas.',
    collabKeyRequiredHint: "Este equipo está cifrado y tu enlace de invitación no tenía clave. Pide un enlace de invitación nuevo.",
    collabOutdatedTeamHint: "Este equipo está desactualizado y ya no sincroniza. Pide un equipo nuevo al anfitrión.",
    collabErrorPermission: 'Bloqueado por las reglas de Firebase. El anfitrión debe activar la autenticación anónima y abrir las reglas de Firestore.',
    collabErrorAuthDisabled: "El inicio de sesión anónimo está desactivado en el proyecto Firebase del anfitrión. El anfitrión debe activarlo en Authentication › Sign-in method.",
    collabErrorNotFound: 'Equipo no encontrado. Puede que se haya eliminado.',
    collabErrorInviteExpired: 'Esta invitación ha caducado. Pide un nuevo enlace al anfitrión.',
    collabErrorInviteInvalid: 'Este enlace de invitación no es válido para ese equipo.',

    nlpToday: ["today"],
    nlpTomorrow: ["tomorrow"],
    nlpNextWeek: ["next week"],
    nlpAt: ["at"],
    nlpDow: [["sunday","sun"],["monday","mon"],["tuesday","tue"],["wednesday","wed"],["thursday","thu"],["friday","fri"],["saturday","sat"]],
    voiceInputAria: "Dictate by voice",
    voiceInputStopAria: "Stop dictation",
    quickActionTaskWordsPlural: ['tareas'],
    quickActionEventWordsPlural: ['eventos de calendario', 'eventos'],
    quickActionCardWordsPlural: ['tarjetas kanban', 'tarjetas'],
    quickActionRespectivelyWords: ['respectivamente'],
    quickActionOrdinalWords: ['primero', 'segundo', 'tercero', 'cuarto', 'quinto', 'sexto', 'séptimo', 'octavo', 'noveno', 'décimo', 'primera', 'segunda', 'tercera', 'cuarta', 'quinta', 'sexta', 'séptima', 'octava', 'novena', 'décima'],
    eventAllDay: "All day",
    eventStartTime: "Start time",
    eventEndTime: "End time",
    viewDay: "Día",
    viewWeek: "Semana",
    viewMonth: "Mes",
    viewYear: "Año",
    notesMentionNoResults: "No matching tasks",
    notesMentionDeletedTask: "Deleted task",
    notesArchive: "Archive",
    notesUnarchive: "Unarchive",
    notesArchived: "Archived",
    notesArchivedEmpty: "No archived notes.",
    eisenhower: "Matriz de Eisenhower",
    eisenhowerEnable: "Activar la matriz de Eisenhower",
    eisenhowerEnableDesc: "Añade una pestaña para ordenar tareas por urgencia e importancia.",
    eisenhowerDoNow: "Urgente e importante",
    eisenhowerSchedule: "Importante, no urgente",
    eisenhowerDelegate: "Urgente, no importante",
    eisenhowerEliminate: "Ninguno de los dos",
    eisenhowerUnsorted: "Tareas sin ordenar",
    eisenhowerUnsortedEmpty: "Nada que ordenar.",
    eisenhowerEmpty: "Arrastra tareas aquí.",
    pomodoro: "Pomodoro",
    pomodoroOverlayFocusing: "concentrado",
    pomodoroStreakTitle: "Racha",
    pomodoroCurrentStreak: "Racha actual",
    pomodoroBestStreak: "Mejor racha",
    pomodoroStreakDaySuffix: "d",
    pomodoroTrendTitle: "Tendencia mensual",
    pomodoroTrendNoData: "Aún no hay datos mensuales.",
    pomodoroCopySummary: "Copiar resumen",
    pomodoroCopiedSummary: "¡Copiado!",
    firebaseRulesTemplateLink: "View Firestore rules template",
    firebaseOpenRulesWarningTitle: "Your database rules may be open",
    firebaseOpenRulesWarningDesc: "Sync is working without authentication, which usually means your Firestore rules allow anyone to read and write your data. Publish the rules template linked below to lock this down.",
    firebaseEncryptionOffTitle: "End-to-end encryption is off",
    firebaseEncryptionOffDesc: "Your data is stored in Firestore as plain text. Turn on encryption so only devices with your key can read it — even if your database rules are ever misconfigured.",
    firebaseEncryptNow: "Encrypt now",
    firebaseEncryptMigrateFailed: "Could not enable encryption. Check your connection and try again.",
    firebaseHaveKeyAlready: "This device already has a key from another install",
    firebaseKeyPastePlaceholder: "Paste your recovery key",
    firebaseKeyInvalid: "That does not look like a valid key.",
    firebaseKeyWrongOrUnreadable: "Could not decrypt with this key. Double check it and try again.",
    firebaseRecoveryKeyShownOnceTitle: "Save this recovery key now",
    firebaseRecoveryKeyShownOnceDesc: "This key is shown only once and is never sent to Firebase. Anyone with it can read your data; anyone without it (including you) cannot recover it if lost. Store it somewhere safe.",
    firebaseKeySavedItConfirm: "I've saved my key",
    firebaseEncryptionOnTitle: "End-to-end encryption is on",
    firebaseEncryptionOnDesc: "Tus datos se cifran en este dispositivo, tanto en el almacenamiento local como antes de llegar a Firestore. Solo los dispositivos con la clave de recuperación pueden descifrarlos.",
    firebaseShowRecoveryKey: "Show recovery key",
    firebaseShowRecoveryKeyConfirmTitle: "Show recovery key?",
    firebaseShowRecoveryKeyConfirmDesc: "Anyone who sees this key can decrypt your data. Only do this somewhere private.",
    firebaseKeyRequiredTitle: "Encryption key needed",
    firebaseKeyRequiredDesc: "This project’s data is encrypted. Paste the recovery key from a device that already has it to unlock sync on this device.",
    firebaseKeyRequiredForImport: "This backup is encrypted. Set up sync with the matching key first, then import again.",
    exportEncrypted: "Organizer format (encrypted)",
    encUnlockTitle: "Desbloquea tus datos",
    encUnlockDesc: "Este dispositivo contiene datos cifrados. Introduce tu contraseña para desbloquearlos.",
    encUnlockHintLabel: "Tu pista",
    encPassphraseLabel: "Contraseña",
    encPassphrasePlaceholder: "Tu contraseña",
    encPassphraseConfirmLabel: "Confirmar contraseña",
    encPassphraseMismatch: "Las dos contraseñas no coinciden.",
    encPassphraseTooShort: "Usa al menos 8 caracteres.",
    encHintLabel: "Pista de la contraseña (opcional)",
    encHintPlaceholder: "Un recordatorio privado, no la contraseña en sí",
    encRecoveryCodeTitle: "Guarda tu código de recuperación",
    encRecoveryCodeDesc: "Estas 12 palabras en inglés son la única forma de volver a entrar si olvidas tu contraseña. Apúntalas o guárdalas en un gestor de contraseñas. No podemos volver a mostrarlas.",
    encRecoveryCodeWordsNote: "12 palabras en inglés. Cópialas exactamente y en orden.",
    encRecoveryCodeSavedConfirm: "He guardado mi código de recuperación",
    encRecoveryCodeQr: "Mostrar código QR",
    encRecoveryCodeQrDesc: "Escanéalo en otro dispositivo para transferir el código de recuperación.",
    encUseRecoveryCode: "Usar el código de recuperación",
    encUsePassphrase: "Usar la contraseña",
    encRecoveryCodeLabel: "Código de recuperación",
    encRecoveryCodePlaceholder: "doce palabras separadas por espacios",
    encRecoveryCodeInvalid: "Ese no es un código de recuperación válido de 12 palabras.",
    encUnlockFailed: "No se pudo desbloquear con eso. Compruébalo e inténtalo de nuevo.",
    encUnlocking: "Desbloqueando…",
    encDeriving: "Derivando la clave…",
    encEnableTitle: "Activar el cifrado de extremo a extremo",
    encEnableDesc: "Tus datos se cifran en este dispositivo antes de llegar a Firestore. Solo los dispositivos con tu contraseña o código de recuperación pueden leerlos.",
    encEnableWarning: "Si pierdes tanto la contraseña como el código de recuperación, nadie podrá recuperar tus datos, nosotros incluidos.",
    encEnableSubmit: "Activar el cifrado",
    encEnableFailed: "No se pudo activar el cifrado. Comprueba tu conexión e inténtalo de nuevo.",
    encManageTitle: "Cifrado",
    encManageDesc: "Tus datos están cifrados de extremo a extremo. El desbloqueo ocurre solo en este dispositivo.",
    encChangePassphrase: "Cambiar la contraseña",
    encChangePassphraseDesc: "Introduce tu contraseña actual y luego la nueva.",
    encCurrentPassphraseLabel: "Contraseña actual",
    encRegenerateRecoveryCode: "Generar un nuevo código de recuperación",
    encRegenerateRecoveryCodeDesc: "Sustituye el código existente. El anterior deja de funcionar.",
    encEditHint: "Editar la pista",
    encRotateDekTitle: "Rotar la clave de cifrado",
    encRotateDekDesc: "Vuelve a cifrar todos tus datos con una clave nueva. Los demás dispositivos tendrán que desbloquear otra vez.",
    encRotateDekWarning: "No cierres la app hasta que esto termine.",
    encRotating: "Volviendo a cifrar…",
    encRotateFailed: "No se pudo rotar la clave. No se cambió nada.",
    encSaved: "Guardado.",
    encStoreUnavailableTitle: "No se puede acceder al almacenamiento seguro",
    encStoreUnavailableDesc: "Este navegador bloqueó el almacén de claves, algo habitual en navegación privada. Tus datos cifrados quedaron intactos. Prueba en una ventana normal.",
    encPlaintextSyncWarnTitle: "La sincronización no está cifrada",
    encPlaintextSyncWarnDesc: "Tus datos se guardan en Firestore como texto plano. Cualquiera que pueda leer tu base de datos puede leerlos.",
    encPlaintextSyncEnable: "Activar el cifrado",
    encPlaintextSyncDismiss: "Ahora no, y no preguntar más",
    encRemoteAlreadyEncrypted: "Este proyecto ya está cifrado. Desbloquéalo para conectar este dispositivo.",
    encRemoteNotEncryptedTitle: "¿Cifrar este proyecto?",
    encRemoteNotEncryptedDesc: "Este proyecto contiene datos sin cifrar. Activa el cifrado ahora y se volverán a subir cifrados.",
    encRemoteNotEncryptedMigrate: "Cifrar y migrar",
    encRemoteNotEncryptedSkip: "Mantenerlo sin cifrar",
    encRemoteUnrecoverable: "Este proyecto está cifrado pero no tiene datos de recuperación, así que no puede desbloquearse. Desconéctate y empieza un proyecto nuevo.",
    encRemoteDekMismatch: "Este proyecto se volvió a cifrar con una clave nueva. Desbloquéalo otra vez con tu contraseña o código de recuperación.",
    encExportPassphraseTitle: "Proteger esta copia de seguridad",
    encExportPassphraseDesc: "Elige una contraseña para el archivo. La necesitarás para restaurar, en cualquier dispositivo.",
    encImportPassphraseTitle: "Desbloquear esta copia de seguridad",
    encImportPassphraseDesc: "Introduce la contraseña que elegiste al exportar.",
    encImportPassphraseFailed: "Contraseña incorrecta para esta copia de seguridad.",
    encTitle: "Cifrado",
    encOffTitle: "El cifrado está desactivado",
    encOffDesc: "Tus datos se guardan como texto plano dondequiera que estén. Activa el cifrado y serán ilegibles sin tu contraseña, en este dispositivo y en cualquier lugar donde se sincronicen.",
    encOnDesc: "Tus datos se cifran antes de guardarse o sincronizarse. Solo los dispositivos con tu contraseña o código de recuperación pueden leerlos.",
    encLockedDesc: "Tus datos guardados están cifrados. Introduce tu contraseña para desbloquearlos en este dispositivo.",
    encEnableAction: "Activar el cifrado",
    encDisableAction: "Desactivar el cifrado",
    encDisableTitle: "¿Desactivar el cifrado?",
    encDisableDesc: "Tus datos se reescribirán como texto plano allí donde estén guardados, y tu contraseña y código de recuperación dejarán de funcionar.",
    encStorageShedTitle: "Algunos datos no cupieron",
    encStorageShedDesc: "Este dispositivo se quedó sin almacenamiento local, así que lo siguiente no se guardó localmente:",
    exportPlaintext: "Human-readable (plaintext JSON)",
    repeat: "Repetir",
    repeatFreqLabel: "Frecuencia",
    repeatFreqDaily: "Diario",
    repeatFreqWeekly: "Semanal",
    repeatFreqMonthly: "Mensual",
    repeatEvery: () => 'Cada',
    repeatIntervalDaily: n => (n === 1 ? 'día' : 'días'),
    repeatIntervalWeekly: n => (n === 1 ? 'semana' : 'semanas'),
    repeatIntervalMonthly: n => (n === 1 ? 'mes' : 'meses'),
    repeatUntil: "Hasta (opcional)",
    kanbanColTodo: "Por hacer", kanbanColInProgress: "En curso", kanbanColDone: "Hecho",
    colourCustom: "Color personalizado",
    googleCalendar: "Google Calendar",
    gcalConnect: "Connect",
    gcalConnected: "Connected",
    gcalConnecting: "Connecting…",
    gcalDisconnect: "Disconnect",
    gcalEnable: "Sync with Google Calendar",
    gcalScopeNotice: "This grants full read/write access to your primary Google Calendar (the \"calendar\" scope). Organizer only reads and writes events you interact with here; your Google credentials never leave your device and are not sent anywhere but Google.",
    gcalStep1Title: "Create a Google Cloud project",
    gcalStep1Desc: "Go to console.cloud.google.com → create a new project (or pick one) → APIs & Services → enable the \"Google Calendar API\".",
    gcalStep2Title: "Configure OAuth consent + credentials",
    gcalStep2Desc: "APIs & Services → OAuth consent screen → set it up (External is fine for personal use, add yourself as a test user). Then Credentials → Create credentials → OAuth client ID → Application type: Web application → add this app's URL to Authorized JavaScript origins.",
    gcalStep3Title: "Paste your Client ID",
    gcalStep3Desc: "Copy the Client ID (ends in .apps.googleusercontent.com) shown after creating it, and paste it below. This value is not secret and is safe to store in this browser.",
    gcalClientIdPlaceholder: "xxxxxxxx.apps.googleusercontent.com",
    gcalClientIdInvalid: "Enter a valid OAuth Client ID.",
    gcalConnectFailed: "Could not connect. Check your Client ID and try again.",
    gcalDisableTitle: "Disconnect Google Calendar?",
    gcalDisableDesc: "Stops syncing with Google Calendar on this device. Events already created stay in both places; sync bookkeeping (Client ID, links) is removed here.",
    eventSyncToGoogle: "Sync to Google Calendar",
    eventSyncToGoogleDesc: "Push this event to your connected Google Calendar.",
    quickActionTaskWords: ["tarea"],
    quickActionEventWords: ["evento de calendario","evento"],
    quickActionCardWords: ["tarjeta kanban","tarjeta"],
    quickActionAddWords: ["añade","añadir","agrega","agregar","crea","crear"],
    quickActionForWords: ["para","de"],
    quickActionAndWords: ["y","e"],
    quickActionOnWords: ["en","día","dia"],
    quickActionArticleWords: ["un","una","unos","unas","el","los"],
    quickActionBoardWords: ["kanban","tablero"],
    quickAction: "Quick action",
    quickActionPlaceholder: "e.g. add task and calendar event for a cbd test on 18/07 at 15h",
    quickActionTab: "Quick action",
    quickActionFormTab: "Form",
    quickActionPreviewTitle: "Will create",
    quickActionPreviewTask: "task",
    quickActionPreviewTaskCalendar: "task (shown on calendar)",
    quickActionPreviewEvent: "calendar event",
    quickActionPreviewCard: column => `kanban card in ${column}`,
    quickActionEmpty: "Couldn't understand that. Try rephrasing.",
    quickActionCreate: "Create",
    quickActionBack: "Back",
    notesDeleteConfirmTitle: "Delete this note?",
    notesDeleteConfirmDesc: "This note will be permanently deleted.",
    notesEmptyTitle: "No notes yet",
    notesEmptyDesc: "Create your first note to get started.",
    notesFilterEmpty: "No notes match your search.",
    notesSelectNote: "Select a note to start editing",
    notesTextNote: "Text note",
    notesCanvasNote: "Canvas note",
    eventStartTimeFirstDay: "Hora de inicio (primer día)",
    eventEndTimeLastDay: "Hora de fin (último día)",
    notesBold: "Negrita",
    notesItalic: "Cursiva",
    notesStrike: "Tachado",
    notesHeading1: "Título 1",
    notesHeading2: "Título 2",
    notesHeading3: "Título 3",
    notesBulletList: "Lista con viñetas",
    notesOrderedList: "Lista numerada",
    notesTaskList: "Lista de tareas",
    notesQuote: "Cita",
    notesInsertTable: "Insertar tabla",
    notesCodeBlock: "Bloque de código",
    notesDivider: "Separador",
    notesAddLink: "Añadir enlace",
    notesRemoveLink: "Quitar enlace",
    notesTextColor: "Color del texto",
    notesColorReset: "Color predeterminado",
    notesColorCustom: "Elegir color personalizado",
    notesColorApply: "Aplicar",
    notesExport: "Exportar nota",
    notesImport: "Importar nota",
    notesGraphEdit: "Editar gráfica",
    notesGraphRange: "x de",
    notesGraphResize: "Arrastra para redimensionar",
    notesGraphResizeWidth: "Arrastra para redimensionar ancho y alto",
    notesGraphInvalid: "Expresión no representable",
    notesGraphAlignleft: "Alinear a la izquierda",
    notesGraphAligncenter: "Centrar",
    notesGraphAlignright: "Alinear a la derecha",
    notesTextSize: "Tamaño del texto",
    notesSizeNormal: "Normal",
    notesSizeSmall: "Pequeño",
    notesSizeLarge: "Grande",
    notesSizeHuge: "Enorme",
    notesUndo: "Deshacer",
    notesRedo: "Rehacer",
    notesViewList: "Vista de lista",
    notesViewMosaic: "Vista de mosaico",
    notesMathEnable: "Resolver matemáticas",
    notesMathEnableDesc: "Escribe una ecuación terminada en = y pulsa Enter para resolverla. Usa x para dibujar una gráfica.",
    notesMathSolve: "Resolver para x",
    notesMathSolveDesc: "Convierte 3x = 3 en x = 1, incluidas inecuaciones y ecuaciones de segundo grado.",
    notesMathSelection: "Graficar la selección",
    notesMathSelectionDesc: "Selecciona una ecuación y pulsa Enter para dibujarla.",
    notesMathSteps: "Mostrar el desarrollo",
    notesMathStepsDesc: "Muestra cada paso de la solución en lugar de solo el resultado.",
    eisenhowerAddTask: "Añadir tarea",
    eisenhowerCustomize: "Personalizar cuadrantes",
    eisenhowerResetDefaults: "Restablecer valores predeterminados",
    eisenhowerCleanDone: "Borrar completadas",
    eisenhowerCleanDoneTitle: "¿Borrar tareas completadas?",
    eisenhowerCleanDoneDesc: "Quita las tareas completadas de la matriz. Siguen en tu lista de tareas.",
    quickActionApp: "Quick Action",
    quickActionAppEnable: "Enable Quick Action",
    quickActionAppEnableDesc: "Adds a spotlight overlay for quickly creating tasks, events, and cards.",
    quickActionTripleTapEnable: "Triple toque en la pantalla", quickActionTripleTapEnableDesc: "Toca 3 veces en cualquier lugar para abrir Quick Action",
    quickActionShortcutEnable: "Keyboard shortcut",
    quickActionShortcutKey: "Shortcut",
    quickActionNavbarButton: "Show in navbar add menu",
    spotlightPlaceholder: "Quick action… (e.g. add task for exam on Monday)",
    themeColor: "Accent color",
    themeColorDesc: "Pick a color for buttons, links, and highlights.",
    themeColorReset: "Reset to default",
    themeFontColor: "Color de fuente", themeHighlightColor: "Color de resaltado", themeBgColor: "Color de fondo",
    defaultTabLabel: "Pantalla inicial", defaultTabDesc: "Elige la pestaña con la que abre la app.",
    defaultTabLast: "Última usada",
    taskReminderOffsetsLabel: "Antelación de los recordatorios", taskReminderOffsetsDesc: "Cuántos días antes de la fecha hay que avisarte. Se aplica a todas las tareas con fecha.",
    taskReminderTimeLabel: "Hora del recordatorio", taskReminderTimeDesc: "Hora a la que saltan los recordatorios anticipados.",
    taskReminderAddOffset: "Días",
    taskReminderOffsetDays: n => (n === 0 ? "El mismo día" : n === 1 ? "1 día antes" : `${n} días antes`),
    taskReminderIn: n => (n === 0 ? "Entrega hoy" : n === 1 ? "Entrega mañana" : `Entrega en ${n} días`),
    habits: "Hábitos", habitsEnable: "Activar Hábitos", habitsEnableDesc: "Sigue hábitos a largo plazo con un botón de registro y un calendario de rachas.",
    habitsEmpty: "Aún no hay hábitos. Añade uno para empezar.",
    habitAdd: "Añadir hábito", habitEdit: "Editar hábito",
    habitTitleLabel: "Hábito", habitTitlePlaceholder: "Leer 20 minutos",
    habitCadenceLabel: "Registrar", habitCadenceDesc: "Con qué frecuencia quieres pulsar el botón.",
    habitCadenceDaily: "Cada día", habitCadence2Days: "Cada 2 días", habitCadence3Days: "Cada 3 días",
    habitCadenceWeekly: "Cada semana", habitCadenceMonthly: "Cada mes",
    habitRequireNote: "Pedir una nota", habitRequireNoteDesc: "Escribe una nota corta cada vez que registras.",
    habitColor: "Color",
    habitClickPrompt: "Marcar como completado", habitDoneForNow: "Hecho",
    habitNotePrompt: "¿Qué tal fue?", habitNotePlaceholder: "Unas palabras",
    habitSeeProgress: "Ver progreso", habitUndoToday: "Deshacer este registro", habitDelete: "Eliminar hábito",
    habitDeleteTitle: "¿Eliminar este hábito?", habitDeleteDesc: "Se borrarán el hábito y todo su historial.",
    habitCurrentStreak: "Racha actual", habitBestStreak: "Mejor racha",
    habitTotalCheckIns: "Registros", habitCompletionRate: "Cumplimiento",
    habitNotesTitle: "Notas",
    habitCadenceCustom: "Días a elegir", habitWeekdaysLabel: "Días de la semana", habitWeekdaysDesc: "Elige los días en los que quieres registrar.", habitRestDay: "Día de descanso",
    habitToneLabel: "Estilo de ánimo", habitToneDesc: "Qué tipo de mensaje recibes tras cada registro.",
    habitTonePurpose: "Propósito y progreso", habitToneWarm: "Cálido y motivador",
    habitToneUpbeat: "Alegre y satisfactorio", habitToneGame: "Videojuego",
    habitToneRandom: "Aleatorio cada vez", habitToneCustom: "Mi propio mensaje",
    habitToneCustomPlaceholder: "Tu mensaje",
    habitTargetLabel: "Meta final", habitTargetDesc: "Cuándo se considera terminado este hábito.",
    habitTargetEndless: "Seguir siempre", habitTargetCount: "Tras un número de registros", habitTargetDate: "Antes de una fecha",
    habitTargetCountPlaceholder: "Registros",
    habitTargetReached: "Hábito alcanzado.",
    habitTargetRemaining: n => (n === 1 ? "Queda 1 registro" : `Quedan ${n} registros`),
    habitTargetDaysLeft: n => (n === 0 ? "Último día" : n === 1 ? "Queda 1 día" : `Quedan ${n} días`),
    habitMessages: {
      purpose: {
        day1: "Primer registro hecho. Empieza el camino.",
        early: "Acumulando constancia día a día.",
        week: "7 días seguidos avanzando.",
        month: "30 días consecutivos completados.",
        daily: "Un día más cerca de tu objetivo a largo plazo.",
        rescue: "Hoy de vuelta al rumbo.",
      },
      warm: {
        day1: "Diste el paso más difícil. Orgullo.",
        early: "Estás demostrando que puedes confiar en ti.",
        week: "¡Una semana entera! Mira lo lejos que has llegado.",
        month: "30 días de dedicación. Has creado un hábito real.",
        daily: "Otro paso firme hoy.",
        rescue: "Me alegra que vuelvas. Cada día es una nueva oportunidad.",
      },
      upbeat: {
        day1: "¡Menudo comienzo!",
        early: "¡Otro buen día registrado!",
        week: "¡7 días seguidos! Trabajo fantástico.",
        month: "¡30 días! Es un hito enorme.",
        daily: "¡Marcado! Sienta bien.",
        rescue: "¡Me alegra que vuelvas! Sigamos.",
      },
      game: {
        day1: "Misión iniciada: nivel 1 completado.",
        early: "Combo activo. XP ganada.",
        week: "Logro desbloqueado: Guerrero de la primera semana.",
        month: "Hito mayor: jefe derrotado.",
        daily: "Misión diaria completada +100 XP.",
        rescue: "Reapareciste. Recuperemos la racha.",
      },
    },
}
