export const fr = {
    months: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'],
    weekdaysShort: ['Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam', 'Dim'],
    weekdays: ['Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi', 'Dimanche'],
    tasks: 'Tâches', kanban: 'Kanban', grades: 'Évaluations', calendar: 'Calendrier', focus: 'Focus', settings: 'Réglages',
    guides: 'Guides',
    noSemester: 'Aucun semestre configuré', goToSettings: 'Allez dans Réglages pour commencer.',
    weekLabel: w => `Semaine ${w}`, done: 'terminées', timeToRelax: 'Temps de repos !',
    addTask: 'Nouvelle tâche', task: 'Tâche', class: 'Matière', priority: 'Priorité',
    editTask: 'Modifier la tâche', moveLeft: 'Déplacer à gauche', moveRight: 'Déplacer à droite', markDone: 'Marquer comme fait',
    addToKanban: 'Ajouter au Kanban', themeLight: 'Thème clair', themeDark: 'Thème sombre', themeSystem: 'Thème système',
    addPartTitle: 'Ajouter une partie',
    fromWeek: 'De la semaine', toWeek: "Jusqu'à la semaine", dueDate: "Date d'échéance",
    other: 'Autre', noTasks: 'Aucune tâche cette semaine.',
    whatNeedsDone: "Qu'y a-t-il à faire ?",
    addTaskBtn: 'Ajouter la tâche', showOnCalendar: 'Afficher sur le calendrier', showOnTasks: 'Afficher dans les tâches',
    clearDone: 'Effacer les terminées', wipeAll: 'Tout effacer',
    addCard: 'Ajouter une carte', addCardPlaceholder: 'Titre de la carte',
    save: 'Enregistrer', cancel: 'Annuler', confirm: 'Confirmer', delete: 'Supprimer',
    addEvent: 'Ajouter un événement', newEvent: 'Nouvel événement', editEvent: "Modifier l'événement",
    eventTitle: "Titre de l'événement", eventDate: 'Date', eventRange: 'Plage de dates',
    eventMultiDay: 'Plusieurs jours', eventColor: 'Couleur', eventNote: 'Note',
    eventNotePlaceholder: 'Note facultative', more: 'plus',
    navbar: 'Barre de navigation', navHide: 'Masquer', navOverflow: 'Déplacer vers le menu', navAddButton: "Afficher le bouton d'ajout",
    navMore: 'Plus', navLabelMode: 'Afficher', navLabelBoth: 'Icônes + noms', navLabelIcons: 'Icônes seules', navLabelNames: 'Noms seuls',
    add: 'Ajouter', navAddLabel: 'Ajouter', navDrag: 'Glisser pour réorganiser',
    appDisableTitle: 'Désactiver et effacer les données ?', appDisableDesc: 'Désactiver cette app supprime définitivement toutes ses données.',
    collabDisableDesc: 'La déconnexion quitte toutes les équipes et supprime définitivement les données de collaboration de cet appareil.',
    navAddAction: "Action du bouton d'ajout", navAddPicker: 'Demander à chaque fois',
    navFolders: 'Dossiers', navNewFolder: 'Nouveau dossier',
    navMobilePosition: 'Position de la barre mobile', navPosBottom: 'Barre en bas', navPosSide: 'Barre latérale',
    addToTasks: 'Ajouter aux tâches', inTasks: 'Dans les tâches',
    standby: 'Veille', standbyEnable: 'Activer la veille paysage',
    standbyDesc: 'Mettez votre téléphone en paysage pour afficher un tableau de bord ambiant.',
    standbyLeft: 'Volet gauche', standbyCenter: 'Volet central', standbyRight: 'Volet droit',
    standbyPanels: 'Volets', standbyPane: n => `Volet ${n}`,
    standbyPaneSecond: 'Deuxième carte (glisser)', standbyPaneNone: 'Aucune',
    paneWheel: 'Roue de progression', paneWheelTime: 'Roue + horloge', paneCalendar: 'Calendrier',
    paneFocus: 'Focus', paneKanban: 'Kanban', paneTasksByCategory: 'Tâches par catégorie',
    notesLastEdit: 'Modifié', notesFolder: 'Dossier', notesNoFolder: 'Sans dossier', notesNewFolder: 'Nouveau dossier',
    notesFolderName: 'Nom du dossier', notesRenameFolder: 'Renommer le dossier', notesDeleteFolder: 'Supprimer le dossier', notesMoveTo: 'Déplacer vers',
    notesEdit: 'Modifier', notesPreview: 'Aperçu', notesBack: 'Retour',
    chunkLoadError: 'Cette partie n\'a pas pu être chargée.', chunkRetry: 'Réessayer',
    apps: 'Apps', appsSearch: 'Rechercher des apps', appsNoResults: 'Aucune app trouvée.', notes: 'Notes',
    notesEnable: 'Activer les Notes', notesEnableDesc: 'Ajoute un onglet Notes pour des notes rapides.',
    notesNew: 'Nouvelle note', notesTitle: 'Titre', notesBody: 'Écrivez quelque chose…', notesSearch: 'Rechercher des notes',
    notesEmpty: 'Aucune note pour le moment.', notesFavorite: 'Favori', notesText: 'Texte', notesCanvas: 'Écriture manuscrite',
    collabApp: 'Collaboration',
    eiCalendar: 'Calendrier EI', eiCalendarEnable: 'Afficher le calendrier EI',
    eiCalendarEnableDesc: "Ajoute le calendrier officiel du cursus EI pour votre année, en lecture seule et toujours à jour.",
    eiCalendarDisableTitle: 'Masquer le calendrier EI ?', eiCalendarDisableDesc: "Cesse d'afficher les événements du calendrier EI. Rien n'est supprimé et vous pouvez le réactiver à tout moment.",
    semester: 'Semestre', classes: 'Matières', gradeComponents: 'Composantes de note',
    kanbanColumns: 'Colonnes Kanban', general: 'Général', data: 'Données et sync',
    holidays: 'Vacances',
    exportJson: 'Exporter JSON', importJson: 'Importer JSON',
    semesterAvg: 'Moyenne du semestre', ectsPassedLabel: 'ECTS validés',
    targetGrade: 'Note visée',
    previousSemesters: 'Semestres précédents',
    courseAvg: 'Moyenne du cours', finalGrade: 'Note finale', previousAvg: 'Moyenne précédente', numSemesters: 'Nb de semestres',
    getStarted: 'Commencer', welcomeTitle: 'Bienvenue sur organizer',
    welcomeDesc: 'Votre espace pour le travail universitaire. Configurez votre semestre et organisez-vous.',
    step1: 'Définir les dates du semestre', step2: 'Ajouter vos matières', step3: 'Planifier les tâches et suivre les notes',
    obNext: 'Suivant', obBack: 'Retour', obFinish: 'Terminer', obSkip: 'Passer',
    obWelcomeTitle: 'Bienvenue sur Organizer', obWelcomeDesc: 'Votre espace calme pour le travail universitaire. Choisissez votre langue et votre thème pour commencer.',
    obModeTitle: 'Comment allez-vous l\'utiliser ?', obModeDesc: 'Activez ce qui vous convient. Les deux peuvent être actifs.',
    obModeWorkToggle: 'Mode travail', obModeWorkToggleDesc: 'Groupes au lieu de matières, sans notes.',
    obModeWeeksToggle: 'Sans semestres', obModeWeeksToggleDesc: 'Organiser par semaine calendaire plutôt que par semestre.',
    obImportOr: 'ou restaurer une sauvegarde',
    obDatesTitle: 'Votre semestre', obDatesDesc: 'Quand commence-t-il et se termine-t-il ?',
    obClassesTitle: 'Vos matières', obClassesDesc: 'Ajoutez les matières que vous suivez.',
    obGroupsTitle: 'Vos groupes', obGroupsDesc: 'Ajoutez les groupes avec lesquels vous travaillez.',
    obInfoTasksTitle: 'Tâches et Kanban', obInfoTasksDesc: 'Ajoutez des tâches par semaine ou par date, puis glissez-les sur votre tableau kanban.',
    obInfoCalTitle: 'Calendrier et Focus', obInfoCalDesc: 'Voyez tout sur le calendrier et lancez des sessions de focus pour avancer.',
    obInfoDoneTitle: 'Tout est prêt', obInfoDoneDesc: 'Vous pourrez modifier tout cela plus tard dans les réglages.',
    shareLink: 'Copier le lien de partage', qrCode: 'Code QR', linkCopied: 'Lien copié !',
    high: 'Haute', medium: 'Moyenne', low: 'Basse', none: 'Aucune',
    addSemester: 'Ajouter un semestre', semesterName: 'Nom du semestre', startDate: 'Date de début', endDate: 'Date de fin',
    weeks: n => `${n} semaines`, addAClass: 'Ajouter une matière', className: 'Nom de la matière', ects: 'ECTS', colour: 'Couleur',
    addComponent: 'Ajouter une composante', componentName: 'Nom de la composante',
    taskSpanLabel: 'Comportement des tâches sur plusieurs semaines', taskSpanDesc: 'Quand une tâche couvre plusieurs semaines, comment est-elle marquée comme faite ?',
    kanbanChecklistInlineLabel: 'Aperçu de la checklist Kanban',
    kanbanChecklistInlineDesc: 'Afficher les éléments de la checklist directement sur les cartes sans ouvrir les détails.',
    kanbanChecklistPreviewNone: 'Masquer sur les cartes',
    kanbanChecklistPreviewAll: 'Afficher sur toutes les cartes',
    kanbanChecklistPreviewPerCard: 'Au cas par cas',
    kanbanAutoAddLabel: 'Ajouter automatiquement les tâches au tableau',
    kanbanAutoAddDesc: 'Ajoute automatiquement les tâches de cette semaine à la première colonne du tableau Kanban.',
    gradeScaleLabel: 'Barème de notation',
    gradeScaleDesc: 'Note maximale possible. Les champs de note sont limités à cette valeur.',
    passingGradeLabel: 'Note de passage',
    passingGradeDesc: 'Note minimale pour réussir. Utilisée pour les mentions de réussite et la note cible par défaut.',
    focusAlertModeLabel: 'Mode d\'alerte Focus',
    focusAlertModeDesc: 'Choisissez comment les alertes Focus sont délivrées au changement de phase.',
    focusAlertNone: 'Aucune',
    focusAlertVibration: 'Vibration',
    focusAlertNotification: 'Notification',
    focusAlertBoth: 'Les deux',
    taskAlertModeLabel: 'Alertes d\'échéance des tâches',
    taskAlertModeDesc: 'Choisissez comment les alertes d\'échéance sont délivrées.',
    taskAlertNone: 'Aucune',
    taskAlertInApp: 'Dans l\'app',
    taskAlertNotification: 'Notification',
    taskAlertBoth: 'Les deux',
    taskAlertNextDayTimeLabel: 'Heure de l\'alerte du lendemain',
    taskAlertNextDayTimeDesc: 'Heure des rappels pour les tâches dues demain.',
    taskDefaultToCalendarLabel: 'Tâches sur le calendrier par défaut',
    taskDefaultToCalendarDesc: 'Les nouvelles tâches auront « Afficher sur le calendrier » activé par défaut.',
    speechInputLabel: 'Voix en texte',
    speechInputDesc: 'Afficher un bouton micro pour dicter du texte dans les champs de tâches, événements et notes.',
    taskDueTodayTitle: count => count === 1 ? 'Tâche due aujourd\'hui' : `${count} tâches dues aujourd'hui`,
    taskAlertHide: 'Masquer l\'alerte',
    taskAlertRemindMeAt: 'Me rappeler à',
    settingEnabled: 'Activé', settingDisabled: 'Désactivé',
    spanSingle: 'Une seule case globale (fait une fois)', spanPerWeek: 'Case par semaine',
    dangerZone: 'Zone sensible', deleteSemester: 'Supprimer ce semestre',
    clearPomodoros: 'Effacer les pomodoros',
    clearPomodorosTitle: 'Effacer tous les pomodoros ?',
    clearPomodorosDesc: 'Tous les pomodoros tombés seront supprimés définitivement.',
    deleteSemesterTitle: 'Supprimer le semestre ?', deleteSemesterDesc: 'Toutes les tâches, notes et données kanban de ce semestre seront supprimées définitivement.',
    clearDoneTitle: 'Effacer la colonne Terminé ?', clearDoneDesc: 'Toutes les cartes de la colonne Terminé seront supprimées.',
    wipeAllTitle: 'Effacer toutes les cartes ?', wipeAllDesc: 'Toutes les cartes du tableau seront supprimées définitivement.',
    selectSemester: 'Sélectionner un semestre', noClassesYet: 'Aucune matière pour le moment', addClassesInSettings: 'Ajoutez des matières dans Réglages.',
    addUnlocks: 'Ajoutez un semestre pour débloquer le reste.',
    checklist: 'Checklist', addItem: 'Ajouter un élément', editCard: 'Modifier la carte',
    notAchievable: '— non atteignable', onRemaining: ' sur les évaluations restantes',
    youNeed: 'Il vous faut', allGraded: 'Toutes les composantes sont notées.',
    noGradeComponents: 'Aucune composante de note configurée. Allez dans Réglages.',
    deleteClassTitle: 'Supprimer la matière ?', deleteClassDesc: 'Cela supprimera aussi toutes les tâches de cette matière.',
    holidayName: 'Nom des vacances', holidayNamePlaceholder: 'ex : Vacances de Noël',
    addHoliday: 'Ajouter des vacances',
    loadPreset: 'Charger un préréglage',
    presetLoading: 'Chargement du préréglage…', presetError: 'Échec du chargement du préréglage.', retry: 'Réessayer', skip: 'Passer',
    newColumnName: 'Nom de la nouvelle colonne',
    focusStart: 'Démarrer', focusPause: 'Pause', focusResume: 'Reprendre', focusReset: 'Réinitialiser', focusSkipBreak: 'Passer la pause',
    focusReady: 'prêt', focusBreak: 'pause',
    focusPhrases: ['continuez', 'restez concentré', 'vous vous en sortez bien', 'un pas à la fois', 'travail profond', 'restez présent'],
    focusEvery: 'toutes les (min)', focusBreakFor: 'pause (min)',
    focusScheduledMode: 'Pauses programmées',
    focusNextBreak: 'Prochaine pause à',
    focusFocusLabel: 'Message de focus', focusBreakLabel: 'Message de pause',
    loadPresetTitle: 'Charger un préréglage',
    presetGroupEI: 'Cursus EI',
    presetGroupGeneric: 'Général',
    backToMenu: 'Retour',
    importData: 'Importer les données',
    importFromFirebase: 'Importer depuis Firebase',
    nextSemesterTitle: 'Semestre terminé',
    nextSemesterDesc: 'Votre semestre est terminé. Charger le suivant ?',
    loadNextSemester: 'Charger le prochain semestre',
    dismissNextSemester: 'Ignorer',
    carryOverTitle: 'Transférer',
    carryKanbanCards: 'Cartes du kanban',
    carryUpcomingTasks: 'Tâches à venir',
    carryUpcomingEvents: 'Événements à venir',
    carryOverAlwaysKept: 'Les notes et les réglages sont toujours conservés.',
    carryOverDiscardWarning: 'Tout le reste de ce semestre est supprimé.',
    noSemesterYet: 'Aucun semestre configuré',
    noSemesterDesc: 'Chargez un préréglage ou importez vos données pour commencer.',
    focusIntervalMode: 'Pauses par intervalle',
    focusIntervalEvery: 'toutes les (min)',
    focusIntervalBreakFor: 'pause (min)',
    focusScheduledBreakFor: 'pause (min)',
    focusAfterBreakReset: 'Après la pause : réinitialiser le minuteur',
    focusAfterBreakContinue: 'Après la pause : continuer à compter',
    firebaseSync: 'Sync Firebase',
    firebaseConnect: 'Connecter',
    firebaseConnected: 'Connecté',
    firebaseDisconnect: 'Déconnecter',
    firebaseSyncing: 'Synchronisation…',
    firebaseLastSync: 'Dernière sync',
    firebaseError: 'Erreur de sync',
    firebaseRemoteNewer: 'Les données cloud proviennent d\'une version plus récente. Sync en pause. Mettez à jour l\'app.',
    collabSyncFailed: 'Impossible de synchroniser le changement partagé. Il a été annulé.',
    newerVersionWarning: 'Vos données ont été enregistrées par une version plus récente. Certaines choses peuvent ne pas s\'afficher correctement avant la mise à jour.',
    firebaseSetupTitle: 'Connecter Firebase',
    firebaseStep1Title: 'Créer un projet Firebase',
    firebaseStep1Desc: 'Allez sur console.firebase.google.com → Ajouter un projet → donnez-lui un nom → désactivez Google Analytics → Créer le projet.',
    firebaseStep2Title: 'Activer Firestore',
    firebaseStep2Desc: 'Allez dans Build → Firestore Database → Créer une base → choisissez une région → Démarrer en mode production → Créer. Ouvrez ensuite l’onglet Règles, remplacez tout par les règles ci-dessous et cliquez sur Publier.',
    firebaseStep3Title: 'Obtenir votre configuration',
    firebaseStep3Desc: 'Allez dans Paramètres du projet (icône engrenage) → Vos apps → Ajouter une app → Web → enregistrez l\'app → copiez l\'objet firebaseConfig affiché.',
    firebaseStep4Title: 'Coller votre configuration',
    firebaseStep4Desc: 'Collez l\'objet firebaseConfig complet (en JSON) ci-dessous.',
    firebaseConfigPlaceholder: '{ "apiKey": "...", "authDomain": "...", "projectId": "...", ... }',
    firebaseConfigInvalid: 'Config invalide : doit inclure apiKey et projectId.',
    firebaseTestFailed: 'Connexion impossible. Vérifiez votre config et les règles de la base.',
    firebaseSave: 'Enregistrer et connecter',
    pomodoroMode: 'Mode Pomodoro',
    pomodoroModeDesc: 'Faites pousser des tomates pendant les sessions de focus. Chaque session terminée dépose une tomate.',
    pomodoroResetPeriod: 'Période de réinitialisation',
    pomodoroResetDay: 'Quotidien', pomodoroResetWeek: 'Hebdomadaire', pomodoroResetMonth: 'Mensuel', pomodoroResetSemester: 'Par semestre',
    pomodoroTrackPeriodStats: 'Suivre les stats de période',
    pomodoroShowAbandoned: 'Afficher les tomates abandonnées',
    pomodoroShowPeriodPomodoros: 'Afficher les pomodoros de la période',
    pomodoroShowOverlay: 'Afficher la superposition globale sur tous les onglets',
    focusNotifTitle: 'Organiseur Focus',
    focusNotifBreakBody: 'C\'est l\'heure de votre pause pomodoro.',
    focusNotifFocusBody: 'Retour à la concentration.',
    tasksNotifTitle: 'Organiseur Tâches',
    taskReminderTitle: 'Rappel de tâche',
    pomodoroStatsTitle: 'Stats Pomodoro',
    pomodoroTotal: 'Total de tomates', pomodoroAbandoned: 'Abandonnées', pomodoroFocusTime: 'Temps de focus total',
    pomodoroPeriodTotal: 'Cette période', pomodoroPeriodFocus: 'Focus cette période',
    pomodoroVsSinceLast: 'vs période précédente',
    pomodoroAllTime: 'Depuis le début',
    pomodoroInsightsDailyTitle: 'Focus quotidien cette semaine',
    pomodoroInsightsWeeklyBreakdownTitle: 'Moyennes hebdomadaires',
    pomodoroInsightsAvgWeekLabel: 'moy/jour (semaine)',
    pomodoroInsightsAvgPeriodLabel: 'moy/jour (période)',
    pomodoroInsightsPerDaySuffix: '/j',
    pomodoroInsightsNoWeeklyData: 'Pas encore de données hebdomadaires.',
    pomodoroInsightsDayLabels: ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
    pomodoroTotalTimeLabel: 'temps total',
    pomodoroClose: 'Fermer',
    pomodoroEraseStats: 'Effacer les stats',
    pomodoroEraseStatsTitle: 'Effacer les stats Pomodoro ?',
    pomodoroEraseStatsDesc: 'Les stats historiques de temps de focus seront supprimées, mais les tomates restent disponibles.',
    pomodoroGraceCancel: 'Annuler (pas de tomate)',
    pomodoroGrace: s => `${s}s pour annuler sans perdre une tomate`,
    workModeLabel: 'Mode travail',
    workModeDesc: 'Masque les notes et renomme les matières en groupes.',
    workModeOnboarding: 'Utiliser ceci pour le travail ?',
    semesterModeLabel: 'Mode sans semestre',
    semesterModeDesc: 'Activez pour utiliser de simples semaines annuelles au lieu des semestres. Les notes sont masquées.',
    semesterModeNone: 'Sans semestres (semaines annuelles)',
    semesterModeSemesters: 'Avec semestres',
    semesterModeOnboarding: 'Sans semestres, juste des semaines ?',
    groups: 'Groupes', group: 'Groupe', addAGroup: 'Ajouter un groupe', groupName: 'Nom du groupe',
    deleteGroupTitle: 'Supprimer le groupe ?', deleteGroupDesc: 'Cela supprimera aussi toutes les tâches de ce groupe.',
    storageWarningTitle: 'Limite de stockage atteinte',
    storageWarningDesc: 'Veuillez activer la sync Firebase, stockage local maximal atteint.',
    storageWarningAction: 'Compris',
    collabConnect: 'Connecter Organizer Collab',
    collabDisconnect: 'Déconnecter Organizer Collab',
    collabRequiresFirebase: 'Connectez d\'abord la sync Firebase pour utiliser Organizer Collab.',
    collabGuideTitle: 'Configuration Organizer Collab',
    collabGuideIntro: 'Configuration unique. Faites ces 4 étapes dans Firebase, puis revenez activer la collab.',
    collabGuideImportantTitle: 'Ce qui change quand la collab est activée',
    collabGuideImportant1: 'Votre base commence à exiger des utilisateurs authentifiés (l\'auth anonyme suffit).',
    collabGuideImportant2: 'La sync normale continue de fonctionner, mais doit d\'abord s\'authentifier.',
    collabGuideImportant3: 'Si la collab est désactivée plus tard, les règles basées sur l\'auth restent utilisables en toute sécurité.',
    collabGuideStep1: 'Ouvrez Firebase Console > Build > Firestore Database > Règles.',
    collabGuideStep2: 'Collez l\'extrait de règles ci-dessous et cliquez sur Publier.',
    collabGuideStep3: 'Ouvrez Security > Authentication > Méthode de connexion > activez Anonyme > Enregistrer.',
    collabGuideStep4: 'Revenez à Organizer et appuyez sur « J\'ai configuré les règles, activer la collab ».',
    collabGuideRulesLabel: 'Règles Firestore',
    collabGuideTroubleshootTitle: 'Si vous voyez une erreur signUp 400',
    collabGuideTroubleshootBody: 'Cela signifie que l\'authentification anonyme est encore désactivée dans Firebase. Activez-la dans Security > Authentication > Méthode de connexion.',
    collabEnableNow: 'J\'ai configuré les règles, activer la collab',
    collabPanelTitle: 'Organizer Collab',
    collabPanelSubtitle: 'Créez des équipes, invitez des personnes et partagez tâches/cartes kanban.',
    collabCreateTeam: 'Créer une équipe',
    collabTeamName: 'Nom de l\'équipe',
    collabTeamDays: 'jours de l\'équipe',
    collabTeamDuration: 'durée de l\'équipe',
    collabDays: 'jours',
    collabJoinTeam: 'Rejoindre une équipe',
    collabInvitePlaceholder: 'Coller le lien d\'invitation',
    collabInviteTtl: 'Validité de l\'invitation',
    collabYourTeams: 'Vos équipes',
    collabNoTeams: 'Aucune équipe pour le moment.',
    collabRoleHost: 'hôte',
    collabRoleMember: 'membre',
    collabEndsAt: 'se termine',
    collabInvite: 'Inviter',
    collabEditTeam: 'Modifier l\'équipe',
    collabTaskCompletionMode: 'Achèvement des tâches partagées',
    collabTaskCompletionPersonal: 'achèvement personnel',
    collabTaskCompletionForAll: 'basculer pour tous',
    collabTaskPermissions: 'Permissions de modification des tâches',
    collabTaskPermissionsEveryone: 'tout le monde peut ajouter/modifier/supprimer des tâches',
    collabTaskPermissionsHostOnly: 'seul l\'hôte peut ajouter/modifier/supprimer des tâches',
    collabLeave: 'Quitter',
    collabDeleteTeam: 'Supprimer',
    collabDefaultTeamName: 'Équipe',
    collabLeavePrompt: 'Quitter cette équipe ?',
    collabLeaveWithLocalPrompt: 'Vous avez partagé des tâches locales dans cette équipe. Les garder localement ?',
    collabDeleteTeamPrompt: 'Supprimer cette équipe ?',
    collabDeleteTeamWithLocalPrompt: 'Vous avez partagé des tâches locales dans cette équipe. Les garder localement avant de supprimer l\'équipe ?',
    collabKeepLocalTasks: 'Garder les tâches locales',
    collabDeleteLocalTasksToo: 'Supprimer les tâches locales',
    collabErrorCreate: 'Impossible de créer l\'équipe.',
    collabErrorInvite: 'Impossible de générer l\'invitation.',
    collabErrorJoin: 'Impossible de rejoindre l\'équipe.',
    collabErrorInvalidLink: 'Lien d\'invitation invalide.',
    collabErrorDeleteTeam: 'Impossible de supprimer l\'équipe.',
    collabGuideChecklistTitle: 'Toujours pas de synchronisation ?',
    collabGuideChecklistBody: 'Les deux étapes qu\'Organizer ne peut pas faire à votre place : activer l\'authentification anonyme et publier les règles Firestore ci-dessus. Si les tâches partagées n\'apparaissent jamais, l\'une d\'elles manque sur le projet de l\'hôte.',
    collabSyncErrorHint: 'Impossible de joindre cette équipe. Vérifiez que le Firebase de l\'hôte a l\'authentification anonyme activée et des règles ouvertes.',
    collabKeyRequiredHint: "Cette équipe est chiffrée et votre lien d’invitation ne contenait aucune clé. Demandez un nouveau lien d’invitation.",
    collabErrorPermission: 'Bloqué par les règles Firebase. L\'hôte doit activer l\'authentification anonyme et ouvrir les règles Firestore.',
    collabErrorNotFound: 'Équipe introuvable. Elle a peut-être été supprimée.',
    collabErrorInviteExpired: 'Cette invitation a expiré. Demandez un nouveau lien à l\'hôte.',
    collabErrorInviteInvalid: 'Ce lien d\'invitation n\'est pas valide pour cette équipe.',

    nlpToday: ["today"],
    nlpTomorrow: ["tomorrow"],
    nlpNextWeek: ["next week"],
    nlpAt: ["at"],
    nlpDow: [["sunday","sun"],["monday","mon"],["tuesday","tue"],["wednesday","wed"],["thursday","thu"],["friday","fri"],["saturday","sat"]],
    voiceInputAria: "Dictate by voice",
    voiceInputStopAria: "Stop dictation",
    quickActionTaskWordsPlural: ['tâches'],
    quickActionEventWordsPlural: ['événements du calendrier', 'événements'],
    quickActionCardWordsPlural: ['cartes kanban', 'cartes'],
    quickActionRespectivelyWords: ['respectivement'],
    quickActionOrdinalWords: ['premier', 'deuxième', 'troisième', 'quatrième', 'cinquième', 'sixième', 'septième', 'huitième', 'neuvième', 'dixième', 'première'],
    eventAllDay: "All day",
    eventStartTime: "Start time",
    eventEndTime: "End time",
    viewDay: "Jour",
    viewWeek: "Semaine",
    viewMonth: "Mois",
    viewYear: "Année",
    notesMentionNoResults: "No matching tasks",
    notesMentionDeletedTask: "Deleted task",
    notesArchive: "Archive",
    notesUnarchive: "Unarchive",
    notesArchived: "Archived",
    notesArchivedEmpty: "No archived notes.",
    eisenhower: "Matrice d'Eisenhower",
    eisenhowerEnable: "Activer la matrice d'Eisenhower",
    eisenhowerEnableDesc: "Ajoute un onglet pour trier les tâches par urgence et importance.",
    eisenhowerDoNow: "Urgent et important",
    eisenhowerSchedule: "Important, pas urgent",
    eisenhowerDelegate: "Urgent, pas important",
    eisenhowerEliminate: "Ni l'un ni l'autre",
    eisenhowerUnsorted: "Tâches non triées",
    eisenhowerUnsortedEmpty: "Rien à trier.",
    eisenhowerEmpty: "Glissez des tâches ici.",
    pomodoro: "Pomodoro",
    pomodoroOverlayFocusing: "concentration",
    pomodoroStreakTitle: "Série",
    pomodoroCurrentStreak: "Série en cours",
    pomodoroBestStreak: "Meilleure série",
    pomodoroStreakDaySuffix: "j",
    pomodoroTrendTitle: "Tendance mensuelle",
    pomodoroTrendNoData: "Pas encore de données mensuelles.",
    pomodoroCopySummary: "Copier le résumé",
    pomodoroCopiedSummary: "Copié !",
    firebaseRulesTemplateLink: "View Firestore rules template",
    firebaseOpenRulesWarningTitle: "Your database rules may be open",
    firebaseOpenRulesWarningDesc: "Sync is working without authentication, which usually means your Firestore rules allow anyone to read and write your data. Publish the rules template linked below to lock this down.",
    firebaseEncryptionOffTitle: "End-to-end encryption is off",
    firebaseEncryptionOffDesc: "Your data is stored in Firestore as plain text. Turn on encryption so only devices with your key can read it — even if your database rules are ever misconfigured.",
    firebaseEncryptNow: "Encrypt now",
    firebaseEncryptMigrateFailed: "Could not enable encryption. Check your connection and try again.",
    firebaseHaveKeyAlready: "This device already has a key from another install",
    firebaseKeyPastePlaceholder: "Paste your recovery key",
    firebaseKeyInvalid: "That does not look like a valid key.",
    firebaseKeyWrongOrUnreadable: "Could not decrypt with this key. Double check it and try again.",
    firebaseRecoveryKeyShownOnceTitle: "Save this recovery key now",
    firebaseRecoveryKeyShownOnceDesc: "This key is shown only once and is never sent to Firebase. Anyone with it can read your data; anyone without it (including you) cannot recover it if lost. Store it somewhere safe.",
    firebaseKeySavedItConfirm: "I've saved my key",
    firebaseEncryptionOnTitle: "End-to-end encryption is on",
    firebaseEncryptionOnDesc: "Vos données sont chiffrées sur cet appareil, dans le stockage local et avant d’atteindre Firestore. Seuls les appareils disposant de la clé de récupération peuvent les déchiffrer.",
    firebaseShowRecoveryKey: "Show recovery key",
    firebaseShowRecoveryKeyConfirmTitle: "Show recovery key?",
    firebaseShowRecoveryKeyConfirmDesc: "Anyone who sees this key can decrypt your data. Only do this somewhere private.",
    firebaseKeyRequiredTitle: "Encryption key needed",
    firebaseKeyRequiredDesc: "This project’s data is encrypted. Paste the recovery key from a device that already has it to unlock sync on this device.",
    firebaseKeyRequiredForImport: "This backup is encrypted. Set up sync with the matching key first, then import again.",
    exportEncrypted: "Organizer format (encrypted)",
    encUnlockTitle: "Déverrouiller vos données",
    encUnlockDesc: "Cet appareil contient des données chiffrées. Saisissez votre phrase secrète pour les déverrouiller.",
    encUnlockHintLabel: "Votre indice",
    encPassphraseLabel: "Phrase secrète",
    encPassphrasePlaceholder: "Votre phrase secrète",
    encPassphraseConfirmLabel: "Confirmer la phrase secrète",
    encPassphraseMismatch: "Les deux phrases secrètes ne correspondent pas.",
    encPassphraseTooShort: "Utilisez au moins 8 caractères.",
    encHintLabel: "Indice de la phrase secrète (facultatif)",
    encHintPlaceholder: "Un rappel privé, pas la phrase secrète elle-même",
    encRecoveryCodeTitle: "Enregistrez votre code de récupération",
    encRecoveryCodeDesc: "Ces 12 mots anglais sont le seul moyen de revenir si vous oubliez votre phrase secrète. Notez-les ou conservez-les dans un gestionnaire de mots de passe. Nous ne pourrons pas les réafficher.",
    encRecoveryCodeWordsNote: "12 mots anglais. Copiez-les exactement, dans l'ordre.",
    encRecoveryCodeSavedConfirm: "J'ai enregistré mon code de récupération",
    encRecoveryCodeQr: "Afficher le QR code",
    encRecoveryCodeQrDesc: "Scannez-le sur un autre appareil pour transférer le code de récupération.",
    encUseRecoveryCode: "Utiliser le code de récupération",
    encUsePassphrase: "Utiliser la phrase secrète",
    encRecoveryCodeLabel: "Code de récupération",
    encRecoveryCodePlaceholder: "douze mots séparés par des espaces",
    encRecoveryCodeInvalid: "Ce n'est pas un code de récupération valide de 12 mots.",
    encUnlockFailed: "Impossible de déverrouiller avec ceci. Vérifiez et réessayez.",
    encUnlocking: "Déverrouillage…",
    encDeriving: "Dérivation de la clé…",
    encEnableTitle: "Activer le chiffrement de bout en bout",
    encEnableDesc: "Vos données sont chiffrées sur cet appareil avant d'atteindre Firestore. Seuls les appareils disposant de votre phrase secrète ou de votre code de récupération peuvent les lire.",
    encEnableWarning: "Si vous perdez à la fois votre phrase secrète et votre code de récupération, personne ne pourra récupérer vos données, nous y compris.",
    encEnableSubmit: "Activer le chiffrement",
    encEnableFailed: "Impossible d'activer le chiffrement. Vérifiez votre connexion et réessayez.",
    encManageTitle: "Chiffrement",
    encManageDesc: "Vos données sont chiffrées de bout en bout. Le déverrouillage a lieu uniquement sur cet appareil.",
    encChangePassphrase: "Changer la phrase secrète",
    encChangePassphraseDesc: "Saisissez votre phrase secrète actuelle, puis la nouvelle.",
    encCurrentPassphraseLabel: "Phrase secrète actuelle",
    encRegenerateRecoveryCode: "Générer un nouveau code de récupération",
    encRegenerateRecoveryCodeDesc: "Remplace votre code existant. L'ancien cesse de fonctionner.",
    encEditHint: "Modifier l'indice",
    encRotateDekTitle: "Faire tourner la clé de chiffrement",
    encRotateDekDesc: "Rechiffre toutes vos données avec une clé entièrement nouvelle. Les autres appareils devront se déverrouiller à nouveau.",
    encRotateDekWarning: "Ne fermez pas l'app avant la fin de l'opération.",
    encRotating: "Rechiffrement…",
    encRotateFailed: "Impossible de faire tourner la clé. Rien n'a été modifié.",
    encSaved: "Enregistré.",
    encStoreUnavailableTitle: "Stockage sécurisé inaccessible",
    encStoreUnavailableDesc: "Ce navigateur a bloqué le coffre de clés, ce qui arrive souvent en navigation privée. Vos données chiffrées sont restées intactes. Essayez dans une fenêtre normale.",
    encPlaintextSyncWarnTitle: "La synchronisation n'est pas chiffrée",
    encPlaintextSyncWarnDesc: "Vos données sont stockées dans Firestore en clair. Quiconque peut lire votre base de données peut les lire.",
    encPlaintextSyncEnable: "Activer le chiffrement",
    encPlaintextSyncDismiss: "Pas maintenant, ne plus demander",
    encRemoteAlreadyEncrypted: "Ce projet est déjà chiffré. Déverrouillez-le pour connecter cet appareil.",
    encRemoteNotEncryptedTitle: "Chiffrer ce projet ?",
    encRemoteNotEncryptedDesc: "Ce projet contient des données non chiffrées. Activez le chiffrement maintenant et elles seront réenvoyées chiffrées.",
    encRemoteNotEncryptedMigrate: "Chiffrer et migrer",
    encRemoteNotEncryptedSkip: "Le laisser non chiffré",
    encRemoteUnrecoverable: "Ce projet est chiffré mais n'a aucune donnée de récupération : il ne peut pas être déverrouillé. Déconnectez-vous et démarrez un nouveau projet.",
    encRemoteDekMismatch: "Ce projet a été rechiffré avec une nouvelle clé. Déverrouillez-le à nouveau avec votre phrase secrète ou votre code de récupération.",
    encExportPassphraseTitle: "Protéger cette sauvegarde",
    encExportPassphraseDesc: "Choisissez une phrase secrète pour le fichier. Vous en aurez besoin pour restaurer, sur n'importe quel appareil.",
    encImportPassphraseTitle: "Déverrouiller cette sauvegarde",
    encImportPassphraseDesc: "Saisissez la phrase secrète choisie lors de l'export.",
    encImportPassphraseFailed: "Phrase secrète incorrecte pour cette sauvegarde.",
    encTitle: "Chiffrement",
    encOffTitle: "Le chiffrement est désactivé",
    encOffDesc: "Vos données sont stockées en clair partout où elles se trouvent. Activez le chiffrement et elles deviennent illisibles sans votre phrase secrète, sur cet appareil comme partout où elles se synchronisent.",
    encOnDesc: "Vos données sont chiffrées avant d'être stockées ou synchronisées. Seuls les appareils disposant de votre phrase secrète ou de votre code de récupération peuvent les lire.",
    encLockedDesc: "Vos données stockées sont chiffrées. Saisissez votre phrase secrète pour les déverrouiller sur cet appareil.",
    encEnableAction: "Activer le chiffrement",
    encDisableAction: "Désactiver le chiffrement",
    encDisableTitle: "Désactiver le chiffrement ?",
    encDisableDesc: "Vos données seront réécrites en clair partout où elles sont stockées, et votre phrase secrète et votre code de récupération cesseront de fonctionner.",
    encStorageShedTitle: "Certaines données n'ont pas tenu",
    encStorageShedDesc: "Cet appareil a manqué de stockage local, donc ceci n'a pas été enregistré localement :",
    exportPlaintext: "Human-readable (plaintext JSON)",
    repeat: "Répéter",
    repeatFreqLabel: "Fréquence",
    repeatFreqDaily: "Quotidien",
    repeatFreqWeekly: "Hebdomadaire",
    repeatFreqMonthly: "Mensuel",
    repeatEvery: freq => (freq === 'weekly' ? 'Toutes les' : 'Tous les'),
    repeatIntervalDaily: n => (n === 1 ? 'jour' : 'jours'),
    repeatIntervalWeekly: n => (n === 1 ? 'semaine' : 'semaines'),
    repeatIntervalMonthly: n => (n === 1 ? 'mois' : 'mois'),
    repeatUntil: "Jusqu'au (facultatif)",
    kanbanColTodo: "À faire", kanbanColInProgress: "En cours", kanbanColDone: "Terminé",
    colourCustom: "Couleur personnalisée",
    googleCalendar: "Google Calendar",
    gcalConnect: "Connect",
    gcalConnected: "Connected",
    gcalConnecting: "Connecting…",
    gcalDisconnect: "Disconnect",
    gcalEnable: "Sync with Google Calendar",
    gcalScopeNotice: "This grants full read/write access to your primary Google Calendar (the \"calendar\" scope). Organizer only reads and writes events you interact with here; your Google credentials never leave your device and are not sent anywhere but Google.",
    gcalStep1Title: "Create a Google Cloud project",
    gcalStep1Desc: "Go to console.cloud.google.com → create a new project (or pick one) → APIs & Services → enable the \"Google Calendar API\".",
    gcalStep2Title: "Configure OAuth consent + credentials",
    gcalStep2Desc: "APIs & Services → OAuth consent screen → set it up (External is fine for personal use, add yourself as a test user). Then Credentials → Create credentials → OAuth client ID → Application type: Web application → add this app's URL to Authorized JavaScript origins.",
    gcalStep3Title: "Paste your Client ID",
    gcalStep3Desc: "Copy the Client ID (ends in .apps.googleusercontent.com) shown after creating it, and paste it below. This value is not secret and is safe to store in this browser.",
    gcalClientIdPlaceholder: "xxxxxxxx.apps.googleusercontent.com",
    gcalClientIdInvalid: "Enter a valid OAuth Client ID.",
    gcalConnectFailed: "Could not connect. Check your Client ID and try again.",
    gcalDisableTitle: "Disconnect Google Calendar?",
    gcalDisableDesc: "Stops syncing with Google Calendar on this device. Events already created stay in both places; sync bookkeeping (Client ID, links) is removed here.",
    eventSyncToGoogle: "Sync to Google Calendar",
    eventSyncToGoogleDesc: "Push this event to your connected Google Calendar.",
    quickActionTaskWords: ["tâche","tache"],
    quickActionEventWords: ["événement du calendrier","evenement du calendrier","événement","evenement"],
    quickActionCardWords: ["carte kanban","carte"],
    quickActionAddWords: ["ajoute","ajouter","crée","cree","créer","creer"],
    quickActionForWords: ["pour","de"],
    quickActionAndWords: ["et"],
    quickActionOnWords: ["au","dans","le"],
    quickActionArticleWords: ["un","une","des","la","les","l'"],
    quickActionBoardWords: ["kanban","tableau"],
    quickAction: "Quick action",
    quickActionPlaceholder: "e.g. add task and calendar event for a cbd test on 18/07 at 15h",
    quickActionTab: "Quick action",
    quickActionFormTab: "Form",
    quickActionPreviewTitle: "Will create",
    quickActionPreviewTask: "task",
    quickActionPreviewTaskCalendar: "task (shown on calendar)",
    quickActionPreviewEvent: "calendar event",
    quickActionPreviewCard: column => `kanban card in ${column}`,
    quickActionEmpty: "Couldn't understand that. Try rephrasing.",
    quickActionCreate: "Create",
    quickActionBack: "Back",
    notesDeleteConfirmTitle: "Delete this note?",
    notesDeleteConfirmDesc: "This note will be permanently deleted.",
    notesEmptyTitle: "No notes yet",
    notesEmptyDesc: "Create your first note to get started.",
    notesFilterEmpty: "No notes match your search.",
    notesSelectNote: "Select a note to start editing",
    notesTextNote: "Text note",
    notesCanvasNote: "Canvas note",
    eventStartTimeFirstDay: "Heure de début (premier jour)",
    eventEndTimeLastDay: "Heure de fin (dernier jour)",
    notesBold: "Gras",
    notesItalic: "Italique",
    notesStrike: "Barré",
    notesHeading1: "Titre 1",
    notesHeading2: "Titre 2",
    notesHeading3: "Titre 3",
    notesBulletList: "Liste à puces",
    notesOrderedList: "Liste numérotée",
    notesTaskList: "Liste de contrôle",
    notesQuote: "Citation",
    notesInsertTable: "Insérer un tableau",
    notesCodeBlock: "Bloc de code",
    notesDivider: "Séparateur",
    notesAddLink: "Ajouter un lien",
    notesRemoveLink: "Supprimer le lien",
    notesTextColor: "Couleur du texte",
    notesColorReset: "Couleur par défaut",
    notesColorCustom: "Choisir une couleur",
    notesColorApply: "Appliquer",
    notesExport: "Exporter la note",
    notesImport: "Importer une note",
    notesGraphEdit: "Modifier le graphique",
    notesGraphRange: "x de",
    notesGraphResize: "Glissez pour redimensionner",
    notesGraphResizeWidth: "Glissez pour redimensionner largeur et hauteur",
    notesGraphInvalid: "Expression non traçable",
    notesGraphAlignleft: "Aligner à gauche",
    notesGraphAligncenter: "Centrer",
    notesGraphAlignright: "Aligner à droite",
    notesTextSize: "Taille du texte",
    notesSizeNormal: "Normal",
    notesSizeSmall: "Petit",
    notesSizeLarge: "Grand",
    notesSizeHuge: "Très grand",
    notesUndo: "Annuler",
    notesRedo: "Rétablir",
    notesViewList: "Vue liste",
    notesViewMosaic: "Vue mosaïque",
    notesMathEnable: "Résolution mathématique",
    notesMathEnableDesc: "Tapez une équation terminée par = puis Entrée pour la résoudre. Utilisez x pour tracer un graphique.",
    notesMathSolve: "Résoudre en x",
    notesMathSolveDesc: "Transforme 3x = 3 en x = 1, y compris les inéquations et les équations du second degré.",
    notesMathSelection: "Tracer la sélection",
    notesMathSelectionDesc: "Sélectionnez une équation et appuyez sur Entrée pour la tracer.",
    notesMathSteps: "Afficher les étapes",
    notesMathStepsDesc: "Affiche chaque étape de la résolution au lieu du seul résultat.",
    eisenhowerAddTask: "Ajouter une tâche",
    eisenhowerCustomize: "Personnaliser les quadrants",
    eisenhowerResetDefaults: "Rétablir les valeurs par défaut",
    eisenhowerCleanDone: "Effacer les terminées",
    eisenhowerCleanDoneTitle: "Effacer les tâches terminées ?",
    eisenhowerCleanDoneDesc: "Retire les tâches terminées de la matrice. Elles restent dans votre liste de tâches.",
    quickActionApp: "Quick Action",
    quickActionAppEnable: "Enable Quick Action",
    quickActionAppEnableDesc: "Adds a spotlight overlay for quickly creating tasks, events, and cards.",
    quickActionTripleTapEnable: "Triple tap sur l'écran", quickActionTripleTapEnableDesc: "Touchez 3 fois n'importe où pour ouvrir Quick Action",
    quickActionShortcutEnable: "Keyboard shortcut",
    quickActionShortcutKey: "Shortcut",
    quickActionNavbarButton: "Show in navbar add menu",
    spotlightPlaceholder: "Quick action… (e.g. add task for exam on Monday)",
    themeColor: "Accent color",
    themeColorDesc: "Pick a color for buttons, links, and highlights.",
    themeColorReset: "Reset to default",
    themeFontColor: "Couleur de police", themeHighlightColor: "Couleur de surbrillance", themeBgColor: "Couleur de fond",
    defaultTabLabel: "Écran par défaut", defaultTabDesc: "Choisis l'onglet sur lequel l'app s'ouvre.",
    defaultTabLast: "Dernier utilisé",
    taskReminderOffsetsLabel: "Délais de rappel", taskReminderOffsetsDesc: "Combien de jours avant l'échéance te prévenir. S'applique à toutes les tâches avec une échéance.",
    taskReminderTimeLabel: "Heure du rappel", taskReminderTimeDesc: "Heure à laquelle les rappels anticipés se déclenchent.",
    taskReminderAddOffset: "Jours",
    taskReminderOffsetDays: n => (n === 0 ? "Le jour même" : n === 1 ? "1 jour avant" : `${n} jours avant`),
    taskReminderIn: n => (n === 0 ? "À rendre aujourd'hui" : n === 1 ? "À rendre demain" : `À rendre dans ${n} jours`),
    goals: "Objectifs", goalsEnable: "Activer les Objectifs", goalsEnableDesc: "Suis tes objectifs de long terme avec un bouton de pointage et un calendrier de séries.",
    goalsEmpty: "Pas encore d'objectifs. Ajoutes-en un pour commencer.",
    goalAdd: "Ajouter un objectif", goalEdit: "Modifier l'objectif",
    goalTitleLabel: "Objectif", goalTitlePlaceholder: "Lire 20 minutes",
    goalCadenceLabel: "Pointer", goalCadenceDesc: "À quelle fréquence tu veux cliquer sur le bouton.",
    goalCadenceDaily: "Chaque jour", goalCadence2Days: "Tous les 2 jours", goalCadence3Days: "Tous les 3 jours",
    goalCadenceWeekly: "Chaque semaine", goalCadenceMonthly: "Chaque mois",
    goalRequireNote: "Demander une note", goalRequireNoteDesc: "Écris une courte note à chaque pointage.",
    goalColor: "Couleur",
    goalClickPrompt: "Marquer comme fait", goalDoneForNow: "Fait",
    goalNotePrompt: "Ça s'est passé comment ?", goalNotePlaceholder: "Quelques mots",
    goalSeeProgress: "Voir la progression", goalUndoToday: "Annuler ce pointage", goalDelete: "Supprimer l'objectif",
    goalDeleteTitle: "Supprimer cet objectif ?", goalDeleteDesc: "L'objectif et tout son historique seront supprimés.",
    goalCurrentStreak: "Série en cours", goalBestStreak: "Meilleure série",
    goalTotalCheckIns: "Pointages", goalCompletionRate: "Réussite",
    goalNotesTitle: "Notes",
    goalCadenceCustom: "Jours choisis", goalWeekdaysLabel: "Jours de la semaine", goalWeekdaysDesc: "Choisis les jours où tu veux pointer.", goalRestDay: "Jour de repos",
    goalToneLabel: "Style d'encouragement", goalToneDesc: "Le type de message reçu après chaque pointage.",
    goalTonePurpose: "Sens et progression", goalToneWarm: "Chaleureux et motivant",
    goalToneUpbeat: "Enjoué et satisfaisant", goalToneGame: "Jeu vidéo",
    goalToneRandom: "Aléatoire à chaque fois", goalToneCustom: "Mon propre message",
    goalToneCustomPlaceholder: "Ton message",
    goalTargetLabel: "Ligne d'arrivée", goalTargetDesc: "Quand cet objectif est considéré comme terminé.",
    goalTargetEndless: "Continuer indéfiniment", goalTargetCount: "Après un nombre de pointages", goalTargetDate: "Avant une date",
    goalTargetCountPlaceholder: "Pointages",
    goalTargetReached: "Objectif atteint.",
    goalTargetRemaining: n => (n === 1 ? "Encore 1 pointage" : `Encore ${n} pointages`),
    goalTargetDaysLeft: n => (n === 0 ? "Dernier jour" : n === 1 ? "1 jour restant" : `${n} jours restants`),
    goalMessages: {
      purpose: {
        day1: "Première entrée enregistrée. Le voyage commence.",
        early: "La régularité s'accumule jour après jour.",
        week: "7 jours d'affilée à avancer.",
        month: "30 jours consécutifs accomplis.",
        daily: "Un jour de plus vers ton objectif de long terme.",
        rescue: "De retour sur la bonne voie aujourd'hui.",
      },
      warm: {
        day1: "Tu as fait le pas le plus dur. Fier de toi.",
        early: "Tu prouves que tu peux te faire confiance.",
        week: "Une semaine entière ! Regarde le chemin parcouru.",
        month: "30 jours de constance. Tu as bâti une vraie habitude.",
        daily: "Encore un pas solide aujourd'hui.",
        rescue: "Content de te revoir. Chaque jour est une nouvelle chance.",
      },
      upbeat: {
        day1: "Quel excellent départ !",
        early: "Encore une belle journée de plus !",
        week: "7 jours d'affilée ! Travail formidable.",
        month: "30 jours ! C'est une étape énorme.",
        daily: "Coché ! Ça fait du bien.",
        rescue: "Content de te revoir ! On continue.",
      },
      game: {
        day1: "Quête lancée : niveau 1 terminé.",
        early: "Combo actif. XP gagnée.",
        week: "Succès débloqué : Guerrier de la première semaine.",
        month: "Étape majeure : boss vaincu.",
        daily: "Quête quotidienne terminée +100 XP.",
        rescue: "Réapparition. Reprenons la série.",
      },
    },
}
