export const fr = {
    tasks: 'Tâches', kanban: 'Kanban', grades: 'Évaluations', calendar: 'Calendrier', focus: 'Focus', settings: 'Réglages',
    noSemester: 'Aucun semestre configuré', goToSettings: 'Allez dans Réglages pour commencer.',
    weekLabel: w => `Semaine ${w}`, done: 'terminées', timeToRelax: 'Temps de repos !',
    addTask: 'Nouvelle tâche', task: 'Tâche', class: 'Matière', priority: 'Priorité',
    editTask: 'Modifier la tâche', moveLeft: 'Déplacer à gauche', moveRight: 'Déplacer à droite', markDone: 'Marquer comme fait',
    addToKanban: 'Ajouter au Kanban', themeLight: 'Thème clair', themeDark: 'Thème sombre', themeSystem: 'Thème système',
    addPartTitle: 'Ajouter une partie',
    fromWeek: 'De la semaine', toWeek: "Jusqu'à la semaine", dueDate: "Date d'échéance",
    other: 'Autre', noTasks: 'Aucune tâche cette semaine.',
    whatNeedsDone: "Qu'y a-t-il à faire ?",
    addTaskBtn: 'Ajouter la tâche', showOnCalendar: 'Afficher sur le calendrier', showOnTasks: 'Afficher dans les tâches',
    clearDone: 'Effacer les terminées', wipeAll: 'Tout effacer',
    addCard: 'Ajouter une carte', addCardPlaceholder: 'Titre de la carte',
    save: 'Enregistrer', cancel: 'Annuler', confirm: 'Confirmer', delete: 'Supprimer',
    addEvent: 'Ajouter un événement', newEvent: 'Nouvel événement', editEvent: "Modifier l'événement",
    eventTitle: "Titre de l'événement", eventDate: 'Date', eventRange: 'Plage de dates',
    eventMultiDay: 'Plusieurs jours', eventColor: 'Couleur', eventNote: 'Note',
    eventNotePlaceholder: 'Note facultative', more: 'plus',
    navbar: 'Barre de navigation', navHide: 'Masquer', navOverflow: 'Déplacer vers le menu', navAddButton: "Afficher le bouton d'ajout",
    navMore: 'Plus', navLabelMode: 'Afficher', navLabelBoth: 'Icônes + noms', navLabelIcons: 'Icônes seules', navLabelNames: 'Noms seuls',
    add: 'Ajouter', navAddLabel: 'Ajouter', navDrag: 'Glisser pour réorganiser',
    appDisableTitle: 'Désactiver et effacer les données ?', appDisableDesc: 'Désactiver cette app supprime définitivement toutes ses données.',
    collabDisableDesc: 'La déconnexion quitte toutes les équipes et supprime définitivement les données de collaboration de cet appareil.',
    navAddAction: "Action du bouton d'ajout", navAddPicker: 'Demander à chaque fois',
    navFolders: 'Dossiers', navNewFolder: 'Nouveau dossier',
    navMobilePosition: 'Position de la barre mobile', navPosBottom: 'Barre en bas', navPosSide: 'Barre latérale',
    addToTasks: 'Ajouter aux tâches', inTasks: 'Dans les tâches',
    standby: 'Veille', standbyEnable: 'Activer la veille paysage',
    standbyDesc: 'Mettez votre téléphone en paysage pour afficher un tableau de bord ambiant.',
    standbyLeft: 'Volet gauche', standbyCenter: 'Volet central', standbyRight: 'Volet droit',
    standbyPanels: 'Volets', standbyPane: n => `Volet ${n}`,
    standbyPaneSecond: 'Deuxième carte (glisser)', standbyPaneNone: 'Aucune',
    paneWheel: 'Roue de progression', paneWheelTime: 'Roue + horloge', paneCalendar: 'Calendrier',
    paneFocus: 'Focus', paneKanban: 'Kanban', paneTasksByCategory: 'Tâches par catégorie',
    notesLastEdit: 'Modifié', notesFolder: 'Dossier', notesNoFolder: 'Sans dossier', notesNewFolder: 'Nouveau dossier',
    notesFolderName: 'Nom du dossier', notesRenameFolder: 'Renommer le dossier', notesDeleteFolder: 'Supprimer le dossier', notesMoveTo: 'Déplacer vers',
    notesEdit: 'Modifier', notesPreview: 'Aperçu', notesBack: 'Retour',
    apps: 'Apps', appsSearch: 'Rechercher des apps', appsNoResults: 'Aucune app trouvée.', notes: 'Notes',
    notesEnable: 'Activer les Notes', notesEnableDesc: 'Ajoute un onglet Notes pour des notes rapides.',
    notesNew: 'Nouvelle note', notesTitle: 'Titre', notesBody: 'Écrivez quelque chose…', notesSearch: 'Rechercher des notes',
    notesEmpty: 'Aucune note pour le moment.', notesFavorite: 'Favori', notesText: 'Texte', notesCanvas: 'Écriture manuscrite',
    notesCanvasWarning: 'Les notes avec dessins peuvent occuper beaucoup d\'espace et ne sont donc disponibles qu\'avec Firebase activé.',
    collabApp: 'Collaboration',
    eiCalendar: 'Calendrier EI', eiCalendarEnable: 'Afficher le calendrier EI',
    eiCalendarEnableDesc: "Ajoute le calendrier officiel du cursus EI pour votre année, en lecture seule et toujours à jour.",
    eiCalendarDisableTitle: 'Masquer le calendrier EI ?', eiCalendarDisableDesc: "Cesse d'afficher les événements du calendrier EI. Rien n'est supprimé et vous pouvez le réactiver à tout moment.",
    semester: 'Semestre', classes: 'Matières', gradeComponents: 'Composantes de note',
    kanbanColumns: 'Colonnes Kanban', general: 'Général', data: 'Données et sync',
    holidays: 'Vacances',
    exportJson: 'Exporter JSON', importJson: 'Importer JSON',
    semesterAvg: 'Moyenne du semestre', ectsPassedLabel: 'ECTS validés',
    targetGrade: 'Note visée',
    previousSemesters: 'Semestres précédents',
    courseAvg: 'Moyenne du cours', finalGrade: 'Note finale', previousAvg: 'Moyenne précédente', numSemesters: 'Nb de semestres',
    getStarted: 'Commencer', welcomeTitle: 'Bienvenue sur organizer',
    welcomeDesc: 'Votre espace pour le travail universitaire. Configurez votre semestre et organisez-vous.',
    step1: 'Définir les dates du semestre', step2: 'Ajouter vos matières', step3: 'Planifier les tâches et suivre les notes',
    obNext: 'Suivant', obBack: 'Retour', obFinish: 'Terminer', obSkip: 'Passer',
    obWelcomeTitle: 'Bienvenue sur Organizer', obWelcomeDesc: 'Votre espace calme pour le travail universitaire. Choisissez votre langue et votre thème pour commencer.',
    obModeTitle: 'Comment allez-vous l\'utiliser ?', obModeDesc: 'Activez ce qui vous convient. Les deux peuvent être actifs.',
    obModeWorkToggle: 'Mode travail', obModeWorkToggleDesc: 'Groupes au lieu de matières, sans notes.',
    obModeWeeksToggle: 'Sans semestres', obModeWeeksToggleDesc: 'Organiser par semaine calendaire plutôt que par semestre.',
    obImportOr: 'ou restaurer une sauvegarde',
    obDatesTitle: 'Votre semestre', obDatesDesc: 'Quand commence-t-il et se termine-t-il ?',
    obClassesTitle: 'Vos matières', obClassesDesc: 'Ajoutez les matières que vous suivez.',
    obGroupsTitle: 'Vos groupes', obGroupsDesc: 'Ajoutez les groupes avec lesquels vous travaillez.',
    obInfoTasksTitle: 'Tâches et Kanban', obInfoTasksDesc: 'Ajoutez des tâches par semaine ou par date, puis glissez-les sur votre tableau kanban.',
    obInfoCalTitle: 'Calendrier et Focus', obInfoCalDesc: 'Voyez tout sur le calendrier et lancez des sessions de focus pour avancer.',
    obInfoDoneTitle: 'Tout est prêt', obInfoDoneDesc: 'Vous pourrez modifier tout cela plus tard dans les réglages.',
    shareLink: 'Copier le lien de partage', qrCode: 'Code QR', linkCopied: 'Lien copié !',
    high: 'Haute', medium: 'Moyenne', low: 'Basse', none: 'Aucune',
    addSemester: 'Ajouter un semestre', semesterName: 'Nom du semestre', startDate: 'Date de début', endDate: 'Date de fin',
    weeks: n => `${n} semaines`, addAClass: 'Ajouter une matière', className: 'Nom de la matière', ects: 'ECTS', colour: 'Couleur',
    addComponent: 'Ajouter une composante', componentName: 'Nom de la composante',
    taskSpanLabel: 'Comportement des tâches sur plusieurs semaines', taskSpanDesc: 'Quand une tâche couvre plusieurs semaines, comment est-elle marquée comme faite ?',
    kanbanChecklistInlineLabel: 'Aperçu de la checklist Kanban',
    kanbanChecklistInlineDesc: 'Afficher les éléments de la checklist directement sur les cartes sans ouvrir les détails.',
    kanbanChecklistPreviewNone: 'Masquer sur les cartes',
    kanbanChecklistPreviewAll: 'Afficher sur toutes les cartes',
    kanbanChecklistPreviewPerCard: 'Au cas par cas',
    focusAlertModeLabel: 'Mode d\'alerte Focus',
    focusAlertModeDesc: 'Choisissez comment les alertes Focus sont délivrées au changement de phase.',
    focusAlertNone: 'Aucune',
    focusAlertVibration: 'Vibration',
    focusAlertNotification: 'Notification',
    focusAlertBoth: 'Les deux',
    taskAlertModeLabel: 'Alertes d\'échéance des tâches',
    taskAlertModeDesc: 'Choisissez comment les alertes d\'échéance sont délivrées.',
    taskAlertNone: 'Aucune',
    taskAlertInApp: 'Dans l\'app',
    taskAlertNotification: 'Notification',
    taskAlertBoth: 'Les deux',
    taskAlertNextDayTimeLabel: 'Heure de l\'alerte du lendemain',
    taskAlertNextDayTimeDesc: 'Heure des rappels pour les tâches dues demain.',
    taskDefaultToCalendarLabel: 'Tâches sur le calendrier par défaut',
    taskDefaultToCalendarDesc: 'Les nouvelles tâches auront « Afficher sur le calendrier » activé par défaut.',
    taskDueTodayTitle: count => count === 1 ? 'Tâche due aujourd\'hui' : `${count} tâches dues aujourd'hui`,
    taskAlertHide: 'Masquer l\'alerte',
    taskAlertRemindMeAt: 'Me rappeler à',
    settingEnabled: 'Activé', settingDisabled: 'Désactivé',
    spanSingle: 'Une seule case globale (fait une fois)', spanPerWeek: 'Case par semaine',
    dangerZone: 'Zone sensible', deleteSemester: 'Supprimer ce semestre',
    clearPomodoros: 'Effacer les pomodoros',
    clearPomodorosTitle: 'Effacer tous les pomodoros ?',
    clearPomodorosDesc: 'Tous les pomodoros tombés seront supprimés définitivement.',
    deleteSemesterTitle: 'Supprimer le semestre ?', deleteSemesterDesc: 'Toutes les tâches, notes et données kanban de ce semestre seront supprimées définitivement.',
    clearDoneTitle: 'Effacer la colonne Terminé ?', clearDoneDesc: 'Toutes les cartes de la colonne Terminé seront supprimées.',
    wipeAllTitle: 'Effacer toutes les cartes ?', wipeAllDesc: 'Toutes les cartes du tableau seront supprimées définitivement.',
    selectSemester: 'Sélectionner un semestre', noClassesYet: 'Aucune matière pour le moment', addClassesInSettings: 'Ajoutez des matières dans Réglages.',
    addUnlocks: 'Ajoutez un semestre pour débloquer le reste.',
    checklist: 'Checklist', addItem: 'Ajouter un élément', editCard: 'Modifier la carte',
    notAchievable: '— non atteignable', onRemaining: ' sur les évaluations restantes',
    youNeed: 'Il vous faut', allGraded: 'Toutes les composantes sont notées.',
    noGradeComponents: 'Aucune composante de note configurée. Allez dans Réglages.',
    deleteClassTitle: 'Supprimer la matière ?', deleteClassDesc: 'Cela supprimera aussi toutes les tâches de cette matière.',
    holidayName: 'Nom des vacances', holidayNamePlaceholder: 'ex : Vacances de Noël',
    addHoliday: 'Ajouter des vacances',
    loadPreset: 'Charger un préréglage',
    presetLoading: 'Chargement du préréglage…', presetError: 'Échec du chargement du préréglage.', retry: 'Réessayer', skip: 'Passer',
    newColumnName: 'Nom de la nouvelle colonne',
    focusStart: 'Démarrer', focusPause: 'Pause', focusResume: 'Reprendre', focusReset: 'Réinitialiser', focusSkipBreak: 'Passer la pause',
    focusReady: 'prêt', focusBreak: 'pause',
    focusPhrases: ['continuez', 'restez concentré', 'vous vous en sortez bien', 'un pas à la fois', 'travail profond', 'restez présent'],
    focusEvery: 'toutes les (min)', focusBreakFor: 'pause (min)',
    focusScheduledMode: 'Pauses programmées',
    focusNextBreak: 'Prochaine pause à',
    focusFocusLabel: 'Message de focus', focusBreakLabel: 'Message de pause',
    loadPresetTitle: 'Charger un préréglage',
    presetGroupEI: 'Cursus EI',
    presetGroupGeneric: 'Général',
    backToMenu: 'Retour',
    importData: 'Importer les données',
    importFromFirebase: 'Importer depuis Firebase',
    nextSemesterTitle: 'Semestre terminé',
    nextSemesterDesc: 'Votre semestre est terminé. Charger le suivant ?',
    loadNextSemester: 'Charger le prochain semestre',
    dismissNextSemester: 'Ignorer',
    noSemesterYet: 'Aucun semestre configuré',
    noSemesterDesc: 'Chargez un préréglage ou importez vos données pour commencer.',
    focusIntervalMode: 'Pauses par intervalle',
    focusIntervalEvery: 'toutes les (min)',
    focusIntervalBreakFor: 'pause (min)',
    focusScheduledBreakFor: 'pause (min)',
    focusAfterBreakReset: 'Après la pause : réinitialiser le minuteur',
    focusAfterBreakContinue: 'Après la pause : continuer à compter',
    firebaseSync: 'Sync Firebase',
    firebaseConnect: 'Connecter',
    firebaseConnected: 'Connecté',
    firebaseDisconnect: 'Déconnecter',
    firebaseSyncing: 'Synchronisation…',
    firebaseLastSync: 'Dernière sync',
    firebaseError: 'Erreur de sync',
    firebaseRemoteNewer: 'Les données cloud proviennent d\'une version plus récente. Sync en pause. Mettez à jour l\'app.',
    collabSyncFailed: 'Impossible de synchroniser le changement partagé. Il a été annulé.',
    newerVersionWarning: 'Vos données ont été enregistrées par une version plus récente. Certaines choses peuvent ne pas s\'afficher correctement avant la mise à jour.',
    firebaseSetupTitle: 'Connecter Firebase',
    firebaseStep1Title: 'Créer un projet Firebase',
    firebaseStep1Desc: 'Allez sur console.firebase.google.com → Ajouter un projet → donnez-lui un nom → désactivez Google Analytics → Créer le projet.',
    firebaseStep2Title: 'Activer Firestore',
    firebaseStep2Desc: 'Allez dans Build → Firestore Database → Créer une base → choisissez une région → Démarrer en mode production → Créer. Puis dans Règles, remplacez le contenu par : allow read, write: if true; et cliquez sur Publier.',
    firebaseStep3Title: 'Obtenir votre configuration',
    firebaseStep3Desc: 'Allez dans Paramètres du projet (icône engrenage) → Vos apps → Ajouter une app → Web → enregistrez l\'app → copiez l\'objet firebaseConfig affiché.',
    firebaseStep4Title: 'Coller votre configuration',
    firebaseStep4Desc: 'Collez l\'objet firebaseConfig complet (en JSON) ci-dessous.',
    firebaseConfigPlaceholder: '{ "apiKey": "...", "authDomain": "...", "projectId": "...", ... }',
    firebaseConfigInvalid: 'Config invalide : doit inclure apiKey et projectId.',
    firebaseTestFailed: 'Connexion impossible. Vérifiez votre config et les règles de la base.',
    firebaseSave: 'Enregistrer et connecter',
    pomodoroMode: 'Mode Pomodoro',
    pomodoroModeDesc: 'Faites pousser des tomates pendant les sessions de focus. Chaque session terminée dépose une tomate.',
    pomodoroResetPeriod: 'Période de réinitialisation',
    pomodoroResetDay: 'Quotidien', pomodoroResetWeek: 'Hebdomadaire', pomodoroResetMonth: 'Mensuel', pomodoroResetSemester: 'Par semestre',
    pomodoroTrackPeriodStats: 'Suivre les stats de période',
    pomodoroShowAbandoned: 'Afficher les tomates abandonnées',
    pomodoroShowPeriodPomodoros: 'Afficher les pomodoros de la période',
    pomodoroStatsTitle: 'Stats Pomodoro',
    pomodoroTotal: 'Total de tomates', pomodoroAbandoned: 'Abandonnées', pomodoroFocusTime: 'Temps de focus total',
    pomodoroPeriodTotal: 'Cette période', pomodoroPeriodFocus: 'Focus cette période',
    pomodoroVsSinceLast: 'vs période précédente',
    pomodoroAllTime: 'Depuis le début',
    pomodoroInsightsDailyTitle: 'Focus quotidien cette semaine',
    pomodoroInsightsWeeklyBreakdownTitle: 'Moyennes hebdomadaires',
    pomodoroInsightsAvgWeekLabel: 'moy/jour (semaine)',
    pomodoroInsightsAvgPeriodLabel: 'moy/jour (période)',
    pomodoroInsightsPerDaySuffix: '/j',
    pomodoroInsightsNoWeeklyData: 'Pas encore de données hebdomadaires.',
    pomodoroInsightsDayLabels: ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
    pomodoroTotalTimeLabel: 'temps total',
    pomodoroClose: 'Fermer',
    pomodoroEraseStats: 'Effacer les stats',
    pomodoroEraseStatsTitle: 'Effacer les stats Pomodoro ?',
    pomodoroEraseStatsDesc: 'Les stats historiques de temps de focus seront supprimées, mais les tomates restent disponibles.',
    pomodoroGraceCancel: 'Annuler (pas de tomate)',
    pomodoroGrace: s => `${s}s pour annuler sans perdre une tomate`,
    workModeLabel: 'Mode travail',
    workModeDesc: 'Masque les notes et renomme les matières en groupes.',
    workModeOnboarding: 'Utiliser ceci pour le travail ?',
    semesterModeLabel: 'Mode sans semestre',
    semesterModeDesc: 'Activez pour utiliser de simples semaines annuelles au lieu des semestres. Les notes sont masquées.',
    semesterModeNone: 'Sans semestres (semaines annuelles)',
    semesterModeSemesters: 'Avec semestres',
    semesterModeOnboarding: 'Sans semestres, juste des semaines ?',
    groups: 'Groupes', addAGroup: 'Ajouter un groupe', groupName: 'Nom du groupe',
    deleteGroupTitle: 'Supprimer le groupe ?', deleteGroupDesc: 'Cela supprimera aussi toutes les tâches de ce groupe.',
    storageWarningTitle: 'Limite de stockage atteinte',
    storageWarningDesc: 'Veuillez activer la sync Firebase, stockage local maximal atteint.',
    storageWarningAction: 'Compris',
    collabConnect: 'Connecter Organizer Collab',
    collabDisconnect: 'Déconnecter Organizer Collab',
    collabRequiresFirebase: 'Connectez d\'abord la sync Firebase pour utiliser Organizer Collab.',
    collabGuideTitle: 'Configuration Organizer Collab',
    collabGuideIntro: 'Configuration unique. Faites ces 4 étapes dans Firebase, puis revenez activer la collab.',
    collabGuideImportantTitle: 'Ce qui change quand la collab est activée',
    collabGuideImportant1: 'Votre base commence à exiger des utilisateurs authentifiés (l\'auth anonyme suffit).',
    collabGuideImportant2: 'La sync normale continue de fonctionner, mais doit d\'abord s\'authentifier.',
    collabGuideImportant3: 'Si la collab est désactivée plus tard, les règles basées sur l\'auth restent utilisables en toute sécurité.',
    collabGuideStep1: 'Ouvrez Firebase Console > Build > Firestore Database > Règles.',
    collabGuideStep2: 'Collez l\'extrait de règles ci-dessous et cliquez sur Publier.',
    collabGuideStep3: 'Ouvrez Security > Authentication > Méthode de connexion > activez Anonyme > Enregistrer.',
    collabGuideStep4: 'Revenez à Organizer et appuyez sur « J\'ai configuré les règles, activer la collab ».',
    collabGuideRulesLabel: 'Règles Firestore',
    collabGuideTroubleshootTitle: 'Si vous voyez une erreur signUp 400',
    collabGuideTroubleshootBody: 'Cela signifie que l\'authentification anonyme est encore désactivée dans Firebase. Activez-la dans Security > Authentication > Méthode de connexion.',
    collabEnableNow: 'J\'ai configuré les règles, activer la collab',
    collabPanelTitle: 'Organizer Collab',
    collabPanelSubtitle: 'Créez des équipes, invitez des personnes et partagez tâches/cartes kanban.',
    collabCreateTeam: 'Créer une équipe',
    collabTeamName: 'Nom de l\'équipe',
    collabTeamDays: 'jours de l\'équipe',
    collabTeamDuration: 'durée de l\'équipe',
    collabDays: 'jours',
    collabJoinTeam: 'Rejoindre une équipe',
    collabInvitePlaceholder: 'Coller le lien d\'invitation',
    collabInviteTtl: 'Validité de l\'invitation',
    collabYourTeams: 'Vos équipes',
    collabNoTeams: 'Aucune équipe pour le moment.',
    collabRoleHost: 'hôte',
    collabRoleMember: 'membre',
    collabEndsAt: 'se termine',
    collabInvite: 'Inviter',
    collabEditTeam: 'Modifier l\'équipe',
    collabTaskCompletionMode: 'Achèvement des tâches partagées',
    collabTaskCompletionPersonal: 'achèvement personnel',
    collabTaskCompletionForAll: 'basculer pour tous',
    collabTaskPermissions: 'Permissions de modification des tâches',
    collabTaskPermissionsEveryone: 'tout le monde peut ajouter/modifier/supprimer des tâches',
    collabTaskPermissionsHostOnly: 'seul l\'hôte peut ajouter/modifier/supprimer des tâches',
    collabLeave: 'Quitter',
    collabDeleteTeam: 'Supprimer',
    collabDefaultTeamName: 'Équipe',
    collabLeavePrompt: 'Quitter cette équipe ?',
    collabLeaveWithLocalPrompt: 'Vous avez partagé des tâches locales dans cette équipe. Les garder localement ?',
    collabDeleteTeamPrompt: 'Supprimer cette équipe ?',
    collabDeleteTeamWithLocalPrompt: 'Vous avez partagé des tâches locales dans cette équipe. Les garder localement avant de supprimer l\'équipe ?',
    collabKeepLocalTasks: 'Garder les tâches locales',
    collabDeleteLocalTasksToo: 'Supprimer les tâches locales',
    collabErrorCreate: 'Impossible de créer l\'équipe.',
    collabErrorInvite: 'Impossible de générer l\'invitation.',
    collabErrorJoin: 'Impossible de rejoindre l\'équipe.',
    collabErrorInvalidLink: 'Lien d\'invitation invalide.',
    collabErrorDeleteTeam: 'Impossible de supprimer l\'équipe.',
    collabGuideChecklistTitle: 'Toujours pas de synchronisation ?',
    collabGuideChecklistBody: 'Les deux étapes qu\'Organizer ne peut pas faire à votre place : activer l\'authentification anonyme et publier les règles Firestore ci-dessus. Si les tâches partagées n\'apparaissent jamais, l\'une d\'elles manque sur le projet de l\'hôte.',
    collabSyncErrorHint: 'Impossible de joindre cette équipe. Vérifiez que le Firebase de l\'hôte a l\'authentification anonyme activée et des règles ouvertes.',
    collabErrorPermission: 'Bloqué par les règles Firebase. L\'hôte doit activer l\'authentification anonyme et ouvrir les règles Firestore.',
    collabErrorNotFound: 'Équipe introuvable. Elle a peut-être été supprimée.',
    collabErrorInviteExpired: 'Cette invitation a expiré. Demandez un nouveau lien à l\'hôte.',
    collabErrorInviteInvalid: 'Ce lien d\'invitation n\'est pas valide pour cette équipe.',
}
