export const pirate = {
  months: ['Janufaárr', 'Februfaárr', 'March', 'April', 'May', 'June', 'July', 'August', 'Septembarr', 'Octobarr', 'Novembarr', 'Decembarr'],
  weekdaysShort: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
  weekdays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  tasks: 'Chores', kanban: 'Plank Board', grades: 'Booty', calendar: 'Almanac', focus: 'Steady Aim', settings: "Ship's Orders",
  guides: 'Charts',
  noSemester: 'No voyage charted', goToSettings: "Sail to Ship's Orders to begin.",
  weekLabel: w => `Fortnight ${w}`, done: 'plundered', timeToRelax: 'Time to swig some grog!',
  addTask: 'New chore', task: 'Chore', class: 'Crew', priority: 'Rank',
  editTask: 'Amend chore', moveLeft: 'Haul larboard', moveRight: 'Haul starboard', markDone: 'Mark plundered',
  addToKanban: 'Add to Plank Board', themeLight: 'Daylight colours', themeDark: 'Midnight colours', themeSystem: 'Ship colours',
  addPartTitle: 'Add a part',
  fromWeek: 'From fortnight', toWeek: 'To fortnight', dueDate: 'Reckoning day',
  other: 'Other', noTasks: 'No chores this fortnight, matey.',
  whatNeedsDone: 'What be needin doin?',
  addTaskBtn: 'Add chore', showOnCalendar: 'Show on almanac', showOnTasks: 'Show on chores',
  clearDone: 'Toss the plundered', wipeAll: 'Scuttle all',
  addCard: 'Add parchment', addCardPlaceholder: 'Parchment title',
  save: 'Stow', cancel: 'Belay', confirm: 'Aye', delete: 'Send to Davy Jones',
  addEvent: 'Add happenin', newEvent: 'New happenin', editEvent: 'Amend happenin',
  eventTitle: 'Happenin title', eventDate: 'Day', eventRange: 'Spell o days',
  eventMultiDay: 'Many a day', eventColor: 'Colour', eventNote: 'Scrawl',
  eventNotePlaceholder: 'Optional scrawl', more: 'more',
  navbar: 'Helm bar', navHide: 'Hide', navOverflow: 'Stow in the more chest', navAddButton: 'Show the add-chore button',
  navMore: 'More', navLabelMode: 'Show', navLabelBoth: 'Marks + names', navLabelIcons: 'Marks only', navLabelNames: 'Names only',
  add: 'Add', navAddLabel: 'Add', navDrag: 'Drag to reorder the ranks',
  appDisableTitle: 'Disable and scuttle the data?', appDisableDesc: 'Turnin this app off sends all its data to the depths forever.',
  collabDisableDesc: 'Disconnectin abandons all crews and sinks the crew-sharin data from this vessel forever.',
  navAddAction: 'Add button deed', navAddPicker: 'Ask each time',
  navFolders: 'Chests', navNewFolder: 'New chest',
  navMobilePosition: 'Spyglass helm position', navPosBottom: 'Bottom rail', navPosSide: 'Side rail',
  addToTasks: 'Add to chores', inTasks: 'In chores',
  standby: 'Anchored', standbyEnable: 'Enable landscape anchored watch',
  standbyDesc: 'Turn yer spyglass sideways to show an ambient watch board.',
  standbyLeft: 'Larboard pane', standbyCenter: 'Midships pane', standbyRight: 'Starboard pane',
  standbyPanels: 'Panes', standbyPane: n => `Pane ${n}`,
  standbyPaneSecond: 'Second parchment (swipe)', standbyPaneNone: 'None',
  paneWheel: 'Ship\'s wheel o progress', paneWheelTime: 'Wheel + bells', paneCalendar: 'Almanac',
  paneFocus: 'Steady Aim', paneKanban: 'Plank Board', paneTasksByCategory: 'Chores by crew',
  notesLastEdit: 'Scrawled', notesFolder: 'Chest', notesNoFolder: 'No chest', notesNewFolder: 'New chest',
  notesFolderName: 'Chest name', notesRenameFolder: 'Rename chest', notesDeleteFolder: 'Scuttle chest', notesMoveTo: 'Haul to',
  notesEdit: 'Amend', notesPreview: 'Peek', notesBack: 'Back',
  chunkLoadError: 'This here part be lost at sea.', chunkRetry: 'Hoist it again',
  apps: 'Riggin', appsSearch: 'Search riggin', appsNoResults: 'No riggin found, matey.', notes: 'Scrolls',
  notesEnable: 'Enable Scrolls', notesEnableDesc: 'Add a Scrolls tab for quick scrawls.',
  notesNew: 'New scroll', notesTitle: 'Title', notesBody: 'Scrawl somethin…', notesSearch: 'Search scrolls',
  notesEmpty: 'No scrolls yet, ye scallywag.', notesFavorite: 'Prized', notesText: 'Text', notesCanvas: 'Quill work',
  collabApp: 'Crewmates',
  eiCalendar: 'EI Almanac', eiCalendarEnable: 'Show EI almanac',
  eiCalendarEnableDesc: 'Adds the official EI course almanac fer yer year, read-only and always fresh as the tide.',
  eiCalendarDisableTitle: 'Hide EI almanac?', eiCalendarDisableDesc: 'Stops showin the EI almanac happenins. Nothin be scuttled and ye can hoist it again anytime.',
  semester: 'Voyage', classes: 'Crews', gradeComponents: 'Booty pieces',
  kanbanColumns: 'Plank Board columns', general: 'General', data: 'Data & sync',
  holidays: 'Shore leave',
  exportJson: 'Export JSON', importJson: 'Import JSON',
  semesterAvg: 'Voyage average', ectsPassedLabel: 'ECTS plundered',
  targetGrade: 'Aimed booty',
  previousSemesters: 'Past voyages',
  courseAvg: 'Course average', finalGrade: 'Final booty', previousAvg: 'Past average', numSemesters: 'No. o voyages',
  getStarted: 'Set sail', welcomeTitle: 'Welcome aboard organizer',
  welcomeDesc: 'Yer quarters fer uni work. Chart yer voyage and get shipshape.',
  step1: 'Set yer voyage dates', step2: 'Muster yer crews', step3: 'Chart chores & track booty',
  obNext: 'Onward', obBack: 'Back', obFinish: 'Weigh anchor', obSkip: 'Skip',
  obWelcomeTitle: 'Welcome aboard Organizer', obWelcomeDesc: 'Yer calm quarters fer uni work. Pick yer tongue and colours to start.',
  obModeTitle: 'How will ye use it?', obModeDesc: 'Toggle what fits ye. Both can be hoisted.',
  obModeWorkToggle: 'Work mode', obModeWorkToggleDesc: 'Bands instead o crews, no booty.',
  obModeWeeksToggle: 'No voyages', obModeWeeksToggleDesc: 'Organise by almanac fortnight instead o voyage.',
  obImportOr: 'or restore a stashed chest',
  obDatesTitle: 'Yer voyage', obDatesDesc: 'When does it set sail and make port?',
  obClassesTitle: 'Yer crews', obClassesDesc: 'Muster the crews ye be sailin with.',
  obGroupsTitle: 'Yer bands', obGroupsDesc: 'Muster the bands ye work with.',
  obInfoTasksTitle: 'Chores & Plank Board', obInfoTasksDesc: 'Add chores per fortnight or day, then drag em across yer plank board.',
  obInfoCalTitle: 'Almanac & Steady Aim', obInfoCalDesc: 'See it all on the almanac and run steady-aim watches to get things done.',
  obInfoDoneTitle: 'Ye be all set', obInfoDoneDesc: 'Ye can change any o this later in ship\'s orders.',
  shareLink: 'Copy the message-in-a-bottle', qrCode: 'QR Mark', linkCopied: 'Bottle cast off!',
  high: 'Cap\'n', medium: 'Bosun', low: 'Swabbie', none: 'None',
  addSemester: 'Add voyage', semesterName: 'Voyage name', startDate: 'Set-sail day', endDate: 'Make-port day',
  weeks: n => `${n} fortnights`, addAClass: 'Muster crew', className: 'Crew name', ects: 'ECTS', colour: 'Colour',
  addComponent: 'Add booty piece', componentName: 'Booty piece name',
  taskSpanLabel: 'Chore span behaviour', taskSpanDesc: 'When a chore spans many a fortnight, how be it marked plundered?',
  kanbanChecklistInlineLabel: 'Plank Board tally peek',
  kanbanChecklistInlineDesc: 'Show the tally marks right on the parchments without openin the log.',
  kanbanChecklistPreviewNone: 'Hide on parchments',
  kanbanChecklistPreviewAll: 'Show on all parchments',
  kanbanChecklistPreviewPerCard: 'Case by case',
  kanbanAutoAddLabel: 'Auto-add booty to th\' board',
  kanbanAutoAddDesc: 'Automatic-like stow this week\'s tasks in th\' first column o\' th\' Kanban board.',
  gradeScaleLabel: 'Markin\' scale',
  gradeScaleDesc: 'Highest mark a scallywag can earn. Mark inputs be capped at this here value.',
  passingGradeLabel: 'Passin\' mark',
  passingGradeDesc: 'Least mark needed to stay afloat. Used fer pass marks an\' th\' default target mark.',
  focusAlertModeLabel: 'Steady Aim alert mode',
  focusAlertModeDesc: 'Choose how Steady Aim alerts be delivered when the glass turns.',
  focusAlertNone: 'None',
  focusAlertVibration: 'Rumble',
  focusAlertNotification: 'Signal flag',
  focusAlertBoth: 'Both',
  taskAlertModeLabel: 'Chore reckoning-day alerts',
  taskAlertModeDesc: 'Choose how chore reckoning-day alerts be delivered.',
  taskAlertNone: 'None',
  taskAlertInApp: 'On deck',
  taskAlertNotification: 'Signal flag',
  taskAlertBoth: 'Both',
  taskAlertNextDayTimeLabel: 'Morrow alert bell',
  taskAlertNextDayTimeDesc: 'Bell fer reminders about chores due on the morrow.',
  taskDefaultToCalendarLabel: 'Chores on almanac by default',
  taskDefaultToCalendarDesc: 'New chores will have "Show on almanac" hoisted by default.',
  speechInputLabel: 'Parrot speak to script',
  speechInputDesc: 'Show a speakin\' horn to bark yer words into chore, event an\' log fields.',
  taskDueTodayTitle: count => count === 1 ? 'Chore due this day' : `${count} chores due this day`,
  taskAlertHide: 'Hide alert',
  taskAlertRemindMeAt: 'Remind me at',
  settingEnabled: 'Hoisted', settingDisabled: 'Lowered',
  spanSingle: 'One global mark (plundered once)', spanPerWeek: 'Mark per fortnight',
  dangerZone: 'Cursed waters', deleteSemester: 'Scuttle this voyage',
  clearPomodoros: 'Toss the tomatas',
  clearPomodorosTitle: 'Toss all tomatas?',
  clearPomodorosDesc: 'All fallen tomatas will be sent to the depths forever.',
  deleteSemesterTitle: 'Scuttle voyage?', deleteSemesterDesc: 'All chores, booty, and plank board data fer this voyage will be sent to Davy Jones forever.',
  clearDoneTitle: 'Toss the plundered column?', clearDoneDesc: 'All parchments in the Plundered column will be scuttled.',
  wipeAllTitle: 'Scuttle all parchments?', wipeAllDesc: 'Every parchment on the board will be sent to the depths forever.',
  selectSemester: 'Choose voyage', noClassesYet: 'No crews yet', addClassesInSettings: "Muster crews in Ship's Orders.",
  addUnlocks: 'Add a voyage to unlock the rest.',
  checklist: 'Tally', addItem: 'Add mark', editCard: 'Amend parchment',
  notAchievable: '— not reachable', onRemaining: ' on remainin trials',
  youNeed: 'Ye need', allGraded: 'All pieces reckoned.',
  noGradeComponents: "No booty pieces set. Sail to Ship's Orders.",
  deleteClassTitle: 'Scuttle crew?', deleteClassDesc: 'This be scuttlin all chores fer this crew too.',
  holidayName: 'Shore leave name', holidayNamePlaceholder: 'e.g. Yuletide break',
  addHoliday: 'Add shore leave',
  loadPreset: 'Load chart',
  presetLoading: 'Loadin chart…', presetError: 'Chart be lost at sea.', retry: 'Try again', skip: 'Skip',
  newColumnName: 'New column name',
  focusStart: 'Set sail', focusPause: 'Drop anchor', focusResume: 'Weigh anchor', focusReset: 'Reset', focusSkipBreak: 'Skip the grog',
  focusReady: 'ready', focusBreak: 'grog',
  focusPhrases: ['keep sailin', 'stay the course', "ye be doin grand", 'one wave at a time', 'deep work, deep waters', 'stay on watch'],
  focusEvery: 'every (min)', focusBreakFor: 'grog (min)',
  focusScheduledMode: 'Scheduled grog',
  focusNextBreak: 'Next grog at',
  focusFocusLabel: 'Steady Aim cry', focusBreakLabel: 'Grog cry',
  loadPresetTitle: 'Load a chart',
  presetGroupEI: 'EI Course',
  presetGroupGeneric: 'General',
  backToMenu: 'Back',
  importData: 'Import data',
  importFromFirebase: 'Import from Firebase',
  nextSemesterTitle: 'Voyage ended',
  nextSemesterDesc: 'Yer voyage has made port. Load the next one?',
  loadNextSemester: 'Load next voyage',
  dismissNextSemester: 'Dismiss',
  carryOverTitle: 'Haul aboard',
  carryKanbanCards: 'Kanban charts',
  carryUpcomingTasks: 'Chores ahead',
  carryUpcomingEvents: 'Doings ahead',
  carryOverAlwaysKept: 'Yer logs an\' riggin\' be always kept.',
  carryOverDiscardWarning: 'All else from this voyage goes to Davy Jones.',
  noSemesterYet: 'No voyage charted',
  noSemesterDesc: 'Load a chart or import yer data to set sail.',
  focusIntervalMode: 'Interval grog',
  focusIntervalEvery: 'every (min)',
  focusIntervalBreakFor: 'grog (min)',
  focusScheduledBreakFor: 'grog (min)',
  focusAfterBreakReset: 'After grog: reset the glass',
  focusAfterBreakContinue: 'After grog: keep the glass runnin',
  firebaseSync: 'Firebase sync',
  firebaseConnect: 'Moor',
  firebaseConnected: 'Moored',
  firebaseDisconnect: 'Cast off',
  firebaseSyncing: 'Syncin…',
  firebaseLastSync: 'Last sync',
  firebaseError: 'Sync be cursed',
  firebaseRemoteNewer: 'Cloud data be from a newer ship. Sync anchored. Update the app.',
  collabSyncFailed: 'Could not sync the shared change. It be reverted.',
  newerVersionWarning: 'Yer data was stowed by a newer ship. Some things may not show right till ye update.',
  firebaseSetupTitle: 'Moor to Firebase',
  firebaseStep1Title: 'Create a Firebase project',
  firebaseStep1Desc: 'Go to console.firebase.google.com → Add project → give it any name → disable Google Analytics → Create project.',
  firebaseStep2Title: 'Enable Firestore',
  firebaseStep2Desc: 'Sail to Build → Firestore Database → Create database → pick a region → Start in production mode → Create. Then open the Rules tab, throw the old scrawl overboard, replace it with the rules below, and click Publish.',
  firebaseStep3Title: 'Get yer config',
  firebaseStep3Desc: 'Go to Project Settings (gear mark) → Yer apps → Add app → Web → register the app → copy the firebaseConfig object shown.',
  firebaseStep4Title: 'Paste yer config',
  firebaseStep4Desc: 'Paste the full firebaseConfig object (as JSON) below.',
  firebaseConfigPlaceholder: '{ "apiKey": "...", "authDomain": "...", "projectId": "...", ... }',
  firebaseConfigInvalid: 'Cursed config: must include apiKey and projectId.',
  firebaseTestFailed: 'Could not moor. Check yer config and database rules.',
  firebaseSave: 'Stow & moor',
  pomodoroMode: 'Tomata mode',
  pomodoroModeDesc: 'Grow tomatas durin steady-aim watches. Each finished watch drops a tomata.',
  pomodoroResetPeriod: 'Reset spell',
  pomodoroResetDay: 'Each dawn', pomodoroResetWeek: 'Fortnightly', pomodoroResetMonth: 'Each moon', pomodoroResetSemester: 'Per voyage',
  pomodoroTrackPeriodStats: 'Track spell tallies',
  pomodoroShowAbandoned: 'Show marooned tomatas',
  pomodoroShowPeriodPomodoros: 'Show spell tomatas',
  pomodoroShowOverlay: 'Hoist yer tomata banner o\'er all decks',
  focusNotifTitle: 'Organiser Crow\'s Nest',
  focusNotifBreakBody: 'Time fer yer tomata shore leave.',
  focusNotifFocusBody: 'Back t\' the watch.',
  tasksNotifTitle: 'Organiser Chores',
  taskReminderTitle: 'Chore Reminder',
  pomodoroStatsTitle: 'Tomata tallies',
  pomodoroTotal: 'Total tomatas', pomodoroAbandoned: 'Marooned', pomodoroFocusTime: 'Total steady-aim time',
  pomodoroPeriodTotal: 'This spell', pomodoroPeriodFocus: 'Aim this spell',
  pomodoroVsSinceLast: 'vs last spell',
  pomodoroAllTime: 'All o\' time',
  pomodoroInsightsDailyTitle: 'Daily aim this fortnight',
  pomodoroInsightsWeeklyBreakdownTitle: 'Fortnight averages',
  pomodoroInsightsAvgWeekLabel: 'avg/day (fortnight)',
  pomodoroInsightsAvgPeriodLabel: 'avg/day (spell)',
  pomodoroInsightsPerDaySuffix: '/d',
  pomodoroInsightsNoWeeklyData: 'No fortnight data yet.',
  pomodoroInsightsDayLabels: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
  pomodoroTotalTimeLabel: 'time on watch',
  pomodoroClose: 'Batten down',
  pomodoroEraseStats: 'Erase tallies',
  pomodoroEraseStatsTitle: 'Erase tomata tallies?',
  pomodoroEraseStatsDesc: 'Historical aim-time tallies will be tossed, but tomata entries stay in the hold.',
  pomodoroGraceCancel: 'Belay (no tomata)',
  pomodoroGrace: s => `${s}s to belay without losin a tomata`,
  workModeLabel: 'Work mode',
  workModeDesc: 'Hides booty and renames crews to bands.',
  workModeOnboarding: 'Usin this fer work?',
  semesterModeLabel: 'No voyage mode',
  semesterModeDesc: 'Turn on to use plain year fortnights instead o voyages. Booty be hidden.',
  semesterModeNone: 'No voyages (year fortnights)',
  semesterModeSemesters: 'Usin voyages',
  semesterModeOnboarding: 'No voyages, just fortnights?',
  groups: 'Bands', group: 'Crew', addAGroup: 'Add band', groupName: 'Band name',
  deleteGroupTitle: 'Scuttle band?', deleteGroupDesc: 'This be scuttlin all chores fer this band too.',
  storageWarningTitle: 'Hold be full',
  storageWarningDesc: 'Hoist Firebase sync, ye reached max local hold.',
  storageWarningAction: 'Aye',
  collabConnect: 'Moor Organizer Collab',
  collabDisconnect: 'Cast off Organizer Collab',
  collabRequiresFirebase: 'Moor Firebase sync first to use Organizer Collab.',
  collabGuideTitle: 'Organizer Collab setup',
  collabGuideIntro: 'One-time riggin. Do these 4 steps in Firebase, then come back and hoist crew.',
  collabGuideImportantTitle: 'What changes when crew be hoisted',
  collabGuideImportant1: 'Yer database starts requirin authenticated hands (anonymous auth be enough).',
  collabGuideImportant2: 'Normal organizer sync keeps sailin, but it must authenticate first.',
  collabGuideImportant3: 'If crew be lowered later, auth-based rules can still be used safely.',
  collabGuideStep1: 'Open Firebase Console > Build > Firestore Database > Rules.',
  collabGuideStep2: 'Paste the rules snippet below and click Publish.',
  collabGuideStep3: 'Open Security > Authentication > Sign-in method > enable Anonymous > Save.',
  collabGuideStep4: 'Return to Organizer and press "I configured rules, hoist crew".',
  collabGuideRulesLabel: 'Firestore rules',
  collabGuideTroubleshootTitle: 'If ye see signUp 400 error',
  collabGuideTroubleshootBody: 'That means Anonymous auth be still lowered in Firebase. Enable it in Security > Authentication > Sign-in method.',
  collabEnableNow: 'I configured rules, hoist crew',
  collabPanelTitle: 'Organizer Collab',
  collabPanelSubtitle: 'Muster crews, invite hands, and share chores/plank board parchments.',
  collabCreateTeam: 'Muster crew',
  collabTeamName: 'Crew name',
  collabTeamDays: 'crew days',
  collabTeamDuration: 'crew duration',
  collabDays: 'days',
  collabJoinTeam: 'Join crew',
  collabInvitePlaceholder: 'Paste the bottle link',
  collabInviteTtl: 'Bottle validity',
  collabYourTeams: 'Yer crews',
  collabNoTeams: 'No crews yet.',
  collabRoleHost: 'cap\'n',
  collabRoleMember: 'hand',
  collabEndsAt: 'ends',
  collabInvite: 'Invite',
  collabEditTeam: 'Amend crew',
  collabTaskCompletionMode: 'Shared chore completion',
  collabTaskCompletionPersonal: 'personal completion',
  collabTaskCompletionForAll: 'toggle for all hands',
  collabTaskPermissions: 'Chore edit rights',
  collabTaskPermissionsEveryone: 'any hand can add/edit/remove chores',
  collabTaskPermissionsHostOnly: 'only the cap\'n can add/edit/remove chores',
  collabLeave: 'Abandon',
  collabDeleteTeam: 'Scuttle',
  collabDefaultTeamName: 'Crew',
  collabLeavePrompt: 'Abandon this crew?',
  collabLeaveWithLocalPrompt: 'Ye shared local chores in this crew. Keep em in yer own hold?',
  collabDeleteTeamPrompt: 'Scuttle this crew?',
  collabDeleteTeamWithLocalPrompt: 'Ye shared local chores in this crew. Keep em in yer own hold before scuttlin the crew?',
  collabKeepLocalTasks: 'Keep local chores',
  collabDeleteLocalTasksToo: 'Scuttle local chores',
  collabErrorCreate: 'Could not muster the crew.',
  collabErrorInvite: 'Could not cast a bottle.',
  collabErrorJoin: 'Could not join the crew.',
  collabErrorInvalidLink: 'Cursed bottle link.',
  collabErrorDeleteTeam: 'Could not scuttle the crew.',
  collabGuideChecklistTitle: 'Still no signal from the crew?',
  collabGuideChecklistBody: "Two things Organizer can't do fer ye: hoist Anonymous Auth and publish the Firestore rules above. If shared booty never shows, one o' these be missin' on the cap'n's project.",
  collabSyncErrorHint: "Can't hail this crew. Make sure the cap'n's Firebase has Anonymous Auth flyin' and the rules be open.",
  collabKeyRequiredHint: "This crew be locked and yer invite carried no key. Beg a fresh invite link.",
  collabErrorPermission: "Firebase rules be blockin' ye. Cap'n must hoist Anonymous Auth and open the Firestore rules.",
  collabErrorNotFound: 'Crew not found. May have been sent to Davy Jones.',
  collabErrorInviteExpired: "This here invite be expired. Beg the cap'n for a fresh link.",
  collabErrorInviteInvalid: 'This invite scroll be no good for that crew.',

    nlpToday: ["today"],
    nlpTomorrow: ["tomorrow"],
    nlpNextWeek: ["next week"],
    nlpAt: ["at"],
    nlpDow: [["sunday","sun"],["monday","mon"],["tuesday","tue"],["wednesday","wed"],["thursday","thu"],["friday","fri"],["saturday","sat"]],
    voiceInputAria: "Dictate by voice",
    voiceInputStopAria: "Stop dictation",
    quickActionTaskWordsPlural: ['tasks', 'duties', 'errands'],
    quickActionEventWordsPlural: ['happenings', 'events'],
    quickActionCardWordsPlural: ['kanban cards', 'cards', 'parchments'],
    quickActionRespectivelyWords: ['respectively', 'in order'],
    quickActionOrdinalWords: ['first', 'second', 'third', 'fourth', 'fifth', 'sixth', 'seventh', 'eighth', 'ninth', 'tenth'],
    eventAllDay: "All day",
    eventStartTime: "Start time",
    eventEndTime: "End time",
    viewDay: "Sun-turn",
    viewWeek: "Sennight",
    viewMonth: "Moon",
    viewYear: "Voyage",
    notesMentionNoResults: "No matching tasks",
    notesMentionDeletedTask: "Deleted task",
    notesArchive: "Archive",
    notesUnarchive: "Unarchive",
    notesArchived: "Archived",
    notesArchivedEmpty: "No archived notes.",
    eisenhower: "Cap'n's Chart",
    eisenhowerEnable: "Hoist th' Cap'n's Chart",
    eisenhowerEnableDesc: "Adds a deck fer sortin' chores by how loud they holler an' how much they matter.",
    eisenhowerDoNow: "Hollerin' an' Weighty",
    eisenhowerSchedule: "Weighty, Not Hollerin'",
    eisenhowerDelegate: "Hollerin', Not Weighty",
    eisenhowerEliminate: "Neither, matey",
    eisenhowerUnsorted: "Chores adrift",
    eisenhowerUnsortedEmpty: "Naught t' sort.",
    eisenhowerEmpty: "Haul chores here.",
    pomodoro: "Pomodoro",
    pomodoroOverlayFocusing: "on watch",
    pomodoroStreakTitle: "Run o' luck",
    pomodoroCurrentStreak: "Current run",
    pomodoroBestStreak: "Finest run",
    pomodoroStreakDaySuffix: "d",
    pomodoroTrendTitle: "Moon-by-moon drift",
    pomodoroTrendNoData: "No moonly tallies yet.",
    pomodoroCopySummary: "Copy th' ledger",
    pomodoroCopiedSummary: "Copied, matey!",
    firebaseRulesTemplateLink: "View Firestore rules template",
    firebaseOpenRulesWarningTitle: "Your database rules may be open",
    firebaseOpenRulesWarningDesc: "Sync is working without authentication, which usually means your Firestore rules allow anyone to read and write your data. Publish the rules template linked below to lock this down.",
    firebaseEncryptionOffTitle: "End-to-end encryption is off",
    firebaseEncryptionOffDesc: "Your data is stored in Firestore as plain text. Turn on encryption so only devices with your key can read it — even if your database rules are ever misconfigured.",
    firebaseEncryptNow: "Encrypt now",
    firebaseEncryptMigrateFailed: "Could not enable encryption. Check your connection and try again.",
    firebaseHaveKeyAlready: "This device already has a key from another install",
    firebaseKeyPastePlaceholder: "Paste your recovery key",
    firebaseKeyInvalid: "That does not look like a valid key.",
    firebaseKeyWrongOrUnreadable: "Could not decrypt with this key. Double check it and try again.",
    firebaseRecoveryKeyShownOnceTitle: "Save this recovery key now",
    firebaseRecoveryKeyShownOnceDesc: "This key is shown only once and is never sent to Firebase. Anyone with it can read your data; anyone without it (including you) cannot recover it if lost. Store it somewhere safe.",
    firebaseKeySavedItConfirm: "I've saved my key",
    firebaseEncryptionOnTitle: "End-to-end encryption is on",
    firebaseEncryptionOnDesc: "Yer treasure be locked on this ship — in the local hold and afore it sails to Firestore. Only crews with the recovery key can crack it open.",
    firebaseShowRecoveryKey: "Show recovery key",
    firebaseShowRecoveryKeyConfirmTitle: "Show recovery key?",
    firebaseShowRecoveryKeyConfirmDesc: "Anyone who sees this key can decrypt your data. Only do this somewhere private.",
    firebaseKeyRequiredTitle: "Encryption key needed",
    firebaseKeyRequiredDesc: "This project’s data is encrypted. Paste the recovery key from a device that already has it to unlock sync on this device.",
    firebaseKeyRequiredForImport: "This backup is encrypted. Set up sync with the matching key first, then import again.",
    exportEncrypted: "Organizer format (encrypted)",
    encUnlockTitle: "Unlock yer treasure",
    encUnlockDesc: "This here vessel be holdin' locked-up booty. Speak yer secret words to open the hold.",
    encUnlockHintLabel: "Yer memory jog",
    encPassphraseLabel: "Secret words",
    encPassphrasePlaceholder: "Yer secret words",
    encPassphraseConfirmLabel: "Say the secret words again",
    encPassphraseMismatch: "Them two secrets don't match, matey.",
    encPassphraseTooShort: "Use at least 8 characters, ye scallywag.",
    encHintLabel: "Memory jog (optional)",
    encHintPlaceholder: "A private nudge, not the secret itself",
    encRecoveryCodeTitle: "Stow yer recovery words",
    encRecoveryCodeDesc: "These 12 English words be the only way back aboard if ye forget yer secret. Carve 'em down or stow 'em in a password chest. We cannot show 'em twice.",
    encRecoveryCodeWordsNote: "12 English words. Copy 'em exact, in order.",
    encRecoveryCodeSavedConfirm: "Aye, I've stowed me recovery words",
    encRecoveryCodeQr: "Show the QR mark",
    encRecoveryCodeQrDesc: "Scan this on another vessel to carry the recovery words across.",
    encUseRecoveryCode: "Use the recovery words instead",
    encUsePassphrase: "Use the secret words instead",
    encRecoveryCodeLabel: "Recovery words",
    encRecoveryCodePlaceholder: "twelve words with spaces between",
    encRecoveryCodeInvalid: "That be no proper 12-word recovery chant.",
    encUnlockFailed: "Couldn't open the hold with that. Check it and try again.",
    encUnlocking: "Openin' the hold…",
    encDeriving: "Forgin' the key…",
    encEnableTitle: "Hoist end-to-end encryption",
    encEnableDesc: "Yer booty be locked up on this vessel afore it reaches Firestore. Only vessels with yer secret words or recovery words can read it.",
    encEnableWarning: "Lose both yer secret words and yer recovery words, and yer booty be gone forever — not even we can fetch it back.",
    encEnableSubmit: "Hoist encryption",
    encEnableFailed: "Couldn't hoist encryption. Check yer connection and try again.",
    encManageTitle: "Encryption",
    encManageDesc: "Yer booty be locked end to end. Unlockin' happens on this vessel alone.",
    encChangePassphrase: "Change yer secret words",
    encChangePassphraseDesc: "Speak yer current secret, then the new one.",
    encCurrentPassphraseLabel: "Current secret words",
    encRegenerateRecoveryCode: "Forge new recovery words",
    encRegenerateRecoveryCodeDesc: "Replaces yer old words. The old chant stops workin'.",
    encEditHint: "Edit the memory jog",
    encRotateDekTitle: "Swap the encryption key",
    encRotateDekDesc: "Locks all yer booty again under a brand new key. Yer other vessels must unlock afresh.",
    encRotateDekWarning: "Don't ye close the app till this be done.",
    encRotating: "Lockin' it all up again…",
    encRotateFailed: "Couldn't swap the key. Nothin' were changed.",
    encSaved: "Stowed.",
    encStoreUnavailableTitle: "Can't reach the strongbox",
    encStoreUnavailableDesc: "This browser barred the key strongbox, as it often does in private waters. Yer locked booty be untouched. Try a normal window.",
    encPlaintextSyncWarnTitle: "Yer sync sails unlocked",
    encPlaintextSyncWarnDesc: "Yer booty sits in Firestore as plain readable text. Any soul who reads yer database reads it all.",
    encPlaintextSyncEnable: "Hoist encryption",
    encPlaintextSyncDismiss: "Not now, and stop askin'",
    encRemoteAlreadyEncrypted: "This here project be locked already. Unlock it to bring this vessel aboard.",
    encRemoteNotEncryptedTitle: "Lock up this project?",
    encRemoteNotEncryptedDesc: "This project holds unlocked booty. Hoist encryption now and it be sent up locked.",
    encRemoteNotEncryptedMigrate: "Lock it and move it",
    encRemoteNotEncryptedSkip: "Leave it unlocked",
    encRemoteUnrecoverable: "This project be locked with no recovery booty aboard, so it cannot be opened. Cut loose and start a fresh project.",
    encRemoteDekMismatch: "This project were locked again under a new key. Unlock it afresh with yer secret words or recovery words.",
    encExportPassphraseTitle: "Guard this here backup",
    encExportPassphraseDesc: "Choose secret words for the file. Ye'll need 'em to restore, on any vessel.",
    encImportPassphraseTitle: "Unlock this here backup",
    encImportPassphraseDesc: "Speak the secret words ye chose when ye exported.",
    encImportPassphraseFailed: "Wrong secret words for this backup.",
    encTitle: "Encryption",
    encOffTitle: "Encryption be struck",
    encOffDesc: "Yer booty be stowed as plain readable text wherever it lies. Hoist encryption and it turns to gibberish without yer secret words — on this vessel and anywhere it sails.",
    encOnDesc: "Yer booty be locked afore it be stowed or synced. Only vessels with yer secret words or recovery words can read it.",
    encLockedDesc: "Yer stowed booty be locked. Speak yer secret words to open it on this vessel.",
    encEnableAction: "Hoist encryption",
    encDisableAction: "Strike the encryption",
    encDisableTitle: "Strike the encryption?",
    encDisableDesc: "Yer booty be written back as plain text wherever it be stowed, and yer secret words and recovery words stop workin'.",
    encStorageShedTitle: "Some booty wouldn't fit",
    encStorageShedDesc: "This vessel ran out of local hold, so the followin' weren't stowed here:",
    exportPlaintext: "Human-readable (plaintext JSON)",
    repeat: "Do it again",
    repeatFreqLabel: "How often",
    repeatFreqDaily: "Every sunrise",
    repeatFreqWeekly: "Every sennight",
    repeatFreqMonthly: "Every moon",
    repeatEvery: () => 'Every',
    repeatIntervalDaily: n => (n === 1 ? 'sunrise' : 'sunrises'),
    repeatIntervalWeekly: n => (n === 1 ? 'sennight' : 'sennights'),
    repeatIntervalMonthly: n => (n === 1 ? 'moon' : 'moons'),
    repeatUntil: "'Til (if ye wish)",
    kanbanColTodo: "To Be Done", kanbanColInProgress: "Underway", kanbanColDone: "Squared Away",
    colourCustom: "Yer own colour",
    googleCalendar: "Google Calendar",
    gcalConnect: "Connect",
    gcalConnected: "Connected",
    gcalConnecting: "Connecting…",
    gcalDisconnect: "Disconnect",
    gcalEnable: "Sync with Google Calendar",
    gcalScopeNotice: "This grants full read/write access to your primary Google Calendar (the \"calendar\" scope). Organizer only reads and writes events you interact with here; your Google credentials never leave your device and are not sent anywhere but Google.",
    gcalStep1Title: "Create a Google Cloud project",
    gcalStep1Desc: "Go to console.cloud.google.com → create a new project (or pick one) → APIs & Services → enable the \"Google Calendar API\".",
    gcalStep2Title: "Configure OAuth consent + credentials",
    gcalStep2Desc: "APIs & Services → OAuth consent screen → set it up (External is fine for personal use, add yourself as a test user). Then Credentials → Create credentials → OAuth client ID → Application type: Web application → add this app's URL to Authorized JavaScript origins.",
    gcalStep3Title: "Paste your Client ID",
    gcalStep3Desc: "Copy the Client ID (ends in .apps.googleusercontent.com) shown after creating it, and paste it below. This value is not secret and is safe to store in this browser.",
    gcalClientIdPlaceholder: "xxxxxxxx.apps.googleusercontent.com",
    gcalClientIdInvalid: "Enter a valid OAuth Client ID.",
    gcalConnectFailed: "Could not connect. Check your Client ID and try again.",
    gcalDisableTitle: "Disconnect Google Calendar?",
    gcalDisableDesc: "Stops syncing with Google Calendar on this device. Events already created stay in both places; sync bookkeeping (Client ID, links) is removed here.",
    eventSyncToGoogle: "Sync to Google Calendar",
    eventSyncToGoogleDesc: "Push this event to your connected Google Calendar.",
    quickActionTaskWords: ["task"],
    quickActionEventWords: ["calendar event","event"],
    quickActionCardWords: ["kanban card","card"],
    quickActionAddWords: ["add"],
    quickActionForWords: ["for", "fer"],
    quickActionAndWords: ["and", "an'"],
    quickActionOnWords: ["on", "upon"],
    quickActionArticleWords: ["a", "an", "the", "th'"],
    quickActionBoardWords: ["kanban", "board", "deck"],
    quickAction: "Quick action",
    quickActionPlaceholder: "e.g. add task and calendar event for a cbd test on 18/07 at 15h",
    quickActionTab: "Quick action",
    quickActionFormTab: "Form",
    quickActionPreviewTitle: "Will create",
    quickActionPreviewTask: "task",
    quickActionPreviewTaskCalendar: "task (shown on calendar)",
    quickActionPreviewEvent: "calendar event",
    quickActionPreviewCard: column => `kanban card in ${column}`,
    quickActionEmpty: "Couldn't understand that. Try rephrasing.",
    quickActionCreate: "Create",
    quickActionBack: "Back",
    notesDeleteConfirmTitle: "Delete this note?",
    notesDeleteConfirmDesc: "This note will be permanently deleted.",
    notesEmptyTitle: "No notes yet",
    notesEmptyDesc: "Create your first note to get started.",
    notesFilterEmpty: "No notes match your search.",
    notesSelectNote: "Select a note to start editing",
    notesTextNote: "Text note",
    notesCanvasNote: "Canvas note",
    eventStartTimeFirstDay: "Castin’ off (first day)",
    eventEndTimeLastDay: "Droppin’ anchor (last day)",
    notesBold: "Bold as brass",
    notesItalic: "Leanin’ like a mast",
    notesStrike: "Struck through",
    notesHeading1: "Grand title",
    notesHeading2: "Lesser title",
    notesHeading3: "Wee title",
    notesBulletList: "Shot list",
    notesOrderedList: "Numbered list",
    notesTaskList: "Ship’s checklist",
    notesQuote: "Quoted yarn",
    notesInsertTable: "Lay out a table",
    notesCodeBlock: "Cipher block",
    notesDivider: "Rope divider",
    notesAddLink: "Tie a line",
    notesRemoveLink: "Cut the line",
    notesTextColor: "Ink colour",
    notesColorReset: "Plain ink",
    notesColorCustom: "Mix yer own ink",
    notesColorApply: "Aye, apply",
    notesExport: "Ship the log out",
    notesImport: "Haul a log aboard",
    notesGraphEdit: "Redraw the chart",
    notesGraphRange: "x from",
    notesGraphResize: "Haul to resize",
  notesGraphResizeWidth: "Haul to resize breadth an' height",
    notesGraphInvalid: "Cannot chart that",
    notesGraphAlignleft: "To port",
    notesGraphAligncenter: "Amidships",
    notesGraphAlignright: "To starboard",
    notesTextSize: "Ink size",
    notesSizeNormal: "Normal",
    notesSizeSmall: "Wee",
    notesSizeLarge: "Big",
    notesSizeHuge: "Monstrous",
    notesUndo: "Belay that",
    notesRedo: "At it again",
    notesViewList: "List view",
    notesViewMosaic: "Mosaic view",
    notesMathEnable: "Reckonin’ the numbers",
    notesMathEnableDesc: "Write a sum endin’ in = and strike Enter to solve it. Use x to chart a curve.",
    notesMathSolve: "Hunt down x",
    notesMathSolveDesc: "Turns 3x = 3 into x = 1, inequalities and squares alike.",
    notesMathSelection: "Chart the marked bit",
    notesMathSelectionDesc: "Mark an equation and strike Enter to chart it.",
    notesMathSteps: "Show the reckonin’",
    notesMathStepsDesc: "Shows every step o’ the workin’, not just the prize.",
    eisenhowerAddTask: "Add chore",
    eisenhowerCustomize: "Rename th' quarters",
    eisenhowerResetDefaults: "Back t' the old chart",
    eisenhowerCleanDone: "Swab th' plundered",
    eisenhowerCleanDoneTitle: "Swab th' plundered chores?",
    eisenhowerCleanDoneDesc: "Casts finished chores off th' chart. They bide in yer chore ledger still.",
    quickActionApp: "Quick Action",
    quickActionAppEnable: "Enable Quick Action",
    quickActionAppEnableDesc: "Adds a spotlight overlay for quickly creating tasks, events, and cards.",
    quickActionTripleTapEnable: "Triple tap upon th' screen", quickActionTripleTapEnableDesc: "Tap thrice anywhere t' summon Quick Action",
    quickActionShortcutEnable: "Keyboard shortcut",
    quickActionShortcutKey: "Shortcut",
    quickActionNavbarButton: "Show in navbar add menu",
    spotlightPlaceholder: "Quick action… (e.g. add task for exam on Monday)",
    themeColor: "Accent color",
    themeColorDesc: "Pick a color for buttons, links, and highlights.",
    themeColorReset: "Reset to default",
    themeFontColor: "Scrawl color", themeHighlightColor: "Glint color", themeBgColor: "Sea color",
    defaultTabLabel: "Home port", defaultTabDesc: "Pick the deck the ship wakes upon.",
    defaultTabLast: "Last port o' call",
    taskReminderOffsetsLabel: "Warnin' bells", taskReminderOffsetsDesc: "How many days afore the deadline to signal ye. Applies to every task bearin' a deadline.",
    taskReminderTimeLabel: "Bell time", taskReminderTimeDesc: "Hour o' the day the early bells ring.",
    taskReminderAddOffset: "Days",
    taskReminderOffsetDays: n => (n === 0 ? "On the very day" : n === 1 ? "1 day afore" : `${n} days afore`),
    taskReminderIn: n => (n === 0 ? "Due this very day" : n === 1 ? "Due on the morrow" : `Due in ${n} days`),
    goals: "Quests", goalsEnable: "Hoist the Quests", goalsEnableDesc: "Track long voyages with a mark button and a calendar o' streaks.",
    goalsEmpty: "No quests yet. Chart one to begin.",
    goalAdd: "New quest", goalEdit: "Amend quest",
    goalTitleLabel: "Quest", goalTitlePlaceholder: "Read for 20 bells",
    goalCadenceLabel: "Mark the log", goalCadenceDesc: "How often ye mean to strike the button.",
    goalCadenceDaily: "Every day", goalCadence2Days: "Every 2 days", goalCadence3Days: "Every 3 days",
    goalCadenceWeekly: "Every week", goalCadenceMonthly: "Every moon",
    goalRequireNote: "Demand a log entry", goalRequireNoteDesc: "Scrawl a short line each time ye mark it.",
    goalColor: "Colour",
    goalClickPrompt: "Mark it done", goalDoneForNow: "Marked",
    goalNotePrompt: "How fared ye?", goalNotePlaceholder: "A word or two",
    goalSeeProgress: "Read the log", goalUndoToday: "Scratch this mark", goalDelete: "Scuttle quest",
    goalDeleteTitle: "Scuttle this quest?", goalDeleteDesc: "The quest an' all its log will be sunk.",
    goalCurrentStreak: "Current run", goalBestStreak: "Finest run",
    goalTotalCheckIns: "Marks", goalCompletionRate: "Kept",
    goalNotesTitle: "Log",
    goalCadenceCustom: "Days o' yer choosin'", goalWeekdaysLabel: "Days o' the week", goalWeekdaysDesc: "Pick the days ye mean to mark the log.", goalRestDay: "Shore leave",
    goalToneLabel: "Manner o' cheer", goalToneDesc: "What sort o' word ye get after each mark.",
    goalTonePurpose: "Purpose an' progress", goalToneWarm: "Warm an' heartenin'",
    goalToneUpbeat: "Merry an' satisfyin'", goalToneGame: "Video game",
    goalToneRandom: "Random each time", goalToneCustom: "Me own words",
    goalToneCustomPlaceholder: "Yer message",
    goalTargetLabel: "Finish line", goalTargetDesc: "When this quest counts as done.",
    goalTargetEndless: "Sail on forever", goalTargetCount: "After a count o' marks", goalTargetDate: "By a date",
    goalTargetCountPlaceholder: "Marks",
    goalTargetReached: "Quest complete.",
    goalTargetRemaining: n => (n === 1 ? "1 mark to go" : `${n} marks to go`),
    goalTargetDaysLeft: n => (n === 0 ? "Last day" : n === 1 ? "1 day left" : `${n} days left`),
    goalMessages: {
      purpose: {
        day1: "First entry in the log. The voyage begins.",
        early: "Stackin' steadiness day by day.",
        week: "7 days straight o' sailin' forward.",
        month: "30 days runnin' completed.",
        daily: "Another day nearer yer distant port.",
        rescue: "Back on course this day.",
      },
      warm: {
        day1: "Ye took the hardest step. Proud o' ye.",
        early: "Ye be provin' ye can trust yerself.",
        week: "A whole week! Look how far ye have sailed.",
        month: "30 days o' devotion. Ye built a true habit.",
        daily: "Another solid step this day.",
        rescue: "Glad ye be back. Every day be a fresh tide.",
      },
      upbeat: {
        day1: "Off to a grand start!",
        early: "Another fine day in the log!",
        week: "7 days straight! Grand work.",
        month: "30 days! That be a mighty milestone.",
        daily: "Struck off! Feelin' fine.",
        rescue: "Glad ye be back! Onward we go.",
      },
      game: {
        day1: "Quest Started: Level 1 complete.",
        early: "Combo streak active. XP earned.",
        week: "Achievement Unlocked: Week One Warrior.",
        month: "Major Milestone: Boss Level Defeated.",
        daily: "Daily Quest Complete +100 XP.",
        rescue: "Respawned. Let us reclaim the streak.",
      },
    },
}
