export const pirate = {
  tasks: 'Chores', kanban: 'Plank Board', grades: 'Booty', calendar: 'Almanac', focus: 'Steady Aim', settings: "Ship's Orders",
  noSemester: 'No voyage charted', goToSettings: "Sail to Ship's Orders to begin.",
  weekLabel: w => `Fortnight ${w}`, done: 'plundered', timeToRelax: 'Time to swig some grog!',
  addTask: 'New chore', task: 'Chore', class: 'Crew', priority: 'Rank',
  editTask: 'Amend chore', moveLeft: 'Haul larboard', moveRight: 'Haul starboard', markDone: 'Mark plundered',
  addToKanban: 'Add to Plank Board', themeLight: 'Daylight colours', themeDark: 'Midnight colours', themeSystem: 'Ship colours',
  addPartTitle: 'Add a part',
  fromWeek: 'From fortnight', toWeek: 'To fortnight', dueDate: 'Reckoning day',
  other: 'Other', noTasks: 'No chores this fortnight, matey.',
  whatNeedsDone: 'What be needin doin?',
  addTaskBtn: 'Add chore', showOnCalendar: 'Show on almanac', showOnTasks: 'Show on chores',
  clearDone: 'Toss the plundered', wipeAll: 'Scuttle all',
  addCard: 'Add parchment', addCardPlaceholder: 'Parchment title',
  save: 'Stow', cancel: 'Belay', confirm: 'Aye', delete: 'Send to Davy Jones',
  addEvent: 'Add happenin', newEvent: 'New happenin', editEvent: 'Amend happenin',
  eventTitle: 'Happenin title', eventDate: 'Day', eventRange: 'Spell o days',
  eventMultiDay: 'Many a day', eventColor: 'Colour', eventNote: 'Scrawl',
  eventNotePlaceholder: 'Optional scrawl', more: 'more',
  navbar: 'Helm bar', navHide: 'Hide', navOverflow: 'Stow in the more chest', navAddButton: 'Show the add-chore button',
  navMore: 'More', navLabelMode: 'Show', navLabelBoth: 'Marks + names', navLabelIcons: 'Marks only', navLabelNames: 'Names only',
  add: 'Add', navAddLabel: 'Add', navDrag: 'Drag to reorder the ranks',
  appDisableTitle: 'Disable and scuttle the data?', appDisableDesc: 'Turnin this app off sends all its data to the depths forever.',
  collabDisableDesc: 'Disconnectin abandons all crews and sinks the crew-sharin data from this vessel forever.',
  navAddAction: 'Add button deed', navAddPicker: 'Ask each time',
  navFolders: 'Chests', navNewFolder: 'New chest',
  navMobilePosition: 'Spyglass helm position', navPosBottom: 'Bottom rail', navPosSide: 'Side rail',
  addToTasks: 'Add to chores', inTasks: 'In chores',
  standby: 'Anchored', standbyEnable: 'Enable landscape anchored watch',
  standbyDesc: 'Turn yer spyglass sideways to show an ambient watch board.',
  standbyLeft: 'Larboard pane', standbyCenter: 'Midships pane', standbyRight: 'Starboard pane',
  standbyPanels: 'Panes', standbyPane: n => `Pane ${n}`,
  standbyPaneSecond: 'Second parchment (swipe)', standbyPaneNone: 'None',
  paneWheel: 'Ship\'s wheel o progress', paneWheelTime: 'Wheel + bells', paneCalendar: 'Almanac',
  paneFocus: 'Steady Aim', paneKanban: 'Plank Board', paneTasksByCategory: 'Chores by crew',
  notesLastEdit: 'Scrawled', notesFolder: 'Chest', notesNoFolder: 'No chest', notesNewFolder: 'New chest',
  notesFolderName: 'Chest name', notesRenameFolder: 'Rename chest', notesDeleteFolder: 'Scuttle chest', notesMoveTo: 'Haul to',
  notesEdit: 'Amend', notesPreview: 'Peek', notesBack: 'Back',
  apps: 'Riggin', appsSearch: 'Search riggin', appsNoResults: 'No riggin found, matey.', notes: 'Scrolls',
  notesEnable: 'Enable Scrolls', notesEnableDesc: 'Add a Scrolls tab for quick scrawls.',
  notesNew: 'New scroll', notesTitle: 'Title', notesBody: 'Scrawl somethin…', notesSearch: 'Search scrolls',
  notesEmpty: 'No scrolls yet, ye scallywag.', notesFavorite: 'Prized', notesText: 'Text', notesCanvas: 'Quill work',
  notesCanvasWarning: 'Scrolls with drawins may hog a lot o hold space, so they be only available with Firebase hoisted.',
  collabApp: 'Crewmates',
  eiCalendar: 'EI Almanac', eiCalendarEnable: 'Show EI almanac',
  eiCalendarEnableDesc: 'Adds the official EI course almanac fer yer year, read-only and always fresh as the tide.',
  eiCalendarDisableTitle: 'Hide EI almanac?', eiCalendarDisableDesc: 'Stops showin the EI almanac happenins. Nothin be scuttled and ye can hoist it again anytime.',
  semester: 'Voyage', classes: 'Crews', gradeComponents: 'Booty pieces',
  kanbanColumns: 'Plank Board columns', general: 'General', data: 'Data & sync',
  holidays: 'Shore leave',
  exportJson: 'Export JSON', importJson: 'Import JSON',
  semesterAvg: 'Voyage average', ectsPassedLabel: 'ECTS plundered',
  targetGrade: 'Aimed booty',
  previousSemesters: 'Past voyages',
  courseAvg: 'Course average', finalGrade: 'Final booty', previousAvg: 'Past average', numSemesters: 'No. o voyages',
  getStarted: 'Set sail', welcomeTitle: 'Welcome aboard organizer',
  welcomeDesc: 'Yer quarters fer uni work. Chart yer voyage and get shipshape.',
  step1: 'Set yer voyage dates', step2: 'Muster yer crews', step3: 'Chart chores & track booty',
  obNext: 'Onward', obBack: 'Back', obFinish: 'Weigh anchor', obSkip: 'Skip',
  obWelcomeTitle: 'Welcome aboard Organizer', obWelcomeDesc: 'Yer calm quarters fer uni work. Pick yer tongue and colours to start.',
  obModeTitle: 'How will ye use it?', obModeDesc: 'Toggle what fits ye. Both can be hoisted.',
  obModeWorkToggle: 'Work mode', obModeWorkToggleDesc: 'Bands instead o crews, no booty.',
  obModeWeeksToggle: 'No voyages', obModeWeeksToggleDesc: 'Organise by almanac fortnight instead o voyage.',
  obImportOr: 'or restore a stashed chest',
  obDatesTitle: 'Yer voyage', obDatesDesc: 'When does it set sail and make port?',
  obClassesTitle: 'Yer crews', obClassesDesc: 'Muster the crews ye be sailin with.',
  obGroupsTitle: 'Yer bands', obGroupsDesc: 'Muster the bands ye work with.',
  obInfoTasksTitle: 'Chores & Plank Board', obInfoTasksDesc: 'Add chores per fortnight or day, then drag em across yer plank board.',
  obInfoCalTitle: 'Almanac & Steady Aim', obInfoCalDesc: 'See it all on the almanac and run steady-aim watches to get things done.',
  obInfoDoneTitle: 'Ye be all set', obInfoDoneDesc: 'Ye can change any o this later in ship\'s orders.',
  shareLink: 'Copy the message-in-a-bottle', qrCode: 'QR Mark', linkCopied: 'Bottle cast off!',
  high: 'Cap\'n', medium: 'Bosun', low: 'Swabbie', none: 'None',
  addSemester: 'Add voyage', semesterName: 'Voyage name', startDate: 'Set-sail day', endDate: 'Make-port day',
  weeks: n => `${n} fortnights`, addAClass: 'Muster crew', className: 'Crew name', ects: 'ECTS', colour: 'Colour',
  addComponent: 'Add booty piece', componentName: 'Booty piece name',
  taskSpanLabel: 'Chore span behaviour', taskSpanDesc: 'When a chore spans many a fortnight, how be it marked plundered?',
  kanbanChecklistInlineLabel: 'Plank Board tally peek',
  kanbanChecklistInlineDesc: 'Show the tally marks right on the parchments without openin the log.',
  kanbanChecklistPreviewNone: 'Hide on parchments',
  kanbanChecklistPreviewAll: 'Show on all parchments',
  kanbanChecklistPreviewPerCard: 'Case by case',
  focusAlertModeLabel: 'Steady Aim alert mode',
  focusAlertModeDesc: 'Choose how Steady Aim alerts be delivered when the glass turns.',
  focusAlertNone: 'None',
  focusAlertVibration: 'Rumble',
  focusAlertNotification: 'Signal flag',
  focusAlertBoth: 'Both',
  taskAlertModeLabel: 'Chore reckoning-day alerts',
  taskAlertModeDesc: 'Choose how chore reckoning-day alerts be delivered.',
  taskAlertNone: 'None',
  taskAlertInApp: 'On deck',
  taskAlertNotification: 'Signal flag',
  taskAlertBoth: 'Both',
  taskAlertNextDayTimeLabel: 'Morrow alert bell',
  taskAlertNextDayTimeDesc: 'Bell fer reminders about chores due on the morrow.',
  taskDefaultToCalendarLabel: 'Chores on almanac by default',
  taskDefaultToCalendarDesc: 'New chores will have "Show on almanac" hoisted by default.',
  taskDueTodayTitle: count => count === 1 ? 'Chore due this day' : `${count} chores due this day`,
  taskAlertHide: 'Hide alert',
  taskAlertRemindMeAt: 'Remind me at',
  settingEnabled: 'Hoisted', settingDisabled: 'Lowered',
  spanSingle: 'One global mark (plundered once)', spanPerWeek: 'Mark per fortnight',
  dangerZone: 'Cursed waters', deleteSemester: 'Scuttle this voyage',
  clearPomodoros: 'Toss the tomatas',
  clearPomodorosTitle: 'Toss all tomatas?',
  clearPomodorosDesc: 'All fallen tomatas will be sent to the depths forever.',
  deleteSemesterTitle: 'Scuttle voyage?', deleteSemesterDesc: 'All chores, booty, and plank board data fer this voyage will be sent to Davy Jones forever.',
  clearDoneTitle: 'Toss the plundered column?', clearDoneDesc: 'All parchments in the Plundered column will be scuttled.',
  wipeAllTitle: 'Scuttle all parchments?', wipeAllDesc: 'Every parchment on the board will be sent to the depths forever.',
  selectSemester: 'Choose voyage', noClassesYet: 'No crews yet', addClassesInSettings: "Muster crews in Ship's Orders.",
  addUnlocks: 'Add a voyage to unlock the rest.',
  checklist: 'Tally', addItem: 'Add mark', editCard: 'Amend parchment',
  notAchievable: '— not reachable', onRemaining: ' on remainin trials',
  youNeed: 'Ye need', allGraded: 'All pieces reckoned.',
  noGradeComponents: "No booty pieces set. Sail to Ship's Orders.",
  deleteClassTitle: 'Scuttle crew?', deleteClassDesc: 'This be scuttlin all chores fer this crew too.',
  holidayName: 'Shore leave name', holidayNamePlaceholder: 'e.g. Yuletide break',
  addHoliday: 'Add shore leave',
  loadPreset: 'Load chart',
  presetLoading: 'Loadin chart…', presetError: 'Chart be lost at sea.', retry: 'Try again', skip: 'Skip',
  newColumnName: 'New column name',
  focusStart: 'Set sail', focusPause: 'Drop anchor', focusResume: 'Weigh anchor', focusReset: 'Reset', focusSkipBreak: 'Skip the grog',
  focusReady: 'ready', focusBreak: 'grog',
  focusPhrases: ['keep sailin', 'stay the course', "ye be doin grand", 'one wave at a time', 'deep work, deep waters', 'stay on watch'],
  focusEvery: 'every (min)', focusBreakFor: 'grog (min)',
  focusScheduledMode: 'Scheduled grog',
  focusNextBreak: 'Next grog at',
  focusFocusLabel: 'Steady Aim cry', focusBreakLabel: 'Grog cry',
  loadPresetTitle: 'Load a chart',
  presetGroupEI: 'EI Course',
  presetGroupGeneric: 'General',
  backToMenu: 'Back',
  importData: 'Import data',
  importFromFirebase: 'Import from Firebase',
  nextSemesterTitle: 'Voyage ended',
  nextSemesterDesc: 'Yer voyage has made port. Load the next one?',
  loadNextSemester: 'Load next voyage',
  dismissNextSemester: 'Dismiss',
  noSemesterYet: 'No voyage charted',
  noSemesterDesc: 'Load a chart or import yer data to set sail.',
  focusIntervalMode: 'Interval grog',
  focusIntervalEvery: 'every (min)',
  focusIntervalBreakFor: 'grog (min)',
  focusScheduledBreakFor: 'grog (min)',
  focusAfterBreakReset: 'After grog: reset the glass',
  focusAfterBreakContinue: 'After grog: keep the glass runnin',
  firebaseSync: 'Firebase sync',
  firebaseConnect: 'Moor',
  firebaseConnected: 'Moored',
  firebaseDisconnect: 'Cast off',
  firebaseSyncing: 'Syncin…',
  firebaseLastSync: 'Last sync',
  firebaseError: 'Sync be cursed',
  firebaseRemoteNewer: 'Cloud data be from a newer ship. Sync anchored. Update the app.',
  collabSyncFailed: 'Could not sync the shared change. It be reverted.',
  newerVersionWarning: 'Yer data was stowed by a newer ship. Some things may not show right till ye update.',
  firebaseSetupTitle: 'Moor to Firebase',
  firebaseStep1Title: 'Create a Firebase project',
  firebaseStep1Desc: 'Go to console.firebase.google.com → Add project → give it any name → disable Google Analytics → Create project.',
  firebaseStep2Title: 'Enable Firestore',
  firebaseStep2Desc: 'Go to Build → Firestore Database → Create database → choose a region → Start in production mode → Create. Then go to Rules, replace the content with: allow read, write: if true; and click Publish.',
  firebaseStep3Title: 'Get yer config',
  firebaseStep3Desc: 'Go to Project Settings (gear mark) → Yer apps → Add app → Web → register the app → copy the firebaseConfig object shown.',
  firebaseStep4Title: 'Paste yer config',
  firebaseStep4Desc: 'Paste the full firebaseConfig object (as JSON) below.',
  firebaseConfigPlaceholder: '{ "apiKey": "...", "authDomain": "...", "projectId": "...", ... }',
  firebaseConfigInvalid: 'Cursed config: must include apiKey and projectId.',
  firebaseTestFailed: 'Could not moor. Check yer config and database rules.',
  firebaseSave: 'Stow & moor',
  pomodoroMode: 'Tomata mode',
  pomodoroModeDesc: 'Grow tomatas durin steady-aim watches. Each finished watch drops a tomata.',
  pomodoroResetPeriod: 'Reset spell',
  pomodoroResetDay: 'Daily', pomodoroResetWeek: 'Fortnightly', pomodoroResetMonth: 'Monthly', pomodoroResetSemester: 'Per voyage',
  pomodoroTrackPeriodStats: 'Track spell tallies',
  pomodoroShowAbandoned: 'Show marooned tomatas',
  pomodoroShowPeriodPomodoros: 'Show spell tomatas',
  pomodoroStatsTitle: 'Tomata tallies',
  pomodoroTotal: 'Total tomatas', pomodoroAbandoned: 'Marooned', pomodoroFocusTime: 'Total steady-aim time',
  pomodoroPeriodTotal: 'This spell', pomodoroPeriodFocus: 'Aim this spell',
  pomodoroVsSinceLast: 'vs last spell',
  pomodoroAllTime: 'All time',
  pomodoroInsightsDailyTitle: 'Daily aim this fortnight',
  pomodoroInsightsWeeklyBreakdownTitle: 'Fortnight averages',
  pomodoroInsightsAvgWeekLabel: 'avg/day (fortnight)',
  pomodoroInsightsAvgPeriodLabel: 'avg/day (spell)',
  pomodoroInsightsPerDaySuffix: '/d',
  pomodoroInsightsNoWeeklyData: 'No fortnight data yet.',
  pomodoroInsightsDayLabels: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
  pomodoroTotalTimeLabel: 'total time',
  pomodoroClose: 'Close',
  pomodoroEraseStats: 'Erase tallies',
  pomodoroEraseStatsTitle: 'Erase tomata tallies?',
  pomodoroEraseStatsDesc: 'Historical aim-time tallies will be tossed, but tomata entries stay in the hold.',
  pomodoroGraceCancel: 'Belay (no tomata)',
  pomodoroGrace: s => `${s}s to belay without losin a tomata`,
  workModeLabel: 'Work mode',
  workModeDesc: 'Hides booty and renames crews to bands.',
  workModeOnboarding: 'Usin this fer work?',
  semesterModeLabel: 'No voyage mode',
  semesterModeDesc: 'Turn on to use plain year fortnights instead o voyages. Booty be hidden.',
  semesterModeNone: 'No voyages (year fortnights)',
  semesterModeSemesters: 'Usin voyages',
  semesterModeOnboarding: 'No voyages, just fortnights?',
  groups: 'Bands', addAGroup: 'Add band', groupName: 'Band name',
  deleteGroupTitle: 'Scuttle band?', deleteGroupDesc: 'This be scuttlin all chores fer this band too.',
  storageWarningTitle: 'Hold be full',
  storageWarningDesc: 'Hoist Firebase sync, ye reached max local hold.',
  storageWarningAction: 'Aye',
  collabConnect: 'Moor Organizer Collab',
  collabDisconnect: 'Cast off Organizer Collab',
  collabRequiresFirebase: 'Moor Firebase sync first to use Organizer Collab.',
  collabGuideTitle: 'Organizer Collab setup',
  collabGuideIntro: 'One-time riggin. Do these 4 steps in Firebase, then come back and hoist crew.',
  collabGuideImportantTitle: 'What changes when crew be hoisted',
  collabGuideImportant1: 'Yer database starts requirin authenticated hands (anonymous auth be enough).',
  collabGuideImportant2: 'Normal organizer sync keeps sailin, but it must authenticate first.',
  collabGuideImportant3: 'If crew be lowered later, auth-based rules can still be used safely.',
  collabGuideStep1: 'Open Firebase Console > Build > Firestore Database > Rules.',
  collabGuideStep2: 'Paste the rules snippet below and click Publish.',
  collabGuideStep3: 'Open Security > Authentication > Sign-in method > enable Anonymous > Save.',
  collabGuideStep4: 'Return to Organizer and press "I configured rules, hoist crew".',
  collabGuideRulesLabel: 'Firestore rules',
  collabGuideTroubleshootTitle: 'If ye see signUp 400 error',
  collabGuideTroubleshootBody: 'That means Anonymous auth be still lowered in Firebase. Enable it in Security > Authentication > Sign-in method.',
  collabEnableNow: 'I configured rules, hoist crew',
  collabPanelTitle: 'Organizer Collab',
  collabPanelSubtitle: 'Muster crews, invite hands, and share chores/plank board parchments.',
  collabCreateTeam: 'Muster crew',
  collabTeamName: 'Crew name',
  collabTeamDays: 'crew days',
  collabTeamDuration: 'crew duration',
  collabDays: 'days',
  collabJoinTeam: 'Join crew',
  collabInvitePlaceholder: 'Paste the bottle link',
  collabInviteTtl: 'Bottle validity',
  collabYourTeams: 'Yer crews',
  collabNoTeams: 'No crews yet.',
  collabRoleHost: 'cap\'n',
  collabRoleMember: 'hand',
  collabEndsAt: 'ends',
  collabInvite: 'Invite',
  collabEditTeam: 'Amend crew',
  collabTaskCompletionMode: 'Shared chore completion',
  collabTaskCompletionPersonal: 'personal completion',
  collabTaskCompletionForAll: 'toggle for all hands',
  collabTaskPermissions: 'Chore edit rights',
  collabTaskPermissionsEveryone: 'any hand can add/edit/remove chores',
  collabTaskPermissionsHostOnly: 'only the cap\'n can add/edit/remove chores',
  collabLeave: 'Abandon',
  collabDeleteTeam: 'Scuttle',
  collabDefaultTeamName: 'Crew',
  collabLeavePrompt: 'Abandon this crew?',
  collabLeaveWithLocalPrompt: 'Ye shared local chores in this crew. Keep em in yer own hold?',
  collabDeleteTeamPrompt: 'Scuttle this crew?',
  collabDeleteTeamWithLocalPrompt: 'Ye shared local chores in this crew. Keep em in yer own hold before scuttlin the crew?',
  collabKeepLocalTasks: 'Keep local chores',
  collabDeleteLocalTasksToo: 'Scuttle local chores',
  collabErrorCreate: 'Could not muster the crew.',
  collabErrorInvite: 'Could not cast a bottle.',
  collabErrorJoin: 'Could not join the crew.',
  collabErrorInvalidLink: 'Cursed bottle link.',
  collabErrorDeleteTeam: 'Could not scuttle the crew.',
  collabGuideChecklistTitle: 'Still no signal from the crew?',
  collabGuideChecklistBody: "Two things Organizer can't do fer ye: hoist Anonymous Auth and publish the Firestore rules above. If shared booty never shows, one o' these be missin' on the cap'n's project.",
  collabSyncErrorHint: "Can't hail this crew. Make sure the cap'n's Firebase has Anonymous Auth flyin' and the rules be open.",
  collabErrorPermission: "Firebase rules be blockin' ye. Cap'n must hoist Anonymous Auth and open the Firestore rules.",
  collabErrorNotFound: 'Crew not found. May have been sent to Davy Jones.',
  collabErrorInviteExpired: "This here invite be expired. Beg the cap'n for a fresh link.",
  collabErrorInviteInvalid: 'This invite scroll be no good for that crew.',
}
