export const pt = {
    months: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
    weekdaysShort: ['Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb', 'Dom'],
    weekdays: ['Segunda-feira', 'Terça-feira', 'Quarta-feira', 'Quinta-feira', 'Sexta-feira', 'Sábado', 'Domingo'],
    tasks: 'Tarefas', kanban: 'Kanban', grades: 'Avaliações', calendar: 'Calendário', focus: 'Foco', settings: 'Definições',
    guides: 'Guias',
    noSemester: 'Nenhum semestre configurado', goToSettings: 'Vai a Definições para começar.',
    weekLabel: w => `Semana ${w}`, done: 'concluídas', timeToRelax: 'Hora de descansar!',
    addTask: 'Nova tarefa', task: 'Tarefa', class: 'Disciplina', priority: 'Prioridade',
    editTask: 'Editar tarefa', moveLeft: 'Mover para a esquerda', moveRight: 'Mover para a direita', markDone: 'Marcar como feito',
    addToKanban: 'Adicionar ao Kanban', themeLight: 'Tema claro', themeDark: 'Tema escuro', themeSystem: 'Tema do sistema',
    addPartTitle: 'Adicionar parte',
    fromWeek: 'Da semana', toWeek: 'Até à semana', dueDate: 'Data limite',
    other: 'Outro', noTasks: 'Sem tarefas esta semana.',
    whatNeedsDone: 'O que precisa de ser feito?',
    addTaskBtn: 'Adicionar tarefa', showOnCalendar: 'Mostrar no calendário', showOnTasks: 'Mostrar nas tarefas',
    clearDone: 'Limpar concluídos', wipeAll: 'Apagar tudo',
    addCard: 'Adicionar cartão', addCardPlaceholder: 'Título do cartão',
    save: 'Guardar', cancel: 'Cancelar', confirm: 'Confirmar', delete: 'Eliminar',
    addEvent: 'Adicionar evento', newEvent: 'Novo evento', editEvent: 'Editar evento',
    eventTitle: 'Título do evento', eventDate: 'Data', eventRange: 'Intervalo de datas',
    eventMultiDay: 'Vários dias', eventColor: 'Cor', eventNote: 'Nota',
    eventNotePlaceholder: 'Nota opcional', more: 'mais',
    navbar: 'Barra de navegação', navHide: 'Ocultar', navOverflow: 'Mover para menu', navAddButton: 'Mostrar botão de adicionar',
    navMore: 'Mais', navLabelMode: 'Mostrar', navLabelBoth: 'Ícones + nomes', navLabelIcons: 'Só ícones', navLabelNames: 'Só nomes',
    add: 'Adicionar', navAddLabel: 'Adicionar', navDrag: 'Arrasta para reordenar',
    appDisableTitle: 'Desativar e apagar dados?', appDisableDesc: 'Desativar esta app elimina permanentemente todos os seus dados.',
    collabDisableDesc: 'Desligar sai de todas as equipas e remove permanentemente os dados de colaboração deste dispositivo.',
    navAddAction: 'Ação do botão adicionar', navAddPicker: 'Perguntar sempre',
    navFolders: 'Pastas', navNewFolder: 'Nova pasta',
    navMobilePosition: 'Posição da barra no telemóvel', navPosBottom: 'Barra inferior', navPosSide: 'Barra lateral',
    addToTasks: 'Adicionar às tarefas', inTasks: 'Nas tarefas',
    standby: 'Repouso', standbyEnable: 'Ativar repouso horizontal',
    standbyDesc: 'Vira o telemóvel na horizontal para mostrar um painel ambiente.',
    standbyLeft: 'Painel esquerdo', standbyCenter: 'Painel central', standbyRight: 'Painel direito',
    standbyPanels: 'Painéis', standbyPane: n => `Painel ${n}`,
    standbyPaneSecond: 'Segundo cartão (deslizar)', standbyPaneNone: 'Nenhum',
    paneWheel: 'Roda de progresso', paneWheelTime: 'Roda + relógio', paneCalendar: 'Calendário',
    paneFocus: 'Foco', paneKanban: 'Kanban', paneTasksByCategory: 'Tarefas por categoria',
    notesLastEdit: 'Editado', notesFolder: 'Pasta', notesNoFolder: 'Sem pasta', notesNewFolder: 'Nova pasta',
    notesFolderName: 'Nome da pasta', notesRenameFolder: 'Renomear pasta', notesDeleteFolder: 'Eliminar pasta', notesMoveTo: 'Mover para',
    notesEdit: 'Editar', notesPreview: 'Pré-visualizar', notesBack: 'Voltar',
    chunkLoadError: 'Não foi possível carregar esta parte.', chunkRetry: 'Tentar novamente',
    apps: 'Apps', appsSearch: 'Procurar apps', appsNoResults: 'Nenhuma app encontrada.', notes: 'Notas',
    notesEnable: 'Ativar Notas', notesEnableDesc: 'Adiciona um separador de notas rápidas.',
    notesNew: 'Nova nota', notesTitle: 'Título', notesBody: 'Escreve algo…', notesSearch: 'Procurar notas',
    notesEmpty: 'Ainda sem notas.', notesFavorite: 'Favorito', notesText: 'Texto', notesCanvas: 'Escrita à mão',
    collabApp: 'Colaboração',
    eiCalendar: 'Calendário EI', eiCalendarEnable: 'Mostrar calendário EI',
    eiCalendarEnableDesc: 'Adiciona ao calendário o calendário oficial do curso de EI do teu ano, só de leitura e sempre atualizado.',
    eiCalendarDisableTitle: 'Ocultar calendário EI?', eiCalendarDisableDesc: 'Deixa de mostrar os eventos do calendário EI. Nada é apagado e podes reativar quando quiseres.',
    semester: 'Semestre', classes: 'Disciplinas', gradeComponents: 'Componentes de avaliação',
    kanbanColumns: 'Colunas do Kanban', general: 'Geral', data: 'Dados e sincronização',
    holidays: 'Feriados',
    exportJson: 'Exportar JSON', importJson: 'Importar JSON',
    semesterAvg: 'Média do semestre', ectsPassedLabel: 'ECTS obtidos',
    targetGrade: 'Nota alvo',
    previousSemesters: 'Semestres anteriores',
    courseAvg: 'Média do curso', finalGrade: 'Nota final', previousAvg: 'Média anterior', numSemesters: 'Nº de semestres',
    getStarted: 'Começar', welcomeTitle: 'Bem-vindo ao Organizador',
    welcomeDesc: 'O teu espaço para a vida universitária. Configura o semestre e organiza-te.',
    step1: 'Define as datas do semestre', step2: 'Adiciona as tuas disciplinas', step3: 'Planeia tarefas e acompanha avaliações',
    obNext: 'Seguinte', obBack: 'Voltar', obFinish: 'Concluir', obSkip: 'Saltar',
    obWelcomeTitle: 'Bem-vindo ao Organizador', obWelcomeDesc: 'O teu espaço calmo para a vida universitária. Escolhe idioma e tema para começar.',
    obModeTitle: 'Como vais usar?', obModeDesc: 'Ativa o que te serve. Podes ter ambos.',
    obModeWorkToggle: 'Modo trabalho', obModeWorkToggleDesc: 'Grupos em vez de disciplinas, sem avaliações.',
    obModeWeeksToggle: 'Sem semestres', obModeWeeksToggleDesc: 'Organiza por semana do calendário.',
    obImportOr: 'ou restaura uma cópia',
    obDatesTitle: 'O teu semestre', obDatesDesc: 'Quando começa e termina?',
    obClassesTitle: 'As tuas disciplinas', obClassesDesc: 'Adiciona as disciplinas que tens.',
    obGroupsTitle: 'Os teus grupos', obGroupsDesc: 'Adiciona os grupos com que trabalhas.',
    obInfoTasksTitle: 'Tarefas e Kanban', obInfoTasksDesc: 'Adiciona tarefas por semana ou data e arrasta-as pelo quadro kanban.',
    obInfoCalTitle: 'Calendário e Foco', obInfoCalDesc: 'Vê tudo no calendário e faz sessões de foco para produzir.',
    obInfoDoneTitle: 'Está tudo pronto', obInfoDoneDesc: 'Podes mudar isto mais tarde nas definições.',
    shareLink: 'Copiar link de partilha', qrCode: 'Código QR', linkCopied: 'Link copiado!',
    high: 'Alta', medium: 'Média', low: 'Baixa', none: 'Nenhuma',
    addSemester: 'Adicionar semestre', semesterName: 'Nome do semestre', startDate: 'Data de início', endDate: 'Data de fim',
    weeks: n => `${n} semanas`, addAClass: 'Adicionar disciplina', className: 'Nome da disciplina', ects: 'ECTS', colour: 'Cor',
    addComponent: 'Adicionar componente', componentName: 'Nome do componente',
    taskSpanLabel: 'Comportamento de tarefas multi-semana', taskSpanDesc: 'Quando uma tarefa abrange várias semanas, como é marcada como concluída?',
    kanbanChecklistInlineLabel: 'Pré-visualização da checklist no Kanban',
    kanbanChecklistInlineDesc: 'Mostra os itens da checklist diretamente nos cartões sem abrir os detalhes.',
    kanbanChecklistPreviewNone: 'Ocultar nos cartões',
    kanbanChecklistPreviewAll: 'Mostrar em todos os cartões',
    kanbanChecklistPreviewPerCard: 'Caso a caso',
    kanbanAutoAddLabel: 'Adicionar tarefas ao quadro automaticamente',
    kanbanAutoAddDesc: 'Adiciona automaticamente as tarefas desta semana à primeira coluna do quadro Kanban.',
    widgetsLabel: 'Widgets no ecrã principal',
    widgetsDesc: 'Mostra tarefas, o dia de hoje e contagens do Kanban no ecrã principal.',
    widgetsEncryptionWarning: 'Os widgets não conseguem ler dados encriptados. Se os ativares, o conteúdo que mostram fica guardado sem encriptação neste dispositivo. É apagado quando bloqueias a app.',
    gradeScaleLabel: 'Escala de avaliação',
    gradeScaleDesc: 'Nota máxima possível. Os campos de nota ficam limitados a este valor.',
    passingGradeLabel: 'Nota mínima de aprovação',
    passingGradeDesc: 'Nota mínima para passar. Usada nas marcas de aprovação e como nota-alvo por omissão.',
    focusAlertModeLabel: 'Modo de alerta no foco',
    focusAlertModeDesc: 'Escolhe como os alertas de foco aparecem quando a fase do cronómetro muda.',
    focusAlertNone: 'Nenhum',
    focusAlertVibration: 'Vibração',
    focusAlertNotification: 'Notificação',
    focusAlertBoth: 'Ambos',
    taskAlertModeLabel: 'Alertas de prazo das tarefas',
    taskAlertModeDesc: 'Escolhe como os alertas de prazo das tarefas são apresentados.',
    taskAlertNone: 'Nenhum',
    taskAlertInApp: 'Na app',
    taskAlertNotification: 'Notificação',
    taskAlertBoth: 'Ambos',
    taskAlertNextDayTimeLabel: 'Hora do alerta para amanhã',
    taskAlertNextDayTimeDesc: 'Hora dos lembretes para tarefas com prazo amanhã.',
    taskDefaultToCalendarLabel: 'Tarefas no calendário por defeito',
    taskDefaultToCalendarDesc: 'Novas tarefas terão "Mostrar no calendário" ativado por defeito.',
    hideCompletedTasksLabel: 'Arrumar tarefas concluídas',
    hideCompletedTasksDesc: 'Mantém a lista focada no que falta. As tarefas concluídas vão para uma secção "Concluídas" que podes abrir quando quiseres.',
    completedTasks: count => `Concluídas (${count})`,
    speechInputLabel: 'Voz para texto',
    speechInputDesc: 'Mostrar um botão de microfone para ditar texto nos campos de tarefas, eventos e notas.',
    taskDueTodayTitle: count => count === 1 ? 'Tarefa para hoje' : `${count} tarefas para hoje`,
    taskAlertHide: 'Ocultar alerta',
    taskAlertRemindMeAt: 'Lembrar-me às',
    settingEnabled: 'Ativado', settingDisabled: 'Desativado',
    spanSingle: 'Uma checkbox global (concluída uma vez)', spanPerWeek: 'Checkbox por semana',
    dangerZone: 'Zona de perigo', deleteSemester: 'Eliminar este semestre',
    clearPomodoros: 'Limpar pomodoros',
    clearPomodorosTitle: 'Limpar todos os pomodoros?',
    clearPomodorosDesc: 'Todos os pomodoros caídos serão eliminados permanentemente.',
    deleteSemesterTitle: 'Eliminar semestre?', deleteSemesterDesc: 'Todas as tarefas, avaliações e dados do Kanban deste semestre serão eliminados permanentemente.',
    clearDoneTitle: 'Limpar coluna concluída?', clearDoneDesc: 'Todos os cartões da coluna Concluído serão eliminados.',
    wipeAllTitle: 'Apagar todos os cartões?', wipeAllDesc: 'Todos os cartões do quadro serão eliminados permanentemente.',
    selectSemester: 'Selecionar semestre', noClassesYet: 'Ainda sem disciplinas', addClassesInSettings: 'Adiciona disciplinas em Definições.',
    addUnlocks: 'Adiciona um semestre para desbloquear o resto.',
    checklist: 'Lista de verificação', addItem: 'Adicionar item', editCard: 'Editar cartão',
    notAchievable: '— impossível de atingir', onRemaining: ' nas componentes restantes',
    youNeed: 'Precisas de', allGraded: 'Todas as componentes avaliadas.',
    noGradeComponents: 'Nenhuma componente configurada. Vai a Definições.',
    deleteClassTitle: 'Eliminar disciplina?', deleteClassDesc: 'Isto irá também eliminar todas as tarefas desta disciplina.',
    holidayName: 'Nome do feriado', holidayNamePlaceholder: 'ex. Natal',
    addHoliday: 'Adicionar feriado',
    loadPreset: 'Carregar preset',
    presetLoading: 'A carregar preset…', presetError: 'Falhou ao carregar o preset.', retry: 'Tentar novamente', skip: 'Saltar',
    newColumnName: 'Nome da nova coluna',
    focusStart: 'Iniciar', focusPause: 'Pausar', focusResume: 'Retomar', focusReset: 'Reiniciar', focusSkipBreak: 'Saltar pausa',
    focusReady: 'pronto', focusBreak: 'pausa',
    focusPhrases: ['continua', 'mantém o foco', 'estás a ir bem', 'um passo de cada vez', 'trabalho profundo', 'fica presente'],
    focusEvery: 'cada (min)', focusBreakFor: 'pausa (min)',
    focusScheduledMode: 'Pausas agendadas',
    focusNextBreak: 'Próxima pausa às',
    focusFocusLabel: 'Mensagem de foco', focusBreakLabel: 'Mensagem de pausa',
    loadPresetTitle: 'Carregar um preset',
    presetGroupEI: 'Curso EI',
    presetGroupGeneric: 'Geral',
    backToMenu: 'Voltar',
    importData: 'Importar dados',
    importFromFirebase: 'Importar do Firebase',
    nextSemesterTitle: 'Semestre terminado',
    nextSemesterDesc: 'O teu semestre terminou. Carregar o próximo?',
    loadNextSemester: 'Carregar próximo semestre',
    dismissNextSemester: 'Dispensar',
    carryOverTitle: 'Transferir',
    carryKanbanCards: 'Cartões do kanban',
    carryUpcomingTasks: 'Tarefas futuras',
    carryUpcomingEvents: 'Eventos futuros',
    carryOverAlwaysKept: 'As notas e as definições são sempre mantidas.',
    carryOverDiscardWarning: 'Todo o resto deste semestre é apagado.',
    noSemesterYet: 'Nenhum semestre configurado',
    noSemesterDesc: 'Carrega um preset ou importa os teus dados para começar.',
    focusIntervalMode: 'Pausas por intervalo',
    focusIntervalEvery: 'cada (min)',
    focusIntervalBreakFor: 'pausa (min)',
    focusScheduledBreakFor: 'pausa (min)',
    focusAfterBreakReset: 'Após pausa: reiniciar timer',
    focusAfterBreakContinue: 'Após pausa: continuar a contar',
    firebaseSync: 'Sincronização Firebase',
    firebaseConnect: 'Ligar',
    firebaseConnected: 'Ligado',
    firebaseDisconnect: 'Desligar',
    firebaseSyncing: 'A sincronizar…',
    firebaseLastSync: 'Última sincronização',
    firebaseError: 'Erro de sincronização',
    firebaseRemoteNewer: 'Os dados na nuvem são de uma versão mais recente. Sincronização em pausa. Atualiza a app.',
    collabSyncFailed: 'Não foi possível sincronizar a alteração partilhada. Foi revertida.',
    newerVersionWarning: 'Os teus dados foram guardados por uma versão mais recente da app. Algumas coisas podem não aparecer corretamente até atualizares.',
    firebaseSetupTitle: 'Ligar ao Firebase',
    firebaseStep1Title: 'Criar um projeto Firebase',
    firebaseStep1Desc: 'Vai a console.firebase.google.com → Adicionar projeto → dá um nome → desativa o Google Analytics → Criar projeto.',
    firebaseStep2Title: 'Ativar o Firestore',
    firebaseStep2Desc: 'Vai a Criar → Firestore Database → Criar base de dados → escolhe uma região → Iniciar em modo de produção → Criar. Depois abre o separador Regras, substitui tudo pelas regras abaixo e clica em Publicar.',
    firebaseStep3Title: 'Obter a configuração',
    firebaseStep3Desc: 'Vai às Definições do projeto (ícone de engrenagem) → As tuas apps → Adicionar app → Web → regista a app → copia o objeto firebaseConfig mostrado.',
    firebaseStep4Title: 'Cola a configuração',
    firebaseStep4Desc: 'Cola o objeto firebaseConfig completo (em JSON) abaixo.',
    firebaseConfigPlaceholder: '{ "apiKey": "...", "authDomain": "...", "projectId": "...", ... }',
    firebaseConfigInvalid: 'Configuração inválida: deve incluir apiKey e projectId.',
    firebaseTestFailed: 'Não foi possível ligar. Verifica a configuração e as regras da base de dados.',
    firebaseSave: 'Guardar e ligar',
    pomodoroMode: 'Modo pomodoro',
    pomodoroModeDesc: 'Faz crescer tomates durante as sessões de foco. Cada sessão completa deixa cair um tomate.',
    pomodoroResetPeriod: 'Período de reset',
    pomodoroResetDay: 'Diário', pomodoroResetWeek: 'Semanal', pomodoroResetMonth: 'Mensal', pomodoroResetSemester: 'Por semestre',
    pomodoroTrackPeriodStats: 'Guardar estatísticas do período',
    pomodoroShowAbandoned: 'Mostrar tomates abandonados',
    pomodoroShowPeriodPomodoros: 'Mostrar pomodoros do período',
    pomodoroShowOverlay: 'Mostrar sobreposição global em todos os separadores',
    focusNotifTitle: 'Organizador Focus',
    focusNotifBreakBody: 'Hora da pausa pomodoro.',
    focusNotifFocusBody: 'De volta ao foco.',
    tasksNotifTitle: 'Organizador Tarefas',
    taskReminderTitle: 'Lembrete de tarefa',
    pomodoroStatsTitle: 'Estatísticas pomodoro',
    pomodoroTotal: 'Total de tomates', pomodoroAbandoned: 'Abandonados', pomodoroFocusTime: 'Tempo total de foco',
    pomodoroPeriodTotal: 'Este período', pomodoroPeriodFocus: 'Foco neste período',
    pomodoroVsSinceLast: 'vs período anterior',
    pomodoroAllTime: 'Todo o tempo',
    pomodoroInsightsDailyTitle: 'Foco diário desta semana',
    pomodoroInsightsWeeklyBreakdownTitle: 'Média por semana',
    pomodoroInsightsAvgWeekLabel: 'média por dia (semana)',
    pomodoroInsightsAvgPeriodLabel: 'média por dia (período)',
    pomodoroInsightsPerDaySuffix: '/d',
    pomodoroInsightsNoWeeklyData: 'Ainda sem dados semanais.',
    pomodoroInsightsDayLabels: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'],
    pomodoroTotalTimeLabel: 'tempo total',
    pomodoroClose: 'Fechar',
    pomodoroEraseStats: 'Apagar estatísticas',
    pomodoroEraseStatsTitle: 'Apagar estatísticas pomodoro?',
    pomodoroEraseStatsDesc: 'As estatísticas históricas de tempo de foco serão removidas, mas os registos de tomates mantêm-se.',
    pomodoroGraceCancel: 'Cancelar (sem tomate)',
    pomodoroGrace: s => `${s}s para cancelar sem perder um tomate`,
    workModeLabel: 'Modo trabalho',
    workModeDesc: 'Oculta avaliações e renomeia disciplinas para grupos.',
    workModeOnboarding: 'Usar para trabalho?',
    semesterModeLabel: 'Modo sem semestres',
    semesterModeDesc: 'Liga para usar semanas do ano em vez de semestres. As avaliações ficam ocultas.',
    semesterModeNone: 'Sem semestres (semanas do ano)',
    semesterModeSemesters: 'A usar semestres',
    semesterModeOnboarding: 'Sem semestres, só semanas?',
    groups: 'Grupos', group: 'Grupo', addAGroup: 'Adicionar grupo', groupName: 'Nome do grupo',
    deleteGroupTitle: 'Eliminar grupo?', deleteGroupDesc: 'Isto irá também eliminar todas as tarefas deste grupo.',
    storageWarningTitle: 'Limite de armazenamento atingido',
    storageWarningDesc: 'Por favor ativa a sincronização Firebase, atingiste o limite de armazenamento local.',
    storageWarningAction: 'Percebido',
    collabConnect: 'Ligar Organizer Collab',
    collabDisconnect: 'Desligar Organizer Collab',
    collabRequiresFirebase: 'Liga primeiro a sincronização Firebase para usar o Organizer Collab.',
    collabGuideTitle: 'Configuração do Organizer Collab',
    collabGuideIntro: 'Configuração única. Faz estes 4 passos no Firebase e depois volta para ativar o collab.',
    collabGuideImportantTitle: 'O que muda quando ativas collab',
    collabGuideImportant1: 'A base de dados passa a exigir utilizadores autenticados (anónimo chega).',
    collabGuideImportant2: 'A sincronização normal do organizer continua a funcionar, mas autentica primeiro.',
    collabGuideImportant3: 'Se desligares collab mais tarde, podes continuar com regras baseadas em auth sem problemas.',
    collabGuideStep1: 'Abre Firebase Console > Build > Firestore Database > Regras.',
    collabGuideStep2: 'Cola o snippet de regras abaixo e clica em Publicar.',
    collabGuideStep3: 'Abre Security > Authentication > Método de início de sessão > ativa Anónimo > Guardar.',
    collabGuideStep4: 'Volta ao Organizer e carrega em "Já configurei as regras, ativar collab".',
    collabGuideRulesLabel: 'Regras Firestore',
    collabRulesHelpTitle: "Regras do Firestore",
    collabRulesHelpHost: "As regras do Firestore da tua equipa estão desatualizadas ou demasiado restritas. Cola as regras abaixo na consola Firebase e recarrega.",
    collabRulesHelpMember: "Não é possível aceder a esta equipa. Só o anfitrião pode resolver — envia-lhe as regras abaixo para colar na consola Firebase.",
    copy: "Copiar",
    copied: "Copiado!",
    collabGuideGotIt: "Entendido",
    collabFirebaseOnlyForCreating: "O Firebase só é necessário para criar equipas. Podes juntar-te a uma a partir de um link de convite sem ele.",
    collabGuideTroubleshootTitle: 'Se aparecer erro signUp 400',
    collabGuideTroubleshootBody: 'Significa que a autenticação Anónima ainda está desativada no Firebase. Ativa em Security > Authentication > Método de início de sessão.',
    collabEnableNow: 'Já configurei as regras, ativar collab',
    collabPanelTitle: 'Organizer Collab',
    collabPanelSubtitle: 'Cria equipas, convida pessoas e partilha tarefas/cartões do kanban.',
    collabCreateTeam: 'Criar equipa',
    collabTeamName: 'Nome da equipa',
    collabTeamDays: 'dias da equipa',
    collabTeamDuration: 'duração da equipa',
    collabDays: 'dias',
    collabJoinTeam: 'Entrar na equipa',
    collabInvitePlaceholder: 'Cola o link de convite',
    collabInviteTtl: 'Validade do convite',
    collabYourTeams: 'As tuas equipas',
    collabNoTeams: 'Ainda sem equipas.',
    collabShare: 'Partilhar',
    collabShareTask: 'Partilhar tarefa',
    collabShareCard: 'Partilhar cartão',
    collabSelectTeam: 'Escolher equipa',
    collabRoleHost: 'host',
    collabRoleMember: 'membro',
    all: "Tudo",
    collabAlias: "O teu nome",
    collabEditAlias: "Editar nome",
    collabMembers: "Membros",
    collabAssignedOnlyComplete: "Só o responsável pode concluir",
    collabKanbanDividers: "Divisórias do Kanban",
    collabSeparateByTeam: "Separar por equipa",
    collabPersonal: "Pessoal",
    collabUnassigned: "Sem responsável",
    collabMe: "Eu",
    collabAssignee: "Responsável",
    collabSeparateByClass: "Separar por disciplina",
    kanbanAllTeams: "Todas as equipas",
    kanbanAllAssignees: "Todos os responsáveis",
    kanbanAllClasses: "Todas as disciplinas",
    kanbanFilterTeam: "Equipa",
    kanbanFilterClass: "Disciplina",
    kanbanNoClass: "Sem disciplina",
    kanbanResetFilters: "Limpar",
    collabEndsAt: 'termina em',
    collabInvite: 'Convidar',
    collabEditTeam: 'Editar equipa',
    collabTaskCompletionMode: 'Conclusão de tarefas partilhadas',
    collabTaskCompletionPersonal: 'conclusão pessoal',
    collabTaskCompletionForAll: 'marcar para todos',
    collabTaskPermissions: 'Permissões de edição de tarefas',
    collabTaskPermissionsEveryone: 'qualquer membro pode adicionar/editar/remover tarefas',
    collabTaskPermissionsHostOnly: 'apenas o host pode adicionar/editar/remover tarefas',
    collabLeave: 'Sair',
    collabDeleteTeam: 'Eliminar',
    collabDefaultTeamName: 'Equipa',
    collabLeavePrompt: 'Sair desta equipa?',
    collabLeaveWithLocalPrompt: 'Partilhaste tarefas locais nesta equipa. Queres mantê-las localmente?',
    collabDeleteTeamPrompt: 'Eliminar esta equipa?',
    collabDeleteTeamWithLocalPrompt: 'Partilhaste tarefas locais nesta equipa. Queres mantê-las localmente antes de eliminar a equipa?',
    collabKeepLocalTasks: 'Manter locais',
    collabDeleteLocalTasksToo: 'Apagar as locais',
    collabErrorCreate: 'Não foi possível criar a equipa.',
    collabErrorInvite: 'Não foi possível gerar convite.',
    collabErrorJoin: 'Não foi possível entrar na equipa.',
    collabErrorInvalidLink: 'Link de convite inválido.',
    collabErrorDeleteTeam: 'Não foi possível eliminar a equipa.',
    collabGuideChecklistTitle: 'Ainda não sincroniza?',
    collabGuideChecklistBody: 'Os dois passos que o Organizer não faz por ti: ativar a autenticação anónima e publicar as regras do Firestore acima. Se as tarefas partilhadas nunca aparecem, falta um destes no projeto do anfitrião.',
    collabSyncErrorHint: 'Não é possível aceder a esta equipa. Verifica se o Firebase do anfitrião tem a autenticação anónima ativada e regras abertas.',
    collabKeyRequiredHint: "Esta equipa está encriptada e o teu link de convite não tinha chave. Pede um novo link de convite.",
    collabOutdatedTeamHint: "Esta equipa está desatualizada e já não sincroniza. Pede uma equipa nova ao anfitrião.",
    collabErrorPermission: 'Bloqueado pelas regras do Firebase. O anfitrião tem de ativar a autenticação anónima e abrir as regras do Firestore.',
    collabErrorAuthDisabled: "O início de sessão anónimo está desativado no projeto Firebase do anfitrião. O anfitrião tem de o ativar em Authentication › Sign-in method.",
    collabErrorNotFound: 'Equipa não encontrada. Pode ter sido eliminada.',
    collabErrorInviteExpired: 'Este convite expirou. Pede um novo link ao anfitrião.',
    collabErrorInviteInvalid: 'Este link de convite não é válido para essa equipa.',

    nlpToday: ["today"],
    nlpTomorrow: ["tomorrow"],
    nlpNextWeek: ["next week"],
    nlpAt: ["at"],
    nlpDow: [["sunday","sun"],["monday","mon"],["tuesday","tue"],["wednesday","wed"],["thursday","thu"],["friday","fri"],["saturday","sat"]],
    voiceInputAria: "Dictate by voice",
    voiceInputStopAria: "Stop dictation",
    quickActionTaskWordsPlural: ['tarefas'],
    quickActionEventWordsPlural: ['eventos do calendário', 'eventos do calendario', 'eventos'],
    quickActionCardWordsPlural: ['cartões kanban', 'cartoes kanban', 'cartões', 'cartoes'],
    quickActionRespectivelyWords: ['respectivamente'],
    quickActionOrdinalWords: ['primeiro', 'segundo', 'terceiro', 'quarto', 'quinto', 'sexto', 'sétimo', 'oitavo', 'nono', 'décimo', 'primeira', 'segunda', 'terceira', 'quarta', 'quinta', 'sexta', 'sétima', 'oitava', 'nona', 'décima'],
    eventAllDay: "All day",
    eventStartTime: "Start time",
    eventEndTime: "End time",
    viewDay: "Dia",
    viewWeek: "Semana",
    viewMonth: "Mês",
    viewYear: "Ano",
    notesMentionNoResults: "No matching tasks",
    notesMentionDeletedTask: "Deleted task",
    notesArchive: "Archive",
    notesUnarchive: "Unarchive",
    notesArchived: "Archived",
    notesArchivedEmpty: "No archived notes.",
    eisenhower: "Matriz de Eisenhower",
    eisenhowerEnable: "Ativar Matriz de Eisenhower",
    eisenhowerEnableDesc: "Adiciona um separador para ordenar tarefas por urgência e importância.",
    eisenhowerDoNow: "Urgente e Importante",
    eisenhowerSchedule: "Importante, Não Urgente",
    eisenhowerDelegate: "Urgente, Não Importante",
    eisenhowerEliminate: "Nenhum dos dois",
    eisenhowerUnsorted: "Tarefas por ordenar",
    eisenhowerUnsortedEmpty: "Nada para ordenar.",
    eisenhowerEmpty: "Arraste tarefas para aqui.",
    pomodoro: "Pomodoro",
    pomodoroOverlayFocusing: "em foco",
    pomodoroStreakTitle: "Sequência",
    pomodoroCurrentStreak: "Sequência atual",
    pomodoroBestStreak: "Melhor sequência",
    pomodoroStreakDaySuffix: "d",
    pomodoroTrendTitle: "Tendência mensal",
    pomodoroTrendNoData: "Ainda não há dados mensais.",
    pomodoroCopySummary: "Copiar resumo",
    pomodoroCopiedSummary: "Copiado!",
    firebaseRulesTemplateLink: "View Firestore rules template",
    firebaseOpenRulesWarningTitle: "Your database rules may be open",
    firebaseOpenRulesWarningDesc: "Sync is working without authentication, which usually means your Firestore rules allow anyone to read and write your data. Publish the rules template linked below to lock this down.",
    firebaseEncryptionOffTitle: "End-to-end encryption is off",
    firebaseEncryptionOffDesc: "Your data is stored in Firestore as plain text. Turn on encryption so only devices with your key can read it — even if your database rules are ever misconfigured.",
    firebaseEncryptNow: "Encrypt now",
    firebaseEncryptMigrateFailed: "Could not enable encryption. Check your connection and try again.",
    firebaseHaveKeyAlready: "This device already has a key from another install",
    firebaseKeyPastePlaceholder: "Paste your recovery key",
    firebaseKeyInvalid: "That does not look like a valid key.",
    firebaseKeyWrongOrUnreadable: "Could not decrypt with this key. Double check it and try again.",
    firebaseRecoveryKeyShownOnceTitle: "Save this recovery key now",
    firebaseRecoveryKeyShownOnceDesc: "This key is shown only once and is never sent to Firebase. Anyone with it can read your data; anyone without it (including you) cannot recover it if lost. Store it somewhere safe.",
    firebaseKeySavedItConfirm: "I've saved my key",
    firebaseEncryptionOnTitle: "End-to-end encryption is on",
    firebaseEncryptionOnDesc: "Os teus dados são encriptados neste dispositivo — no armazenamento local e antes de chegarem ao Firestore. Só dispositivos com a chave de recuperação os conseguem desencriptar.",
    firebaseShowRecoveryKey: "Show recovery key",
    firebaseShowRecoveryKeyConfirmTitle: "Show recovery key?",
    firebaseShowRecoveryKeyConfirmDesc: "Anyone who sees this key can decrypt your data. Only do this somewhere private.",
    firebaseKeyRequiredTitle: "Encryption key needed",
    firebaseKeyRequiredDesc: "This project’s data is encrypted. Paste the recovery key from a device that already has it to unlock sync on this device.",
    firebaseKeyRequiredForImport: "This backup is encrypted. Set up sync with the matching key first, then import again.",
    exportEncrypted: "Organizer format (encrypted)",
    encUnlockTitle: "Desbloquear os teus dados",
    encUnlockDesc: "Este dispositivo tem dados encriptados. Introduz a tua palavra-passe para os desbloquear.",
    encUnlockHintLabel: "A tua dica",
    encPassphraseLabel: "Palavra-passe",
    encPassphrasePlaceholder: "A tua palavra-passe",
    encPassphraseConfirmLabel: "Confirmar palavra-passe",
    encPassphraseMismatch: "As duas palavras-passe não coincidem.",
    encPassphraseTooShort: "Usa pelo menos 8 caracteres.",
    encHintLabel: "Dica da palavra-passe (opcional)",
    encHintPlaceholder: "Um lembrete privado, não a própria palavra-passe",
    encRecoveryCodeTitle: "Guarda o teu código de recuperação",
    encRecoveryCodeDesc: "Estas 12 palavras em inglês são a única forma de voltar a entrar se te esqueceres da palavra-passe. Escreve-as ou guarda-as num gestor de palavras-passe. Não as podemos mostrar outra vez.",
    encRecoveryCodeWordsNote: "12 palavras em inglês. Copia-as exatamente, pela mesma ordem.",
    encRecoveryCodeSavedConfirm: "Já guardei o meu código de recuperação",
    encRecoveryCodeQr: "Mostrar código QR",
    encRecoveryCodeQrDesc: "Lê isto noutro dispositivo para transferir o código de recuperação.",
    encUseRecoveryCode: "Usar o código de recuperação",
    encUsePassphrase: "Usar a palavra-passe",
    encRecoveryCodeLabel: "Código de recuperação",
    encRecoveryCodePlaceholder: "doze palavras separadas por espaços",
    encRecoveryCodeInvalid: "Este não é um código de recuperação válido de 12 palavras.",
    encUnlockFailed: "Não foi possível desbloquear com isso. Verifica e tenta outra vez.",
    encUnlocking: "A desbloquear…",
    encDeriving: "A derivar a chave…",
    encEnableTitle: "Ativar encriptação ponta a ponta",
    encEnableDesc: "Os teus dados são encriptados neste dispositivo antes de chegarem ao Firestore. Só dispositivos com a tua palavra-passe ou código de recuperação os conseguem ler.",
    encEnableWarning: "Se perderes a palavra-passe e o código de recuperação, os teus dados não podem ser recuperados por ninguém, incluindo nós.",
    encEnableSubmit: "Ativar encriptação",
    encEnableFailed: "Não foi possível ativar a encriptação. Verifica a ligação e tenta outra vez.",
    encManageTitle: "Encriptação",
    encManageDesc: "Os teus dados estão encriptados ponta a ponta. O desbloqueio acontece só neste dispositivo.",
    encChangePassphrase: "Mudar a palavra-passe",
    encChangePassphraseDesc: "Introduz a palavra-passe atual e depois a nova.",
    encCurrentPassphraseLabel: "Palavra-passe atual",
    encRegenerateRecoveryCode: "Gerar um novo código de recuperação",
    encRegenerateRecoveryCodeDesc: "Substitui o código existente. O antigo deixa de funcionar.",
    encEditHint: "Editar a dica",
    encRotateDekTitle: "Rodar a chave de encriptação",
    encRotateDekDesc: "Volta a encriptar todos os teus dados com uma chave nova. Os outros dispositivos terão de desbloquear novamente.",
    encRotateDekWarning: "Não feches a app até isto terminar.",
    encRotating: "A voltar a encriptar…",
    encRotateFailed: "Não foi possível rodar a chave. Nada foi alterado.",
    encSaved: "Guardado.",
    encStoreUnavailableTitle: "Não foi possível acessar o armazenamento seguro",
    encStoreUnavailableDesc: "Este navegador bloqueou o cofre de chaves, o que costuma acontecer em navegação privada. Os teus dados encriptados ficaram intactos. Tenta numa janela normal.",
    encPlaintextSyncWarnTitle: "A sincronização não está encriptada",
    encPlaintextSyncWarnDesc: "Os teus dados são guardados no Firestore em texto simples. Quem conseguir ler a tua base de dados consegue lê-los.",
    encPlaintextSyncEnable: "Ativar encriptação",
    encPlaintextSyncDismiss: "Agora não, e não perguntar outra vez",
    encRemoteAlreadyEncrypted: "Este projeto já está encriptado. Desbloqueia-o para ligar este dispositivo.",
    encRemoteNotEncryptedTitle: "Encriptar este projeto?",
    encRemoteNotEncryptedDesc: "Este projeto tem dados não encriptados. Ativa a encriptação agora e serão novamente carregados encriptados.",
    encRemoteNotEncryptedMigrate: "Encriptar e migrar",
    encRemoteNotEncryptedSkip: "Manter sem encriptação",
    encRemoteUnrecoverable: "Este projeto está encriptado mas não tem dados de recuperação, por isso não pode ser desbloqueado. Desliga-te e começa um projeto novo.",
    encRemoteDekMismatch: "Este projeto foi novamente encriptado com uma chave nova. Desbloqueia-o outra vez com a palavra-passe ou o código de recuperação.",
    encExportPassphraseTitle: "Proteger esta cópia de segurança",
    encExportPassphraseDesc: "Escolhe uma palavra-passe para o ficheiro. Vais precisar dela para restaurar, em qualquer dispositivo.",
    encImportPassphraseTitle: "Desbloquear esta cópia de segurança",
    encImportPassphraseDesc: "Introduz a palavra-passe que escolheste ao exportar.",
    encImportPassphraseFailed: "Palavra-passe errada para esta cópia de segurança.",
    encTitle: "Encriptação",
    encOffTitle: "A encriptação está desativada",
    encOffDesc: "Os teus dados são guardados em texto simples onde quer que estejam. Ativa a encriptação e ficam ilegíveis sem a tua palavra-passe, neste dispositivo e em qualquer sítio onde sincronizem.",
    encOnDesc: "Os teus dados são encriptados antes de serem guardados ou sincronizados. Só dispositivos com a tua palavra-passe ou código de recuperação os conseguem ler.",
    encLockedDesc: "Os teus dados guardados estão encriptados. Introduz a palavra-passe para os desbloquear neste dispositivo.",
    encEnableAction: "Ativar encriptação",
    encDisableAction: "Desativar encriptação",
    encDisableTitle: "Desativar a encriptação?",
    encDisableDesc: "Os teus dados voltam a ser escritos em texto simples onde estiverem guardados e a palavra-passe e o código de recuperação deixam de funcionar.",
    encStorageShedTitle: "Alguns dados não couberam",
    encStorageShedDesc: "Este dispositivo ficou sem armazenamento local, por isso o seguinte não foi guardado localmente:",
    exportPlaintext: "Human-readable (plaintext JSON)",
    repeat: "Repetir",
    repeatFreqLabel: "Frequência",
    repeatFreqDaily: "Diário",
    repeatFreqWeekly: "Semanal",
    repeatFreqMonthly: "Mensal",
    repeatEvery: () => 'A cada',
    repeatIntervalDaily: n => (n === 1 ? 'dia' : 'dias'),
    repeatIntervalWeekly: n => (n === 1 ? 'semana' : 'semanas'),
    repeatIntervalMonthly: n => (n === 1 ? 'mês' : 'meses'),
    repeatUntil: "Até (opcional)",
    kanbanColTodo: "A fazer", kanbanColInProgress: "Em curso", kanbanColDone: "Concluído",
    colourCustom: "Cor personalizada",
    googleCalendar: "Google Calendar",
    gcalConnect: "Connect",
    gcalConnected: "Connected",
    gcalConnecting: "Connecting…",
    gcalDisconnect: "Disconnect",
    gcalEnable: "Sync with Google Calendar",
    gcalScopeNotice: "This grants full read/write access to your primary Google Calendar (the \"calendar\" scope). Organizer only reads and writes events you interact with here; your Google credentials never leave your device and are not sent anywhere but Google.",
    gcalStep1Title: "Create a Google Cloud project",
    gcalStep1Desc: "Go to console.cloud.google.com → create a new project (or pick one) → APIs & Services → enable the \"Google Calendar API\".",
    gcalStep2Title: "Configure OAuth consent + credentials",
    gcalStep2Desc: "APIs & Services → OAuth consent screen → set it up (External is fine for personal use, add yourself as a test user). Then Credentials → Create credentials → OAuth client ID → Application type: Web application → add this app's URL to Authorized JavaScript origins.",
    gcalStep3Title: "Paste your Client ID",
    gcalStep3Desc: "Copy the Client ID (ends in .apps.googleusercontent.com) shown after creating it, and paste it below. This value is not secret and is safe to store in this browser.",
    gcalClientIdPlaceholder: "xxxxxxxx.apps.googleusercontent.com",
    gcalClientIdInvalid: "Enter a valid OAuth Client ID.",
    gcalConnectFailed: "Could not connect. Check your Client ID and try again.",
    gcalDisableTitle: "Disconnect Google Calendar?",
    gcalDisableDesc: "Stops syncing with Google Calendar on this device. Events already created stay in both places; sync bookkeeping (Client ID, links) is removed here.",
    eventSyncToGoogle: "Sync to Google Calendar",
    eventSyncToGoogleDesc: "Push this event to your connected Google Calendar.",
    quickActionTaskWords: ["tarefa"],
    quickActionEventWords: ["evento do calendário","evento do calendario","evento"],
    quickActionCardWords: ["cartão kanban","cartao kanban","cartão","cartao"],
    quickActionAddWords: ["adiciona","adicionar","cria","criar","adicione","crie"],
    quickActionForWords: ["para","de"],
    quickActionAndWords: ["e"],
    quickActionOnWords: ["em","no","na","dia"],
    quickActionArticleWords: ["um","uma","uns","umas","o","os","as"],
    quickActionBoardWords: ["kanban","quadro"],
    quickAction: "Quick action",
    quickActionPlaceholder: "e.g. add task and calendar event for a cbd test on 18/07 at 15h",
    quickActionTab: "Quick action",
    quickActionFormTab: "Form",
    quickActionPreviewTitle: "Will create",
    quickActionPreviewTask: "task",
    quickActionPreviewTaskCalendar: "task (shown on calendar)",
    quickActionPreviewEvent: "calendar event",
    quickActionPreviewCard: column => `kanban card in ${column}`,
    quickActionEmpty: "Couldn't understand that. Try rephrasing.",
    quickActionCreate: "Create",
    quickActionBack: "Back",
    notesDeleteConfirmTitle: "Delete this note?",
    notesDeleteConfirmDesc: "This note will be permanently deleted.",
    notesEmptyTitle: "No notes yet",
    notesEmptyDesc: "Create your first note to get started.",
    notesFilterEmpty: "No notes match your search.",
    notesSelectNote: "Select a note to start editing",
    notesTextNote: "Text note",
    notesCanvasNote: "Canvas note",
    eventStartTimeFirstDay: "Hora de início (primeiro dia)",
    eventEndTimeLastDay: "Hora de fim (último dia)",
    notesBold: "Negrito",
    notesItalic: "Itálico",
    notesStrike: "Rasurado",
    notesHeading1: "Título 1",
    notesHeading2: "Título 2",
    notesHeading3: "Título 3",
    notesBulletList: "Lista com marcadores",
    notesOrderedList: "Lista numerada",
    notesTaskList: "Lista de verificação",
    notesQuote: "Citação",
    notesInsertTable: "Inserir tabela",
    notesCodeBlock: "Bloco de código",
    notesDivider: "Separador",
    notesAddLink: "Adicionar ligação",
    notesRemoveLink: "Remover ligação",
    notesTextColor: "Cor do texto",
    notesColorReset: "Cor predefinida",
    notesColorCustom: "Escolher cor personalizada",
    notesColorApply: "Aplicar",
    notesExport: "Exportar nota",
    notesImport: "Importar nota",
    notesGraphEdit: "Editar gráfico",
    notesGraphRange: "x de",
    notesGraphResize: "Arrasta para redimensionar",
    notesGraphResizeWidth: "Arrasta para redimensionar largura e altura",
    notesGraphInvalid: "Expressão não representável",
    notesGraphAlignleft: "Alinhar à esquerda",
    notesGraphAligncenter: "Centrar",
    notesGraphAlignright: "Alinhar à direita",
    notesTextSize: "Tamanho do texto",
    notesSizeNormal: "Normal",
    notesSizeSmall: "Pequeno",
    notesSizeLarge: "Grande",
    notesSizeHuge: "Enorme",
    notesUndo: "Anular",
    notesRedo: "Refazer",
    notesViewList: "Vista de lista",
    notesViewMosaic: "Vista de mosaico",
    notesMathEnable: "Resolver matemática",
    notesMathEnableDesc: "Escreve uma equação terminada em = e prime Enter para a resolver. Usa x para desenhar um gráfico.",
    notesMathSolve: "Resolver em ordem a x",
    notesMathSolveDesc: "Transforma 3x = 3 em x = 1, incluindo inequações e equações do 2.º grau.",
    notesMathSelection: "Gráfico da seleção",
    notesMathSelectionDesc: "Seleciona uma equação e prime Enter para a desenhar.",
    notesMathSteps: "Mostrar os passos",
    notesMathStepsDesc: "Mostra cada passo da resolução em vez de apenas o resultado.",
    eisenhowerAddTask: "Adicionar tarefa",
    eisenhowerCustomize: "Personalizar quadrantes",
    eisenhowerResetDefaults: "Repor predefinições",
    eisenhowerCleanDone: "Limpar concluídas",
    eisenhowerCleanDoneTitle: "Limpar tarefas concluídas?",
    eisenhowerCleanDoneDesc: "Remove as tarefas concluídas da matriz. Continuam na tua lista de tarefas.",
    quickActionApp: "Quick Action",
    quickActionAppEnable: "Enable Quick Action",
    quickActionAppEnableDesc: "Adds a spotlight overlay for quickly creating tasks, events, and cards.",
    quickActionTripleTapEnable: "Toque triplo no ecrã", quickActionTripleTapEnableDesc: "Toque 3 vezes em qualquer lugar para abrir o Quick Action",
    quickActionShortcutEnable: "Keyboard shortcut",
    quickActionShortcutKey: "Shortcut",
    quickActionNavbarButton: "Show in navbar add menu",
    spotlightPlaceholder: "Quick action… (e.g. add task for exam on Monday)",
    themeColor: "Accent color",
    themeColorDesc: "Pick a color for buttons, links, and highlights.",
    themeColorReset: "Reset to default",
    themeFontColor: "Cor da fonte", themeHighlightColor: "Cor de destaque", themeBgColor: "Cor de fundo",
    defaultTabLabel: "Ecrã inicial", defaultTabDesc: "Escolhe o separador em que a app abre.",
    defaultTabLast: "Último usado",
    taskReminderOffsetsLabel: "Antecedência dos lembretes", taskReminderOffsetsDesc: "Quantos dias antes do prazo te devemos lembrar. Aplica-se a todas as tarefas com prazo.",
    taskReminderTimeLabel: "Hora do lembrete", taskReminderTimeDesc: "Hora a que os lembretes antecipados aparecem.",
    taskReminderAddOffset: "Dias",
    taskReminderOffsetDays: n => (n === 0 ? "No próprio dia" : n === 1 ? "1 dia antes" : `${n} dias antes`),
    taskReminderIn: n => (n === 0 ? "Entrega hoje" : n === 1 ? "Entrega amanhã" : `Entrega em ${n} dias`),
    habits: "Hábitos", habitsEnable: "Ativar Hábitos", habitsEnableDesc: "Acompanha hábitos de longo prazo com um botão de registo e um calendário de sequências.",
    habitsEmpty: "Ainda não há hábitos. Adiciona um para começar.",
    habitAdd: "Adicionar hábito", habitEdit: "Editar hábito",
    habitTitleLabel: "Hábito", habitTitlePlaceholder: "Ler 20 minutos",
    habitCadenceLabel: "Registar", habitCadenceDesc: "Com que frequência queres clicar no botão.",
    habitCadenceDaily: "Todos os dias", habitCadence2Days: "A cada 2 dias", habitCadence3Days: "A cada 3 dias",
    habitCadenceWeekly: "Todas as semanas", habitCadenceMonthly: "Todos os meses",
    habitRequireNote: "Pedir uma nota", habitRequireNoteDesc: "Escreve uma nota curta sempre que registas.",
    habitColor: "Cor",
    habitClickPrompt: "Marcar como concluído", habitDoneForNow: "Feito",
    habitNotePrompt: "Como correu?", habitNotePlaceholder: "Duas palavras",
    habitSeeProgress: "Ver progresso", habitUndoToday: "Anular este registo", habitDelete: "Eliminar hábito",
    habitDeleteTitle: "Eliminar este hábito?", habitDeleteDesc: "O hábito e todo o seu histórico serão removidos.",
    habitCurrentStreak: "Sequência atual", habitBestStreak: "Melhor sequência",
    habitTotalCheckIns: "Registos", habitCompletionRate: "Conclusão",
    habitNotesTitle: "Notas",
    habitCadenceCustom: "Dias à escolha", habitWeekdaysLabel: "Dias da semana", habitWeekdaysDesc: "Escolhe os dias em que queres registar.", habitRestDay: "Dia de descanso",
    habitToneLabel: "Estilo de incentivo", habitToneDesc: "Que tipo de mensagem recebes depois de cada registo.",
    habitTonePurpose: "Propósito e progresso", habitToneWarm: "Caloroso e encorajador",
    habitToneUpbeat: "Animado e satisfatório", habitToneGame: "Videojogo",
    habitToneRandom: "Aleatório de cada vez", habitToneCustom: "A minha mensagem",
    habitToneCustomPlaceholder: "A tua mensagem",
    habitTargetLabel: "Meta final", habitTargetDesc: "Quando este hábito conta como terminado.",
    habitTargetEndless: "Continuar sempre", habitTargetCount: "Ao fim de N registos", habitTargetDate: "Até uma data",
    habitTargetCountPlaceholder: "Registos",
    habitTargetReached: "Hábito alcançado.",
    habitTargetRemaining: n => (n === 1 ? "Falta 1 registo" : `Faltam ${n} registos`),
    habitTargetDaysLeft: n => (n === 0 ? "Último dia" : n === 1 ? "Falta 1 dia" : `Faltam ${n} dias`),
    habitMessages: {
      purpose: {
        day1: "Primeiro registo feito. A jornada começa.",
        early: "A acumular consistência dia após dia.",
        week: "7 dias seguidos a avançar.",
        month: "30 dias consecutivos concluídos.",
        daily: "Mais um dia perto do teu objetivo de longo prazo.",
        rescue: "De volta ao rumo certo hoje.",
      },
      warm: {
        day1: "Deste o passo mais difícil. Orgulho em ti.",
        early: "Estás a provar que podes confiar em ti.",
        week: "Uma semana inteira! Vê o quanto já avançaste.",
        month: "30 dias de dedicação. Criaste mesmo um hábito.",
        daily: "Mais um passo firme hoje.",
        rescue: "Que bom ter-te de volta. Cada dia é uma nova oportunidade.",
      },
      upbeat: {
        day1: "Que começo fantástico!",
        early: "Mais um bom dia registado!",
        week: "7 dias seguidos! Excelente trabalho.",
        month: "30 dias! Isso é um marco enorme.",
        daily: "Riscado! Sabe bem.",
        rescue: "Que bom ter-te de volta! Vamos continuar.",
      },
      game: {
        day1: "Missão iniciada: nível 1 concluído.",
        early: "Combo ativo. XP ganho.",
        week: "Conquista desbloqueada: Guerreiro da Primeira Semana.",
        month: "Marco maior: chefe derrotado.",
        daily: "Missão diária concluída +100 XP.",
        rescue: "Ressuscitaste. Vamos recuperar a sequência.",
      },
    },
}
