export const pt = {
    tasks: 'Tarefas', kanban: 'Kanban', grades: 'Avaliações', calendar: 'Calendário', focus: 'Foco', settings: 'Definições',
    noSemester: 'Nenhum semestre configurado', goToSettings: 'Vai a Definições para começar.',
    weekLabel: w => `Semana ${w}`, done: 'concluídas', timeToRelax: 'Hora de descansar!',
    addTask: 'Nova tarefa', task: 'Tarefa', class: 'Disciplina', priority: 'Prioridade',
    editTask: 'Editar tarefa', moveLeft: 'Mover para a esquerda', moveRight: 'Mover para a direita', markDone: 'Marcar como feito',
    addToKanban: 'Adicionar ao Kanban', themeLight: 'Tema claro', themeDark: 'Tema escuro', themeSystem: 'Tema do sistema',
    addPartTitle: 'Adicionar parte',
    fromWeek: 'Da semana', toWeek: 'Até à semana', dueDate: 'Data limite',
    other: 'Outro', noTasks: 'Sem tarefas esta semana.',
    whatNeedsDone: 'O que precisa de ser feito?',
    addTaskBtn: 'Adicionar tarefa', showOnCalendar: 'Mostrar no calendário', showOnTasks: 'Mostrar nas tarefas',
    clearDone: 'Limpar concluídos', wipeAll: 'Apagar tudo',
    addCard: 'Adicionar cartão', addCardPlaceholder: 'Título do cartão',
    save: 'Guardar', cancel: 'Cancelar', confirm: 'Confirmar', delete: 'Eliminar',
    addEvent: 'Adicionar evento', newEvent: 'Novo evento', editEvent: 'Editar evento',
    eventTitle: 'Título do evento', eventDate: 'Data', eventRange: 'Intervalo de datas',
    eventMultiDay: 'Vários dias', eventColor: 'Cor', eventNote: 'Nota',
    eventNotePlaceholder: 'Nota opcional', more: 'mais',
    navbar: 'Barra de navegação', navHide: 'Ocultar', navOverflow: 'Mover para menu', navAddButton: 'Mostrar botão de adicionar',
    navMore: 'Mais', navLabelMode: 'Mostrar', navLabelBoth: 'Ícones + nomes', navLabelIcons: 'Só ícones', navLabelNames: 'Só nomes',
    add: 'Adicionar', navAddLabel: 'Adicionar', navDrag: 'Arrasta para reordenar',
    appDisableTitle: 'Desativar e apagar dados?', appDisableDesc: 'Desativar esta app elimina permanentemente todos os seus dados.',
    collabDisableDesc: 'Desligar sai de todas as equipas e remove permanentemente os dados de colaboração deste dispositivo.',
    navAddAction: 'Ação do botão adicionar', navAddPicker: 'Perguntar sempre',
    navFolders: 'Pastas', navNewFolder: 'Nova pasta',
    navMobilePosition: 'Posição da barra no telemóvel', navPosBottom: 'Barra inferior', navPosSide: 'Barra lateral',
    addToTasks: 'Adicionar às tarefas', inTasks: 'Nas tarefas',
    standby: 'Repouso', standbyEnable: 'Ativar repouso horizontal',
    standbyDesc: 'Vira o telemóvel na horizontal para mostrar um painel ambiente.',
    standbyLeft: 'Painel esquerdo', standbyCenter: 'Painel central', standbyRight: 'Painel direito',
    standbyPanels: 'Painéis', standbyPane: n => `Painel ${n}`,
    standbyPaneSecond: 'Segundo cartão (deslizar)', standbyPaneNone: 'Nenhum',
    paneWheel: 'Roda de progresso', paneWheelTime: 'Roda + relógio', paneCalendar: 'Calendário',
    paneFocus: 'Foco', paneKanban: 'Kanban', paneTasksByCategory: 'Tarefas por categoria',
    notesLastEdit: 'Editado', notesFolder: 'Pasta', notesNoFolder: 'Sem pasta', notesNewFolder: 'Nova pasta',
    notesFolderName: 'Nome da pasta', notesRenameFolder: 'Renomear pasta', notesDeleteFolder: 'Eliminar pasta', notesMoveTo: 'Mover para',
    notesEdit: 'Editar', notesPreview: 'Pré-visualizar', notesBack: 'Voltar',
    apps: 'Apps', appsSearch: 'Procurar apps', appsNoResults: 'Nenhuma app encontrada.', notes: 'Notas',
    notesEnable: 'Ativar Notas', notesEnableDesc: 'Adiciona um separador de notas rápidas.',
    notesNew: 'Nova nota', notesTitle: 'Título', notesBody: 'Escreve algo…', notesSearch: 'Procurar notas',
    notesEmpty: 'Ainda sem notas.', notesFavorite: 'Favorito', notesText: 'Texto', notesCanvas: 'Escrita à mão',
    notesCanvasWarning: 'Notas com desenhos podem ocupar muito espaço e por isso só estão disponíveis com o Firebase ativo.',
    collabApp: 'Colaboração',
    eiCalendar: 'Calendário EI', eiCalendarEnable: 'Mostrar calendário EI',
    eiCalendarEnableDesc: 'Adiciona ao calendário o calendário oficial do curso de EI do teu ano, só de leitura e sempre atualizado.',
    eiCalendarDisableTitle: 'Ocultar calendário EI?', eiCalendarDisableDesc: 'Deixa de mostrar os eventos do calendário EI. Nada é apagado e podes reativar quando quiseres.',
    semester: 'Semestre', classes: 'Disciplinas', gradeComponents: 'Componentes de avaliação',
    kanbanColumns: 'Colunas do Kanban', general: 'Geral', data: 'Dados e sincronização',
    holidays: 'Feriados',
    exportJson: 'Exportar JSON', importJson: 'Importar JSON',
    semesterAvg: 'Média do semestre', ectsPassedLabel: 'ECTS obtidos',
    targetGrade: 'Nota alvo',
    previousSemesters: 'Semestres anteriores',
    courseAvg: 'Média do curso', finalGrade: 'Nota final', previousAvg: 'Média anterior', numSemesters: 'Nº de semestres',
    getStarted: 'Começar', welcomeTitle: 'Bem-vindo ao Organizador',
    welcomeDesc: 'O teu espaço para a vida universitária. Configura o semestre e organiza-te.',
    step1: 'Define as datas do semestre', step2: 'Adiciona as tuas disciplinas', step3: 'Planeia tarefas e acompanha avaliações',
    obNext: 'Seguinte', obBack: 'Voltar', obFinish: 'Concluir', obSkip: 'Saltar',
    obWelcomeTitle: 'Bem-vindo ao Organizador', obWelcomeDesc: 'O teu espaço calmo para a vida universitária. Escolhe idioma e tema para começar.',
    obModeTitle: 'Como vais usar?', obModeDesc: 'Ativa o que te serve. Podes ter ambos.',
    obModeWorkToggle: 'Modo trabalho', obModeWorkToggleDesc: 'Grupos em vez de disciplinas, sem avaliações.',
    obModeWeeksToggle: 'Sem semestres', obModeWeeksToggleDesc: 'Organiza por semana do calendário.',
    obImportOr: 'ou restaura uma cópia',
    obDatesTitle: 'O teu semestre', obDatesDesc: 'Quando começa e termina?',
    obClassesTitle: 'As tuas disciplinas', obClassesDesc: 'Adiciona as disciplinas que tens.',
    obGroupsTitle: 'Os teus grupos', obGroupsDesc: 'Adiciona os grupos com que trabalhas.',
    obInfoTasksTitle: 'Tarefas e Kanban', obInfoTasksDesc: 'Adiciona tarefas por semana ou data e arrasta-as pelo quadro kanban.',
    obInfoCalTitle: 'Calendário e Foco', obInfoCalDesc: 'Vê tudo no calendário e faz sessões de foco para produzir.',
    obInfoDoneTitle: 'Está tudo pronto', obInfoDoneDesc: 'Podes mudar isto mais tarde nas definições.',
    shareLink: 'Copiar link de partilha', qrCode: 'Código QR', linkCopied: 'Link copiado!',
    high: 'Alta', medium: 'Média', low: 'Baixa', none: 'Nenhuma',
    addSemester: 'Adicionar semestre', semesterName: 'Nome do semestre', startDate: 'Data de início', endDate: 'Data de fim',
    weeks: n => `${n} semanas`, addAClass: 'Adicionar disciplina', className: 'Nome da disciplina', ects: 'ECTS', colour: 'Cor',
    addComponent: 'Adicionar componente', componentName: 'Nome do componente',
    taskSpanLabel: 'Comportamento de tarefas multi-semana', taskSpanDesc: 'Quando uma tarefa abrange várias semanas, como é marcada como concluída?',
    kanbanChecklistInlineLabel: 'Pré-visualização da checklist no Kanban',
    kanbanChecklistInlineDesc: 'Mostra os itens da checklist diretamente nos cartões sem abrir os detalhes.',
    kanbanChecklistPreviewNone: 'Ocultar nos cartões',
    kanbanChecklistPreviewAll: 'Mostrar em todos os cartões',
    kanbanChecklistPreviewPerCard: 'Caso a caso',
    focusAlertModeLabel: 'Modo de alerta no foco',
    focusAlertModeDesc: 'Escolhe como os alertas de foco aparecem quando a fase do cronómetro muda.',
    focusAlertNone: 'Nenhum',
    focusAlertVibration: 'Vibração',
    focusAlertNotification: 'Notificação',
    focusAlertBoth: 'Ambos',
    taskAlertModeLabel: 'Alertas de prazo das tarefas',
    taskAlertModeDesc: 'Escolhe como os alertas de prazo das tarefas são apresentados.',
    taskAlertNone: 'Nenhum',
    taskAlertInApp: 'Na app',
    taskAlertNotification: 'Notificação',
    taskAlertBoth: 'Ambos',
    taskAlertNextDayTimeLabel: 'Hora do alerta para amanhã',
    taskAlertNextDayTimeDesc: 'Hora dos lembretes para tarefas com prazo amanhã.',
    taskDefaultToCalendarLabel: 'Tarefas no calendário por defeito',
    taskDefaultToCalendarDesc: 'Novas tarefas terão "Mostrar no calendário" ativado por defeito.',
    taskDueTodayTitle: count => count === 1 ? 'Tarefa para hoje' : `${count} tarefas para hoje`,
    taskAlertHide: 'Ocultar alerta',
    taskAlertRemindMeAt: 'Lembrar-me às',
    settingEnabled: 'Ativado', settingDisabled: 'Desativado',
    spanSingle: 'Uma checkbox global (concluída uma vez)', spanPerWeek: 'Checkbox por semana',
    dangerZone: 'Zona de perigo', deleteSemester: 'Eliminar este semestre',
    clearPomodoros: 'Limpar pomodoros',
    clearPomodorosTitle: 'Limpar todos os pomodoros?',
    clearPomodorosDesc: 'Todos os pomodoros caídos serão eliminados permanentemente.',
    deleteSemesterTitle: 'Eliminar semestre?', deleteSemesterDesc: 'Todas as tarefas, avaliações e dados do Kanban deste semestre serão eliminados permanentemente.',
    clearDoneTitle: 'Limpar coluna concluída?', clearDoneDesc: 'Todos os cartões da coluna Concluído serão eliminados.',
    wipeAllTitle: 'Apagar todos os cartões?', wipeAllDesc: 'Todos os cartões do quadro serão eliminados permanentemente.',
    selectSemester: 'Selecionar semestre', noClassesYet: 'Ainda sem disciplinas', addClassesInSettings: 'Adiciona disciplinas em Definições.',
    addUnlocks: 'Adiciona um semestre para desbloquear o resto.',
    checklist: 'Lista de verificação', addItem: 'Adicionar item', editCard: 'Editar cartão',
    notAchievable: '— impossível de atingir', onRemaining: ' nas componentes restantes',
    youNeed: 'Precisas de', allGraded: 'Todas as componentes avaliadas.',
    noGradeComponents: 'Nenhuma componente configurada. Vai a Definições.',
    deleteClassTitle: 'Eliminar disciplina?', deleteClassDesc: 'Isto irá também eliminar todas as tarefas desta disciplina.',
    holidayName: 'Nome do feriado', holidayNamePlaceholder: 'ex. Natal',
    addHoliday: 'Adicionar feriado',
    loadPreset: 'Carregar preset',
    presetLoading: 'A carregar preset…', presetError: 'Falhou ao carregar o preset.', retry: 'Tentar novamente', skip: 'Saltar',
    newColumnName: 'Nome da nova coluna',
    focusStart: 'Iniciar', focusPause: 'Pausar', focusResume: 'Retomar', focusReset: 'Reiniciar', focusSkipBreak: 'Saltar pausa',
    focusReady: 'pronto', focusBreak: 'pausa',
    focusPhrases: ['continua', 'mantém o foco', 'estás a ir bem', 'um passo de cada vez', 'trabalho profundo', 'fica presente'],
    focusEvery: 'cada (min)', focusBreakFor: 'pausa (min)',
    focusScheduledMode: 'Pausas agendadas',
    focusNextBreak: 'Próxima pausa às',
    focusFocusLabel: 'Mensagem de foco', focusBreakLabel: 'Mensagem de pausa',
    loadPresetTitle: 'Carregar um preset',
    presetGroupEI: 'Curso EI',
    presetGroupGeneric: 'Geral',
    backToMenu: 'Voltar',
    importData: 'Importar dados',
    importFromFirebase: 'Importar do Firebase',
    nextSemesterTitle: 'Semestre terminado',
    nextSemesterDesc: 'O teu semestre terminou. Carregar o próximo?',
    loadNextSemester: 'Carregar próximo semestre',
    dismissNextSemester: 'Dispensar',
    noSemesterYet: 'Nenhum semestre configurado',
    noSemesterDesc: 'Carrega um preset ou importa os teus dados para começar.',
    focusIntervalMode: 'Pausas por intervalo',
    focusIntervalEvery: 'cada (min)',
    focusIntervalBreakFor: 'pausa (min)',
    focusScheduledBreakFor: 'pausa (min)',
    focusAfterBreakReset: 'Após pausa: reiniciar timer',
    focusAfterBreakContinue: 'Após pausa: continuar a contar',
    firebaseSync: 'Sincronização Firebase',
    firebaseConnect: 'Ligar',
    firebaseConnected: 'Ligado',
    firebaseDisconnect: 'Desligar',
    firebaseSyncing: 'A sincronizar…',
    firebaseLastSync: 'Última sincronização',
    firebaseError: 'Erro de sincronização',
    firebaseRemoteNewer: 'Os dados na nuvem são de uma versão mais recente. Sincronização em pausa. Atualiza a app.',
    collabSyncFailed: 'Não foi possível sincronizar a alteração partilhada. Foi revertida.',
    newerVersionWarning: 'Os teus dados foram guardados por uma versão mais recente da app. Algumas coisas podem não aparecer corretamente até atualizares.',
    firebaseSetupTitle: 'Ligar ao Firebase',
    firebaseStep1Title: 'Criar um projeto Firebase',
    firebaseStep1Desc: 'Vai a console.firebase.google.com → Adicionar projeto → dá um nome → desativa o Google Analytics → Criar projeto.',
    firebaseStep2Title: 'Ativar o Firestore',
    firebaseStep2Desc: 'Vai a Criar → Firestore Database → Criar base de dados → escolhe uma região → Iniciar em modo de produção → Criar. Depois vai a Regras, substitui o conteúdo por: allow read, write: if true; e clica em Publicar.',
    firebaseStep3Title: 'Obter a configuração',
    firebaseStep3Desc: 'Vai às Definições do projeto (ícone de engrenagem) → As tuas apps → Adicionar app → Web → regista a app → copia o objeto firebaseConfig mostrado.',
    firebaseStep4Title: 'Cola a configuração',
    firebaseStep4Desc: 'Cola o objeto firebaseConfig completo (em JSON) abaixo.',
    firebaseConfigPlaceholder: '{ "apiKey": "...", "authDomain": "...", "projectId": "...", ... }',
    firebaseConfigInvalid: 'Configuração inválida: deve incluir apiKey e projectId.',
    firebaseTestFailed: 'Não foi possível ligar. Verifica a configuração e as regras da base de dados.',
    firebaseSave: 'Guardar e ligar',
    pomodoroMode: 'Modo pomodoro',
    pomodoroModeDesc: 'Faz crescer tomates durante as sessões de foco. Cada sessão completa deixa cair um tomate.',
    pomodoroResetPeriod: 'Período de reset',
    pomodoroResetDay: 'Diário', pomodoroResetWeek: 'Semanal', pomodoroResetMonth: 'Mensal', pomodoroResetSemester: 'Por semestre',
    pomodoroTrackPeriodStats: 'Guardar estatísticas do período',
    pomodoroShowAbandoned: 'Mostrar tomates abandonados',
    pomodoroShowPeriodPomodoros: 'Mostrar pomodoros do período',
    pomodoroStatsTitle: 'Estatísticas pomodoro',
    pomodoroTotal: 'Total de tomates', pomodoroAbandoned: 'Abandonados', pomodoroFocusTime: 'Tempo total de foco',
    pomodoroPeriodTotal: 'Este período', pomodoroPeriodFocus: 'Foco neste período',
    pomodoroVsSinceLast: 'vs período anterior',
    pomodoroAllTime: 'Todo o tempo',
    pomodoroInsightsDailyTitle: 'Foco diário desta semana',
    pomodoroInsightsWeeklyBreakdownTitle: 'Média por semana',
    pomodoroInsightsAvgWeekLabel: 'média por dia (semana)',
    pomodoroInsightsAvgPeriodLabel: 'média por dia (período)',
    pomodoroInsightsPerDaySuffix: '/d',
    pomodoroInsightsNoWeeklyData: 'Ainda sem dados semanais.',
    pomodoroInsightsDayLabels: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'],
    pomodoroTotalTimeLabel: 'tempo total',
    pomodoroClose: 'Fechar',
    pomodoroEraseStats: 'Apagar estatísticas',
    pomodoroEraseStatsTitle: 'Apagar estatísticas pomodoro?',
    pomodoroEraseStatsDesc: 'As estatísticas históricas de tempo de foco serão removidas, mas os registos de tomates mantêm-se.',
    pomodoroGraceCancel: 'Cancelar (sem tomate)',
    pomodoroGrace: s => `${s}s para cancelar sem perder um tomate`,
    workModeLabel: 'Modo trabalho',
    workModeDesc: 'Oculta avaliações e renomeia disciplinas para grupos.',
    workModeOnboarding: 'Usar para trabalho?',
    semesterModeLabel: 'Modo sem semestres',
    semesterModeDesc: 'Liga para usar semanas do ano em vez de semestres. As avaliações ficam ocultas.',
    semesterModeNone: 'Sem semestres (semanas do ano)',
    semesterModeSemesters: 'A usar semestres',
    semesterModeOnboarding: 'Sem semestres, só semanas?',
    groups: 'Grupos', addAGroup: 'Adicionar grupo', groupName: 'Nome do grupo',
    deleteGroupTitle: 'Eliminar grupo?', deleteGroupDesc: 'Isto irá também eliminar todas as tarefas deste grupo.',
    storageWarningTitle: 'Limite de armazenamento atingido',
    storageWarningDesc: 'Por favor ativa a sincronização Firebase, atingiste o limite de armazenamento local.',
    storageWarningAction: 'Percebido',
    collabConnect: 'Ligar Organizer Collab',
    collabDisconnect: 'Desligar Organizer Collab',
    collabRequiresFirebase: 'Liga primeiro a sincronização Firebase para usar o Organizer Collab.',
    collabGuideTitle: 'Configuração do Organizer Collab',
    collabGuideIntro: 'Configuração única. Faz estes 4 passos no Firebase e depois volta para ativar o collab.',
    collabGuideImportantTitle: 'O que muda quando ativas collab',
    collabGuideImportant1: 'A base de dados passa a exigir utilizadores autenticados (anónimo chega).',
    collabGuideImportant2: 'A sincronização normal do organizer continua a funcionar, mas autentica primeiro.',
    collabGuideImportant3: 'Se desligares collab mais tarde, podes continuar com regras baseadas em auth sem problemas.',
    collabGuideStep1: 'Abre Firebase Console > Build > Firestore Database > Regras.',
    collabGuideStep2: 'Cola o snippet de regras abaixo e clica em Publicar.',
    collabGuideStep3: 'Abre Security > Authentication > Método de início de sessão > ativa Anónimo > Guardar.',
    collabGuideStep4: 'Volta ao Organizer e carrega em "Já configurei as regras, ativar collab".',
    collabGuideRulesLabel: 'Regras Firestore',
    collabGuideTroubleshootTitle: 'Se aparecer erro signUp 400',
    collabGuideTroubleshootBody: 'Significa que a autenticação Anónima ainda está desativada no Firebase. Ativa em Security > Authentication > Método de início de sessão.',
    collabEnableNow: 'Já configurei as regras, ativar collab',
    collabPanelTitle: 'Organizer Collab',
    collabPanelSubtitle: 'Cria equipas, convida pessoas e partilha tarefas/cartões do kanban.',
    collabCreateTeam: 'Criar equipa',
    collabTeamName: 'Nome da equipa',
    collabTeamDays: 'dias da equipa',
    collabTeamDuration: 'duração da equipa',
    collabDays: 'dias',
    collabJoinTeam: 'Entrar na equipa',
    collabInvitePlaceholder: 'Cola o link de convite',
    collabInviteTtl: 'Validade do convite',
    collabYourTeams: 'As tuas equipas',
    collabNoTeams: 'Ainda sem equipas.',
    collabRoleHost: 'host',
    collabRoleMember: 'membro',
    collabEndsAt: 'termina em',
    collabInvite: 'Convidar',
    collabEditTeam: 'Editar equipa',
    collabTaskCompletionMode: 'Conclusão de tarefas partilhadas',
    collabTaskCompletionPersonal: 'conclusão pessoal',
    collabTaskCompletionForAll: 'marcar para todos',
    collabTaskPermissions: 'Permissões de edição de tarefas',
    collabTaskPermissionsEveryone: 'qualquer membro pode adicionar/editar/remover tarefas',
    collabTaskPermissionsHostOnly: 'apenas o host pode adicionar/editar/remover tarefas',
    collabLeave: 'Sair',
    collabDeleteTeam: 'Eliminar',
    collabDefaultTeamName: 'Equipa',
    collabLeavePrompt: 'Sair desta equipa?',
    collabLeaveWithLocalPrompt: 'Partilhaste tarefas locais nesta equipa. Queres mantê-las localmente?',
    collabDeleteTeamPrompt: 'Eliminar esta equipa?',
    collabDeleteTeamWithLocalPrompt: 'Partilhaste tarefas locais nesta equipa. Queres mantê-las localmente antes de eliminar a equipa?',
    collabKeepLocalTasks: 'Manter locais',
    collabDeleteLocalTasksToo: 'Apagar as locais',
    collabErrorCreate: 'Não foi possível criar a equipa.',
    collabErrorInvite: 'Não foi possível gerar convite.',
    collabErrorJoin: 'Não foi possível entrar na equipa.',
    collabErrorInvalidLink: 'Link de convite inválido.',
    collabErrorDeleteTeam: 'Não foi possível eliminar a equipa.',
    collabGuideChecklistTitle: 'Ainda não sincroniza?',
    collabGuideChecklistBody: 'Os dois passos que o Organizer não faz por ti: ativar a autenticação anónima e publicar as regras do Firestore acima. Se as tarefas partilhadas nunca aparecem, falta um destes no projeto do anfitrião.',
    collabSyncErrorHint: 'Não é possível aceder a esta equipa. Verifica se o Firebase do anfitrião tem a autenticação anónima ativada e regras abertas.',
    collabErrorPermission: 'Bloqueado pelas regras do Firebase. O anfitrião tem de ativar a autenticação anónima e abrir as regras do Firestore.',
    collabErrorNotFound: 'Equipa não encontrada. Pode ter sido eliminada.',
    collabErrorInviteExpired: 'Este convite expirou. Pede um novo link ao anfitrião.',
    collabErrorInviteInvalid: 'Este link de convite não é válido para essa equipa.',
}
