export const STRINGS = {
  en: {
    tasks: 'Tasks', kanban: 'Kanban', grades: 'Grades', calendar: 'Calendar', focus: 'Focus', settings: 'Settings',
    noSemester: 'No semester set up', goToSettings: 'Head to Settings to get started.',
    weekLabel: w => `Week ${w}`, done: 'done', timeToRelax: 'Time to relax!',
    addTask: 'New task', task: 'Task', class: 'Class', priority: 'Priority',
    editTask: 'Edit task', moveLeft: 'Move left', moveRight: 'Move right', markDone: 'Mark done',
    addToKanban: 'Add to Kanban', themeLight: 'Light theme', themeDark: 'Dark theme', themeSystem: 'System theme',
    addPartTitle: 'Add part',
    fromWeek: 'From week', toWeek: 'To week', dueDate: 'Due date',
    other: 'Other', noTasks: 'No tasks this week.',
    whatNeedsDone: 'What needs to be done?',
    addTaskBtn: 'Add task', showOnCalendar: 'Show on calendar', showOnTasks: 'Show on tasks',
    clearDone: 'Clear done', wipeAll: 'Wipe all',
    addCard: 'Add card', addCardPlaceholder: 'Card title',
    save: 'Save', cancel: 'Cancel', confirm: 'Confirm', delete: 'Delete',
    addEvent: 'Add event', newEvent: 'New event', editEvent: 'Edit event',
    eventTitle: 'Event title', eventDate: 'Date', eventRange: 'Date range',
    eventMultiDay: 'Multiple days', eventColor: 'Color', eventNote: 'Note',
    eventNotePlaceholder: 'Optional note', more: 'more',
    navbar: 'Navbar', navHide: 'Hide', navOverflow: 'Move to more menu', navAddButton: 'Show add-task button',
    navMore: 'More', navLabelMode: 'Show', navLabelBoth: 'Icons + names', navLabelIcons: 'Icons only', navLabelNames: 'Names only',
    add: 'Add', navAddLabel: 'Add', navDrag: 'Drag to reorder',
    appDisableTitle: 'Disable and erase data?', appDisableDesc: 'Turning this app off permanently deletes all its data.',
    collabDisableDesc: 'Disconnecting leaves all teams and permanently removes collaboration data from this device.',
    navAddAction: 'Add button action', navAddPicker: 'Ask each time',
    navFolders: 'Folders', navNewFolder: 'New folder',
    navMobilePosition: 'Mobile navbar position', navPosBottom: 'Bottom bar', navPosSide: 'Side bar',
    addToTasks: 'Add to tasks', inTasks: 'In tasks',
    standby: 'Standby', standbyEnable: 'Enable landscape standby',
    standbyDesc: 'Turn your phone landscape to show an ambient dashboard.',
    standbyLeft: 'Left pane', standbyCenter: 'Center pane', standbyRight: 'Right pane',
    standbyPanels: 'Panels', standbyPane: n => `Pane ${n}`,
    paneWheel: 'Progress wheel', paneWheelTime: 'Wheel + clock', paneCalendar: 'Calendar',
    paneFocus: 'Focus', paneKanban: 'Kanban', paneTasksByCategory: 'Tasks by category',
    notesLastEdit: 'Edited', notesFolder: 'Folder', notesNoFolder: 'No folder', notesNewFolder: 'New folder',
    notesFolderName: 'Folder name', notesRenameFolder: 'Rename folder', notesDeleteFolder: 'Delete folder', notesMoveTo: 'Move to',
    notesEdit: 'Edit', notesPreview: 'Preview', notesBack: 'Back',
    apps: 'Apps', appsSearch: 'Search apps', appsNoResults: 'No apps found.', notes: 'Notes',
    notesEnable: 'Enable Notes', notesEnableDesc: 'Add a Notes tab for quick text notes.',
    notesNew: 'New note', notesTitle: 'Title', notesBody: 'Write something…', notesSearch: 'Search notes',
    notesEmpty: 'No notes yet.', notesFavorite: 'Favorite', notesText: 'Text', notesCanvas: 'Handwriting',
    notesCanvasWarning: 'Notes with drawings may use a lot of space, and as such are only available with Firebase active.',
    collabApp: 'Collaboration',
    eiCalendar: 'EI Calendar', eiCalendarEnable: 'Show EI calendar',
    eiCalendarEnableDesc: 'Adds the official EI course calendar for your year to the calendar, read-only and always up to date.',
    eiCalendarDisableTitle: 'Hide EI calendar?', eiCalendarDisableDesc: 'Stops showing the EI calendar events. Nothing is deleted and you can turn it back on anytime.',
    semester: 'Semester', classes: 'Classes', gradeComponents: 'Grade components',
    kanbanColumns: 'Kanban columns', general: 'General', data: 'Data & sync',
    holidays: 'Holidays',
    exportJson: 'Export JSON', importJson: 'Import JSON',
    semesterAvg: 'Semester average', ectsPassedLabel: 'ECTS passed',
    targetGrade: 'Target grade',
    previousSemesters: 'Previous semesters',
    courseAvg: 'Course average', finalGrade: 'Final grade', previousAvg: 'Previous avg', numSemesters: 'No. of semesters',
    getStarted: 'Get started', welcomeTitle: 'Welcome to organizer',
    welcomeDesc: 'Your space for uni work. Set up your semester and get organised.',
    step1: 'Set your semester dates', step2: 'Add your classes', step3: 'Plan tasks & track grades',
    obNext: 'Next', obBack: 'Back', obFinish: 'Finish', obSkip: 'Skip',
    obWelcomeTitle: 'Welcome to Organizer', obWelcomeDesc: 'Your calm space for uni work. Pick your language and theme to start.',
    obModeTitle: 'How will you use it?', obModeDesc: 'Toggle what fits you. Both can be on.',
    obModeWorkToggle: 'Work mode', obModeWorkToggleDesc: 'Groups instead of classes, no grades.',
    obModeWeeksToggle: 'No semesters', obModeWeeksToggleDesc: 'Organise by calendar week instead of semester.',
    obImportOr: 'or restore a backup',
    obDatesTitle: 'Your semester', obDatesDesc: 'When does it start and end?',
    obClassesTitle: 'Your classes', obClassesDesc: 'Add the classes you are taking.',
    obGroupsTitle: 'Your groups', obGroupsDesc: 'Add the groups you work with.',
    obInfoTasksTitle: 'Tasks & Kanban', obInfoTasksDesc: 'Add tasks per week or date, then drag them across your kanban board.',
    obInfoCalTitle: 'Calendar & Focus', obInfoCalDesc: 'See everything on the calendar and run focus sessions to get things done.',
    obInfoDoneTitle: 'You are all set', obInfoDoneDesc: 'You can change any of this later in settings.',
    shareLink: 'Copy share link', qrCode: 'QR Code', linkCopied: 'Link copied!',
    high: 'High', medium: 'Medium', low: 'Low', none: 'None',
    addSemester: 'Add semester', semesterName: 'Semester name', startDate: 'Start date', endDate: 'End date',
    weeks: n => `${n} weeks`, addAClass: 'Add class', className: 'Class name', ects: 'ECTS', colour: 'Colour',
    addComponent: 'Add component', componentName: 'Component name',
    taskSpanLabel: 'Task span behaviour', taskSpanDesc: 'When a task spans multiple weeks, how is it marked done?',
    kanbanChecklistInlineLabel: 'Kanban checklist preview',
    kanbanChecklistInlineDesc: 'Show checklist items directly on cards without opening details.',
    kanbanChecklistPreviewNone: 'Hide on cards',
    kanbanChecklistPreviewAll: 'Show on all cards',
    kanbanChecklistPreviewPerCard: 'Case by case',
    focusAlertModeLabel: 'Focus alert mode',
    focusAlertModeDesc: 'Choose how Focus alerts are delivered when the timer phase changes.',
    focusAlertNone: 'None',
    focusAlertVibration: 'Vibration',
    focusAlertNotification: 'Notification',
    focusAlertBoth: 'Both',
    taskAlertModeLabel: 'Task due-date alerts',
    taskAlertModeDesc: 'Choose how task due-date alerts are delivered.',
    taskAlertNone: 'None',
    taskAlertInApp: 'In-app',
    taskAlertNotification: 'Notification',
    taskAlertBoth: 'Both',
    taskAlertNextDayTimeLabel: 'Next-day alert time',
    taskAlertNextDayTimeDesc: 'Time for reminders about tasks due tomorrow.',
    taskDefaultToCalendarLabel: 'Tasks on calendar by default',
    taskDefaultToCalendarDesc: 'New tasks will have "Show on calendar" enabled by default.',
    taskDueTodayTitle: count => count === 1 ? 'Task due today' : `${count} tasks due today`,
    taskAlertHide: 'Hide alert',
    taskAlertRemindMeAt: 'Remind me at',
    settingEnabled: 'Enabled', settingDisabled: 'Disabled',
    spanSingle: 'One global checkbox (done once)', spanPerWeek: 'Per-week checkbox',
    dangerZone: 'Danger zone', deleteSemester: 'Delete this semester',
    clearPomodoros: 'Clear pomodoros',
    clearPomodorosTitle: 'Clear all pomodoros?',
    clearPomodorosDesc: 'All fallen pomodoros will be permanently deleted.',
    deleteSemesterTitle: 'Delete semester?', deleteSemesterDesc: 'All tasks, grades, and kanban data for this semester will be permanently deleted.',
    clearDoneTitle: 'Clear done column?', clearDoneDesc: 'All cards in the Done column will be deleted.',
    wipeAllTitle: 'Wipe all cards?', wipeAllDesc: 'Every card on the board will be permanently deleted.',
    selectSemester: 'Select semester', noClassesYet: 'No classes yet', addClassesInSettings: 'Add classes in Settings.',
    addUnlocks: 'Add a semester to unlock the rest.',
    checklist: 'Checklist', addItem: 'Add item', editCard: 'Edit card',
    notAchievable: '— not achievable', onRemaining: ' on remaining assessments',
    youNeed: 'You need', allGraded: 'All components graded.',
    noGradeComponents: 'No grade components configured. Go to Settings.',
    deleteClassTitle: 'Delete class?', deleteClassDesc: 'This will also delete all tasks for this class.',
    holidayName: 'Holiday name', holidayNamePlaceholder: 'e.g. Christmas Break',
    addHoliday: 'Add holiday',
    loadPreset: 'Load preset',
    presetLoading: 'Loading preset…', presetError: 'Failed to load preset.', retry: 'Retry', skip: 'Skip',
    newColumnName: 'New column name',
    focusStart: 'Start', focusPause: 'Pause', focusResume: 'Resume', focusReset: 'Reset', focusSkipBreak: 'Skip break',
    focusReady: 'ready', focusBreak: 'break',
    focusPhrases: ['keep going', 'stay with it', "you're doing great", 'one step at a time', 'deep work', 'stay present'],
    focusEvery: 'every (min)', focusBreakFor: 'break (min)',
    focusScheduledMode: 'Scheduled breaks',
    focusNextBreak: 'Next break at',
    focusFocusLabel: 'Focus message', focusBreakLabel: 'Break message',
    loadPresetTitle: 'Load a preset',
    presetGroupEI: 'EI Course',
    presetGroupGeneric: 'General',
    backToMenu: 'Back',
    importData: 'Import data',
    importFromFirebase: 'Import from Firebase',
    nextSemesterTitle: 'Semester ended',
    nextSemesterDesc: 'Your semester has ended. Load the next one?',
    loadNextSemester: 'Load next semester',
    dismissNextSemester: 'Dismiss',
    noSemesterYet: 'No semester configured',
    noSemesterDesc: 'Load a preset or import your data to get started.',
    focusIntervalMode: 'Interval breaks',
    focusIntervalEvery: 'every (min)',
    focusIntervalBreakFor: 'break (min)',
    focusScheduledBreakFor: 'break (min)',
    focusAfterBreakReset: 'After break: reset timer',
    focusAfterBreakContinue: 'After break: keep counting',
    firebaseSync: 'Firebase sync',
    firebaseConnect: 'Connect',
    firebaseConnected: 'Connected',
    firebaseDisconnect: 'Disconnect',
    firebaseSyncing: 'Syncing…',
    firebaseLastSync: 'Last sync',
    firebaseError: 'Sync error',
    firebaseRemoteNewer: 'Cloud data is from a newer app version. Sync paused. Update the app.',
    collabSyncFailed: 'Could not sync shared change. It was reverted.',
    newerVersionWarning: 'Your data was saved by a newer app version. Some things may not display correctly until you update.',
    firebaseSetupTitle: 'Connect Firebase',
    firebaseStep1Title: 'Create a Firebase project',
    firebaseStep1Desc: 'Go to console.firebase.google.com → Add project → give it any name → disable Google Analytics → Create project.',
    firebaseStep2Title: 'Enable Firestore',
    firebaseStep2Desc: 'Go to Build → Firestore Database → Create database → choose a region → Start in production mode → Create. Then go to Rules, replace the content with: allow read, write: if true; and click Publish.',
    firebaseStep3Title: 'Get your config',
    firebaseStep3Desc: 'Go to Project Settings (gear icon) → Your apps → Add app → Web → register the app → copy the firebaseConfig object shown.',
    firebaseStep4Title: 'Paste your config',
    firebaseStep4Desc: 'Paste the full firebaseConfig object (as JSON) below.',
    firebaseConfigPlaceholder: '{ "apiKey": "...", "authDomain": "...", "projectId": "...", ... }',
    firebaseConfigInvalid: 'Invalid config: must include apiKey and projectId.',
    firebaseTestFailed: 'Could not connect. Check your config and database rules.',
    firebaseSave: 'Save & connect',
    pomodoroMode: 'Pomodoro mode',
    pomodoroModeDesc: 'Grow tomatoes during focus sessions. Each completed session drops a tomato.',
    pomodoroResetPeriod: 'Reset period',
    pomodoroResetDay: 'Daily', pomodoroResetWeek: 'Weekly', pomodoroResetMonth: 'Monthly', pomodoroResetSemester: 'Per semester',
    pomodoroTrackPeriodStats: 'Track period stats',
    pomodoroShowAbandoned: 'Show abandoned tomatoes',
    pomodoroShowPeriodPomodoros: 'Show period pomodoros',
    pomodoroStatsTitle: 'Pomodoro stats',
    pomodoroTotal: 'Total tomatoes', pomodoroAbandoned: 'Abandoned', pomodoroFocusTime: 'Total focus time',
    pomodoroPeriodTotal: 'This period', pomodoroPeriodFocus: 'Focus this period',
    pomodoroVsSinceLast: 'vs last period',
    pomodoroAllTime: 'All time',
    pomodoroInsightsDailyTitle: 'Daily focus this week',
    pomodoroInsightsWeeklyBreakdownTitle: 'Weekly averages',
    pomodoroInsightsAvgWeekLabel: 'avg/day (week)',
    pomodoroInsightsAvgPeriodLabel: 'avg/day (period)',
    pomodoroInsightsPerDaySuffix: '/d',
    pomodoroInsightsNoWeeklyData: 'No weekly data yet.',
    pomodoroInsightsDayLabels: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
    pomodoroTotalTimeLabel: 'total time',
    pomodoroClose: 'Close',
    pomodoroEraseStats: 'Erase stats',
    pomodoroEraseStatsTitle: 'Erase pomodoro stats?',
    pomodoroEraseStatsDesc: 'Historical focus-time stats will be removed, but tomato entries stay available.',
    pomodoroGraceCancel: 'Cancel (no tomato)',
    pomodoroGrace: s => `${s}s to cancel without losing a tomato`,
    workModeLabel: 'Work mode',
    workModeDesc: 'Hides grades and renames classes to groups.',
    workModeOnboarding: 'Using this for work?',
    semesterModeLabel: 'No semester mode',
    semesterModeDesc: 'Turn on to use plain year weeks instead of semesters. Grades are hidden.',
    semesterModeNone: 'No semesters (year weeks)',
    semesterModeSemesters: 'Using semesters',
    semesterModeOnboarding: 'No semesters, just weeks?',
    groups: 'Groups', addAGroup: 'Add group', groupName: 'Group name',
    deleteGroupTitle: 'Delete group?', deleteGroupDesc: 'This will also delete all tasks for this group.',
    storageWarningTitle: 'Storage limit reached',
    storageWarningDesc: 'Please activate Firebase sync, reached max local storage.',
    storageWarningAction: 'Got it',
    collabConnect: 'Connect Organizer Collab',
    collabDisconnect: 'Disconnect Organizer Collab',
    collabRequiresFirebase: 'Connect Firebase sync first to use Organizer Collab.',
    collabGuideTitle: 'Organizer Collab setup',
    collabGuideIntro: 'One-time setup. Do these 4 steps in Firebase, then come back and enable collab.',
    collabGuideImportantTitle: 'What changes when collab is enabled',
    collabGuideImportant1: 'Your database starts requiring authenticated users (anonymous auth is enough).',
    collabGuideImportant2: 'Normal organizer sync keeps working, but it must authenticate first.',
    collabGuideImportant3: 'If collab is disabled later, auth-based rules can still be used safely.',
    collabGuideStep1: 'Open Firebase Console > Build > Firestore Database > Rules.',
    collabGuideStep2: 'Paste the rules snippet below and click Publish.',
    collabGuideStep3: 'Open Security > Authentication > Sign-in method > enable Anonymous > Save.',
    collabGuideStep4: 'Return to Organizer and press "I configured rules, enable collab".',
    collabGuideRulesLabel: 'Firestore rules',
    collabGuideTroubleshootTitle: 'If you see signUp 400 error',
    collabGuideTroubleshootBody: 'That means Anonymous authentication is still disabled in Firebase. Enable it in Security > Authentication > Sign-in method.',
    collabEnableNow: 'I configured rules, enable collab',
    collabPanelTitle: 'Organizer Collab',
    collabPanelSubtitle: 'Create teams, invite people, and share tasks/kanban cards.',
    collabCreateTeam: 'Create team',
    collabTeamName: 'Team name',
    collabTeamDays: 'team days',
    collabTeamDuration: 'team duration',
    collabDays: 'days',
    collabJoinTeam: 'Join team',
    collabInvitePlaceholder: 'Paste invite link',
    collabInviteTtl: 'Invite validity',
    collabYourTeams: 'Your teams',
    collabNoTeams: 'No teams yet.',
    collabRoleHost: 'host',
    collabRoleMember: 'member',
    collabEndsAt: 'ends',
    collabInvite: 'Invite',
    collabEditTeam: 'Edit team',
    collabTaskCompletionMode: 'Shared task completion',
    collabTaskCompletionPersonal: 'personal completion',
    collabTaskCompletionForAll: 'toggle for everyone',
    collabTaskPermissions: 'Task edit permissions',
    collabTaskPermissionsEveryone: 'anyone can add/edit/remove tasks',
    collabTaskPermissionsHostOnly: 'only host can add/edit/remove tasks',
    collabLeave: 'Leave',
    collabDeleteTeam: 'Delete',
    collabDefaultTeamName: 'Team',
    collabLeavePrompt: 'Leave this team?',
    collabLeaveWithLocalPrompt: 'You shared local tasks in this team. Keep them locally?',
    collabDeleteTeamPrompt: 'Delete this team?',
    collabDeleteTeamWithLocalPrompt: 'You shared local tasks in this team. Keep them locally before deleting the team?',
    collabKeepLocalTasks: 'Keep local tasks',
    collabDeleteLocalTasksToo: 'Delete local tasks',
    collabErrorCreate: 'Could not create team.',
    collabErrorInvite: 'Could not generate invite.',
    collabErrorJoin: 'Could not join team.',
    collabErrorInvalidLink: 'Invalid invite link.',
    collabErrorDeleteTeam: 'Could not delete team.',
  },
  pt: {
    tasks: 'Tarefas', kanban: 'Kanban', grades: 'Avaliações', calendar: 'Calendário', focus: 'Foco', settings: 'Definições',
    noSemester: 'Nenhum semestre configurado', goToSettings: 'Vai a Definições para começar.',
    weekLabel: w => `Semana ${w}`, done: 'concluídas', timeToRelax: 'Hora de descansar!',
    addTask: 'Nova tarefa', task: 'Tarefa', class: 'Disciplina', priority: 'Prioridade',
    editTask: 'Editar tarefa', moveLeft: 'Mover para a esquerda', moveRight: 'Mover para a direita', markDone: 'Marcar como feito',
    addToKanban: 'Adicionar ao Kanban', themeLight: 'Tema claro', themeDark: 'Tema escuro', themeSystem: 'Tema do sistema',
    addPartTitle: 'Adicionar parte',
    fromWeek: 'Da semana', toWeek: 'Até à semana', dueDate: 'Data limite',
    other: 'Outro', noTasks: 'Sem tarefas esta semana.',
    whatNeedsDone: 'O que precisa de ser feito?',
    addTaskBtn: 'Adicionar tarefa', showOnCalendar: 'Mostrar no calendário', showOnTasks: 'Mostrar nas tarefas',
    clearDone: 'Limpar concluídos', wipeAll: 'Apagar tudo',
    addCard: 'Adicionar cartão', addCardPlaceholder: 'Título do cartão',
    save: 'Guardar', cancel: 'Cancelar', confirm: 'Confirmar', delete: 'Eliminar',
    addEvent: 'Adicionar evento', newEvent: 'Novo evento', editEvent: 'Editar evento',
    eventTitle: 'Título do evento', eventDate: 'Data', eventRange: 'Intervalo de datas',
    eventMultiDay: 'Vários dias', eventColor: 'Cor', eventNote: 'Nota',
    eventNotePlaceholder: 'Nota opcional', more: 'mais',
    navbar: 'Barra de navegação', navHide: 'Ocultar', navOverflow: 'Mover para menu', navAddButton: 'Mostrar botão de adicionar',
    navMore: 'Mais', navLabelMode: 'Mostrar', navLabelBoth: 'Ícones + nomes', navLabelIcons: 'Só ícones', navLabelNames: 'Só nomes',
    add: 'Adicionar', navAddLabel: 'Adicionar', navDrag: 'Arrasta para reordenar',
    appDisableTitle: 'Desativar e apagar dados?', appDisableDesc: 'Desativar esta app elimina permanentemente todos os seus dados.',
    collabDisableDesc: 'Desligar sai de todas as equipas e remove permanentemente os dados de colaboração deste dispositivo.',
    navAddAction: 'Ação do botão adicionar', navAddPicker: 'Perguntar sempre',
    navFolders: 'Pastas', navNewFolder: 'Nova pasta',
    navMobilePosition: 'Posição da barra no telemóvel', navPosBottom: 'Barra inferior', navPosSide: 'Barra lateral',
    addToTasks: 'Adicionar às tarefas', inTasks: 'Nas tarefas',
    standby: 'Repouso', standbyEnable: 'Ativar repouso horizontal',
    standbyDesc: 'Vira o telemóvel na horizontal para mostrar um painel ambiente.',
    standbyLeft: 'Painel esquerdo', standbyCenter: 'Painel central', standbyRight: 'Painel direito',
    standbyPanels: 'Painéis', standbyPane: n => `Painel ${n}`,
    paneWheel: 'Roda de progresso', paneWheelTime: 'Roda + relógio', paneCalendar: 'Calendário',
    paneFocus: 'Foco', paneKanban: 'Kanban', paneTasksByCategory: 'Tarefas por categoria',
    notesLastEdit: 'Editado', notesFolder: 'Pasta', notesNoFolder: 'Sem pasta', notesNewFolder: 'Nova pasta',
    notesFolderName: 'Nome da pasta', notesRenameFolder: 'Renomear pasta', notesDeleteFolder: 'Eliminar pasta', notesMoveTo: 'Mover para',
    notesEdit: 'Editar', notesPreview: 'Pré-visualizar', notesBack: 'Voltar',
    apps: 'Apps', appsSearch: 'Procurar apps', appsNoResults: 'Nenhuma app encontrada.', notes: 'Notas',
    notesEnable: 'Ativar Notas', notesEnableDesc: 'Adiciona um separador de notas rápidas.',
    notesNew: 'Nova nota', notesTitle: 'Título', notesBody: 'Escreve algo…', notesSearch: 'Procurar notas',
    notesEmpty: 'Ainda sem notas.', notesFavorite: 'Favorito', notesText: 'Texto', notesCanvas: 'Escrita à mão',
    notesCanvasWarning: 'Notas com desenhos podem ocupar muito espaço e por isso só estão disponíveis com o Firebase ativo.',
    collabApp: 'Colaboração',
    eiCalendar: 'Calendário EI', eiCalendarEnable: 'Mostrar calendário EI',
    eiCalendarEnableDesc: 'Adiciona ao calendário o calendário oficial do curso de EI do teu ano, só de leitura e sempre atualizado.',
    eiCalendarDisableTitle: 'Ocultar calendário EI?', eiCalendarDisableDesc: 'Deixa de mostrar os eventos do calendário EI. Nada é apagado e podes reativar quando quiseres.',
    semester: 'Semestre', classes: 'Disciplinas', gradeComponents: 'Componentes de avaliação',
    kanbanColumns: 'Colunas do Kanban', general: 'Geral', data: 'Dados e sincronização',
    holidays: 'Feriados',
    exportJson: 'Exportar JSON', importJson: 'Importar JSON',
    semesterAvg: 'Média do semestre', ectsPassedLabel: 'ECTS obtidos',
    targetGrade: 'Nota alvo',
    previousSemesters: 'Semestres anteriores',
    courseAvg: 'Média do curso', finalGrade: 'Nota final', previousAvg: 'Média anterior', numSemesters: 'Nº de semestres',
    getStarted: 'Começar', welcomeTitle: 'Bem-vindo ao Organizador',
    welcomeDesc: 'O teu espaço para a vida universitária. Configura o semestre e organiza-te.',
    step1: 'Define as datas do semestre', step2: 'Adiciona as tuas disciplinas', step3: 'Planeia tarefas e acompanha avaliações',
    obNext: 'Seguinte', obBack: 'Voltar', obFinish: 'Concluir', obSkip: 'Saltar',
    obWelcomeTitle: 'Bem-vindo ao Organizador', obWelcomeDesc: 'O teu espaço calmo para a vida universitária. Escolhe idioma e tema para começar.',
    obModeTitle: 'Como vais usar?', obModeDesc: 'Ativa o que te serve. Podes ter ambos.',
    obModeWorkToggle: 'Modo trabalho', obModeWorkToggleDesc: 'Grupos em vez de disciplinas, sem avaliações.',
    obModeWeeksToggle: 'Sem semestres', obModeWeeksToggleDesc: 'Organiza por semana do calendário.',
    obImportOr: 'ou restaura uma cópia',
    obDatesTitle: 'O teu semestre', obDatesDesc: 'Quando começa e termina?',
    obClassesTitle: 'As tuas disciplinas', obClassesDesc: 'Adiciona as disciplinas que tens.',
    obGroupsTitle: 'Os teus grupos', obGroupsDesc: 'Adiciona os grupos com que trabalhas.',
    obInfoTasksTitle: 'Tarefas e Kanban', obInfoTasksDesc: 'Adiciona tarefas por semana ou data e arrasta-as pelo quadro kanban.',
    obInfoCalTitle: 'Calendário e Foco', obInfoCalDesc: 'Vê tudo no calendário e faz sessões de foco para produzir.',
    obInfoDoneTitle: 'Está tudo pronto', obInfoDoneDesc: 'Podes mudar isto mais tarde nas definições.',
    shareLink: 'Copiar link de partilha', qrCode: 'Código QR', linkCopied: 'Link copiado!',
    high: 'Alta', medium: 'Média', low: 'Baixa', none: 'Nenhuma',
    addSemester: 'Adicionar semestre', semesterName: 'Nome do semestre', startDate: 'Data de início', endDate: 'Data de fim',
    weeks: n => `${n} semanas`, addAClass: 'Adicionar disciplina', className: 'Nome da disciplina', ects: 'ECTS', colour: 'Cor',
    addComponent: 'Adicionar componente', componentName: 'Nome do componente',
    taskSpanLabel: 'Comportamento de tarefas multi-semana', taskSpanDesc: 'Quando uma tarefa abrange várias semanas, como é marcada como concluída?',
    kanbanChecklistInlineLabel: 'Pré-visualização da checklist no Kanban',
    kanbanChecklistInlineDesc: 'Mostra os itens da checklist diretamente nos cartões sem abrir os detalhes.',
    kanbanChecklistPreviewNone: 'Ocultar nos cartões',
    kanbanChecklistPreviewAll: 'Mostrar em todos os cartões',
    kanbanChecklistPreviewPerCard: 'Caso a caso',
    focusAlertModeLabel: 'Modo de alerta no foco',
    focusAlertModeDesc: 'Escolhe como os alertas de foco aparecem quando a fase do cronómetro muda.',
    focusAlertNone: 'Nenhum',
    focusAlertVibration: 'Vibração',
    focusAlertNotification: 'Notificação',
    focusAlertBoth: 'Ambos',
    taskAlertModeLabel: 'Alertas de prazo das tarefas',
    taskAlertModeDesc: 'Escolhe como os alertas de prazo das tarefas são apresentados.',
    taskAlertNone: 'Nenhum',
    taskAlertInApp: 'Na app',
    taskAlertNotification: 'Notificação',
    taskAlertBoth: 'Ambos',
    taskAlertNextDayTimeLabel: 'Hora do alerta para amanhã',
    taskAlertNextDayTimeDesc: 'Hora dos lembretes para tarefas com prazo amanhã.',
    taskDefaultToCalendarLabel: 'Tarefas no calendário por defeito',
    taskDefaultToCalendarDesc: 'Novas tarefas terão "Mostrar no calendário" ativado por defeito.',
    taskDueTodayTitle: count => count === 1 ? 'Tarefa para hoje' : `${count} tarefas para hoje`,
    taskAlertHide: 'Ocultar alerta',
    taskAlertRemindMeAt: 'Lembrar-me às',
    settingEnabled: 'Ativado', settingDisabled: 'Desativado',
    spanSingle: 'Uma checkbox global (concluída uma vez)', spanPerWeek: 'Checkbox por semana',
    dangerZone: 'Zona de perigo', deleteSemester: 'Eliminar este semestre',
    clearPomodoros: 'Limpar pomodoros',
    clearPomodorosTitle: 'Limpar todos os pomodoros?',
    clearPomodorosDesc: 'Todos os pomodoros caídos serão eliminados permanentemente.',
    deleteSemesterTitle: 'Eliminar semestre?', deleteSemesterDesc: 'Todas as tarefas, avaliações e dados do Kanban deste semestre serão eliminados permanentemente.',
    clearDoneTitle: 'Limpar coluna concluída?', clearDoneDesc: 'Todos os cartões da coluna Concluído serão eliminados.',
    wipeAllTitle: 'Apagar todos os cartões?', wipeAllDesc: 'Todos os cartões do quadro serão eliminados permanentemente.',
    selectSemester: 'Selecionar semestre', noClassesYet: 'Ainda sem disciplinas', addClassesInSettings: 'Adiciona disciplinas em Definições.',
    addUnlocks: 'Adiciona um semestre para desbloquear o resto.',
    checklist: 'Lista de verificação', addItem: 'Adicionar item', editCard: 'Editar cartão',
    notAchievable: '— impossível de atingir', onRemaining: ' nas componentes restantes',
    youNeed: 'Precisas de', allGraded: 'Todas as componentes avaliadas.',
    noGradeComponents: 'Nenhuma componente configurada. Vai a Definições.',
    deleteClassTitle: 'Eliminar disciplina?', deleteClassDesc: 'Isto irá também eliminar todas as tarefas desta disciplina.',
    holidayName: 'Nome do feriado', holidayNamePlaceholder: 'ex. Natal',
    addHoliday: 'Adicionar feriado',
    loadPreset: 'Carregar preset',
    presetLoading: 'A carregar preset…', presetError: 'Falhou ao carregar o preset.', retry: 'Tentar novamente', skip: 'Saltar',
    newColumnName: 'Nome da nova coluna',
    focusStart: 'Iniciar', focusPause: 'Pausar', focusResume: 'Retomar', focusReset: 'Reiniciar', focusSkipBreak: 'Saltar pausa',
    focusReady: 'pronto', focusBreak: 'pausa',
    focusPhrases: ['continua', 'mantém o foco', 'estás a ir bem', 'um passo de cada vez', 'trabalho profundo', 'fica presente'],
    focusEvery: 'cada (min)', focusBreakFor: 'pausa (min)',
    focusScheduledMode: 'Pausas agendadas',
    focusNextBreak: 'Próxima pausa às',
    focusFocusLabel: 'Mensagem de foco', focusBreakLabel: 'Mensagem de pausa',
    loadPresetTitle: 'Carregar um preset',
    presetGroupEI: 'Curso EI',
    presetGroupGeneric: 'Geral',
    backToMenu: 'Voltar',
    importData: 'Importar dados',
    importFromFirebase: 'Importar do Firebase',
    nextSemesterTitle: 'Semestre terminado',
    nextSemesterDesc: 'O teu semestre terminou. Carregar o próximo?',
    loadNextSemester: 'Carregar próximo semestre',
    dismissNextSemester: 'Dispensar',
    noSemesterYet: 'Nenhum semestre configurado',
    noSemesterDesc: 'Carrega um preset ou importa os teus dados para começar.',
    focusIntervalMode: 'Pausas por intervalo',
    focusIntervalEvery: 'cada (min)',
    focusIntervalBreakFor: 'pausa (min)',
    focusScheduledBreakFor: 'pausa (min)',
    focusAfterBreakReset: 'Após pausa: reiniciar timer',
    focusAfterBreakContinue: 'Após pausa: continuar a contar',
    firebaseSync: 'Sincronização Firebase',
    firebaseConnect: 'Ligar',
    firebaseConnected: 'Ligado',
    firebaseDisconnect: 'Desligar',
    firebaseSyncing: 'A sincronizar…',
    firebaseLastSync: 'Última sincronização',
    firebaseError: 'Erro de sincronização',
    firebaseRemoteNewer: 'Os dados na nuvem são de uma versão mais recente. Sincronização em pausa. Atualiza a app.',
    collabSyncFailed: 'Não foi possível sincronizar a alteração partilhada. Foi revertida.',
    newerVersionWarning: 'Os teus dados foram guardados por uma versão mais recente da app. Algumas coisas podem não aparecer corretamente até atualizares.',
    firebaseSetupTitle: 'Ligar ao Firebase',
    firebaseStep1Title: 'Criar um projeto Firebase',
    firebaseStep1Desc: 'Vai a console.firebase.google.com → Adicionar projeto → dá um nome → desativa o Google Analytics → Criar projeto.',
    firebaseStep2Title: 'Ativar o Firestore',
    firebaseStep2Desc: 'Vai a Criar → Firestore Database → Criar base de dados → escolhe uma região → Iniciar em modo de produção → Criar. Depois vai a Regras, substitui o conteúdo por: allow read, write: if true; e clica em Publicar.',
    firebaseStep3Title: 'Obter a configuração',
    firebaseStep3Desc: 'Vai às Definições do projeto (ícone de engrenagem) → As tuas apps → Adicionar app → Web → regista a app → copia o objeto firebaseConfig mostrado.',
    firebaseStep4Title: 'Cola a configuração',
    firebaseStep4Desc: 'Cola o objeto firebaseConfig completo (em JSON) abaixo.',
    firebaseConfigPlaceholder: '{ "apiKey": "...", "authDomain": "...", "projectId": "...", ... }',
    firebaseConfigInvalid: 'Configuração inválida: deve incluir apiKey e projectId.',
    firebaseTestFailed: 'Não foi possível ligar. Verifica a configuração e as regras da base de dados.',
    firebaseSave: 'Guardar e ligar',
    pomodoroMode: 'Modo pomodoro',
    pomodoroModeDesc: 'Faz crescer tomates durante as sessões de foco. Cada sessão completa deixa cair um tomate.',
    pomodoroResetPeriod: 'Período de reset',
    pomodoroResetDay: 'Diário', pomodoroResetWeek: 'Semanal', pomodoroResetMonth: 'Mensal', pomodoroResetSemester: 'Por semestre',
    pomodoroTrackPeriodStats: 'Guardar estatísticas do período',
    pomodoroShowAbandoned: 'Mostrar tomates abandonados',
    pomodoroShowPeriodPomodoros: 'Mostrar pomodoros do período',
    pomodoroStatsTitle: 'Estatísticas pomodoro',
    pomodoroTotal: 'Total de tomates', pomodoroAbandoned: 'Abandonados', pomodoroFocusTime: 'Tempo total de foco',
    pomodoroPeriodTotal: 'Este período', pomodoroPeriodFocus: 'Foco neste período',
    pomodoroVsSinceLast: 'vs período anterior',
    pomodoroAllTime: 'Todo o tempo',
    pomodoroInsightsDailyTitle: 'Foco diário desta semana',
    pomodoroInsightsWeeklyBreakdownTitle: 'Média por semana',
    pomodoroInsightsAvgWeekLabel: 'média por dia (semana)',
    pomodoroInsightsAvgPeriodLabel: 'média por dia (período)',
    pomodoroInsightsPerDaySuffix: '/d',
    pomodoroInsightsNoWeeklyData: 'Ainda sem dados semanais.',
    pomodoroInsightsDayLabels: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'],
    pomodoroTotalTimeLabel: 'tempo total',
    pomodoroClose: 'Fechar',
    pomodoroEraseStats: 'Apagar estatísticas',
    pomodoroEraseStatsTitle: 'Apagar estatísticas pomodoro?',
    pomodoroEraseStatsDesc: 'As estatísticas históricas de tempo de foco serão removidas, mas os registos de tomates mantêm-se.',
    pomodoroGraceCancel: 'Cancelar (sem tomate)',
    pomodoroGrace: s => `${s}s para cancelar sem perder um tomate`,
    workModeLabel: 'Modo trabalho',
    workModeDesc: 'Oculta avaliações e renomeia disciplinas para grupos.',
    workModeOnboarding: 'Usar para trabalho?',
    semesterModeLabel: 'Modo sem semestres',
    semesterModeDesc: 'Liga para usar semanas do ano em vez de semestres. As avaliações ficam ocultas.',
    semesterModeNone: 'Sem semestres (semanas do ano)',
    semesterModeSemesters: 'A usar semestres',
    semesterModeOnboarding: 'Sem semestres, só semanas?',
    groups: 'Grupos', addAGroup: 'Adicionar grupo', groupName: 'Nome do grupo',
    deleteGroupTitle: 'Eliminar grupo?', deleteGroupDesc: 'Isto irá também eliminar todas as tarefas deste grupo.',
    storageWarningTitle: 'Limite de armazenamento atingido',
    storageWarningDesc: 'Por favor ativa a sincronização Firebase, atingiste o limite de armazenamento local.',
    storageWarningAction: 'Percebido',
    collabConnect: 'Ligar Organizer Collab',
    collabDisconnect: 'Desligar Organizer Collab',
    collabRequiresFirebase: 'Liga primeiro a sincronização Firebase para usar o Organizer Collab.',
    collabGuideTitle: 'Configuração do Organizer Collab',
    collabGuideIntro: 'Configuração única. Faz estes 4 passos no Firebase e depois volta para ativar o collab.',
    collabGuideImportantTitle: 'O que muda quando ativas collab',
    collabGuideImportant1: 'A base de dados passa a exigir utilizadores autenticados (anónimo chega).',
    collabGuideImportant2: 'A sincronização normal do organizer continua a funcionar, mas autentica primeiro.',
    collabGuideImportant3: 'Se desligares collab mais tarde, podes continuar com regras baseadas em auth sem problemas.',
    collabGuideStep1: 'Abre Firebase Console > Build > Firestore Database > Regras.',
    collabGuideStep2: 'Cola o snippet de regras abaixo e clica em Publicar.',
    collabGuideStep3: 'Abre Security > Authentication > Método de início de sessão > ativa Anónimo > Guardar.',
    collabGuideStep4: 'Volta ao Organizer e carrega em "Já configurei as regras, ativar collab".',
    collabGuideRulesLabel: 'Regras Firestore',
    collabGuideTroubleshootTitle: 'Se aparecer erro signUp 400',
    collabGuideTroubleshootBody: 'Significa que a autenticação Anónima ainda está desativada no Firebase. Ativa em Security > Authentication > Método de início de sessão.',
    collabEnableNow: 'Já configurei as regras, ativar collab',
    collabPanelTitle: 'Organizer Collab',
    collabPanelSubtitle: 'Cria equipas, convida pessoas e partilha tarefas/cartões do kanban.',
    collabCreateTeam: 'Criar equipa',
    collabTeamName: 'Nome da equipa',
    collabTeamDays: 'dias da equipa',
    collabTeamDuration: 'duração da equipa',
    collabDays: 'dias',
    collabJoinTeam: 'Entrar na equipa',
    collabInvitePlaceholder: 'Cola o link de convite',
    collabInviteTtl: 'Validade do convite',
    collabYourTeams: 'As tuas equipas',
    collabNoTeams: 'Ainda sem equipas.',
    collabRoleHost: 'host',
    collabRoleMember: 'membro',
    collabEndsAt: 'termina em',
    collabInvite: 'Convidar',
    collabEditTeam: 'Editar equipa',
    collabTaskCompletionMode: 'Conclusão de tarefas partilhadas',
    collabTaskCompletionPersonal: 'conclusão pessoal',
    collabTaskCompletionForAll: 'marcar para todos',
    collabTaskPermissions: 'Permissões de edição de tarefas',
    collabTaskPermissionsEveryone: 'qualquer membro pode adicionar/editar/remover tarefas',
    collabTaskPermissionsHostOnly: 'apenas o host pode adicionar/editar/remover tarefas',
    collabLeave: 'Sair',
    collabDeleteTeam: 'Eliminar',
    collabDefaultTeamName: 'Equipa',
    collabLeavePrompt: 'Sair desta equipa?',
    collabLeaveWithLocalPrompt: 'Partilhaste tarefas locais nesta equipa. Queres mantê-las localmente?',
    collabDeleteTeamPrompt: 'Eliminar esta equipa?',
    collabDeleteTeamWithLocalPrompt: 'Partilhaste tarefas locais nesta equipa. Queres mantê-las localmente antes de eliminar a equipa?',
    collabKeepLocalTasks: 'Manter locais',
    collabDeleteLocalTasksToo: 'Apagar as locais',
    collabErrorCreate: 'Não foi possível criar a equipa.',
    collabErrorInvite: 'Não foi possível gerar convite.',
    collabErrorJoin: 'Não foi possível entrar na equipa.',
    collabErrorInvalidLink: 'Link de convite inválido.',
    collabErrorDeleteTeam: 'Não foi possível eliminar a equipa.',
  },
  fr: {
    tasks: 'Tâches', kanban: 'Kanban', grades: 'Notes', calendar: 'Calendrier', focus: 'Focus', settings: 'Réglages',
    noSemester: 'Aucun semestre configuré', goToSettings: 'Allez dans Réglages pour commencer.',
    weekLabel: w => `Semaine ${w}`, done: 'terminées', timeToRelax: 'Temps de repos !',
    addTask: 'Nouvelle tâche', task: 'Tâche', class: 'Matière', priority: 'Priorité',
    editTask: 'Modifier la tâche', moveLeft: 'Déplacer à gauche', moveRight: 'Déplacer à droite', markDone: 'Marquer comme fait',
    addToKanban: 'Ajouter au Kanban', themeLight: 'Thème clair', themeDark: 'Thème sombre', themeSystem: 'Thème système',
    addPartTitle: 'Ajouter une partie',
    fromWeek: 'De la semaine', toWeek: "Jusqu'à la semaine", dueDate: "Date d'échéance",
    other: 'Autre', noTasks: 'Aucune tâche cette semaine.',
    whatNeedsDone: "Qu'y a-t-il à faire ?",
    addTaskBtn: 'Ajouter la tâche', showOnCalendar: 'Afficher sur le calendrier', showOnTasks: 'Afficher dans les tâches',
    clearDone: 'Effacer les terminées', wipeAll: 'Tout effacer',
    addCard: 'Ajouter une carte', addCardPlaceholder: 'Titre de la carte',
    save: 'Enregistrer', cancel: 'Annuler', confirm: 'Confirmer', delete: 'Supprimer',
    addEvent: 'Ajouter un événement', newEvent: 'Nouvel événement', editEvent: "Modifier l'événement",
    eventTitle: "Titre de l'événement", eventDate: 'Date', eventRange: 'Plage de dates',
    eventMultiDay: 'Plusieurs jours', eventColor: 'Couleur', eventNote: 'Note',
    eventNotePlaceholder: 'Note facultative', more: 'plus',
    navbar: 'Barre de navigation', navHide: 'Masquer', navOverflow: 'Déplacer vers le menu', navAddButton: "Afficher le bouton d'ajout",
    navMore: 'Plus', navLabelMode: 'Afficher', navLabelBoth: 'Icônes + noms', navLabelIcons: 'Icônes seules', navLabelNames: 'Noms seuls',
    add: 'Ajouter', navAddLabel: 'Ajouter', navDrag: 'Glisser pour réorganiser',
    appDisableTitle: 'Désactiver et effacer les données ?', appDisableDesc: 'Désactiver cette app supprime définitivement toutes ses données.',
    collabDisableDesc: 'La déconnexion quitte toutes les équipes et supprime définitivement les données de collaboration de cet appareil.',
    navAddAction: "Action du bouton d'ajout", navAddPicker: 'Demander à chaque fois',
    navFolders: 'Dossiers', navNewFolder: 'Nouveau dossier',
    navMobilePosition: 'Position de la barre mobile', navPosBottom: 'Barre en bas', navPosSide: 'Barre latérale',
    addToTasks: 'Ajouter aux tâches', inTasks: 'Dans les tâches',
    standby: 'Veille', standbyEnable: 'Activer la veille paysage',
    standbyDesc: 'Mettez votre téléphone en paysage pour afficher un tableau de bord ambiant.',
    standbyLeft: 'Volet gauche', standbyCenter: 'Volet central', standbyRight: 'Volet droit',
    standbyPanels: 'Volets', standbyPane: n => `Volet ${n}`,
    paneWheel: 'Roue de progression', paneWheelTime: 'Roue + horloge', paneCalendar: 'Calendrier',
    paneFocus: 'Focus', paneKanban: 'Kanban', paneTasksByCategory: 'Tâches par catégorie',
    notesLastEdit: 'Modifié', notesFolder: 'Dossier', notesNoFolder: 'Sans dossier', notesNewFolder: 'Nouveau dossier',
    notesFolderName: 'Nom du dossier', notesRenameFolder: 'Renommer le dossier', notesDeleteFolder: 'Supprimer le dossier', notesMoveTo: 'Déplacer vers',
    notesEdit: 'Modifier', notesPreview: 'Aperçu', notesBack: 'Retour',
    apps: 'Apps', appsSearch: 'Rechercher des apps', appsNoResults: 'Aucune app trouvée.', notes: 'Notes',
    notesEnable: 'Activer les Notes', notesEnableDesc: 'Ajoute un onglet Notes pour des notes rapides.',
    notesNew: 'Nouvelle note', notesTitle: 'Titre', notesBody: 'Écrivez quelque chose…', notesSearch: 'Rechercher des notes',
    notesEmpty: 'Aucune note pour le moment.', notesFavorite: 'Favori', notesText: 'Texte', notesCanvas: 'Écriture manuscrite',
    notesCanvasWarning: 'Les notes avec dessins peuvent occuper beaucoup d\'espace et ne sont donc disponibles qu\'avec Firebase activé.',
    collabApp: 'Collaboration',
    eiCalendar: 'Calendrier EI', eiCalendarEnable: 'Afficher le calendrier EI',
    eiCalendarEnableDesc: "Ajoute le calendrier officiel du cursus EI pour votre année, en lecture seule et toujours à jour.",
    eiCalendarDisableTitle: 'Masquer le calendrier EI ?', eiCalendarDisableDesc: "Cesse d'afficher les événements du calendrier EI. Rien n'est supprimé et vous pouvez le réactiver à tout moment.",
    semester: 'Semestre', classes: 'Matières', gradeComponents: 'Composantes de note',
    kanbanColumns: 'Colonnes Kanban', general: 'Général', data: 'Données et sync',
    holidays: 'Vacances',
    exportJson: 'Exporter JSON', importJson: 'Importer JSON',
    semesterAvg: 'Moyenne du semestre', ectsPassedLabel: 'ECTS validés',
    targetGrade: 'Note visée',
    previousSemesters: 'Semestres précédents',
    courseAvg: 'Moyenne du cours', finalGrade: 'Note finale', previousAvg: 'Moyenne précédente', numSemesters: 'Nb de semestres',
    getStarted: 'Commencer', welcomeTitle: 'Bienvenue sur organizer',
    welcomeDesc: 'Votre espace pour le travail universitaire. Configurez votre semestre et organisez-vous.',
    step1: 'Définir les dates du semestre', step2: 'Ajouter vos matières', step3: 'Planifier les tâches et suivre les notes',
    obNext: 'Suivant', obBack: 'Retour', obFinish: 'Terminer', obSkip: 'Passer',
    obWelcomeTitle: 'Bienvenue sur Organizer', obWelcomeDesc: 'Votre espace calme pour le travail universitaire. Choisissez votre langue et votre thème pour commencer.',
    obModeTitle: 'Comment allez-vous l\'utiliser ?', obModeDesc: 'Activez ce qui vous convient. Les deux peuvent être actifs.',
    obModeWorkToggle: 'Mode travail', obModeWorkToggleDesc: 'Groupes au lieu de matières, sans notes.',
    obModeWeeksToggle: 'Sans semestres', obModeWeeksToggleDesc: 'Organiser par semaine calendaire plutôt que par semestre.',
    obImportOr: 'ou restaurer une sauvegarde',
    obDatesTitle: 'Votre semestre', obDatesDesc: 'Quand commence-t-il et se termine-t-il ?',
    obClassesTitle: 'Vos matières', obClassesDesc: 'Ajoutez les matières que vous suivez.',
    obGroupsTitle: 'Vos groupes', obGroupsDesc: 'Ajoutez les groupes avec lesquels vous travaillez.',
    obInfoTasksTitle: 'Tâches et Kanban', obInfoTasksDesc: 'Ajoutez des tâches par semaine ou par date, puis glissez-les sur votre tableau kanban.',
    obInfoCalTitle: 'Calendrier et Focus', obInfoCalDesc: 'Voyez tout sur le calendrier et lancez des sessions de focus pour avancer.',
    obInfoDoneTitle: 'Tout est prêt', obInfoDoneDesc: 'Vous pourrez modifier tout cela plus tard dans les réglages.',
    shareLink: 'Copier le lien de partage', qrCode: 'Code QR', linkCopied: 'Lien copié !',
    high: 'Haute', medium: 'Moyenne', low: 'Basse', none: 'Aucune',
    addSemester: 'Ajouter un semestre', semesterName: 'Nom du semestre', startDate: 'Date de début', endDate: 'Date de fin',
    weeks: n => `${n} semaines`, addAClass: 'Ajouter une matière', className: 'Nom de la matière', ects: 'ECTS', colour: 'Couleur',
    addComponent: 'Ajouter une composante', componentName: 'Nom de la composante',
    taskSpanLabel: 'Comportement des tâches sur plusieurs semaines', taskSpanDesc: 'Quand une tâche couvre plusieurs semaines, comment est-elle marquée comme faite ?',
    kanbanChecklistInlineLabel: 'Aperçu de la checklist Kanban',
    kanbanChecklistInlineDesc: 'Afficher les éléments de la checklist directement sur les cartes sans ouvrir les détails.',
    kanbanChecklistPreviewNone: 'Masquer sur les cartes',
    kanbanChecklistPreviewAll: 'Afficher sur toutes les cartes',
    kanbanChecklistPreviewPerCard: 'Au cas par cas',
    focusAlertModeLabel: 'Mode d\'alerte Focus',
    focusAlertModeDesc: 'Choisissez comment les alertes Focus sont délivrées au changement de phase.',
    focusAlertNone: 'Aucune',
    focusAlertVibration: 'Vibration',
    focusAlertNotification: 'Notification',
    focusAlertBoth: 'Les deux',
    taskAlertModeLabel: 'Alertes d\'échéance des tâches',
    taskAlertModeDesc: 'Choisissez comment les alertes d\'échéance sont délivrées.',
    taskAlertNone: 'Aucune',
    taskAlertInApp: 'Dans l\'app',
    taskAlertNotification: 'Notification',
    taskAlertBoth: 'Les deux',
    taskAlertNextDayTimeLabel: 'Heure de l\'alerte du lendemain',
    taskAlertNextDayTimeDesc: 'Heure des rappels pour les tâches dues demain.',
    taskDefaultToCalendarLabel: 'Tâches sur le calendrier par défaut',
    taskDefaultToCalendarDesc: 'Les nouvelles tâches auront « Afficher sur le calendrier » activé par défaut.',
    taskDueTodayTitle: count => count === 1 ? 'Tâche due aujourd\'hui' : `${count} tâches dues aujourd'hui`,
    taskAlertHide: 'Masquer l\'alerte',
    taskAlertRemindMeAt: 'Me rappeler à',
    settingEnabled: 'Activé', settingDisabled: 'Désactivé',
    spanSingle: 'Une seule case globale (fait une fois)', spanPerWeek: 'Case par semaine',
    dangerZone: 'Zone sensible', deleteSemester: 'Supprimer ce semestre',
    clearPomodoros: 'Effacer les pomodoros',
    clearPomodorosTitle: 'Effacer tous les pomodoros ?',
    clearPomodorosDesc: 'Tous les pomodoros tombés seront supprimés définitivement.',
    deleteSemesterTitle: 'Supprimer le semestre ?', deleteSemesterDesc: 'Toutes les tâches, notes et données kanban de ce semestre seront supprimées définitivement.',
    clearDoneTitle: 'Effacer la colonne Terminé ?', clearDoneDesc: 'Toutes les cartes de la colonne Terminé seront supprimées.',
    wipeAllTitle: 'Effacer toutes les cartes ?', wipeAllDesc: 'Toutes les cartes du tableau seront supprimées définitivement.',
    selectSemester: 'Sélectionner un semestre', noClassesYet: 'Aucune matière pour le moment', addClassesInSettings: 'Ajoutez des matières dans Réglages.',
    addUnlocks: 'Ajoutez un semestre pour débloquer le reste.',
    checklist: 'Checklist', addItem: 'Ajouter un élément', editCard: 'Modifier la carte',
    notAchievable: '— non atteignable', onRemaining: ' sur les évaluations restantes',
    youNeed: 'Il vous faut', allGraded: 'Toutes les composantes sont notées.',
    noGradeComponents: 'Aucune composante de note configurée. Allez dans Réglages.',
    deleteClassTitle: 'Supprimer la matière ?', deleteClassDesc: 'Cela supprimera aussi toutes les tâches de cette matière.',
    holidayName: 'Nom des vacances', holidayNamePlaceholder: 'ex : Vacances de Noël',
    addHoliday: 'Ajouter des vacances',
    loadPreset: 'Charger un préréglage',
    presetLoading: 'Chargement du préréglage…', presetError: 'Échec du chargement du préréglage.', retry: 'Réessayer', skip: 'Passer',
    newColumnName: 'Nom de la nouvelle colonne',
    focusStart: 'Démarrer', focusPause: 'Pause', focusResume: 'Reprendre', focusReset: 'Réinitialiser', focusSkipBreak: 'Passer la pause',
    focusReady: 'prêt', focusBreak: 'pause',
    focusPhrases: ['continuez', 'restez concentré', 'vous vous en sortez bien', 'un pas à la fois', 'travail profond', 'restez présent'],
    focusEvery: 'toutes les (min)', focusBreakFor: 'pause (min)',
    focusScheduledMode: 'Pauses programmées',
    focusNextBreak: 'Prochaine pause à',
    focusFocusLabel: 'Message de focus', focusBreakLabel: 'Message de pause',
    loadPresetTitle: 'Charger un préréglage',
    presetGroupEI: 'Cursus EI',
    presetGroupGeneric: 'Général',
    backToMenu: 'Retour',
    importData: 'Importer les données',
    importFromFirebase: 'Importer depuis Firebase',
    nextSemesterTitle: 'Semestre terminé',
    nextSemesterDesc: 'Votre semestre est terminé. Charger le suivant ?',
    loadNextSemester: 'Charger le prochain semestre',
    dismissNextSemester: 'Ignorer',
    noSemesterYet: 'Aucun semestre configuré',
    noSemesterDesc: 'Chargez un préréglage ou importez vos données pour commencer.',
    focusIntervalMode: 'Pauses par intervalle',
    focusIntervalEvery: 'toutes les (min)',
    focusIntervalBreakFor: 'pause (min)',
    focusScheduledBreakFor: 'pause (min)',
    focusAfterBreakReset: 'Après la pause : réinitialiser le minuteur',
    focusAfterBreakContinue: 'Après la pause : continuer à compter',
    firebaseSync: 'Sync Firebase',
    firebaseConnect: 'Connecter',
    firebaseConnected: 'Connecté',
    firebaseDisconnect: 'Déconnecter',
    firebaseSyncing: 'Synchronisation…',
    firebaseLastSync: 'Dernière sync',
    firebaseError: 'Erreur de sync',
    firebaseRemoteNewer: 'Les données cloud proviennent d\'une version plus récente. Sync en pause. Mettez à jour l\'app.',
    collabSyncFailed: 'Impossible de synchroniser le changement partagé. Il a été annulé.',
    newerVersionWarning: 'Vos données ont été enregistrées par une version plus récente. Certaines choses peuvent ne pas s\'afficher correctement avant la mise à jour.',
    firebaseSetupTitle: 'Connecter Firebase',
    firebaseStep1Title: 'Créer un projet Firebase',
    firebaseStep1Desc: 'Allez sur console.firebase.google.com → Ajouter un projet → donnez-lui un nom → désactivez Google Analytics → Créer le projet.',
    firebaseStep2Title: 'Activer Firestore',
    firebaseStep2Desc: 'Allez dans Build → Firestore Database → Créer une base → choisissez une région → Démarrer en mode production → Créer. Puis dans Règles, remplacez le contenu par : allow read, write: if true; et cliquez sur Publier.',
    firebaseStep3Title: 'Obtenir votre configuration',
    firebaseStep3Desc: 'Allez dans Paramètres du projet (icône engrenage) → Vos apps → Ajouter une app → Web → enregistrez l\'app → copiez l\'objet firebaseConfig affiché.',
    firebaseStep4Title: 'Coller votre configuration',
    firebaseStep4Desc: 'Collez l\'objet firebaseConfig complet (en JSON) ci-dessous.',
    firebaseConfigPlaceholder: '{ "apiKey": "...", "authDomain": "...", "projectId": "...", ... }',
    firebaseConfigInvalid: 'Config invalide : doit inclure apiKey et projectId.',
    firebaseTestFailed: 'Connexion impossible. Vérifiez votre config et les règles de la base.',
    firebaseSave: 'Enregistrer et connecter',
    pomodoroMode: 'Mode Pomodoro',
    pomodoroModeDesc: 'Faites pousser des tomates pendant les sessions de focus. Chaque session terminée dépose une tomate.',
    pomodoroResetPeriod: 'Période de réinitialisation',
    pomodoroResetDay: 'Quotidien', pomodoroResetWeek: 'Hebdomadaire', pomodoroResetMonth: 'Mensuel', pomodoroResetSemester: 'Par semestre',
    pomodoroTrackPeriodStats: 'Suivre les stats de période',
    pomodoroShowAbandoned: 'Afficher les tomates abandonnées',
    pomodoroShowPeriodPomodoros: 'Afficher les pomodoros de la période',
    pomodoroStatsTitle: 'Stats Pomodoro',
    pomodoroTotal: 'Total de tomates', pomodoroAbandoned: 'Abandonnées', pomodoroFocusTime: 'Temps de focus total',
    pomodoroPeriodTotal: 'Cette période', pomodoroPeriodFocus: 'Focus cette période',
    pomodoroVsSinceLast: 'vs période précédente',
    pomodoroAllTime: 'Depuis le début',
    pomodoroInsightsDailyTitle: 'Focus quotidien cette semaine',
    pomodoroInsightsWeeklyBreakdownTitle: 'Moyennes hebdomadaires',
    pomodoroInsightsAvgWeekLabel: 'moy/jour (semaine)',
    pomodoroInsightsAvgPeriodLabel: 'moy/jour (période)',
    pomodoroInsightsPerDaySuffix: '/j',
    pomodoroInsightsNoWeeklyData: 'Pas encore de données hebdomadaires.',
    pomodoroInsightsDayLabels: ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
    pomodoroTotalTimeLabel: 'temps total',
    pomodoroClose: 'Fermer',
    pomodoroEraseStats: 'Effacer les stats',
    pomodoroEraseStatsTitle: 'Effacer les stats Pomodoro ?',
    pomodoroEraseStatsDesc: 'Les stats historiques de temps de focus seront supprimées, mais les tomates restent disponibles.',
    pomodoroGraceCancel: 'Annuler (pas de tomate)',
    pomodoroGrace: s => `${s}s pour annuler sans perdre une tomate`,
    workModeLabel: 'Mode travail',
    workModeDesc: 'Masque les notes et renomme les matières en groupes.',
    workModeOnboarding: 'Utiliser ceci pour le travail ?',
    semesterModeLabel: 'Mode sans semestre',
    semesterModeDesc: 'Activez pour utiliser de simples semaines annuelles au lieu des semestres. Les notes sont masquées.',
    semesterModeNone: 'Sans semestres (semaines annuelles)',
    semesterModeSemesters: 'Avec semestres',
    semesterModeOnboarding: 'Sans semestres, juste des semaines ?',
    groups: 'Groupes', addAGroup: 'Ajouter un groupe', groupName: 'Nom du groupe',
    deleteGroupTitle: 'Supprimer le groupe ?', deleteGroupDesc: 'Cela supprimera aussi toutes les tâches de ce groupe.',
    storageWarningTitle: 'Limite de stockage atteinte',
    storageWarningDesc: 'Veuillez activer la sync Firebase, stockage local maximal atteint.',
    storageWarningAction: 'Compris',
    collabConnect: 'Connecter Organizer Collab',
    collabDisconnect: 'Déconnecter Organizer Collab',
    collabRequiresFirebase: 'Connectez d\'abord la sync Firebase pour utiliser Organizer Collab.',
    collabGuideTitle: 'Configuration Organizer Collab',
    collabGuideIntro: 'Configuration unique. Faites ces 4 étapes dans Firebase, puis revenez activer la collab.',
    collabGuideImportantTitle: 'Ce qui change quand la collab est activée',
    collabGuideImportant1: 'Votre base commence à exiger des utilisateurs authentifiés (l\'auth anonyme suffit).',
    collabGuideImportant2: 'La sync normale continue de fonctionner, mais doit d\'abord s\'authentifier.',
    collabGuideImportant3: 'Si la collab est désactivée plus tard, les règles basées sur l\'auth restent utilisables en toute sécurité.',
    collabGuideStep1: 'Ouvrez Firebase Console > Build > Firestore Database > Règles.',
    collabGuideStep2: 'Collez l\'extrait de règles ci-dessous et cliquez sur Publier.',
    collabGuideStep3: 'Ouvrez Security > Authentication > Méthode de connexion > activez Anonyme > Enregistrer.',
    collabGuideStep4: 'Revenez à Organizer et appuyez sur « J\'ai configuré les règles, activer la collab ».',
    collabGuideRulesLabel: 'Règles Firestore',
    collabGuideTroubleshootTitle: 'Si vous voyez une erreur signUp 400',
    collabGuideTroubleshootBody: 'Cela signifie que l\'authentification anonyme est encore désactivée dans Firebase. Activez-la dans Security > Authentication > Méthode de connexion.',
    collabEnableNow: 'J\'ai configuré les règles, activer la collab',
    collabPanelTitle: 'Organizer Collab',
    collabPanelSubtitle: 'Créez des équipes, invitez des personnes et partagez tâches/cartes kanban.',
    collabCreateTeam: 'Créer une équipe',
    collabTeamName: 'Nom de l\'équipe',
    collabTeamDays: 'jours de l\'équipe',
    collabTeamDuration: 'durée de l\'équipe',
    collabDays: 'jours',
    collabJoinTeam: 'Rejoindre une équipe',
    collabInvitePlaceholder: 'Coller le lien d\'invitation',
    collabInviteTtl: 'Validité de l\'invitation',
    collabYourTeams: 'Vos équipes',
    collabNoTeams: 'Aucune équipe pour le moment.',
    collabRoleHost: 'hôte',
    collabRoleMember: 'membre',
    collabEndsAt: 'se termine',
    collabInvite: 'Inviter',
    collabEditTeam: 'Modifier l\'équipe',
    collabTaskCompletionMode: 'Achèvement des tâches partagées',
    collabTaskCompletionPersonal: 'achèvement personnel',
    collabTaskCompletionForAll: 'basculer pour tous',
    collabTaskPermissions: 'Permissions de modification des tâches',
    collabTaskPermissionsEveryone: 'tout le monde peut ajouter/modifier/supprimer des tâches',
    collabTaskPermissionsHostOnly: 'seul l\'hôte peut ajouter/modifier/supprimer des tâches',
    collabLeave: 'Quitter',
    collabDeleteTeam: 'Supprimer',
    collabDefaultTeamName: 'Équipe',
    collabLeavePrompt: 'Quitter cette équipe ?',
    collabLeaveWithLocalPrompt: 'Vous avez partagé des tâches locales dans cette équipe. Les garder localement ?',
    collabDeleteTeamPrompt: 'Supprimer cette équipe ?',
    collabDeleteTeamWithLocalPrompt: 'Vous avez partagé des tâches locales dans cette équipe. Les garder localement avant de supprimer l\'équipe ?',
    collabKeepLocalTasks: 'Garder les tâches locales',
    collabDeleteLocalTasksToo: 'Supprimer les tâches locales',
    collabErrorCreate: 'Impossible de créer l\'équipe.',
    collabErrorInvite: 'Impossible de générer l\'invitation.',
    collabErrorJoin: 'Impossible de rejoindre l\'équipe.',
    collabErrorInvalidLink: 'Lien d\'invitation invalide.',
    collabErrorDeleteTeam: 'Impossible de supprimer l\'équipe.',
  },
  de: {
    tasks: 'Aufgaben', kanban: 'Kanban', grades: 'Noten', calendar: 'Kalender', focus: 'Fokus', settings: 'Einstellungen',
    noSemester: 'Kein Semester eingerichtet', goToSettings: 'Gehe zu Einstellungen, um zu starten.',
    weekLabel: w => `Woche ${w}`, done: 'erledigt', timeToRelax: 'Zeit zum Entspannen!',
    addTask: 'Neue Aufgabe', task: 'Aufgabe', class: 'Fach', priority: 'Priorität',
    editTask: 'Aufgabe bearbeiten', moveLeft: 'Nach links', moveRight: 'Nach rechts', markDone: 'Als erledigt markieren',
    addToKanban: 'Zu Kanban hinzufügen', themeLight: 'Helles Design', themeDark: 'Dunkles Design', themeSystem: 'Systemdesign',
    addPartTitle: 'Teil hinzufügen',
    fromWeek: 'Von Woche', toWeek: 'Bis Woche', dueDate: 'Fälligkeitsdatum',
    other: 'Sonstiges', noTasks: 'Keine Aufgaben diese Woche.',
    whatNeedsDone: 'Was muss erledigt werden?',
    addTaskBtn: 'Aufgabe hinzufügen', showOnCalendar: 'Im Kalender anzeigen', showOnTasks: 'In Aufgaben anzeigen',
    clearDone: 'Erledigte löschen', wipeAll: 'Alles löschen',
    addCard: 'Karte hinzufügen', addCardPlaceholder: 'Kartentitel',
    save: 'Speichern', cancel: 'Abbrechen', confirm: 'Bestätigen', delete: 'Löschen',
    addEvent: 'Termin hinzufügen', newEvent: 'Neuer Termin', editEvent: 'Termin bearbeiten',
    eventTitle: 'Termintitel', eventDate: 'Datum', eventRange: 'Zeitraum',
    eventMultiDay: 'Mehrere Tage', eventColor: 'Farbe', eventNote: 'Notiz',
    eventNotePlaceholder: 'Optionale Notiz', more: 'mehr',
    navbar: 'Navigationsleiste', navHide: 'Ausblenden', navOverflow: 'Ins Mehr-Menü verschieben', navAddButton: 'Hinzufügen-Button anzeigen',
    navMore: 'Mehr', navLabelMode: 'Anzeigen', navLabelBoth: 'Symbole + Namen', navLabelIcons: 'Nur Symbole', navLabelNames: 'Nur Namen',
    add: 'Hinzufügen', navAddLabel: 'Hinzufügen', navDrag: 'Zum Umsortieren ziehen',
    appDisableTitle: 'Deaktivieren und Daten löschen?', appDisableDesc: 'Das Deaktivieren dieser App löscht alle ihre Daten dauerhaft.',
    collabDisableDesc: 'Das Trennen verlässt alle Teams und entfernt Kollaborationsdaten dauerhaft von diesem Gerät.',
    navAddAction: 'Aktion des Hinzufügen-Buttons', navAddPicker: 'Jedes Mal fragen',
    navFolders: 'Ordner', navNewFolder: 'Neuer Ordner',
    navMobilePosition: 'Position der mobilen Leiste', navPosBottom: 'Untere Leiste', navPosSide: 'Seitenleiste',
    addToTasks: 'Zu Aufgaben hinzufügen', inTasks: 'In Aufgaben',
    standby: 'Standby', standbyEnable: 'Querformat-Standby aktivieren',
    standbyDesc: 'Drehe dein Telefon ins Querformat, um ein Ambient-Dashboard anzuzeigen.',
    standbyLeft: 'Linkes Feld', standbyCenter: 'Mittleres Feld', standbyRight: 'Rechtes Feld',
    standbyPanels: 'Felder', standbyPane: n => `Feld ${n}`,
    paneWheel: 'Fortschrittsrad', paneWheelTime: 'Rad + Uhr', paneCalendar: 'Kalender',
    paneFocus: 'Fokus', paneKanban: 'Kanban', paneTasksByCategory: 'Aufgaben nach Kategorie',
    notesLastEdit: 'Bearbeitet', notesFolder: 'Ordner', notesNoFolder: 'Kein Ordner', notesNewFolder: 'Neuer Ordner',
    notesFolderName: 'Ordnername', notesRenameFolder: 'Ordner umbenennen', notesDeleteFolder: 'Ordner löschen', notesMoveTo: 'Verschieben nach',
    notesEdit: 'Bearbeiten', notesPreview: 'Vorschau', notesBack: 'Zurück',
    apps: 'Apps', appsSearch: 'Apps suchen', appsNoResults: 'Keine Apps gefunden.', notes: 'Notizen',
    notesEnable: 'Notizen aktivieren', notesEnableDesc: 'Fügt einen Notizen-Tab für schnelle Textnotizen hinzu.',
    notesNew: 'Neue Notiz', notesTitle: 'Titel', notesBody: 'Schreibe etwas…', notesSearch: 'Notizen suchen',
    notesEmpty: 'Noch keine Notizen.', notesFavorite: 'Favorit', notesText: 'Text', notesCanvas: 'Handschrift',
    notesCanvasWarning: 'Notizen mit Zeichnungen können viel Speicher belegen und sind daher nur mit aktivem Firebase verfügbar.',
    collabApp: 'Kollaboration',
    eiCalendar: 'EI-Kalender', eiCalendarEnable: 'EI-Kalender anzeigen',
    eiCalendarEnableDesc: 'Fügt den offiziellen EI-Studiengangkalender für dein Jahr zum Kalender hinzu, schreibgeschützt und immer aktuell.',
    eiCalendarDisableTitle: 'EI-Kalender ausblenden?', eiCalendarDisableDesc: 'Beendet die Anzeige der EI-Kalendertermine. Nichts wird gelöscht und du kannst es jederzeit wieder einschalten.',
    semester: 'Semester', classes: 'Fächer', gradeComponents: 'Notenbestandteile',
    kanbanColumns: 'Kanban-Spalten', general: 'Allgemein', data: 'Daten & Sync',
    holidays: 'Ferien',
    exportJson: 'JSON exportieren', importJson: 'JSON importieren',
    semesterAvg: 'Semesterdurchschnitt', ectsPassedLabel: 'ECTS bestanden',
    targetGrade: 'Zielnote',
    previousSemesters: 'Frühere Semester',
    courseAvg: 'Kursdurchschnitt', finalGrade: 'Endnote', previousAvg: 'Früherer Durchschn.', numSemesters: 'Anzahl Semester',
    getStarted: 'Loslegen', welcomeTitle: 'Willkommen bei organizer',
    welcomeDesc: 'Dein Raum für die Uni-Arbeit. Richte dein Semester ein und organisiere dich.',
    step1: 'Semesterdaten festlegen', step2: 'Deine Fächer hinzufügen', step3: 'Aufgaben planen & Noten verfolgen',
    obNext: 'Weiter', obBack: 'Zurück', obFinish: 'Fertig', obSkip: 'Überspringen',
    obWelcomeTitle: 'Willkommen bei Organizer', obWelcomeDesc: 'Dein ruhiger Raum für die Uni-Arbeit. Wähle Sprache und Design zum Starten.',
    obModeTitle: 'Wie wirst du es nutzen?', obModeDesc: 'Aktiviere, was zu dir passt. Beides kann an sein.',
    obModeWorkToggle: 'Arbeitsmodus', obModeWorkToggleDesc: 'Gruppen statt Fächer, keine Noten.',
    obModeWeeksToggle: 'Keine Semester', obModeWeeksToggleDesc: 'Nach Kalenderwoche statt Semester organisieren.',
    obImportOr: 'oder ein Backup wiederherstellen',
    obDatesTitle: 'Dein Semester', obDatesDesc: 'Wann beginnt und endet es?',
    obClassesTitle: 'Deine Fächer', obClassesDesc: 'Füge die Fächer hinzu, die du belegst.',
    obGroupsTitle: 'Deine Gruppen', obGroupsDesc: 'Füge die Gruppen hinzu, mit denen du arbeitest.',
    obInfoTasksTitle: 'Aufgaben & Kanban', obInfoTasksDesc: 'Füge Aufgaben pro Woche oder Datum hinzu und ziehe sie über dein Kanban-Board.',
    obInfoCalTitle: 'Kalender & Fokus', obInfoCalDesc: 'Sieh alles im Kalender und starte Fokus-Sessions, um Dinge zu erledigen.',
    obInfoDoneTitle: 'Alles bereit', obInfoDoneDesc: 'Du kannst all das später in den Einstellungen ändern.',
    shareLink: 'Freigabelink kopieren', qrCode: 'QR-Code', linkCopied: 'Link kopiert!',
    high: 'Hoch', medium: 'Mittel', low: 'Niedrig', none: 'Keine',
    addSemester: 'Semester hinzufügen', semesterName: 'Semestername', startDate: 'Startdatum', endDate: 'Enddatum',
    weeks: n => `${n} Wochen`, addAClass: 'Fach hinzufügen', className: 'Fachname', ects: 'ECTS', colour: 'Farbe',
    addComponent: 'Bestandteil hinzufügen', componentName: 'Name des Bestandteils',
    taskSpanLabel: 'Verhalten mehrwöchiger Aufgaben', taskSpanDesc: 'Wenn eine Aufgabe mehrere Wochen umfasst, wie wird sie als erledigt markiert?',
    kanbanChecklistInlineLabel: 'Kanban-Checklisten-Vorschau',
    kanbanChecklistInlineDesc: 'Checklistenelemente direkt auf Karten anzeigen, ohne Details zu öffnen.',
    kanbanChecklistPreviewNone: 'Auf Karten ausblenden',
    kanbanChecklistPreviewAll: 'Auf allen Karten anzeigen',
    kanbanChecklistPreviewPerCard: 'Von Fall zu Fall',
    focusAlertModeLabel: 'Fokus-Alarmmodus',
    focusAlertModeDesc: 'Wähle, wie Fokus-Alarme beim Phasenwechsel des Timers geliefert werden.',
    focusAlertNone: 'Keine',
    focusAlertVibration: 'Vibration',
    focusAlertNotification: 'Benachrichtigung',
    focusAlertBoth: 'Beides',
    taskAlertModeLabel: 'Fälligkeits-Alarme für Aufgaben',
    taskAlertModeDesc: 'Wähle, wie Fälligkeits-Alarme geliefert werden.',
    taskAlertNone: 'Keine',
    taskAlertInApp: 'In der App',
    taskAlertNotification: 'Benachrichtigung',
    taskAlertBoth: 'Beides',
    taskAlertNextDayTimeLabel: 'Alarmzeit für den nächsten Tag',
    taskAlertNextDayTimeDesc: 'Zeit für Erinnerungen an morgen fällige Aufgaben.',
    taskDefaultToCalendarLabel: 'Aufgaben standardmäßig im Kalender',
    taskDefaultToCalendarDesc: 'Neue Aufgaben haben „Im Kalender anzeigen“ standardmäßig aktiviert.',
    taskDueTodayTitle: count => count === 1 ? 'Aufgabe heute fällig' : `${count} Aufgaben heute fällig`,
    taskAlertHide: 'Alarm ausblenden',
    taskAlertRemindMeAt: 'Erinnere mich um',
    settingEnabled: 'Aktiviert', settingDisabled: 'Deaktiviert',
    spanSingle: 'Ein globales Kästchen (einmal erledigt)', spanPerWeek: 'Kästchen pro Woche',
    dangerZone: 'Gefahrenzone', deleteSemester: 'Dieses Semester löschen',
    clearPomodoros: 'Pomodoros löschen',
    clearPomodorosTitle: 'Alle Pomodoros löschen?',
    clearPomodorosDesc: 'Alle gefallenen Pomodoros werden dauerhaft gelöscht.',
    deleteSemesterTitle: 'Semester löschen?', deleteSemesterDesc: 'Alle Aufgaben, Noten und Kanban-Daten dieses Semesters werden dauerhaft gelöscht.',
    clearDoneTitle: 'Spalte „Erledigt“ löschen?', clearDoneDesc: 'Alle Karten in der Spalte Erledigt werden gelöscht.',
    wipeAllTitle: 'Alle Karten löschen?', wipeAllDesc: 'Jede Karte auf dem Board wird dauerhaft gelöscht.',
    selectSemester: 'Semester auswählen', noClassesYet: 'Noch keine Fächer', addClassesInSettings: 'Füge Fächer in den Einstellungen hinzu.',
    addUnlocks: 'Füge ein Semester hinzu, um den Rest freizuschalten.',
    checklist: 'Checkliste', addItem: 'Element hinzufügen', editCard: 'Karte bearbeiten',
    notAchievable: '— nicht erreichbar', onRemaining: ' bei den verbleibenden Prüfungen',
    youNeed: 'Du brauchst', allGraded: 'Alle Bestandteile benotet.',
    noGradeComponents: 'Keine Notenbestandteile konfiguriert. Gehe zu Einstellungen.',
    deleteClassTitle: 'Fach löschen?', deleteClassDesc: 'Dies löscht auch alle Aufgaben dieses Fachs.',
    holidayName: 'Feriennamen', holidayNamePlaceholder: 'z. B. Weihnachtsferien',
    addHoliday: 'Ferien hinzufügen',
    loadPreset: 'Vorlage laden',
    presetLoading: 'Vorlage wird geladen…', presetError: 'Vorlage konnte nicht geladen werden.', retry: 'Erneut versuchen', skip: 'Überspringen',
    newColumnName: 'Name der neuen Spalte',
    focusStart: 'Start', focusPause: 'Pause', focusResume: 'Fortsetzen', focusReset: 'Zurücksetzen', focusSkipBreak: 'Pause überspringen',
    focusReady: 'bereit', focusBreak: 'Pause',
    focusPhrases: ['weiter so', 'bleib dran', 'du machst das großartig', 'Schritt für Schritt', 'tiefe Arbeit', 'bleib präsent'],
    focusEvery: 'alle (Min)', focusBreakFor: 'Pause (Min)',
    focusScheduledMode: 'Geplante Pausen',
    focusNextBreak: 'Nächste Pause um',
    focusFocusLabel: 'Fokus-Nachricht', focusBreakLabel: 'Pausen-Nachricht',
    loadPresetTitle: 'Vorlage laden',
    presetGroupEI: 'EI-Studiengang',
    presetGroupGeneric: 'Allgemein',
    backToMenu: 'Zurück',
    importData: 'Daten importieren',
    importFromFirebase: 'Aus Firebase importieren',
    nextSemesterTitle: 'Semester beendet',
    nextSemesterDesc: 'Dein Semester ist beendet. Das nächste laden?',
    loadNextSemester: 'Nächstes Semester laden',
    dismissNextSemester: 'Verwerfen',
    noSemesterYet: 'Kein Semester konfiguriert',
    noSemesterDesc: 'Lade eine Vorlage oder importiere deine Daten, um zu starten.',
    focusIntervalMode: 'Intervall-Pausen',
    focusIntervalEvery: 'alle (Min)',
    focusIntervalBreakFor: 'Pause (Min)',
    focusScheduledBreakFor: 'Pause (Min)',
    focusAfterBreakReset: 'Nach der Pause: Timer zurücksetzen',
    focusAfterBreakContinue: 'Nach der Pause: weiterzählen',
    firebaseSync: 'Firebase-Sync',
    firebaseConnect: 'Verbinden',
    firebaseConnected: 'Verbunden',
    firebaseDisconnect: 'Trennen',
    firebaseSyncing: 'Synchronisiere…',
    firebaseLastSync: 'Letzte Sync',
    firebaseError: 'Sync-Fehler',
    firebaseRemoteNewer: 'Cloud-Daten stammen von einer neueren App-Version. Sync pausiert. Aktualisiere die App.',
    collabSyncFailed: 'Geteilte Änderung konnte nicht synchronisiert werden. Sie wurde rückgängig gemacht.',
    newerVersionWarning: 'Deine Daten wurden von einer neueren App-Version gespeichert. Manches wird möglicherweise erst nach dem Update korrekt angezeigt.',
    firebaseSetupTitle: 'Firebase verbinden',
    firebaseStep1Title: 'Firebase-Projekt erstellen',
    firebaseStep1Desc: 'Gehe zu console.firebase.google.com → Projekt hinzufügen → gib ihm einen Namen → Google Analytics deaktivieren → Projekt erstellen.',
    firebaseStep2Title: 'Firestore aktivieren',
    firebaseStep2Desc: 'Gehe zu Build → Firestore Database → Datenbank erstellen → wähle eine Region → Im Produktionsmodus starten → Erstellen. Dann zu Regeln, ersetze den Inhalt durch: allow read, write: if true; und klicke Veröffentlichen.',
    firebaseStep3Title: 'Deine Konfiguration holen',
    firebaseStep3Desc: 'Gehe zu Projekteinstellungen (Zahnrad) → Deine Apps → App hinzufügen → Web → App registrieren → kopiere das angezeigte firebaseConfig-Objekt.',
    firebaseStep4Title: 'Deine Konfiguration einfügen',
    firebaseStep4Desc: 'Füge das vollständige firebaseConfig-Objekt (als JSON) unten ein.',
    firebaseConfigPlaceholder: '{ "apiKey": "...", "authDomain": "...", "projectId": "...", ... }',
    firebaseConfigInvalid: 'Ungültige Konfiguration: muss apiKey und projectId enthalten.',
    firebaseTestFailed: 'Verbindung fehlgeschlagen. Prüfe deine Konfiguration und die Datenbankregeln.',
    firebaseSave: 'Speichern & verbinden',
    pomodoroMode: 'Pomodoro-Modus',
    pomodoroModeDesc: 'Ziehe während Fokus-Sessions Tomaten. Jede abgeschlossene Session lässt eine Tomate fallen.',
    pomodoroResetPeriod: 'Zurücksetzzeitraum',
    pomodoroResetDay: 'Täglich', pomodoroResetWeek: 'Wöchentlich', pomodoroResetMonth: 'Monatlich', pomodoroResetSemester: 'Pro Semester',
    pomodoroTrackPeriodStats: 'Zeitraum-Statistiken verfolgen',
    pomodoroShowAbandoned: 'Aufgegebene Tomaten anzeigen',
    pomodoroShowPeriodPomodoros: 'Zeitraum-Pomodoros anzeigen',
    pomodoroStatsTitle: 'Pomodoro-Statistiken',
    pomodoroTotal: 'Tomaten gesamt', pomodoroAbandoned: 'Aufgegeben', pomodoroFocusTime: 'Gesamte Fokuszeit',
    pomodoroPeriodTotal: 'Dieser Zeitraum', pomodoroPeriodFocus: 'Fokus in diesem Zeitraum',
    pomodoroVsSinceLast: 'vs. letzter Zeitraum',
    pomodoroAllTime: 'Insgesamt',
    pomodoroInsightsDailyTitle: 'Täglicher Fokus diese Woche',
    pomodoroInsightsWeeklyBreakdownTitle: 'Wöchentliche Durchschnitte',
    pomodoroInsightsAvgWeekLabel: 'Ø/Tag (Woche)',
    pomodoroInsightsAvgPeriodLabel: 'Ø/Tag (Zeitraum)',
    pomodoroInsightsPerDaySuffix: '/T',
    pomodoroInsightsNoWeeklyData: 'Noch keine wöchentlichen Daten.',
    pomodoroInsightsDayLabels: ['S', 'M', 'D', 'M', 'D', 'F', 'S'],
    pomodoroTotalTimeLabel: 'Gesamtzeit',
    pomodoroClose: 'Schließen',
    pomodoroEraseStats: 'Statistiken löschen',
    pomodoroEraseStatsTitle: 'Pomodoro-Statistiken löschen?',
    pomodoroEraseStatsDesc: 'Historische Fokuszeit-Statistiken werden entfernt, aber Tomaten-Einträge bleiben verfügbar.',
    pomodoroGraceCancel: 'Abbrechen (keine Tomate)',
    pomodoroGrace: s => `${s}s zum Abbrechen ohne Tomatenverlust`,
    workModeLabel: 'Arbeitsmodus',
    workModeDesc: 'Blendet Noten aus und benennt Fächer in Gruppen um.',
    workModeOnboarding: 'Nutzt du das für die Arbeit?',
    semesterModeLabel: 'Modus ohne Semester',
    semesterModeDesc: 'Aktiviere, um einfache Jahreswochen statt Semester zu nutzen. Noten werden ausgeblendet.',
    semesterModeNone: 'Keine Semester (Jahreswochen)',
    semesterModeSemesters: 'Mit Semestern',
    semesterModeOnboarding: 'Keine Semester, nur Wochen?',
    groups: 'Gruppen', addAGroup: 'Gruppe hinzufügen', groupName: 'Gruppenname',
    deleteGroupTitle: 'Gruppe löschen?', deleteGroupDesc: 'Dies löscht auch alle Aufgaben dieser Gruppe.',
    storageWarningTitle: 'Speicherlimit erreicht',
    storageWarningDesc: 'Bitte aktiviere Firebase-Sync, maximaler lokaler Speicher erreicht.',
    storageWarningAction: 'Verstanden',
    collabConnect: 'Organizer Collab verbinden',
    collabDisconnect: 'Organizer Collab trennen',
    collabRequiresFirebase: 'Verbinde zuerst Firebase-Sync, um Organizer Collab zu nutzen.',
    collabGuideTitle: 'Organizer Collab einrichten',
    collabGuideIntro: 'Einmalige Einrichtung. Führe diese 4 Schritte in Firebase aus und aktiviere dann Collab.',
    collabGuideImportantTitle: 'Was sich ändert, wenn Collab aktiviert ist',
    collabGuideImportant1: 'Deine Datenbank verlangt dann authentifizierte Nutzer (anonyme Auth genügt).',
    collabGuideImportant2: 'Die normale Organizer-Sync funktioniert weiter, muss sich aber zuerst authentifizieren.',
    collabGuideImportant3: 'Wird Collab später deaktiviert, können auth-basierte Regeln weiterhin sicher genutzt werden.',
    collabGuideStep1: 'Öffne Firebase Console > Build > Firestore Database > Regeln.',
    collabGuideStep2: 'Füge den Regel-Ausschnitt unten ein und klicke Veröffentlichen.',
    collabGuideStep3: 'Öffne Security > Authentication > Anmeldemethode > aktiviere Anonym > Speichern.',
    collabGuideStep4: 'Kehre zu Organizer zurück und drücke „Ich habe die Regeln konfiguriert, Collab aktivieren“.',
    collabGuideRulesLabel: 'Firestore-Regeln',
    collabGuideTroubleshootTitle: 'Wenn du einen signUp-400-Fehler siehst',
    collabGuideTroubleshootBody: 'Das bedeutet, dass anonyme Authentifizierung in Firebase noch deaktiviert ist. Aktiviere sie unter Security > Authentication > Anmeldemethode.',
    collabEnableNow: 'Ich habe die Regeln konfiguriert, Collab aktivieren',
    collabPanelTitle: 'Organizer Collab',
    collabPanelSubtitle: 'Erstelle Teams, lade Leute ein und teile Aufgaben/Kanban-Karten.',
    collabCreateTeam: 'Team erstellen',
    collabTeamName: 'Teamname',
    collabTeamDays: 'Teamtage',
    collabTeamDuration: 'Teamdauer',
    collabDays: 'Tage',
    collabJoinTeam: 'Team beitreten',
    collabInvitePlaceholder: 'Einladungslink einfügen',
    collabInviteTtl: 'Gültigkeit der Einladung',
    collabYourTeams: 'Deine Teams',
    collabNoTeams: 'Noch keine Teams.',
    collabRoleHost: 'Host',
    collabRoleMember: 'Mitglied',
    collabEndsAt: 'endet',
    collabInvite: 'Einladen',
    collabEditTeam: 'Team bearbeiten',
    collabTaskCompletionMode: 'Abschluss geteilter Aufgaben',
    collabTaskCompletionPersonal: 'persönlicher Abschluss',
    collabTaskCompletionForAll: 'für alle umschalten',
    collabTaskPermissions: 'Bearbeitungsrechte für Aufgaben',
    collabTaskPermissionsEveryone: 'jeder kann Aufgaben hinzufügen/bearbeiten/entfernen',
    collabTaskPermissionsHostOnly: 'nur der Host kann Aufgaben hinzufügen/bearbeiten/entfernen',
    collabLeave: 'Verlassen',
    collabDeleteTeam: 'Löschen',
    collabDefaultTeamName: 'Team',
    collabLeavePrompt: 'Dieses Team verlassen?',
    collabLeaveWithLocalPrompt: 'Du hast lokale Aufgaben in diesem Team geteilt. Lokal behalten?',
    collabDeleteTeamPrompt: 'Dieses Team löschen?',
    collabDeleteTeamWithLocalPrompt: 'Du hast lokale Aufgaben in diesem Team geteilt. Vor dem Löschen des Teams lokal behalten?',
    collabKeepLocalTasks: 'Lokale Aufgaben behalten',
    collabDeleteLocalTasksToo: 'Lokale Aufgaben löschen',
    collabErrorCreate: 'Team konnte nicht erstellt werden.',
    collabErrorInvite: 'Einladung konnte nicht erstellt werden.',
    collabErrorJoin: 'Beitritt zum Team nicht möglich.',
    collabErrorInvalidLink: 'Ungültiger Einladungslink.',
    collabErrorDeleteTeam: 'Team konnte nicht gelöscht werden.',
  },
  es: {
    tasks: 'Tareas', kanban: 'Kanban', grades: 'Notas', calendar: 'Calendario', focus: 'Enfoque', settings: 'Ajustes',
    noSemester: 'Ningún semestre configurado', goToSettings: 'Ve a Ajustes para empezar.',
    weekLabel: w => `Semana ${w}`, done: 'completadas', timeToRelax: '¡Hora de relajarse!',
    addTask: 'Nueva tarea', task: 'Tarea', class: 'Asignatura', priority: 'Prioridad',
    editTask: 'Editar tarea', moveLeft: 'Mover a la izquierda', moveRight: 'Mover a la derecha', markDone: 'Marcar como hecha',
    addToKanban: 'Añadir al Kanban', themeLight: 'Tema claro', themeDark: 'Tema oscuro', themeSystem: 'Tema del sistema',
    addPartTitle: 'Añadir parte',
    fromWeek: 'Desde la semana', toWeek: 'Hasta la semana', dueDate: 'Fecha límite',
    other: 'Otro', noTasks: 'Sin tareas esta semana.',
    whatNeedsDone: '¿Qué hay que hacer?',
    addTaskBtn: 'Añadir tarea', showOnCalendar: 'Mostrar en el calendario', showOnTasks: 'Mostrar en las tareas',
    clearDone: 'Borrar completadas', wipeAll: 'Borrar todo',
    addCard: 'Añadir tarjeta', addCardPlaceholder: 'Título de la tarjeta',
    save: 'Guardar', cancel: 'Cancelar', confirm: 'Confirmar', delete: 'Eliminar',
    addEvent: 'Añadir evento', newEvent: 'Nuevo evento', editEvent: 'Editar evento',
    eventTitle: 'Título del evento', eventDate: 'Fecha', eventRange: 'Rango de fechas',
    eventMultiDay: 'Varios días', eventColor: 'Color', eventNote: 'Nota',
    eventNotePlaceholder: 'Nota opcional', more: 'más',
    navbar: 'Barra de navegación', navHide: 'Ocultar', navOverflow: 'Mover al menú más', navAddButton: 'Mostrar botón de añadir',
    navMore: 'Más', navLabelMode: 'Mostrar', navLabelBoth: 'Iconos + nombres', navLabelIcons: 'Solo iconos', navLabelNames: 'Solo nombres',
    add: 'Añadir', navAddLabel: 'Añadir', navDrag: 'Arrastra para reordenar',
    appDisableTitle: '¿Desactivar y borrar datos?', appDisableDesc: 'Desactivar esta app elimina permanentemente todos sus datos.',
    collabDisableDesc: 'Desconectar abandona todos los equipos y elimina permanentemente los datos de colaboración de este dispositivo.',
    navAddAction: 'Acción del botón de añadir', navAddPicker: 'Preguntar cada vez',
    navFolders: 'Carpetas', navNewFolder: 'Nueva carpeta',
    navMobilePosition: 'Posición de la barra móvil', navPosBottom: 'Barra inferior', navPosSide: 'Barra lateral',
    addToTasks: 'Añadir a tareas', inTasks: 'En tareas',
    standby: 'Reposo', standbyEnable: 'Activar reposo horizontal',
    standbyDesc: 'Pon tu teléfono en horizontal para mostrar un panel ambiental.',
    standbyLeft: 'Panel izquierdo', standbyCenter: 'Panel central', standbyRight: 'Panel derecho',
    standbyPanels: 'Paneles', standbyPane: n => `Panel ${n}`,
    paneWheel: 'Rueda de progreso', paneWheelTime: 'Rueda + reloj', paneCalendar: 'Calendario',
    paneFocus: 'Enfoque', paneKanban: 'Kanban', paneTasksByCategory: 'Tareas por categoría',
    notesLastEdit: 'Editado', notesFolder: 'Carpeta', notesNoFolder: 'Sin carpeta', notesNewFolder: 'Nueva carpeta',
    notesFolderName: 'Nombre de la carpeta', notesRenameFolder: 'Renombrar carpeta', notesDeleteFolder: 'Eliminar carpeta', notesMoveTo: 'Mover a',
    notesEdit: 'Editar', notesPreview: 'Vista previa', notesBack: 'Atrás',
    apps: 'Apps', appsSearch: 'Buscar apps', appsNoResults: 'No se encontraron apps.', notes: 'Notas',
    notesEnable: 'Activar Notas', notesEnableDesc: 'Añade una pestaña de Notas para notas rápidas.',
    notesNew: 'Nueva nota', notesTitle: 'Título', notesBody: 'Escribe algo…', notesSearch: 'Buscar notas',
    notesEmpty: 'Aún no hay notas.', notesFavorite: 'Favorita', notesText: 'Texto', notesCanvas: 'Escritura a mano',
    notesCanvasWarning: 'Las notas con dibujos pueden usar mucho espacio, por lo que solo están disponibles con Firebase activo.',
    collabApp: 'Colaboración',
    eiCalendar: 'Calendario EI', eiCalendarEnable: 'Mostrar calendario EI',
    eiCalendarEnableDesc: 'Añade el calendario oficial del grado EI de tu año al calendario, de solo lectura y siempre actualizado.',
    eiCalendarDisableTitle: '¿Ocultar calendario EI?', eiCalendarDisableDesc: 'Deja de mostrar los eventos del calendario EI. No se elimina nada y puedes reactivarlo cuando quieras.',
    semester: 'Semestre', classes: 'Asignaturas', gradeComponents: 'Componentes de nota',
    kanbanColumns: 'Columnas Kanban', general: 'General', data: 'Datos y sync',
    holidays: 'Vacaciones',
    exportJson: 'Exportar JSON', importJson: 'Importar JSON',
    semesterAvg: 'Media del semestre', ectsPassedLabel: 'ECTS aprobados',
    targetGrade: 'Nota objetivo',
    previousSemesters: 'Semestres anteriores',
    courseAvg: 'Media del curso', finalGrade: 'Nota final', previousAvg: 'Media anterior', numSemesters: 'Nº de semestres',
    getStarted: 'Empezar', welcomeTitle: 'Bienvenido a organizer',
    welcomeDesc: 'Tu espacio para el trabajo universitario. Configura tu semestre y organízate.',
    step1: 'Define las fechas del semestre', step2: 'Añade tus asignaturas', step3: 'Planifica tareas y sigue las notas',
    obNext: 'Siguiente', obBack: 'Atrás', obFinish: 'Finalizar', obSkip: 'Omitir',
    obWelcomeTitle: 'Bienvenido a Organizer', obWelcomeDesc: 'Tu espacio tranquilo para el trabajo universitario. Elige tu idioma y tema para empezar.',
    obModeTitle: '¿Cómo lo usarás?', obModeDesc: 'Activa lo que te convenga. Ambos pueden estar activos.',
    obModeWorkToggle: 'Modo trabajo', obModeWorkToggleDesc: 'Grupos en vez de asignaturas, sin notas.',
    obModeWeeksToggle: 'Sin semestres', obModeWeeksToggleDesc: 'Organizar por semana natural en vez de semestre.',
    obImportOr: 'o restaurar una copia de seguridad',
    obDatesTitle: 'Tu semestre', obDatesDesc: '¿Cuándo empieza y termina?',
    obClassesTitle: 'Tus asignaturas', obClassesDesc: 'Añade las asignaturas que cursas.',
    obGroupsTitle: 'Tus grupos', obGroupsDesc: 'Añade los grupos con los que trabajas.',
    obInfoTasksTitle: 'Tareas y Kanban', obInfoTasksDesc: 'Añade tareas por semana o fecha y arrástralas por tu tablero kanban.',
    obInfoCalTitle: 'Calendario y Enfoque', obInfoCalDesc: 'Ve todo en el calendario y ejecuta sesiones de enfoque para avanzar.',
    obInfoDoneTitle: 'Todo listo', obInfoDoneDesc: 'Puedes cambiar todo esto más tarde en los ajustes.',
    shareLink: 'Copiar enlace para compartir', qrCode: 'Código QR', linkCopied: '¡Enlace copiado!',
    high: 'Alta', medium: 'Media', low: 'Baja', none: 'Ninguna',
    addSemester: 'Añadir semestre', semesterName: 'Nombre del semestre', startDate: 'Fecha de inicio', endDate: 'Fecha de fin',
    weeks: n => `${n} semanas`, addAClass: 'Añadir asignatura', className: 'Nombre de la asignatura', ects: 'ECTS', colour: 'Color',
    addComponent: 'Añadir componente', componentName: 'Nombre del componente',
    taskSpanLabel: 'Comportamiento de tareas de varias semanas', taskSpanDesc: 'Cuando una tarea abarca varias semanas, ¿cómo se marca como hecha?',
    kanbanChecklistInlineLabel: 'Vista previa de checklist Kanban',
    kanbanChecklistInlineDesc: 'Muestra los elementos de la checklist directamente en las tarjetas sin abrir los detalles.',
    kanbanChecklistPreviewNone: 'Ocultar en las tarjetas',
    kanbanChecklistPreviewAll: 'Mostrar en todas las tarjetas',
    kanbanChecklistPreviewPerCard: 'Caso por caso',
    focusAlertModeLabel: 'Modo de alerta de Enfoque',
    focusAlertModeDesc: 'Elige cómo se entregan las alertas de Enfoque al cambiar de fase el temporizador.',
    focusAlertNone: 'Ninguna',
    focusAlertVibration: 'Vibración',
    focusAlertNotification: 'Notificación',
    focusAlertBoth: 'Ambas',
    taskAlertModeLabel: 'Alertas de fecha límite',
    taskAlertModeDesc: 'Elige cómo se entregan las alertas de fecha límite.',
    taskAlertNone: 'Ninguna',
    taskAlertInApp: 'En la app',
    taskAlertNotification: 'Notificación',
    taskAlertBoth: 'Ambas',
    taskAlertNextDayTimeLabel: 'Hora de alerta del día siguiente',
    taskAlertNextDayTimeDesc: 'Hora de los recordatorios de tareas que vencen mañana.',
    taskDefaultToCalendarLabel: 'Tareas en el calendario por defecto',
    taskDefaultToCalendarDesc: 'Las nuevas tareas tendrán «Mostrar en el calendario» activado por defecto.',
    taskDueTodayTitle: count => count === 1 ? 'Tarea para hoy' : `${count} tareas para hoy`,
    taskAlertHide: 'Ocultar alerta',
    taskAlertRemindMeAt: 'Recordarme a las',
    settingEnabled: 'Activado', settingDisabled: 'Desactivado',
    spanSingle: 'Una casilla global (hecha una vez)', spanPerWeek: 'Casilla por semana',
    dangerZone: 'Zona de peligro', deleteSemester: 'Eliminar este semestre',
    clearPomodoros: 'Borrar pomodoros',
    clearPomodorosTitle: '¿Borrar todos los pomodoros?',
    clearPomodorosDesc: 'Todos los pomodoros caídos se eliminarán permanentemente.',
    deleteSemesterTitle: '¿Eliminar semestre?', deleteSemesterDesc: 'Todas las tareas, notas y datos kanban de este semestre se eliminarán permanentemente.',
    clearDoneTitle: '¿Borrar la columna Hecho?', clearDoneDesc: 'Todas las tarjetas de la columna Hecho se eliminarán.',
    wipeAllTitle: '¿Borrar todas las tarjetas?', wipeAllDesc: 'Cada tarjeta del tablero se eliminará permanentemente.',
    selectSemester: 'Seleccionar semestre', noClassesYet: 'Aún no hay asignaturas', addClassesInSettings: 'Añade asignaturas en Ajustes.',
    addUnlocks: 'Añade un semestre para desbloquear el resto.',
    checklist: 'Checklist', addItem: 'Añadir elemento', editCard: 'Editar tarjeta',
    notAchievable: '— no alcanzable', onRemaining: ' en las evaluaciones restantes',
    youNeed: 'Necesitas', allGraded: 'Todos los componentes calificados.',
    noGradeComponents: 'No hay componentes de nota configurados. Ve a Ajustes.',
    deleteClassTitle: '¿Eliminar asignatura?', deleteClassDesc: 'Esto también eliminará todas las tareas de esta asignatura.',
    holidayName: 'Nombre de las vacaciones', holidayNamePlaceholder: 'ej: Vacaciones de Navidad',
    addHoliday: 'Añadir vacaciones',
    loadPreset: 'Cargar preajuste',
    presetLoading: 'Cargando preajuste…', presetError: 'Error al cargar el preajuste.', retry: 'Reintentar', skip: 'Omitir',
    newColumnName: 'Nombre de la nueva columna',
    focusStart: 'Iniciar', focusPause: 'Pausar', focusResume: 'Reanudar', focusReset: 'Reiniciar', focusSkipBreak: 'Saltar descanso',
    focusReady: 'listo', focusBreak: 'descanso',
    focusPhrases: ['sigue así', 'mantente en ello', 'lo estás haciendo genial', 'paso a paso', 'trabajo profundo', 'mantente presente'],
    focusEvery: 'cada (min)', focusBreakFor: 'descanso (min)',
    focusScheduledMode: 'Descansos programados',
    focusNextBreak: 'Próximo descanso a las',
    focusFocusLabel: 'Mensaje de enfoque', focusBreakLabel: 'Mensaje de descanso',
    loadPresetTitle: 'Cargar un preajuste',
    presetGroupEI: 'Grado EI',
    presetGroupGeneric: 'General',
    backToMenu: 'Atrás',
    importData: 'Importar datos',
    importFromFirebase: 'Importar desde Firebase',
    nextSemesterTitle: 'Semestre terminado',
    nextSemesterDesc: 'Tu semestre ha terminado. ¿Cargar el siguiente?',
    loadNextSemester: 'Cargar el próximo semestre',
    dismissNextSemester: 'Descartar',
    noSemesterYet: 'Ningún semestre configurado',
    noSemesterDesc: 'Carga un preajuste o importa tus datos para empezar.',
    focusIntervalMode: 'Descansos por intervalo',
    focusIntervalEvery: 'cada (min)',
    focusIntervalBreakFor: 'descanso (min)',
    focusScheduledBreakFor: 'descanso (min)',
    focusAfterBreakReset: 'Tras el descanso: reiniciar temporizador',
    focusAfterBreakContinue: 'Tras el descanso: seguir contando',
    firebaseSync: 'Sync de Firebase',
    firebaseConnect: 'Conectar',
    firebaseConnected: 'Conectado',
    firebaseDisconnect: 'Desconectar',
    firebaseSyncing: 'Sincronizando…',
    firebaseLastSync: 'Última sync',
    firebaseError: 'Error de sync',
    firebaseRemoteNewer: 'Los datos de la nube son de una versión más reciente. Sync en pausa. Actualiza la app.',
    collabSyncFailed: 'No se pudo sincronizar el cambio compartido. Se revirtió.',
    newerVersionWarning: 'Tus datos se guardaron con una versión más reciente. Algunas cosas pueden no mostrarse bien hasta que actualices.',
    firebaseSetupTitle: 'Conectar Firebase',
    firebaseStep1Title: 'Crear un proyecto de Firebase',
    firebaseStep1Desc: 'Ve a console.firebase.google.com → Añadir proyecto → dale un nombre → desactiva Google Analytics → Crear proyecto.',
    firebaseStep2Title: 'Activar Firestore',
    firebaseStep2Desc: 'Ve a Build → Firestore Database → Crear base de datos → elige una región → Iniciar en modo producción → Crear. Luego en Reglas, reemplaza el contenido por: allow read, write: if true; y pulsa Publicar.',
    firebaseStep3Title: 'Obtener tu configuración',
    firebaseStep3Desc: 'Ve a Configuración del proyecto (icono de engranaje) → Tus apps → Añadir app → Web → registra la app → copia el objeto firebaseConfig mostrado.',
    firebaseStep4Title: 'Pegar tu configuración',
    firebaseStep4Desc: 'Pega el objeto firebaseConfig completo (como JSON) abajo.',
    firebaseConfigPlaceholder: '{ "apiKey": "...", "authDomain": "...", "projectId": "...", ... }',
    firebaseConfigInvalid: 'Config inválida: debe incluir apiKey y projectId.',
    firebaseTestFailed: 'No se pudo conectar. Revisa tu config y las reglas de la base de datos.',
    firebaseSave: 'Guardar y conectar',
    pomodoroMode: 'Modo Pomodoro',
    pomodoroModeDesc: 'Cultiva tomates durante las sesiones de enfoque. Cada sesión completada suelta un tomate.',
    pomodoroResetPeriod: 'Periodo de reinicio',
    pomodoroResetDay: 'Diario', pomodoroResetWeek: 'Semanal', pomodoroResetMonth: 'Mensual', pomodoroResetSemester: 'Por semestre',
    pomodoroTrackPeriodStats: 'Seguir estadísticas del periodo',
    pomodoroShowAbandoned: 'Mostrar tomates abandonados',
    pomodoroShowPeriodPomodoros: 'Mostrar pomodoros del periodo',
    pomodoroStatsTitle: 'Estadísticas Pomodoro',
    pomodoroTotal: 'Total de tomates', pomodoroAbandoned: 'Abandonados', pomodoroFocusTime: 'Tiempo total de enfoque',
    pomodoroPeriodTotal: 'Este periodo', pomodoroPeriodFocus: 'Enfoque este periodo',
    pomodoroVsSinceLast: 'vs periodo anterior',
    pomodoroAllTime: 'Histórico',
    pomodoroInsightsDailyTitle: 'Enfoque diario esta semana',
    pomodoroInsightsWeeklyBreakdownTitle: 'Medias semanales',
    pomodoroInsightsAvgWeekLabel: 'media/día (semana)',
    pomodoroInsightsAvgPeriodLabel: 'media/día (periodo)',
    pomodoroInsightsPerDaySuffix: '/d',
    pomodoroInsightsNoWeeklyData: 'Aún no hay datos semanales.',
    pomodoroInsightsDayLabels: ['D', 'L', 'M', 'X', 'J', 'V', 'S'],
    pomodoroTotalTimeLabel: 'tiempo total',
    pomodoroClose: 'Cerrar',
    pomodoroEraseStats: 'Borrar estadísticas',
    pomodoroEraseStatsTitle: '¿Borrar estadísticas Pomodoro?',
    pomodoroEraseStatsDesc: 'Se eliminarán las estadísticas históricas de tiempo de enfoque, pero las entradas de tomate seguirán disponibles.',
    pomodoroGraceCancel: 'Cancelar (sin tomate)',
    pomodoroGrace: s => `${s}s para cancelar sin perder un tomate`,
    workModeLabel: 'Modo trabajo',
    workModeDesc: 'Oculta las notas y renombra las asignaturas como grupos.',
    workModeOnboarding: '¿Usas esto para el trabajo?',
    semesterModeLabel: 'Modo sin semestre',
    semesterModeDesc: 'Activa para usar simples semanas del año en vez de semestres. Las notas se ocultan.',
    semesterModeNone: 'Sin semestres (semanas del año)',
    semesterModeSemesters: 'Con semestres',
    semesterModeOnboarding: '¿Sin semestres, solo semanas?',
    groups: 'Grupos', addAGroup: 'Añadir grupo', groupName: 'Nombre del grupo',
    deleteGroupTitle: '¿Eliminar grupo?', deleteGroupDesc: 'Esto también eliminará todas las tareas de este grupo.',
    storageWarningTitle: 'Límite de almacenamiento alcanzado',
    storageWarningDesc: 'Activa la sync de Firebase, se alcanzó el máximo de almacenamiento local.',
    storageWarningAction: 'Entendido',
    collabConnect: 'Conectar Organizer Collab',
    collabDisconnect: 'Desconectar Organizer Collab',
    collabRequiresFirebase: 'Conecta primero la sync de Firebase para usar Organizer Collab.',
    collabGuideTitle: 'Configuración de Organizer Collab',
    collabGuideIntro: 'Configuración única. Haz estos 4 pasos en Firebase y luego vuelve para activar collab.',
    collabGuideImportantTitle: 'Qué cambia cuando collab está activado',
    collabGuideImportant1: 'Tu base de datos empieza a requerir usuarios autenticados (basta con auth anónima).',
    collabGuideImportant2: 'La sync normal sigue funcionando, pero debe autenticarse primero.',
    collabGuideImportant3: 'Si collab se desactiva luego, las reglas basadas en auth siguen siendo seguras de usar.',
    collabGuideStep1: 'Abre Firebase Console > Build > Firestore Database > Reglas.',
    collabGuideStep2: 'Pega el fragmento de reglas de abajo y pulsa Publicar.',
    collabGuideStep3: 'Abre Security > Authentication > Método de acceso > activa Anónimo > Guardar.',
    collabGuideStep4: 'Vuelve a Organizer y pulsa «Configuré las reglas, activar collab».',
    collabGuideRulesLabel: 'Reglas de Firestore',
    collabGuideTroubleshootTitle: 'Si ves un error signUp 400',
    collabGuideTroubleshootBody: 'Significa que la autenticación anónima sigue desactivada en Firebase. Actívala en Security > Authentication > Método de acceso.',
    collabEnableNow: 'Configuré las reglas, activar collab',
    collabPanelTitle: 'Organizer Collab',
    collabPanelSubtitle: 'Crea equipos, invita a personas y comparte tareas/tarjetas kanban.',
    collabCreateTeam: 'Crear equipo',
    collabTeamName: 'Nombre del equipo',
    collabTeamDays: 'días del equipo',
    collabTeamDuration: 'duración del equipo',
    collabDays: 'días',
    collabJoinTeam: 'Unirse a un equipo',
    collabInvitePlaceholder: 'Pega el enlace de invitación',
    collabInviteTtl: 'Validez de la invitación',
    collabYourTeams: 'Tus equipos',
    collabNoTeams: 'Aún no hay equipos.',
    collabRoleHost: 'anfitrión',
    collabRoleMember: 'miembro',
    collabEndsAt: 'termina',
    collabInvite: 'Invitar',
    collabEditTeam: 'Editar equipo',
    collabTaskCompletionMode: 'Finalización de tareas compartidas',
    collabTaskCompletionPersonal: 'finalización personal',
    collabTaskCompletionForAll: 'alternar para todos',
    collabTaskPermissions: 'Permisos de edición de tareas',
    collabTaskPermissionsEveryone: 'cualquiera puede añadir/editar/eliminar tareas',
    collabTaskPermissionsHostOnly: 'solo el anfitrión puede añadir/editar/eliminar tareas',
    collabLeave: 'Salir',
    collabDeleteTeam: 'Eliminar',
    collabDefaultTeamName: 'Equipo',
    collabLeavePrompt: '¿Salir de este equipo?',
    collabLeaveWithLocalPrompt: 'Compartiste tareas locales en este equipo. ¿Conservarlas localmente?',
    collabDeleteTeamPrompt: '¿Eliminar este equipo?',
    collabDeleteTeamWithLocalPrompt: 'Compartiste tareas locales en este equipo. ¿Conservarlas localmente antes de eliminar el equipo?',
    collabKeepLocalTasks: 'Conservar tareas locales',
    collabDeleteLocalTasksToo: 'Eliminar tareas locales',
    collabErrorCreate: 'No se pudo crear el equipo.',
    collabErrorInvite: 'No se pudo generar la invitación.',
    collabErrorJoin: 'No se pudo unir al equipo.',
    collabErrorInvalidLink: 'Enlace de invitación inválido.',
    collabErrorDeleteTeam: 'No se pudo eliminar el equipo.',
  },
}

export function useStrings(lang) {
  return STRINGS[lang] ?? STRINGS.en
}
